// packages/react/src/components/ProgressIndicator/next/ProgressIndicator.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import PropTypes from 'prop-types';
import React, { useState } from 'react';
import { usePrefix } from '../../../internal/usePrefix';

function ProgressIndicator({
  children,
  className: customClassName,
  currentIndex: controlledIndex = 0,
  onChange,
  spaceEqually,
  vertical,
  ...rest
}) {
  const prefix = usePrefix();
  const [currentIndex, setCurrentIndex] = useState(controlledIndex);
  const [prevControlledIndex, setPrevControlledIndex] = useState(
    controlledIndex
  );
  const className = cx({
    [`${prefix}--progress`]: true,
    [`${prefix}--progress--vertical`]: vertical,
    [`${prefix}--progress--space-equal`]: spaceEqually && !vertical,
    [customClassName]: customClassName,
  });

  if (controlledIndex !== prevControlledIndex) {
    setCurrentIndex(controlledIndex);
    setPrevControlledIndex(controlledIndex);
  }

  return (
    <ul className={className} {...rest}>
      {React.Children.map(children, (child, index) => {
        // only setup click handlers if onChange event is passed
        const onClick = onChange ? () => onChange(index) : undefined;
        if (index === currentIndex) {
          return React.cloneElement(child, {
            current: true,
            index,
            onClick,
          });
        }
        if (index < currentIndex) {
          return React.cloneElement(child, {
            complete: true,
            index,
            onClick,
          });
        }
        if (index > currentIndex) {
          return React.cloneElement(child, {
            complete: child.props.complete || false,
            index,
            onClick,
          });
        }
        return null;
      })}
    </ul>
  );
}

ProgressIndicator.propTypes = {
  /**
   * Provide <ProgressStep> components to be rendered in the
   * <ProgressIndicator>
   */
  children: PropTypes.node,

  /**
   * Provide an optional className to be applied to the containing node
   */
  className: PropTypes.string,

  /**
   * Optionally specify the current step array index
   */
  currentIndex: PropTypes.number,

  /**
   * Optional callback called if a ProgressStep is clicked on.  Returns the index of the step.
   */
  onChange: PropTypes.func,

  /**
   * Specify whether the progress steps should be split equally in size in the div
   */
  spaceEqually: PropTypes.bool,
  /**
   * Determines whether or not the ProgressIndicator should be rendered vertically.
   */
  vertical: PropTypes.bool,
};

export { ProgressIndicator };

// web-components/packages/carbon-web-components/src/components/progress-indicator/progress-indicator.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import { forEach } from '../../globals/internal/collection-helpers';
import CDSProgressStep from './progress-step';
import styles from './progress-indicator.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Progress indicator.
 *
 * @element cds-progress-indicator
 */
@customElement(`${prefix}-progress-indicator`)
export default class CDSProgressIndicator extends LitElement {
  /**
   * Determines whether or not the progress indicator should be rendered
   * vertically.
   */
  @property({ type: Boolean, reflect: true })
  vertical = false;

  /**
   * Specify whether the progress steps should be split equally in size in the
   * div
   */
  @property({ type: Boolean, reflect: true, attribute: 'space-equally' })
  spaceEqually = false;

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'list');
    }
    super.connectedCallback();
  }

  updated(changedProperties) {
    const spacingValue = this.vertical ? false : this.spaceEqually;
    if (changedProperties.has('vertical')) {
      // Propagate `vertical` attribute to descendants until
      // `:host-context()` gets supported in all major browsers
      forEach(
        this.querySelectorAll(
          (this.constructor as typeof CDSProgressIndicator).selectorStep
        ),
        (item) => {
          (item as CDSProgressStep).vertical = this.vertical;
          (item as CDSProgressStep).spaceEqually = spacingValue;
        }
      );
    }
    if (changedProperties.has('spaceEqually')) {
      // Propagate `spaceEqually` attribute to descendants until
      // `:host-context()` gets supported in all major browsers
      forEach(
        this.querySelectorAll(
          (this.constructor as typeof CDSProgressIndicator).selectorStep
        ),
        (item) => {
          (item as CDSProgressStep).spaceEqually = spacingValue;
        }
      );
    }
  }

  render() {
    return html`<slot></slot>`;
  }

  /**
   * A selector that will return progress steps.
   */
  static get selectorStep() {
    return `${prefix}-progress-step`;
  }

  static styles = styles;
}
