// packages/ibm-products-web-components/.storybook/welcome/welcome.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { query } from 'lit/decorators/query.js';
import '@carbon/web-components/es/components/tag/index.js';
import '@carbon/web-components/es/components/link/index.js';
import '@aarsteinmedia/dotlottie-player/light';
import type DotLottiePlayer from '@aarsteinmedia/dotlottie-player';
import welcomeStyles from './welcome.scss?lit';
import animation from './welcome-lottie.json';
import PackageInfo from '../../package.json';

@customElement('c4p-welcome')
export class CDSWelcome extends LitElement {
  static styles = welcomeStyles;

  @query('dotlottie-player')
  _player!: DotLottiePlayer;

  firstUpdated() {
    this._player.addEventListener('rendered', async () => {
      // Despite the docs saying "Load animation by URL or JSON object" the typing is string
      // https://github.com/aarsteinmedia/dotlottie-player?tab=readme-ov-file#methods
      // @ts-ignore
      await this._player.load(animation);
    });
  }

  render() {
    return html`
      <div class="welcome__container--outer">
        <div class="welcome__container--inner">
          <div class="welcome__col--left">
            <hgroup class="welcome__header">
              <h2 class="welcome__heading">
                Carbon for
                <br />
                IBM Products Web Components
              </h2>
              <h4 class="welcome__subtitle">v${PackageInfo.version}</h4>
              <cds-tag size="md" type="purple" class="welcome__tag--xl">
                Carbon 11
              </cds-tag>
            </hgroup>
            <div class="welcome__links">
              <cds-link
                href="https://pages.github.ibm.com/carbon/ibm-products/"
                class="welcome__link"
                size="lg"
              >
                Website (IBMers only)
              </cds-link>
              <cds-link
                href="https://carbon-for-ibm-products.netlify.app/?path=/story/overview-welcome--overview"
                class="welcome__link"
                size="lg"
              >
                React Storybook
              </cds-link>
              <cds-link
                href="https://github.com/carbon-design-system/ibm-products"
                class="welcome__link"
                size="lg"
              >
                GitHub repo
              </cds-link>
              <cds-link
                href="https://github.com/carbon-design-system/ibm-products/wiki/Carbon-for-IBM-Products-Releases"
                class="welcome__link"
                size="lg"
              >
                Release schedule
              </cds-link>
              <cds-link
                href="https://github.com/carbon-design-system/ibm-products?tab=security-ov-file"
                class="welcome__link"
                size="lg"
              >
                Security policy
              </cds-link>
              <cds-link
                href="https://pages.github.ibm.com/carbon/ibm-products/developing/get-started/"
                class="welcome__link"
                size="lg"
              >
                Get started
              </cds-link>
            </div>
          </div>
          <div class="welcome__col--right">
            <div class="welcome__animation">
              <dotlottie-player autoplay loop></dotlottie-player>
            </div>
          </div>
        </div>
      </div>
    `;
  }
}

// packages/ibm-products/.storybook/Welcome/Welcome.jsx
/**
 * Copyright IBM Corp. 2023, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useRef, useState } from 'react';
import PackageInfo from '../../../ibm-products/package.json';
import { Link, Tag } from '@carbon/react';
import { ArrowRight, Pause, Play } from '@carbon/react/icons';
import lottie from 'lottie-web/build/player/lottie_light';
import WelcomeLottie from './welcome-lottie.json';
import './_storybook-styles.scss';

const Welcome = () => {
  const animationRef = useRef(null);

  // eslint-disable-next-line ssr-friendly/no-dom-globals-in-react-fc
  let prefersReducedMotion = window.matchMedia(
    `(prefers-reduced-motion: reduce)`
  ).matches;

  const [isAnimating, setIsAnimating] = useState(prefersReducedMotion);

  React.useEffect(() => {
    lottie.loadAnimation({
      container: animationRef.current,
      animationData: WelcomeLottie,
      autoplay: !prefersReducedMotion,
    });
  }, [prefersReducedMotion]);

  const toggleAnimation = () => {
    setIsAnimating(!isAnimating);

    if (isAnimating) {
      lottie.play();
    } else {
      lottie.pause();
    }
  };

  return (
    <div className="welcome__container--outer">
      <div className="welcome__container--inner">
        <div className="welcome__col--left">
          <hgroup className="welcome__header">
            <h2 className="welcome__heading">
              Carbon for
              <br />
              IBM Products
            </h2>
            <h4 className="welcome__subtitle">{`v${PackageInfo.version}`}</h4>
            <Tag size="md" type="purple" className="welcome__tag--xl">
              Carbon 11 (v2)
            </Tag>
          </hgroup>
          <div className="welcome__links">
            <Link
              href="https://pages.github.ibm.com/carbon/ibm-products/"
              className="welcome__link"
              renderIcon={ArrowRight}
              size="lg"
            >
              Website (IBMers only)
            </Link>

            <Link
              href="https://ibm-products-web-components.carbondesignsystem.com/"
              className="welcome__link"
              renderIcon={ArrowRight}
              size="lg"
            >
              Web Components Storybook
            </Link>

            <Link
              href="https://github.com/carbon-design-system/ibm-products"
              className="welcome__link"
              renderIcon={ArrowRight}
              size="lg"
            >
              GitHub repo
            </Link>

            <Link
              href="https://github.com/carbon-design-system/ibm-products/wiki/Carbon-for-IBM-Products-Releases"
              className="welcome__link"
              renderIcon={ArrowRight}
              size="lg"
            >
              Release schedule
            </Link>

            <Link
              href="https://github.com/carbon-design-system/ibm-products?tab=security-ov-file"
              className="welcome__link"
              renderIcon={ArrowRight}
              size="lg"
            >
              Security policy
            </Link>

            <Link
              href="https://github.com/carbon-design-system/ibm-products/blob/main/docs/guides/v2.md"
              className="welcome__link"
              renderIcon={ArrowRight}
              size="lg"
            >
              v1 to v2 migration guide
            </Link>
            <Link
              href="https://pages.github.ibm.com/carbon/ibm-products/developing/get-started/"
              className="welcome__link"
              renderIcon={ArrowRight}
              size="lg"
            >
              Get started
            </Link>
          </div>
        </div>
        <div className="welcome__col--right">
          <div ref={animationRef} className="welcome__animation">
            <button
              type="button"
              className="welcome__pause-button"
              onClick={toggleAnimation}
            >
              {isAnimating ? <Play /> : <Pause />}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Welcome;
