// packages/react/src/components/FileUploader/FileUploader-story.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

/* eslint-disable no-console */

import React from 'react';
import { action } from '@storybook/addon-actions';
import {
  withKnobs,
  array,
  boolean,
  number,
  select,
  text,
} from '@storybook/addon-knobs';
import { settings } from 'carbon-components';
import FileUploader, { FileUploaderButton } from '../FileUploader';
import FileUploaderSkeleton from '../FileUploader/FileUploader.Skeleton';
import FileUploaderItem from './FileUploaderItem';
import FileUploaderDropContainer from './FileUploaderDropContainer';
import mdx from './FileUploader.mdx';

const { prefix } = settings;
const buttonKinds = {
  'Primary (primary)': 'primary',
  'Secondary (secondary)': 'secondary',
  'Danger (danger)': 'danger',
  'Ghost (ghost)': 'ghost',
  'Danger Primary (danger--primary)': 'danger--primary',
  'Tertiary (tertiary)': 'tertiary',
};
const sizes = {
  Default: 'default',
  Field: 'field',
  Small: 'small',
};
const filenameStatuses = {
  'Edit (edit)': 'edit',
  'Complete (complete)': 'complete',
  'Uploading (uploading)': 'uploading',
};

const props = {
  fileUploaderButton: () => {
    const buttonKind = select('Button kind (buttonKind)', buttonKinds, '');
    return {
      className: 'bob',
      labelText: text('Label text (labelText)', 'Add files'),
      name: text('Form item name: (name)', ''),
      multiple: boolean('Supports multiple files (multiple)', true),
      disabled: boolean('Disabled (disabled)', false),
      buttonKind: buttonKind || 'primary',
      size: select('Button size (size)', sizes, 'default'),
      disableLabelChanges: boolean(
        'Prevent the label from being replaced with file selected file (disableLabelChanges)',
        false
      ),
      role: text('ARIA role of the button (role)', 'button'),
      tabIndex: number('Tab index (tabIndex)', 0),
      onChange: action('onChange'),
    };
  },
  fileUploader: () => {
    const buttonKind = select(
      'Button kind (buttonKind)',
      {
        'Primary (primary)': 'primary',
        'Tertiary (tertiary)': 'tertiary',
      },
      ''
    );
    return {
      labelTitle: text('The label title (labelTitle)', 'Upload'),
      labelDescription: text(
        'The label description (labelDescription)',
        'only .jpg files at 500mb or less'
      ),
      buttonLabel: text('The button label (buttonLabel)', 'Add files'),
      buttonKind: buttonKind || 'primary',
      size: select('Button size (size)', sizes, 'default'),
      filenameStatus: select(
        'Status for file name (filenameStatus)',
        filenameStatuses,
        'edit'
      ),
      accept: array('Accepted file extensions (accept)', ['.jpg', '.png'], ','),
      name: text('Form item name: (name)', ''),
      multiple: boolean('Supports multiple files (multiple)', true),
      iconDescription: text(
        'Close button icon description (iconDescription)',
        'Clear file'
      ),
      onChange: action('onChange'),
      onClick: action('onClick'),
      onDelete: action('onDelete'),
    };
  },
  fileUploaderItem: () => ({
    name: text('Filename (name)', 'README.md'),
    status: select('Status for file name (status)', filenameStatuses, 'edit'),
    iconDescription: text(
      'Close button icon description (iconDescription)',
      'Clear file'
    ),
    onDelete: action('onDelete'),
    invalid: boolean('Invalid (invalid)', false),
    errorSubject: text(
      'Error subject (errorSubject)',
      'File size exceeds limit'
    ),
    errorBody: text(
      'Error body (errorBody)',
      '500kb max file size. Select a new file and try again.'
    ),
    size: select('FileUploaderItem height (size)', sizes, 'default'),
  }),
  fileUploaderDropContainer: () => ({
    size: select('Filename height (size)', sizes, 'default'),
    labelText: text(
      'Label text (labelText)',
      'Drag and drop files here or click to upload'
    ),
    name: text('Form item name (name)', ''),
    multiple: boolean('Supports multiple files (multiple)', true),
    accept: array(
      'Accepted MIME types or file extensions (accept)',
      ['image/jpeg', 'image/png'],
      ','
    ),
    disabled: boolean('Disabled (disabled)', false),
    role: text('ARIA role of the button (role)', ''),
    tabIndex: number('Tab index (tabIndex)', 0),
    onChange: action('onChange'),
  }),
};

export default {
  title: 'FileUploader',
  decorators: [withKnobs],

  parameters: {
    component: FileUploader,
    docs: {
      page: mdx,
    },

    subcomponents: {
      FileUploaderButton,
      FileUploaderSkeleton,
      FileUploaderItem,
      FileUploaderDropContainer,
    },
  },
};

export const _FileUploaderButton = () => (
  <FileUploaderButton {...props.fileUploaderButton()} />
);

_FileUploaderButton.storyName = 'FileUploaderButton';

export const _FileUploader = () => {
  return (
    <div className={`${prefix}--file__container`}>
      <FileUploader {...props.fileUploader()} />
    </div>
  );
};

_FileUploader.storyName = 'FileUploader';

export const _FileUploaderItem = () => (
  <FileUploaderItem {...props.fileUploaderItem()} />
);

_FileUploaderItem.storyName = 'FileUploaderItem';

export const _FileUploaderDropContainer = () => (
  <FileUploaderDropContainer {...props.fileUploaderDropContainer()} />
);

_FileUploaderDropContainer.storyName = 'FileUploaderDropContainer';

export const DragAndDropUploadContainerExampleApplication = () =>
  require('./stories/drop-container').default(
    props.fileUploaderDropContainer()
  );

DragAndDropUploadContainerExampleApplication.storyName =
  'Drag and drop upload container example application';

export const Skeleton = () => (
  <div style={{ width: '500px' }}>
    <FileUploaderSkeleton />
  </div>
);

Skeleton.storyName = 'skeleton';

// web-components/packages/carbon-web-components/src/components/file-uploader/file-uploader-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { action } from '@storybook/addon-actions';
import { boolean, select } from '@storybook/addon-knobs';
import { ifDefined } from 'lit/directives/if-defined.js';
import { prefix } from '../../globals/settings';
import './index';
import './demo-file-uploader';
import { FILE_UPLOADER_ITEM_STATE } from './file-uploader-item';
import { BUTTON_KIND, BUTTON_SIZE } from '../button/button';
import textNullable from '../../../.storybook/knob-text-nullable';
import storyDocs from './file-uploader-story.mdx';

const kind = {
  [`Primary button (${BUTTON_KIND.PRIMARY})`]: BUTTON_KIND.PRIMARY,
  [`Secondary button (${BUTTON_KIND.SECONDARY})`]: BUTTON_KIND.SECONDARY,
  [`Tertiary button (${BUTTON_KIND.TERTIARY})`]: BUTTON_KIND.TERTIARY,
  [`Danger primary button (${BUTTON_KIND.DANGER_PRIMARY})`]:
    BUTTON_KIND.DANGER_PRIMARY,
  [`Danger button (${BUTTON_KIND.DANGER})`]: BUTTON_KIND.DANGER,
  [`Ghost button (${BUTTON_KIND.GHOST})`]: BUTTON_KIND.GHOST,
};

const states = {
  [`Upload in progress (${FILE_UPLOADER_ITEM_STATE.UPLOADING})`]:
    FILE_UPLOADER_ITEM_STATE.UPLOADING,
  [`Upload complete (${FILE_UPLOADER_ITEM_STATE.COMPLETE})`]:
    FILE_UPLOADER_ITEM_STATE.COMPLETE,
  [`Edit upload (${FILE_UPLOADER_ITEM_STATE.EDIT})`]:
    FILE_UPLOADER_ITEM_STATE.EDIT,
};

const sizes = {
  [`sm (${BUTTON_SIZE.SMALL})`]: BUTTON_SIZE.SMALL,
  [`md (${BUTTON_SIZE.MEDIUM})`]: BUTTON_SIZE.MEDIUM,
  [`lg (${BUTTON_SIZE.LARGE})`]: BUTTON_SIZE.LARGE,
};

export const Default = () => {
  return html`
    <cds-ce-demo-file-uploader
      accept="image/jpeg"
      button
      label-description="Max file size is 500mb. Only .jpg files are supported."
      label-title="Upload files">
    </cds-ce-demo-file-uploader>
  `;
};

Default.storyName = 'Default';

export const DragAndDropUploadContainerExampleApplication = () => {
  return html`
    <cds-ce-demo-file-uploader
      accept="image/jpeg image/png"
      label-description="Max file size is 500kb. Supported file types are .jpg and .png."
      label-title="Upload files">
    </cds-ce-demo-file-uploader>
  `;
};

DragAndDropUploadContainerExampleApplication.storyName =
  'Drag And Drop Upload Container Example Application';

export const FileUploaderDropContainer = () => {
  return html`
    <cds-file-uploader-drop-container accept="image/jpeg image/png">
      Drag and drop files here or click to upload
    </cds-file-uploader-drop-container>
  `;
};

FileUploaderDropContainer.storyName = 'File Uploader Drop Container';

export const FileUploaderItem = () => {
  return html`
    <cds-file-uploader-item state="${FILE_UPLOADER_ITEM_STATE.EDIT}">
      README.md
    </cds-file-uploader-item>
  `;
};

FileUploaderItem.storyName = 'File Uploader Item';

export const Skeleton = () => {
  return html` <cds-file-uploader-skeleton></cds-file-uploader-skeleton> `;
};

export const Playground = (args) => {
  const {
    buttonKind,
    buttonLabel,
    disabled,
    state,
    iconDescription,
    labelDescription,
    labelTitle,
    multiple,
    onDelete,
    onChange,
    name,
    size,
  } = args?.[`${prefix}-file-uploader`] ?? {};

  return html`
    <cds-ce-demo-file-uploader
      button-kind="${buttonKind}"
      button-label="${buttonLabel}"
      input-state="${state}"
      icon-description="${iconDescription}"
      accept="image/jpeg"
      button
      ?disabled="${disabled}"
      label-description="${ifDefined(labelDescription)}"
      label-title="${ifDefined(labelTitle)}"
      ?multiple="${multiple}"
      size="${ifDefined(size)}"
      input-name="${ifDefined(name)}"
      @cds-file-uploader-item-deleted="${onDelete}"
      @cds-file-uploader-drop-container-changed="${onChange}">
    </cds-ce-demo-file-uploader>
  `;
};

Playground.parameters = {
  knobs: {
    [`${prefix}-file-uploader`]: () => ({
      buttonKind: select(
        'Button kind (button-kind)',
        kind,
        BUTTON_KIND.PRIMARY
      ),
      buttonLabel: textNullable('Button Label', 'Add file'),
      disabled: boolean('Disabled (disabled)', false),
      state: select(
        'File uploader item state (state)',
        states,
        FILE_UPLOADER_ITEM_STATE.UPLOADING
      ),
      iconDescription: textNullable(
        'Icon description (icon-description)',
        'Delete file'
      ),
      labelDescription: textNullable(
        'Label description (label-description)',
        'Max file size is 500mb. Only .jpg files are supported.'
      ),
      labelTitle: textNullable('Label title (label-title)', 'Upload files'),
      name: textNullable('Input name (name)', ''),
      onDelete: action('cds-file-uploader-item-deleted'),
      onChange: action('cds-drop-container-changed'),
      multiple: boolean('Multiple (multiple)', false),
      size: select('Size (size)', sizes, BUTTON_SIZE.MEDIUM),
    }),
  },
};

export default {
  title: 'Components/File uploader',
  parameters: {
    ...storyDocs.parameters,
  },
};
