// packages/react/src/components/Pagination/Pagination.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React, { Component } from 'react';
import classnames from 'classnames';
import { CaretRight16, CaretLeft16 } from '@carbon/icons-react';
import { settings } from 'carbon-components';
import Select from '../Select';
import SelectItem from '../SelectItem';
import { equals } from '../../tools/array';
import Button from '../Button';
import deprecate from '../../prop-types/deprecate';

const { prefix } = settings;

let instanceId = 0;

const mapPageSizesToObject = (sizes) => {
  return typeof sizes[0] === 'object' && sizes[0] !== null
    ? sizes
    : sizes.map((size) => ({ text: size, value: size }));
};

export default class Pagination extends Component {
  constructor(props) {
    super(props);
    const { pageSizes: _pageSizes, page, pageSize } = this.props;

    const pageSizes = mapPageSizesToObject(_pageSizes);

    this.state = {
      page: page,
      pageSize:
        pageSize && pageSizes.some((sizeObj) => pageSize === sizeObj.value)
          ? pageSize
          : pageSizes[0].value,
      prevPageSizes: pageSizes,
      prevPage: page,
      prevPageSize: pageSize,
    };
    this.uniqueId = ++instanceId;
  }

  static propTypes = {
    /**
     * The description for the backward icon.
     */
    backwardText: PropTypes.string,

    /**
     * The CSS class names.
     */
    className: PropTypes.string,

    /**
     * `true` if the backward/forward buttons, as well as the page select elements,  should be disabled.
     */
    disabled: PropTypes.bool,

    /**
     * The description for the forward icon.
     */
    forwardText: PropTypes.string,

    /**
     * The unique ID of this component instance.
     */
    id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),

    // TODO: remove when v9 is deprecated
    /**
     * `true` if the current page should be the last page.
     */
    isLastPage: PropTypes.bool,

    /**
     * The function returning a translatable text showing where the current page is,
     * in a manner of the range of items.
     */
    itemRangeText: PropTypes.func,

    /**
     * A variant of `itemRangeText`, used if the total number of items is unknown.
     */
    itemText: PropTypes.func,

    /**
     * The translatable text indicating the number of items per page.
     */
    itemsPerPageText: PropTypes.string,

    /**
     * The callback function called when the current page changes.
     */
    onChange: PropTypes.func,

    /**
     * The current page.
     */
    page: PropTypes.number,

    /**
     * Deprecated; `true` if the select box to change the page should be disabled.
     */
    pageInputDisabled: deprecate(
      PropTypes.bool,
      `The prop \`pageInputDisabled\` for Pagination has been deprecated, as the feature of \`pageInputDisabled\` has been combined with the general \`disabled\` prop.`
    ),

    pageNumberText: PropTypes.string,

    /**
     * A function returning PII showing where the current page is.
     */
    pageRangeText: PropTypes.func,

    /**
     * The number dictating how many items a page contains.
     */
    pageSize: PropTypes.number,

    /**
     * The choices for `pageSize`.
     */
    pageSizes: PropTypes.oneOfType([
      PropTypes.arrayOf(PropTypes.number),
      PropTypes.arrayOf(
        PropTypes.shape({
          text: PropTypes.text,
          value: PropTypes.number,
        })
      ),
    ]).isRequired,

    /**
     * The translatable text showing the current page.
     */
    pageText: PropTypes.func,

    /**
     * `true` if the total number of items is unknown.
     */
    pagesUnknown: PropTypes.bool,

    /**
     * The total number of items.
     */
    totalItems: PropTypes.number,
  };

  static defaultProps = {
    backwardText: 'Previous page',
    itemRangeText: (min, max, total) => `${min}–${max} of ${total} items`,
    forwardText: 'Next page',
    itemsPerPageText: 'Items per page:',
    pageNumberText: 'Page Number',
    pageRangeText: (current, total) =>
      `of ${total} ${total === 1 ? 'page' : 'pages'}`,
    disabled: false,
    page: 1,
    pagesUnknown: false,
    isLastPage: false,
    itemText: (min, max) => `${min}–${max} items`,
    pageText: (page) => `page ${page}`,
  };

  static getDerivedStateFromProps(
    { pageSizes: _pageSizes, page, pageSize },
    state
  ) {
    const {
      prevPageSizes,
      prevPage,
      prevPageSize,
      page: currentPage,
      pageSize: currentPageSize,
    } = state;

    const pageSizes = mapPageSizesToObject(_pageSizes);
    const pageSizesValues = pageSizes.map((sizeObj) => sizeObj.value);
    const prevPageSizesValues = prevPageSizes.map((sizeObj) => sizeObj.value);

    const pageSizesChanged = !equals(pageSizesValues, prevPageSizesValues);
    if (
      pageSizesChanged &&
      !pageSizes.some((sizeObj) => pageSize === sizeObj.value)
    ) {
      pageSize = pageSizes[0].value;
    }
    const pageChanged = page !== prevPage;
    const pageSizeChanged = pageSize !== prevPageSize;
    return !pageSizesChanged && !pageChanged && !pageSizeChanged
      ? null
      : {
          page: (pageSizeChanged && 1) || (pageChanged && page) || currentPage,
          pageSize: pageSizeChanged ? pageSize : currentPageSize,
          prevPageSizes: pageSizes,
          prevPage: page,
          prevPageSize: pageSize,
        };
  }

  handleSizeChange = (evt) => {
    const pageSize = Number(evt.target.value);
    this.setState({ pageSize, page: 1 });
    this.props.onChange({ page: 1, pageSize });
  };

  handlePageChange = (evt) => {
    this.setState({ page: evt.target.value });
  };

  handlePageInputChange = (evt) => {
    const page = Number(evt.target.value);
    if (
      page > 0 &&
      page <=
        Math.max(Math.ceil(this.props.totalItems / this.state.pageSize), 1)
    ) {
      this.setState({ page });
      this.props.onChange({
        page,
        pageSize: this.state.pageSize,
      });
    }
  };

  incrementPage = () => {
    const page = this.state.page + 1;
    this.setState({ page });
    this.props.onChange({ page, pageSize: this.state.pageSize });
  };

  decrementPage = () => {
    const page = this.state.page - 1;
    this.setState({ page });
    this.props.onChange({ page, pageSize: this.state.pageSize });
  };

  renderSelectItems = (total) => {
    let counter = 1;
    let itemArr = [];
    while (counter <= total) {
      itemArr.push(
        <SelectItem key={counter} value={counter} text={String(counter)} />
      );
      counter++;
    }
    return itemArr;
  };

  render() {
    const {
      backwardText,
      className,
      forwardText,
      id,
      itemsPerPageText,
      itemRangeText,
      pageRangeText,
      pageSize, // eslint-disable-line no-unused-vars
      pageSizes: _pageSizes,
      itemText,
      pageText,
      pageNumberText, // eslint-disable-line no-unused-vars
      pagesUnknown,
      isLastPage,
      disabled,
      pageInputDisabled,
      totalItems,
      onChange, // eslint-disable-line no-unused-vars
      page: pageNumber, // eslint-disable-line no-unused-vars
      ...other
    } = this.props;

    const classNames = classnames(`${prefix}--pagination`, className);
    const inputId = id || this.uniqueId;
    const { page: statePage, pageSize: statePageSize } = this.state;
    const totalPages = Math.max(Math.ceil(totalItems / statePageSize), 1);
    const backButtonDisabled = disabled || statePage === 1;
    const backButtonClasses = classnames(
      `${prefix}--pagination__button`,
      `${prefix}--pagination__button--backward`,
      {
        [`${prefix}--pagination__button--no-index`]: backButtonDisabled,
      }
    );
    const forwardButtonDisabled = disabled || statePage === totalPages;
    const forwardButtonClasses = classnames(
      `${prefix}--pagination__button`,
      `${prefix}--pagination__button--forward`,
      {
        [`${prefix}--pagination__button--no-index`]: forwardButtonDisabled,
      }
    );
    const selectItems = this.renderSelectItems(totalPages);
    const pageSizes = mapPageSizesToObject(_pageSizes);

    return (
      <div className={classNames} {...other}>
        <div className={`${prefix}--pagination__left`}>
          <label
            id={`${prefix}-pagination-select-${inputId}-count-label`}
            className={`${prefix}--pagination__text`}
            htmlFor={`${prefix}-pagination-select-${inputId}`}>
            {itemsPerPageText}
          </label>
          <Select
            id={`${prefix}-pagination-select-${inputId}`}
            className={`${prefix}--select__item-count`}
            labelText=""
            hideLabel
            noLabel
            inline
            onChange={this.handleSizeChange}
            disabled={pageInputDisabled || disabled}
            value={statePageSize}>
            {pageSizes.map((sizeObj) => (
              <SelectItem
                key={sizeObj.value}
                value={sizeObj.value}
                text={String(sizeObj.text)}
              />
            ))}
          </Select>
          <span
            className={`${prefix}--pagination__text ${prefix}--pagination__items-count`}>
            {pagesUnknown
              ? itemText(
                  statePageSize * (statePage - 1) + 1,
                  statePage * statePageSize
                )
              : itemRangeText(
                  Math.min(statePageSize * (statePage - 1) + 1, totalItems),
                  Math.min(statePage * statePageSize, totalItems),
                  totalItems
                )}
          </span>
        </div>
        <div className={`${prefix}--pagination__right`}>
          <Select
            id={`${prefix}-pagination-select-${inputId}-right`}
            className={`${prefix}--select__page-number`}
            labelText={`Page number, of ${totalPages} pages`}
            inline
            hideLabel
            onChange={this.handlePageInputChange}
            value={statePage}
            disabled={pageInputDisabled || disabled}>
            {selectItems}
          </Select>
          <span className={`${prefix}--pagination__text`}>
            {pagesUnknown
              ? pageText(statePage)
              : pageRangeText(statePage, totalPages)}
          </span>
          <div className={`${prefix}--pagination__control-buttons`}>
            <Button
              kind="ghost"
              className={backButtonClasses}
              hasIconOnly
              renderIcon={CaretLeft16}
              iconDescription={backwardText}
              tooltipAlignment="center"
              tooltipPosition="top"
              onClick={this.decrementPage}
              disabled={backButtonDisabled}
            />
            <Button
              kind="ghost"
              className={forwardButtonClasses}
              hasIconOnly
              renderIcon={CaretRight16}
              iconDescription={forwardText}
              tooltipAlignment="end"
              tooltipPosition="top"
              onClick={this.incrementPage}
              disabled={forwardButtonDisabled || isLastPage}
            />
          </div>
        </div>
      </div>
    );
  }
}

// web-components/packages/carbon-web-components/src/components/pagination/pagination.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property, customElement, query } from 'lit/decorators.js';
import CaretLeft16 from '@carbon/icons/lib/caret--left/16';
import CaretRight16 from '@carbon/icons/lib/caret--right/16';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import HostListenerMixin from '../../globals/mixins/host-listener';
import HostListener from '../../globals/decorators/host-listener';
import styles from './pagination.scss';
import { PAGINATION_SIZE } from './defs';
import CDSSelect from '../select/select';
import '../button/index';

/**
 * Pagination UI.
 *
 * @element cds-pagination
 * @slot page-sizes-select - Where to put in the `<page-sizes-select>`.
 * @fires cds-pages-select-changed - The custom event fired after the current page is changed from `<cds-pages-select>`.
 * @fires cds-page-sizes-select-changed
 *   The custom event fired after the number of rows per page is changed from `<cds-page-sizes-select>`.
 */
@customElement(`${prefix}-pagination`)
class CDSPagination extends FocusMixin(HostListenerMixin(LitElement)) {
  @query(`${prefix}-select`)
  private _pageSizeSelect!: HTMLElement;

  private _handleSlotChange({ target }: Event) {
    const content = (target as HTMLSlotElement)
      .assignedNodes()
      .filter(
        (node) => node.nodeType !== Node.TEXT_NODE || node!.textContent!.trim()
      );

    content.forEach((item) => {
      this._pageSizeSelect.appendChild(item);
    });
  }

  /**
   * @returns Page status text.
   */
  private _renderStatusText() {
    const {
      start,
      pageSize,
      totalItems,
      pagesUnknown,
      formatStatusWithDeterminateTotal,
      formatStatusWithIndeterminateTotal,
    } = this;
    // * Regular: `1-10 of 100 items`
    // * Indeterminate total: `Item 1-10` (`Item 11-` at the last page)
    const end = Math.min(
      start + pageSize,
      totalItems == null ? Infinity : totalItems
    );
    const format =
      totalItems == null || pagesUnknown
        ? formatStatusWithIndeterminateTotal
        : formatStatusWithDeterminateTotal;

    // `start`/`end` properties starts with zero, whereas we want to show number starting with 1
    return format({ start: start + 1, end, count: totalItems });
  }

  /**
   * Handles user-initiated change in the row number the current page starts with.
   *
   * @param start The new current row number, index that starts with zero.
   */
  private _handleUserInitiatedChangeStart(start: number) {
    this.start = start;
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSPagination).eventChangeCurrent,
        {
          bubbles: true,
          composed: true,
          detail: {
            page: this.page,
            pageSize: this.pageSize,
          },
        }
      )
    );
  }

  /**
   * Handles `click` event on the previous button.
   */
  private _handleClickPrevButton() {
    const { start: oldStart, pageSize } = this;
    this.page--;
    const newStart = Math.max(oldStart - pageSize, 0);
    if (newStart !== oldStart) {
      this._handleUserInitiatedChangeStart(newStart);
    }
  }

  /**
   * Handles `click` event on the next button.
   */
  private _handleClickNextButton() {
    const { start: oldStart, pageSize, totalItems } = this;
    this.page++;
    const newStart = oldStart + pageSize;
    if (newStart < (totalItems == null ? Infinity : totalItems)) {
      this._handleUserInitiatedChangeStart(newStart);
    }
  }

  /**
   * Handles user-initiated change in number of rows per page.
   *
   * @param event The event.
   */
  @HostListener('eventChangeSelect')
  // @ts-ignore: The decorator refers to this method but TS thinks this method is not referred to
  private _handleChangeSelector(event) {
    const { value } = event.detail;
    const { totalItems, pageSize } = this;

    if (event.composedPath()[0] === this._pageSizeSelect) {
      this.pageSize = parseInt(value);
      this.totalPages = Math.ceil(totalItems / pageSize);
      this.page = 1;
      this.start = 0;
    } else {
      this.page = value;
      this._handleUserInitiatedChangeStart((value - 1) * pageSize);
    }
  }

  /**
   * The assistive text for the button to go to previous page.
   */
  @property({ attribute: 'backward-text' })
  backwardText = 'Previous page';

  /**
   * The current page
   */
  @property({ type: Number, reflect: true })
  page = 1;

  /**
   * The formatter for the assistive text for screen readers to announce.
   * Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatLabelText = ({ count }) =>
    `Page number, of ${count} page${count <= 1 ? '' : 's'}`;

  /**
   * The formatter, used with determinate the total pages. Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatStatusWithDeterminateTotal = ({ start, end, count }) =>
    `${start}–${end} of ${count} item${count <= 1 ? '' : 's'}`;

  /**
   * The formatter, used with indeterminate the total pages. Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatStatusWithIndeterminateTotal = ({ start, end, count }) =>
    end == null
      ? `Item ${start}–`
      : `${start}–${end} item${count <= 1 ? '' : 's'}`;

  /**
   * The formatter for the text next to the select box. Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatSupplementalText = ({ count }) =>
    this.pagesUnknown || !this.totalItems
      ? `page`
      : `of ${count} page${count <= 1 ? '' : 's'}`;
  /**
   * `true` to explicitly state that user is at the last page.
   */
  @property({ type: Boolean, attribute: 'is-last-page' })
  isLastPage!: boolean;

  /**
   * The translatable text indicating the number of items per page.
   */
  @property({ attribute: 'items-per-page-text' })
  itemsPerPageText = 'Items per page:';

  /**
   * `true` if the pagination UI should be disabled.
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /**
   * The assistive text for the button to go to next page.
   */
  @property({ attribute: 'forward-text' })
  forwardText = 'Next page';

  /**
   * true if the select box to change the page should be disabled.
   */
  @property({ attribute: 'page-input-disabled' })
  pageInputDisabled;

  /**
   * Number of items per page.
   */
  @property({ type: Number, attribute: 'page-size', reflect: true })
  pageSize = 10;

  /**
   * true if the select box to change the items per page should be disabled.
   */
  @property({ type: Boolean, attribute: 'page-size-input-disabled' })
  pageSizeInputDisabled;

  /**
   * The label text for the UI to select page size.
   */
  @property({ attribute: 'page-size-label-text' })
  pageSizeLabelText!: string;

  /**
   * true if the total number of items is unknown.
   */
  @property({ type: Boolean, reflect: true, attribute: 'pages-unknown' })
  pagesUnknown = false;

  /**
   * Specify the size of the Pagination.
   */
  @property({ reflect: true })
  size = PAGINATION_SIZE.MEDIUM;

  /**
   * The row number where current page start with, index that starts with zero.
   */
  @property({ type: Number })
  start = 0;

  /**
   * The number of total items.
   */
  @property({ type: Number, attribute: 'total-items' })
  totalItems!: number;

  /**
   * The number of total pages.
   */
  @property({ type: Number })
  totalPages = 1;

  updated(changedProperties) {
    const { page, pageSize, totalItems } = this;
    const { selectorPageSizesSelect, selectorPagesSelect } = this
      .constructor as typeof CDSPagination;

    if (changedProperties.has('pageSize')) {
      (this.shadowRoot!.querySelector(selectorPageSizesSelect) as any).value =
        pageSize;
    }
    if (changedProperties.has('pageSize') || changedProperties.has('start')) {
      this.totalPages = Math.ceil(totalItems / pageSize);
      (this.shadowRoot!.querySelector(selectorPagesSelect) as CDSSelect).value =
        this.page.toString();
    }

    if (changedProperties.has('page')) {
      this._handleUserInitiatedChangeStart((page - 1) * pageSize);
    }
  }

  render() {
    const {
      page,
      disabled,
      forwardText,
      backwardText,
      itemsPerPageText,
      pageInputDisabled,
      pageSize,
      pageSizeInputDisabled,
      pagesUnknown,
      size,
      start,
      totalItems,
      totalPages,
      _handleClickPrevButton: handleClickPrevButton,
      _handleClickNextButton: handleClickNextButton,
      _handleSlotChange: handleSlotChange,
      formatLabelText,
      formatSupplementalText,
    } = this;

    const { isLastPage = start + pageSize >= totalItems } = this;
    const prevButtonDisabled = disabled || start === 0;
    const nextButtonDisabled = disabled || isLastPage;

    const prevButtonClassMap = {
      [`${prefix}--btn`]: true,
      [`${prefix}--btn--icon-only`]: true,
      [`${prefix}--pagination__button`]: true,
      [`${prefix}--pagination__button--backward`]: true,
      [`${prefix}--pagination__button--no-index`]: prevButtonDisabled,
      [`${prefix}--btn--${size}`]: true,
      [`${prefix}--btn--ghost`]: true,
    };
    const nextButtonClassMap = {
      [`${prefix}--btn`]: true,
      [`${prefix}--btn--icon-only`]: true,
      [`${prefix}--pagination__button`]: true,
      [`${prefix}--pagination__button--forward`]: true,
      [`${prefix}--pagination__button--no-index`]: nextButtonDisabled,
      [`${prefix}--btn--${size}`]: true,
      [`${prefix}--btn--ghost`]: true,
    };

    const prevButtonClasses = Object.entries(prevButtonClassMap)
      .filter(([, value]) => value === true)
      .map(([key]) => key)
      .join(' ');
    const nextButtonClasses = Object.entries(nextButtonClassMap)
      .filter(([, value]) => value === true)
      .map(([key]) => key)
      .join(' ');

    return html`
      <div class="${prefix}--pagination__left">
        <label for="select" class="${prefix}--pagination__text"
          ><slot name="label-text">${itemsPerPageText}</slot></label
        >
        <cds-select
          ?disabled=${disabled || pageSizeInputDisabled}
          id="page-size-select"
          left-select
          pagination
          inline
          value="${pageSize}">
          <slot @slotchange=${handleSlotChange}></slot>
        </cds-select>
        <span
          class="${prefix}--pagination__text ${prefix}--pagination__items-count"
          >${this._renderStatusText()}</span
        >
      </div>
      <div class="${prefix}--pagination__right">
        <label for="select" class="${prefix}--label ${prefix}--visually-hidden">
          ${formatLabelText({ count: totalPages })}
        </label>
        ${pagesUnknown || !totalItems
          ? html`
              <span
                class="${prefix}--pagination__text ${prefix}--pagination__page-text"
                >${formatSupplementalText({ count: totalPages })}</span
              >

              <cds-select
                ?disabled=${disabled || pageInputDisabled}
                id="pages-select"
                pagination
                inline
                value="${page}">
                ${Array.from(new Array(totalPages)).map(
                  (_item, index) =>
                    html`
                      <cds-select-item value="${index + 1}">
                        ${index + 1}
                      </cds-select-item>
                    `
                )}
              </cds-select>
            `
          : html`
              <cds-select
                ?disabled=${disabled || pageInputDisabled}
                id="pages-select"
                pagination
                inline
                value="${page}">
                ${Array.from(new Array(totalPages)).map(
                  (_item, index) =>
                    html`
                      <cds-select-item value="${index + 1}">
                        ${index + 1}
                      </cds-select-item>
                    `
                )}
              </cds-select>
              <span class="${prefix}--pagination__text"
                >${formatSupplementalText({ count: totalPages })}</span
              >
            `}

        <div class="${prefix}--pagination__control-buttons">
          <cds-button
            pagination
            ?disabled="${prevButtonDisabled}"
            button-class-name="${prevButtonClasses}"
            tooltip-text="${backwardText}"
            @click="${handleClickPrevButton}">
            ${CaretLeft16({ slot: 'icon' })}
          </cds-button>
          <cds-button
            tooltip-position="top-right"
            pagination
            ?disabled="${nextButtonDisabled}"
            button-class-name="${nextButtonClasses}"
            tooltip-text="${forwardText}"
            @click="${handleClickNextButton}">
            ${CaretRight16({ slot: 'icon' })}
          </cds-button>
        </div>
      </div>
    `;
  }

  /**
   * A selector that will return the select box for the current page.
   */
  static get selectorPagesSelect() {
    return `${prefix}-select#pages-select`;
  }

  /**
   * A selector that will return the select box for page sizes.
   */
  static get selectorPageSizesSelect() {
    return `${prefix}-select`;
  }

  /**
   * The name of the custom event fired after the current row number is changed.
   */
  static get eventChangeCurrent() {
    return `${prefix}-pagination-changed-current`;
  }

  /**
   * The name of the custom event fired after the number of rows per page is changed from `<cds-page-sizes-select>`.
   */
  static get eventChangeSelect() {
    return `${prefix}-select-selected`;
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSPagination;
