// web-components/packages/carbon-web-components/src/components/skeleton-text/skeleton-text-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { boolean, number, select, text } from '@storybook/addon-knobs';
import { ifDefined } from 'lit/directives/if-defined.js';
import { prefix } from '../../globals/settings';
import { SKELETON_TEXT_TYPE } from './skeleton-text';
import storyDocs from './skeleton-text-story.mdx';

const types = {
  Regular: null,
  [`Heading (${SKELETON_TEXT_TYPE.HEADING})`]: SKELETON_TEXT_TYPE.HEADING,
};

export const Default = (args) => {
  const { type } = args?.[`${prefix}-skeleton-text`] ?? {};
  return html`
    <cds-skeleton-text type="${ifDefined(type)}"></cds-skeleton-text>
  `;
};

Default.parameters = {
  knobs: {
    [`${prefix}-skeleton-text`]: () => ({
      type: select('Skeleton text type (type)', types, null),
    }),
  },
};

export const Lines = (args) => {
  const { paragraph, lineCount, width } =
    args?.[`${prefix}-skeleton-text`] ?? {};
  return html`
    <cds-skeleton-text
      type="line"
      ?paragraph="${paragraph}"
      lineCount="${lineCount}"
      width="${width}"></cds-skeleton-text>
  `;
};

Lines.parameters = {
  knobs: {
    [`${prefix}-skeleton-text`]: () => ({
      paragraph: boolean('Use multiple lines of text (paragraph)', true),
      lineCount: number('The number of lines in a paragraph (lineCount)', 3),
      width: text(
        'Width (in px or %) of single line of text or max-width of paragraph lines (width)',
        '100%'
      ),
    }),
  },
};

export default {
  title: 'Components/Skeleton text',
  parameters: {
    ...storyDocs.parameters,
    percy: {
      skip: true,
    },
  },
};

// packages/react/src/components/SkeletonText/SkeletonText-story.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

/* eslint-disable no-console */

import React from 'react';

import { withKnobs, boolean, number, select } from '@storybook/addon-knobs';
import SkeletonText from '../SkeletonText';
import mdx from './SkeletonText.mdx';

const widths = {
  '100%': '100%',
  '250px': '250px',
};

const props = () => ({
  heading: boolean('Skeleton text at a larger size (heading)'),
  paragraph: boolean('Use multiple lines of text (paragraph)'),
  lineCount: number('The number of lines in a paragraph (lineCount)', 3),
  width: select(
    'Width (in px or %) of single line of text or max-width of paragraph lines (width)',
    widths,
    '100%'
  ),
});

export default {
  title: 'Components/Skeleton/SkeletonText',
  component: SkeletonText,
  decorators: [withKnobs],
  parameters: {
    docs: {
      page: mdx,
    },
  },
};

export const Default = () => (
  <div style={{ width: '300px' }}>
    <SkeletonText {...props()} />
  </div>
);
