// packages/react/src/components/UIShell/SideNavDivider.js
/**
 * Copyright IBM Corp. 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { settings } from 'carbon-components';
import cx from 'classnames';
import PropTypes from 'prop-types';
import React from 'react';

const { prefix } = settings;

const SideNavDivider = ({ className }) => {
  const classNames = cx(`${prefix}--side-nav__divider`, className);
  return <li role="separator" className={classNames} />;
};

SideNavDivider.propTypes = {
  /**
   * Provide an optional class to be applied to the containing node
   */
  className: PropTypes.string,
};

export default SideNavDivider;

// packages/web-components/src/components/ui-shell/side-nav-divider.ts
/**
 * Copyright IBM Corp. 2021, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './side-nav.scss?lit';

/**
 * A divider in side nav.
 *
 * @element cds-side-nav-divider
 */
class CDSSideNavDivider extends LitElement {
  static is = `${prefix}-side-nav-divider`;

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'separator');
    }
    super.connectedCallback();
  }

  static styles = styles;
}

export default CDSSideNavDivider;
