// packages/web-components/src/components/tag/tag-skeleton.ts
/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { prefix } from '../../globals/settings';
import { TAG_SIZE } from './defs';
import styles from './tag.scss?lit';

/**
 * Skeleton of tag.
 *
 * @element cds-tag-skeleton
 */
export default class CDSTagSkeleton extends LitElement {
  static is = `${prefix}-tag-skeleton`;

  /**
   * Specify the size of the Tag. Currently supports either `sm`,
   * `md` (default) or `lg` sizes.
   */
  @property({ reflect: true, type: String })
  size = TAG_SIZE.SMALL;

  render() {
    const tagClasses = classMap({
      [`${prefix}--tag`]: true,
      [`${prefix}--skeleton`]: true,
      [`${prefix}--layout--size-${this.size}`]: this.size,
    });
    return html` <span class="${tagClasses}"></span> `;
  }

  static styles = styles;
}

// packages/react/src/components/Tag/Tag.Skeleton.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import classNames from 'classnames';
import { usePrefix } from '../../internal/usePrefix';

export interface TagSkeletonProps
  extends React.HTMLAttributes<HTMLSpanElement> {
  /**
   * Specify an optional className to add.
   */
  className?: string;

  /**
   * Specify the size of the Tag. Currently supports either `sm` or
   * default sizes.
   */
  size?: 'sm';
}

function TagSkeleton({ className, size, ...rest }: TagSkeletonProps) {
  const prefix = usePrefix();
  const tagClasses = classNames(
    `${prefix}--tag`,
    `${prefix}--skeleton`,
    className,
    {
      [`${prefix}--tag--${size}`]: size, // TODO: V12 - Remove this class
      [`${prefix}--layout--size-${size}`]: size,
    }
  );
  return <span className={tagClasses} {...rest} />;
}

TagSkeleton.propTypes = {
  /**
   * Specify an optional className to add.
   */
  className: PropTypes.string,

  /**
   * Specify the size of the Tag. Currently supports either `sm` or
   * default sizes.
   */
  size: PropTypes.oneOf(['sm']),
};

export default TagSkeleton;
export { TagSkeleton };
