// web-components/packages/carbon-web-components/src/components/skeleton-placeholder/skeleton-placeholder.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import styles from './skeleton-placeholder.scss';

const { prefix } = settings;

/**
 * Skeleton placeholder.
 *
 * @element bx-skeleton-placeholder
 */
@customElement(`${prefix}-skeleton-placeholder`)
class BXSkeletonPlaceholder extends LitElement {
  render() {
    return html`
      <div class="${prefix}--skeleton__placeholder"></div>
    `;
  }

  static styles = styles;
}

export default BXSkeletonPlaceholder;

// packages/react/src/components/SkeletonPlaceholder/SkeletonPlaceholder.js
/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import { settings } from 'carbon-components';

const { prefix } = settings;

const SkeletonPlaceholder = ({ className, ...other }) => {
  const skeletonPlaceholderClasses = classNames({
    [`${prefix}--skeleton__placeholder`]: true,
    [className]: className,
  });

  return <div className={skeletonPlaceholderClasses} {...other} />;
};

SkeletonPlaceholder.propTypes = {
  /**
   * the class to be applied to the component
   */
  className: PropTypes.string,
};

export default SkeletonPlaceholder;
