// web-components/packages/carbon-web-components/src/components/skeleton-placeholder/skeleton-placeholder.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import styles from './skeleton-placeholder.scss';

const { prefix } = settings;

/**
 * Skeleton placeholder.
 *
 * @element bx-skeleton-placeholder
 */
@customElement(`${prefix}-skeleton-placeholder`)
class BXSkeletonPlaceholder extends LitElement {
  render() {
    return html`
      <div class="${prefix}--skeleton__placeholder"></div>
    `;
  }

  static styles = styles;
}

export default BXSkeletonPlaceholder;

// packages/react/src/components/SkeletonPlaceholder/SkeletonPlaceholder.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import { usePrefix } from '../../internal/usePrefix';

export interface SkeletonPlaceholderProps {
  /**
   * Add a custom class to the component to set the height and width
   */
  className?: string;
}

const SkeletonPlaceholder = ({
  className,
  ...other
}: SkeletonPlaceholderProps) => {
  const prefix = usePrefix();
  const skeletonPlaceholderClasses = classNames(
    {
      [`${prefix}--skeleton__placeholder`]: true,
    },
    className
  );

  return <div className={skeletonPlaceholderClasses} {...other} />;
};

SkeletonPlaceholder.propTypes = {
  /**
   * Add a custom class to the component
   * to set the height and width
   */
  className: PropTypes.string,
};

export default SkeletonPlaceholder;
