// packages/web-components/src/components/tearsheet/tearsheet-footer.ts
/**
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, LitElement } from 'lit';
import { property, query } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import HostListenerMixin from '../../globals/mixins/host-listener';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { classMap } from 'lit-html/directives/class-map.js';
import styles from './tearsheet.scss?lit';
import type { ActionButton, ButtonSize } from '../action-set/index.js';
import {
  tearsheetContext,
  defaultTearsheetState,
  type TearsheetContextValue,
} from './tearsheet-context';
import { consume } from '@lit/context';
import '../action-set/index.js';
import { registerFocusableContainers } from '../../utilities/manageFocusTrap/manageFocusTrap';

const blockClass = `${prefix}--tearsheet`;

/**
 * Tearsheet Footer component - Contains action buttons at the bottom of the tearsheet.
 *
 * @element cds-tearsheet-footer
 * @slot - Default slot for custom footer content (rendered before actions)
 */
@customElement(`${prefix}-tearsheet-footer`)
class CDSTearsheetFooter extends HostListenerMixin(LitElement) {
  @property({ reflect: true })
  slot = 'footer';

  @property({ type: Array })
  actions: ActionButton[] = [];

  @property({ attribute: 'button-size' })
  buttonSize?: ButtonSize;

  @query('cds-action-set')
  private actionSetElement?: HTMLElement;

  private _actionSetRegistered = false;

  @consume({ context: tearsheetContext, subscribe: true })
  private _tearsheetCtx?: TearsheetContextValue;

  protected override firstUpdated(): void {
    registerFocusableContainers(this, this._getUniqueId());
  }

  private _getUniqueId(): string {
    const host = this.closest(`${prefix}-tearsheet`);
    return (host as HTMLElement & { uniqueId?: string })?.uniqueId ?? '';
  }

  protected override updated(): void {
    if (
      this.actionSetElement?.shadowRoot &&
      this._getUniqueId() &&
      !this._actionSetRegistered
    ) {
      registerFocusableContainers(
        this.actionSetElement.shadowRoot,
        this._getUniqueId()
      );
      this._actionSetRegistered = true;
    }
  }

  private _renderActions() {
    if (!this.actions || this.actions.length === 0) {
      return null;
    }
    const { variant } = this._tearsheetCtx?.state ?? defaultTearsheetState;
    const actionSetSize = variant === 'wide' ? '2xl' : 'lg';
    const buttonSize = this.buttonSize || (variant === 'wide' ? '2xl' : 'xl');

    return html`
      <cds-action-set
        size="${actionSetSize}"
        button-size="${buttonSize}"
        .actions="${this.actions}"
        ?disable-stacking="${true}">
      </cds-action-set>
    `;
  }

  render() {
    const actionCount = this.actions?.length || 0;
    const classes = classMap({
      [`${blockClass}__footer`]: true,
      [`${blockClass}__footer--three-actions`]: actionCount === 3,
      [`${blockClass}__footer--many-actions`]: actionCount > 3,
    });

    return html`<footer class="${classes}">
      <slot></slot>
      ${this._renderActions()}
    </footer>`;
  }

  static styles = styles;
}

export default CDSTearsheetFooter;

// packages/react/src/components/Tearsheet/TearsheetFooter.tsx
/**
 * Copyright IBM Corp. 2025, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { forwardRef, ReactNode, useContext } from 'react';
import cx from 'classnames';
import Button, { type ButtonProps } from '../Button';
import { ButtonSet } from '../ButtonSet';
import { TearsheetContext } from './context';
import { usePrefix } from '../../internal/usePrefix';

export interface TearsheetFooterProps {
  /**
   * Optional children to render in the footer. If provided, children are
   * rendered as-is (full custom layout).
   */
  children?: ReactNode;
  /**
   * Optional class name to add to the footer element.
   */
  className?: string;
  /**
   * Optional array of action button configurations rendered in a fluid
   * `ButtonSet`. Buttons are ordered ghost → secondary → primary automatically.
   * Ignored when `children` is provided.
   */
  actions?: (ButtonProps<React.ElementType> & { label?: string })[];
  /**
   * Size applied to every action button. Defaults to `'2xl'` for wide
   * tearsheets and `'xl'` for narrow ones.
   */
  buttonSize?: ButtonProps<React.ElementType>['size'];
}

const TearsheetFooter = forwardRef<HTMLDivElement, TearsheetFooterProps>(
  ({ children, className, actions, buttonSize }, ref) => {
    const prefix = usePrefix();
    const blockClass = `${prefix}--tearsheet`;
    const { variant } = useContext(TearsheetContext);
    const defaultSize = variant === 'wide' ? '2xl' : 'xl';
    const resolvedSize = buttonSize ?? defaultSize;

    return (
      <div className={cx(`${blockClass}__footer`, className)} ref={ref}>
        {children}
        {!children && actions && actions.length > 0 && (
          <ButtonSet fluid className={`${blockClass}__footer-button-set`}>
            {actions.map(({ label, ...action }, i) => (
              <Button key={i} {...action} size={resolvedSize}>
                {label}
              </Button>
            ))}
          </ButtonSet>
        )}
      </div>
    );
  }
);

TearsheetFooter.displayName = 'TearsheetFooter';

export default TearsheetFooter;
