// packages/react/src/components/TimePicker/next/TimePicker.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import cx from 'classnames';
import { usePrefix } from '../../../internal/usePrefix';
import deprecate from '../../../prop-types/deprecate';

const TimePicker = React.forwardRef(function TimePicker(
  {
    children,
    className,
    disabled = false,
    hideLabel,
    id,
    invalidText = 'Invalid time format.',
    invalid = false,
    labelText,
    light = false,
    maxLength = 5,
    onChange = () => {},
    onClick = () => {},
    onBlur = () => {},
    pattern = '(1[012]|[1-9]):[0-5][0-9](\\s)?',
    placeholder = 'hh:mm',
    size,
    type = 'text',
    value,
    ...rest
  },
  ref
) {
  const prefix = usePrefix();

  const [isValue, setValue] = React.useState(value);
  const [prevValue, setPrevValue] = React.useState(value);

  if (value !== prevValue) {
    setValue(value);
    setPrevValue(value);
  }

  const timePickerInputProps = {
    className: cx(
      `${prefix}--time-picker__input-field`,
      `${prefix}--text-input`,
      [className],
      {
        [`${prefix}--text-input--light`]: light,
      }
    ),

    onChange: (evt) => {
      if (!disabled) {
        // https://github.com/carbon-design-system/carbon/issues/9535
        evt.persist();
        setValue(isValue);
        onChange(evt);
      }
    },
    onClick: (evt) => {
      if (!disabled) {
        // https://github.com/carbon-design-system/carbon/issues/9535
        evt.persist();
        setValue(isValue);
        onClick(evt);
      }
    },
    onBlur: (event) => {
      if (!disabled) {
        // https://github.com/carbon-design-system/carbon/issues/9535
        event.persist();
        setValue(isValue);
        onBlur(event);
      }
    },
    pattern,
    placeholder,
    maxLength,
    id,
    type,
    disabled,
    value,
  };

  const timePickerClasses = cx({
    [`${prefix}--time-picker`]: true,
    [`${prefix}--time-picker--light`]: light,
    [`${prefix}--time-picker--invalid`]: invalid,
    [`${prefix}--time-picker--${size}`]: size,
    [className]: className,
  });

  const labelClasses = cx(`${prefix}--label`, {
    [`${prefix}--visually-hidden`]: hideLabel,
    [`${prefix}--label--disabled`]: disabled,
  });

  const label = labelText ? (
    <label htmlFor={id} className={labelClasses}>
      {labelText}
    </label>
  ) : null;

  const error = invalid ? (
    <div className={`${prefix}--form-requirement`}>{invalidText}</div>
  ) : null;

  return (
    <div className={cx(`${prefix}--form-item`, className)} ref={ref}>
      {label}
      <div className={timePickerClasses}>
        <div className={`${prefix}--time-picker__input`}>
          <input
            data-invalid={invalid ? invalid : undefined}
            {...timePickerInputProps}
            {...rest}
          />
        </div>
        {children}
      </div>
      {error}
    </div>
  );
});

TimePicker.propTypes = {
  /**
   * Pass in the children that will be rendered next to the form control
   */
  children: PropTypes.node,

  /**
   * Specify an optional className to be applied to the container node
   */
  className: PropTypes.string,

  /**
   * Specify whether the `<input>` should be disabled
   */
  disabled: PropTypes.bool,

  /**
   * Specify whether you want the underlying label to be visually hidden
   */
  hideLabel: PropTypes.bool,

  /**
   * Specify a custom `id` for the `<input>`
   */
  id: PropTypes.string.isRequired,

  /**
   * Specify whether the control is currently invalid
   */
  invalid: PropTypes.bool,

  /**
   * Provide the text that is displayed when the control is in an invalid state
   */
  invalidText: PropTypes.node,

  /**
   * Provide the text that will be read by a screen reader when visiting this
   * control
   */
  labelText: PropTypes.node,

  /**
   * `true` to use the light version. TODO: V12 remove this.
   */
  light: deprecate(
    PropTypes.bool,
    'The `light` prop for `Tile` is no longer needed and has been deprecated. It will be removed in the next major release. Use the Layer component instead.'
  ),

  /**
   * Specify the maximum length of the time string in `<input>`
   */
  maxLength: PropTypes.number,

  /**
   * Optionally provide an `onBlur` handler that is called whenever the
   * `<input>` loses focus
   */
  onBlur: PropTypes.func,

  /**
   * Optionally provide an `onChange` handler that is called whenever `<input>`
   * is updated
   */
  onChange: PropTypes.func,

  /**
   * Optionally provide an `onClick` handler that is called whenever the
   * `<input>` is clicked
   */
  onClick: PropTypes.func,

  /**
   * Specify the regular expression working as the pattern of the time string in `<input>`
   */
  pattern: PropTypes.string,

  /**
   * Specify the placeholder attribute for the `<input>`
   */
  placeholder: PropTypes.string,

  /**
   * Specify the size of the Time Picker. Currently supports either `sm`, 'md' (default) or 'lg` as an option.
   */
  size: PropTypes.oneOf(['sm', 'md', 'lg']),

  /**
   * Specify the type of the `<input>`
   */
  type: PropTypes.string,

  /**
   * Specify the value of the `<input>`
   */
  value: PropTypes.string,
};

export default TimePicker;

// packages/web-components/src/components/time-picker/time-picker.ts
/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property, query } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import WarningFilled16 from '@carbon/icons/lib/warning--filled/16.js';
import WarningAltFilled16 from '@carbon/icons/lib/warning--alt--filled/16.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import ValidityMixin from '../../globals/mixins/validity';
import FormMixin from '../../globals/mixins/form';
import { prefix } from '../../globals/settings';
import styles from './time-picker.scss?lit';
import ifNonEmpty from '../../globals/directives/if-non-empty';
import { TIME_PICKER_SIZE } from './defs';

/**
 * Time Picker component.
 * @element cds-time-picker
 * @slot label-text - The label text.
 * @slot time-picker-select - Slot for time picker select components.
 * @slot validity-message - The validity message. If present and non-empty, this input shows the UI of its invalid state.
 */
@customElement(`${prefix}-time-picker`)
class CDSTimePicker extends ValidityMixin(FormMixin(LitElement)) {
  /**
   * The underlying input element
   */
  @query('input')
  protected _input!: HTMLInputElement;

  /**
   * The internal value.
   */
  protected _value = '';

  protected _handleInput({ target }: Event) {
    this.value = (target as HTMLInputElement).value;
    this.dispatchEvent(
      new CustomEvent('change', {
        bubbles: true,
        composed: true,
        detail: { value: this.value },
      })
    );
  }

  /**
   * Handle slotchange event for time-picker-select slot
   * to propagate properties to child elements
   */
  protected _handleSlotChange() {
    this.requestUpdate();
  }

  _handleFormdata(event: Event) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- https://github.com/carbon-design-system/carbon/issues/20071
    const { formData } = event as any;
    const { disabled, name, value } = this;
    if (!disabled) {
      formData.append(name, value);
    }
  }

  /**
   * Specify whether the control is disabled
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /**
   * Specify whether the control is currently invalid
   */
  @property({ type: Boolean, reflect: true })
  invalid = false;

  /**
   * Provide the text that is displayed when the control is in an invalid state
   */
  @property({ attribute: 'invalid-text' })
  invalidText = 'Invalid time format.';

  /**
   * Specify whether the control is in warning state
   */
  @property({ type: Boolean, reflect: true })
  warning = false;

  /**
   * Provide the text that is displayed when the control is in a warning state
   */
  @property({ attribute: 'warning-text' })
  warningText = 'Warning message.';

  /**
   * Specify whether the label should be hidden
   */
  @property({ attribute: 'hide-label', type: Boolean, reflect: true })
  hideLabel = false;

  /**
   * Name for the input in FormData
   */
  @property()
  name = '';

  /**
   * Provide label text to be read by screen readers
   */
  @property({ attribute: 'label-text' })
  labelText = 'Select a time';

  /**
   * Placeholder text for the input
   */
  @property({ reflect: true })
  placeholder = 'hh:mm';

  /**
   * Specify whether the control should be read-only
   */
  @property({ type: Boolean, reflect: true })
  readOnly = false;

  /**
   * Specify the maximum length of the input value
   */
  @property({ type: Number, attribute: 'max-length', reflect: true })
  maxLength = 5;

  /**
   * Pattern for input validation
   */
  @property()
  pattern = '(1[012]|[1-9]):[0-5][0-9](\\s)?';

  /**
   * Size of the time picker
   */
  @property({ reflect: true })
  size = TIME_PICKER_SIZE.MEDIUM;

  /**
   * Input type
   */
  @property({ reflect: true })
  type = 'text';

  /**
   * Validity message
   */
  @property({ attribute: 'validity-message' })
  validityMessage = '';

  /**
   * Whether the input is required
   */
  @property({ type: Boolean, reflect: true })
  required = false;

  /**
   * Custom message for required validation
   */
  @property({ attribute: 'required-validity-message' })
  requiredValidityMessage = 'Please fill out this field.';

  /**
   * Value of the input
   */
  @property({ reflect: true })
  get value() {
    return this._input ? this._input.value : this._value;
  }

  set value(value) {
    const oldValue = this._value;
    this._value = value;
    this.requestUpdate('value', oldValue);
    if (this._input) {
      this._input.value = value;
    }
  }

  render() {
    const {
      className,
      disabled,
      hideLabel,
      invalid,
      invalidText,
      warning,
      warningText,
      labelText,
      placeholder,
      readOnly,
      maxLength,
      pattern,
      size,
      type,
      value,
      _handleInput: handleInput,
      _handleSlotChange: handleSlotChange,
    } = this;

    const labelClasses = classMap({
      [`${prefix}--label`]: true,
      [`${prefix}--visually-hidden`]: hideLabel,
      [`${prefix}--label--disabled`]: disabled,
    });

    const timePickerClasses = classMap({
      [`${prefix}--time-picker`]: true,
      [`${prefix}--time-picker--invalid`]: invalid,
      [`${prefix}--time-picker--warning`]: warning,
      [`${prefix}--time-picker--readonly`]: readOnly,
      [`${prefix}--time-picker--${size}`]: size,
      ...(className && { [className]: true }),
    });

    const inputClasses = classMap({
      [`${prefix}--time-picker__input-field`]: true,
      [`${prefix}--text-input`]: true,
      [`${prefix}--time-picker__input-field-error`]: invalid || warning,
      ...(className && { [className]: true }),
    });
    const label = labelText
      ? html`<label class="${labelClasses}">${labelText}</label>`
      : null;

    return html`
      <div class="${prefix}--form-item ">
        ${label}
        <div class="${timePickerClasses}">
          <div class="${prefix}--time-picker__input">
            <input
              class="${inputClasses}"
              ?data-invalid="${invalid}"
              ?disabled="${disabled}"
              maxlength="${ifNonEmpty(maxLength)}"
              name="${ifNonEmpty(this.name)}"
              pattern="${ifNonEmpty(pattern)}"
              placeholder="${ifNonEmpty(placeholder)}"
              ?readonly="${readOnly}"
              type="${ifNonEmpty(type)}"
              .value="${value}"
              @input="${handleInput}" />
            ${invalid || warning
              ? html`
                  <div class="${prefix}--time-picker__error__icon">
                    ${invalid
                      ? WarningFilled16({
                          class: `${prefix}--checkbox__invalid-icon`,
                        })
                      : WarningAltFilled16({
                          class: `${prefix}--text-input__invalid-icon--warning`,
                        })}
                  </div>
                `
              : null}
          </div>
          <slot @slotchange="${handleSlotChange}"></slot>
        </div>
        ${invalid || warning
          ? html`
              <div class="${prefix}--form-requirement">
                ${invalid ? invalidText : warningText}
              </div>
            `
          : null}
      </div>
    `;
  }
  updated(changedProperties) {
    super.updated(changedProperties);

    const { selectorTimePickerSelect } = this
      .constructor as typeof CDSTimePicker;
    const timePickerSelects = this.querySelectorAll(selectorTimePickerSelect);

    ['disabled', 'readOnly', 'size'].forEach((name) => {
      if (changedProperties.has(name)) {
        const { [name as keyof CDSTimePicker]: value } = this;
        // Propagate the property to descendants
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- https://github.com/carbon-design-system/carbon/issues/20071
        timePickerSelects.forEach((elem: any) => {
          elem[name] = value;
        });
      }
    });
  }
  static get selectorTimePickerSelect() {
    return `${prefix}-time-picker-select`;
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static styles = styles;
}

export default CDSTimePicker;
