// packages/react/src/components/Search/Search.Skeleton.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React, { Component } from 'react';
import classNames from 'classnames';
import { settings } from 'carbon-components';

const { prefix } = settings;

export default class SearchSkeleton extends Component {
  static propTypes = {
    /**
     * Specify whether the Search should be a small variant
     */
    small: PropTypes.bool,
  };

  static defaultProps = {
    small: false,
  };

  render() {
    const { small } = this.props;

    const searchClasses = classNames({
      [`${prefix}--skeleton`]: true,
      [`${prefix}--search--xl`]: !small,
      [`${prefix}--search--sm`]: small,
    });

    return (
      <div className={searchClasses}>
        <span className={`${prefix}--label`} />
        <div className={`${prefix}--search-input`} />
      </div>
    );
  }
}

// packages/web-components/src/components/search/search-skeleton.ts
/**
 * Copyright IBM Corp. 2019, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import { SEARCH_SIZE } from './defs';
import styles from './search.scss?lit';

/**
 * Skeleton of search.
 */
class CDSSearchSkeleton extends LitElement {
  static is = `${prefix}-search-skeleton`;

  /**
   * The search skeleton size.
   */
  @property({ reflect: true })
  size?: SEARCH_SIZE;

  render() {
    const { size } = this;
    const searchClasses = classMap({
      [`${prefix}--skeleton`]: true,
      [`${prefix}--layout--size-${size}`]: size !== undefined,
    });
    return html`
      <div class="${searchClasses}">
        <div class="${prefix}--search-input"></div>
      </div>
    `;
  }

  static styles = styles;
}

export default CDSSearchSkeleton;
