// packages/react/src/components/RadioTile/RadioTile.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import uid from '../../tools/uniqueId';
import classNames from 'classnames';
import { settings } from 'carbon-components';
import { CheckmarkFilled16 as CheckmarkFilled } from '@carbon/icons-react';
import { keys, matches } from '../../internal/keyboard';

const { prefix } = settings;

export default class RadioTile extends React.Component {
  static propTypes = {
    /**
     * `true` if this tile should be selected.
     */
    checked: PropTypes.bool,

    /**
     * The CSS class names.
     */
    className: PropTypes.string,

    /**
     * `true` if the `<input>` should be checked at initialization.
     */
    defaultChecked: PropTypes.bool,

    /**
     * The ID of the `<input>`.
     */
    id: PropTypes.string,

    /**
     * The `name` of the `<input>`.
     */
    name: PropTypes.string,

    /**
     * The description of the tile checkmark icon.
     */
    iconDescription: PropTypes.string,

    /**
     * The handler of the massaged `change` event on the `<input>`.
     */
    onChange: PropTypes.func,

    /**
     * The `value` of the `<input>`.
     */
    value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,

    /**
     * Specify the tab index of the wrapper element
     */
    tabIndex: PropTypes.number,

    /**
     * `true` to use the light version.
     */
    light: PropTypes.bool,
  };

  static defaultProps = {
    iconDescription: 'Tile checkmark',
    onChange: () => {},
    tabIndex: 0,
    light: false,
  };

  uid = this.props.id || uid();

  handleChange = evt => {
    this.props.onChange(this.props.value, this.props.name, evt);
  };

  handleKeyDown = evt => {
    if (matches(evt, [keys.Enter, keys.Space])) {
      evt.preventDefault();
      this.props.onChange(this.props.value, this.props.name, evt);
    }
  };

  render() {
    const {
      children,
      className,
      iconDescription,
      light,
      ...other
    } = this.props;
    const classes = classNames(
      className,
      `${prefix}--tile`,
      `${prefix}--tile--selectable`,
      {
        [`${prefix}--tile--is-selected`]: this.props.checked,
        [`${prefix}--tile--light`]: light,
      }
    );

    return (
      <>
        <input
          {...other}
          type="radio"
          className={`${prefix}--tile-input`}
          onChange={this.handleChange}
          id={this.uid}
        />
        <label
          htmlFor={this.uid}
          className={classes}
          tabIndex={this.props.tabIndex}
          onKeyDown={this.handleKeyDown}>
          <div className={`${prefix}--tile__checkmark`}>
            <CheckmarkFilled aria-label={iconDescription}>
              {iconDescription && <title>{iconDescription}</title>}
            </CheckmarkFilled>
          </div>
          <div className={`${prefix}--tile-content`}>{children}</div>
        </label>
      </>
    );
  }
}

// web-components/packages/carbon-web-components/src/components/tile/radio-tile.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, svg } from 'lit';
import { classMap } from 'lit-html/directives/class-map';
import { ifDefined } from 'lit/directives/if-defined';
import { customElement } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import SelectableTile from './selectable-tile';
import CheckmarkFilled16 from '@carbon/icons/lib/checkmark--filled/16';

/**
 * Single-selectable tile.
 *
 * @element cds-radio-tile
 */
@customElement(`${prefix}-radio-tile`)
class CDSRadioTile extends SelectableTile {
  /**
   * The `type` attribute of the `<input>`.
   */
  protected _inputType = 'radio';

  /**
   * Handles `change` event on the `<input>` in the shadow DOM.
   */
  protected _handleChange() {
    this.selected = true;
    const { selected, name } = this;
    const { eventRadioChange } = this.constructor as typeof CDSRadioTile;
    this.dispatchEvent(
      new CustomEvent(eventRadioChange, {
        bubbles: true,
        composed: true,
        detail: {
          selected,
          name,
        },
      })
    );
  }

  render() {
    const {
      colorScheme,
      checkmarkLabel,
      name,
      selected,
      value,
      _inputType: inputType,
      _handleChange: handleChange,
    } = this;
    const classes = classMap({
      [`${prefix}--tile`]: true,
      [`${prefix}--tile--selectable`]: true,
      [`${prefix}--tile--is-selected`]: selected,
      [`${prefix}--tile--${colorScheme}`]: colorScheme,
    });
    return html`
      <input
        type="${inputType}"
        id="input"
        class="${prefix}--tile-input"
        tabindex="-1"
        name="${ifDefined(name)}"
        value="${ifDefined(value)}"
        .checked=${selected}
        @change=${handleChange} />
      <label for="input" class="${classes}" tabindex="0">
        <div class="${prefix}--tile__checkmark">
          ${CheckmarkFilled16({
            children: !checkmarkLabel
              ? undefined
              : svg`<title>${checkmarkLabel}</title>`,
          })}
        </div>
        <div class="${prefix}--tile-content"><slot></slot></div>
      </label>
    `;
  }

  /**
   * The name of the custom event fired after this selectable tile changes its selected state.
   */
  static get eventRadioChange() {
    return `${prefix}-radio-tile-selected`;
  }
}

export default CDSRadioTile;
