// packages/react/src/components/FluidDropdown/FluidDropdown.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import classnames from 'classnames';
import Dropdown from '../Dropdown';
import { usePrefix } from '../../internal/usePrefix';
import { FormContext } from '../FluidForm/FormContext';

function FluidDropdown({ className, isCondensed, ...other }) {
  const prefix = usePrefix();
  const classNames = classnames(
    `${prefix}--dropdown__wrapper--fluid`,
    className,
    { [`${prefix}--dropdown__wrapper--fluid--condensed`]: isCondensed }
  );

  return (
    <FormContext.Provider value={{ isFluid: true }}>
      <Dropdown className={classNames} {...other} />
    </FormContext.Provider>
  );
}

FluidDropdown.propTypes = {
  /**
   * Specify an optional className to be applied to the outer FluidForm wrapper
   */
  className: PropTypes.string,

  // /**
  //  * Optionally provide the default value of the `<input>`
  //  */
  // defaultValue: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),

  // /**
  //  * Specify whether the `<input>` should be disabled
  //  */
  // disabled: PropTypes.bool,

  // /**
  //  * Specify a custom `id` for the `<input>`
  //  */
  // id: PropTypes.string.isRequired,

  // /**
  //  * Specify whether the control is currently invalid
  //  */
  // invalid: PropTypes.bool,

  /**
   * Provide the text that is displayed when the control is in an invalid state
   */
  invalidText: PropTypes.node,

  /**
   * Specify if the `FluidDropdown` should render its menu items in condensed mode
   */
  isCondensed: PropTypes.bool,

  // /**
  //  * Provide the text that will be read by a screen reader when visiting this
  //  * control
  //  */
  // labelText: PropTypes.node.isRequired,

  // /**
  //  * Optionally provide an `onChange` handler that is called whenever `<input>`
  //  * is updated
  //  */
  // onChange: PropTypes.func,

  // /**
  //  * Optionally provide an `onClick` handler that is called whenever the
  //  * `<input>` is clicked
  //  */
  // onClick: PropTypes.func,

  // /**
  //  * Specify the placeholder attribute for the `<input>`
  //  */
  // placeholder: PropTypes.string,

  // /**
  //  * Specify the value of the `<input>`
  //  */
  // value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),

  // /**
  //  * Specify whether the control is currently in warning state
  //  */
  // warn: PropTypes.bool,

  // /**
  //  * Provide the text that is displayed when the control is in warning state
  //  */
  // warnText: PropTypes.node,
};

export default FluidDropdown;

// packages/web-components/src/components/fluid-dropdown/fluid-dropdown.ts
/**
 * Copyright IBM Corp.2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { prefix } from '../../globals/settings';
import { html } from 'lit';
import CDSDropdown from '../dropdown/dropdown';
import styles from './fluid-dropdown.scss?lit';
import { property } from 'lit/decorators.js';

/**
 * Fluid dropdown.
 *
 * @element cds-fluid-dropdown
 */
class CDSFluidDropdown extends CDSDropdown {
  static is = `${prefix}-fluid-dropdown`;

  // Specify if the FluidDropdown should render its menu items in condensed mode
  @property({ type: Boolean, reflect: true, attribute: 'is-condensed' })
  isCondensed = false;
  connectedCallback() {
    this.setAttribute('isFluid', 'true');
    super.connectedCallback();
  }

  updated(changedProperties) {
    super.updated(changedProperties);
    if (
      changedProperties.has('invalid') ||
      changedProperties.has('disabled') ||
      changedProperties.has('readOnly') ||
      changedProperties.has('warn')
    ) {
      this.requestUpdate();
    }
  }

  render() {
    return html`${super.render()}`;
  }

  static styles = [CDSDropdown.styles, styles];
}

export default CDSFluidDropdown;
