// packages/react/src/components/FluidMultiSelect/FluidMultiSelect.Skeleton.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';

export interface FluidMultiSelectSkeletonProps {
  /**
   * Specify an optional className to add.
   */
  className?: string;
}

const FluidMultiSelectSkeleton: React.FC<FluidMultiSelectSkeletonProps> = ({
  className,
  ...rest
}) => {
  const prefix = usePrefix();
  const wrapperClasses = cx(className, `${prefix}--list-box__wrapper--fluid`);

  return (
    <div className={wrapperClasses} {...rest}>
      <div className={`${prefix}--skeleton ${prefix}--list-box`}>
        <span className={`${prefix}--list-box__label`} />
        <div className={`${prefix}--list-box__field`} />
      </div>
    </div>
  );
};

FluidMultiSelectSkeleton.propTypes = {
  /**
   * Specify an optional className to add.
   */
  className: PropTypes.string,
};

export default FluidMultiSelectSkeleton;

// packages/web-components/src/components/fluid-multi-select/fluid-multi-select-skeleton.ts
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { prefix } from '../../globals/settings';
import { LitElement, html } from 'lit';
import styles from './fluid-multi-select.scss?lit';

/**
 * Fluid multi select skeleton.
 *
 * @element cds-fluid-multi-select-skeleton
 */
class CDSFluidMultiSelectSkeleton extends LitElement {
  static is = `${prefix}-fluid-multi-select-skeleton`;

  render() {
    return html`
      <div class="${prefix}--list-box__wrapper--fluid">
        <div class="${prefix}--skeleton ${prefix}--list-box">
          <span class="${prefix}--list-box__label"></span>
          <div class="${prefix}--list-box__field"></div>
        </div>
      </div>
    `;
  }
  static styles = styles;
}

export default CDSFluidMultiSelectSkeleton;
