// packages/react/src/components/ContainedList/ContainedList.tsx
/**
 * Copyright IBM Corp. 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { ReactNode } from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import { LayoutConstraint } from '../Layout';
import { useId } from '../../internal/useId';
import { usePrefix } from '../../internal/usePrefix';

const variants: ('on-page' | 'disclosed')[] = ['on-page', 'disclosed'];

interface ContainedListProps {
  /**
   * A slot for a possible interactive element to render.
   */
  action?: ReactNode;

  /**
   * A collection of ContainedListItems to be rendered in the ContainedList
   */
  children?: ReactNode;

  /**
   * Additional CSS class names.
   */
  className?: string;

  /**
   * Specify whether the dividing lines in between list items should be inset.
   */
  isInset?: boolean;

  /**
   * The kind of ContainedList you want to display
   */
  kind?: 'on-page' | 'disclosed';

  /**
   * A label describing the contained list.
   */
  label: ReactNode;

  /**
   * Specify the size of the contained list.
   */
  size?: 'sm' | 'md' | 'lg' | 'xl';
}

function filterChildren(children) {
  if (Array.isArray(children)) {
    return children?.filter(
      (child) =>
        !['Search', 'ExpandableSearch'].includes(child?.type?.displayName)
    );
  }

  if (
    children &&
    !['Search', 'ExpandableSearch'].includes(children?.type?.displayName)
  ) {
    return children;
  }

  return null;
}

function renderChildren(children) {
  if (Array.isArray(children)) {
    children.map((child, index) => {
      if (index === 0 && child.type?.displayName === 'Search') {
        return child;
      }

      return child;
    });
  }

  if (children && children.type?.displayName === 'Search') {
    return children;
  }

  return children;
}

const ContainedList: React.FC<ContainedListProps> = ({
  action,
  children,
  className,
  isInset,
  kind = variants[0],
  label,
  size,
  ...rest
}) => {
  const labelId = `${useId('contained-list')}-header`;
  const prefix = usePrefix();

  const classes = classNames(
    `${prefix}--contained-list`,
    {
      [`${prefix}--contained-list--inset-rulers`]: isInset,
      [`${prefix}--contained-list--${size}`]: size, // TODO: V12 - Remove this class
      [`${prefix}--layout--size-${size}`]: size,
    },
    `${prefix}--contained-list--${kind}`,
    className
  );

  const filteredChildren = filterChildren(children);

  const isActionSearch =
    React.isValidElement(action) &&
    (typeof action.type === 'string'
      ? ['Search', 'ExpandableSearch'].includes(action.type)
      : typeof action.type === 'function' &&
        'displayName' in action.type &&
        (action.type.displayName === 'Search' ||
          action.type.displayName === 'ExpandableSearch'));

  const renderedChildren = renderChildren(children);

  return (
    <div className={classes} {...rest}>
      <div className={`${prefix}--contained-list__header`}>
        <div id={labelId} className={`${prefix}--contained-list__label`}>
          {label}
        </div>
        <LayoutConstraint
          size={{ min: 'sm', max: 'xl' }}
          className={`${prefix}--contained-list__action`}>
          {action}
        </LayoutConstraint>
      </div>
      {children && (
        /**
         * Webkit removes implicit "list" semantics when "list-style-type: none" is set.
         * Explicitly setting the "list" role ensures assistive technology in webkit
         * browsers correctly announce the semantics.
         *
         * Ref https://bugs.webkit.org/show_bug.cgi?id=170179#c1
         */
        // eslint-disable-next-line jsx-a11y/no-redundant-roles
        <ul role="list" aria-labelledby={labelId}>
          {isActionSearch ? filteredChildren : renderedChildren}
        </ul>
      )}
    </div>
  );
};

ContainedList.propTypes = {
  /**
   * A slot for a possible interactive element to render.
   */
  action: PropTypes.node,

  /**
   * A collection of ContainedListItems to be rendered in the ContainedList
   */
  children: PropTypes.node,

  /**
   * Additional CSS class names.
   */
  className: PropTypes.string,

  /**
   * Specify whether the dividing lines in between list items should be inset.
   */
  isInset: PropTypes.bool,

  /**
   * The kind of ContainedList you want to display
   */
  kind: PropTypes.oneOf(variants),

  /**
   * A label describing the contained list.
   */
  label: PropTypes.oneOfType([PropTypes.string, PropTypes.node]).isRequired,

  /**
   * Specify the size of the contained list.
   */
  size: PropTypes.oneOf(['sm', 'md', 'lg', 'xl']),
};

export default ContainedList;

// packages/web-components/src/components/contained-list/contained-list.ts
/**
 * Copyright IBM Corp. 2022, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { prefix } from '../../globals/settings';
import styles from './contained-list.scss?lit';

export type Variants = 'on-page' | 'disclosed';

/**
 * Contained list.
 *
 * @element cds-contained-list
 * @slot - The list items (cds-contained-list-item elements)
 * @slot action - The action slot for interactive elements in header
 * @slot label - The label text
 */
class CDSContainedList extends LitElement {
  static is = `${prefix}-contained-list`;

  /**
   * Specify whether the dividing lines in between list items should be inset.
   */
  @property({ type: Boolean, reflect: true, attribute: 'is-inset' })
  isInset = false;

  /**
   * The kind of ContainedList you want to display
   */
  @property({ reflect: true })
  kind: Variants = 'on-page';

  /**
   * A label describing the contained list.
   */
  @property({ reflect: true })
  label = '';

  /**
   * Specify the size of the contained list.
   */
  @property({ reflect: true })
  size?: 'sm' | 'md' | 'lg' | 'xl';

  render() {
    const { isInset, kind, label, size } = this;

    const classes = classMap({
      [`${prefix}--contained-list`]: true,
      [`${prefix}--contained-list--${kind}`]: true,
      [`${prefix}--contained-list--inset-rulers`]: isInset,
      [`${prefix}--layout--size-${size}`]: !!size,
    });

    const hasLabelSlot = this.querySelector('[slot="label"]') !== null;

    return html`
      <div class="${classes}">
        ${label || hasLabelSlot
          ? html`
              <div class="${prefix}--contained-list__header">
                <div class="${prefix}--contained-list__label">
                  ${hasLabelSlot ? html`<slot name="label"></slot>` : label}
                </div>
                <div class="${prefix}--contained-list__action">
                  <slot name="action"></slot>
                </div>
              </div>
            `
          : ''}
        <ul role="list">
          <slot></slot>
        </ul>
      </div>
    `;
  }

  static styles = styles;
}

export default CDSContainedList;
