// packages/react/src/components/ContainedList/ContainedListItem/ContainedListItem.js
/**
 * Copyright IBM Corp. 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import { usePrefix } from '../../../internal/usePrefix';

function ContainedListItem({
  action,
  children,
  className,
  disabled = false,
  onClick,
}) {
  const prefix = usePrefix();

  const isClickable = onClick !== undefined;

  const classes = classNames(`${prefix}--contained-list-item`, className, {
    [`${prefix}--contained-list-item--clickable`]: isClickable,
  });

  const content = isClickable ? (
    <>
      <button
        className={`${prefix}--contained-list-item__content`}
        type="button"
        disabled={disabled}
        onClick={onClick}>
        {children}
      </button>
      <div className={`${prefix}--contained-list-item__action`}>{action}</div>
    </>
  ) : (
    <>
      <div className={`${prefix}--contained-list-item__content`}>
        {children}
      </div>
      <div className={`${prefix}--contained-list-item__action`}>{action}</div>
    </>
  );

  return <li className={classes}>{content}</li>;
}

ContainedListItem.propTypes = {
  /**
   * A slot for a possible interactive element to render.
   */
  action: PropTypes.node,

  /**
   * The content of this item
   */
  children: PropTypes.node,

  /**
   * Additional CSS class names.
   */
  className: PropTypes.string,

  /**
   * Whether this item is disabled.
   */
  disabled: PropTypes.bool,

  /**
   * Provide an optional function to be called when the item is clicked
   */
  onClick: PropTypes.func,
};

export default ContainedListItem;

// packages/web-components/src/components/contained-list/contained-list-item.ts
/**
 * Copyright IBM Corp. 2022, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { prefix } from '../../globals/settings';
import styles from './contained-list.scss?lit';

/**
 * Contained list item.
 *
 * @element cds-contained-list-item
 * @slot - The content of the list item
 * @slot icon - The icon slot for rendering an icon
 * @slot action - The action slot for interactive elements
 * @fires cds-contained-list-item-click - Fires when clickable item is clicked
 */
class CDSContainedListItem extends LitElement {
  static is = `${prefix}-contained-list-item`;

  /**
   * Whether this item is clickable
   */
  @property({ type: Boolean, reflect: true })
  clickable = false;

  /**
   * Whether this item is disabled.
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /**
   * Handles slot change for icon
   */
  private _handleIconSlotChange({ target }: Event) {
    const slot = target as HTMLSlotElement;
    const hasIcon = slot.assignedElements().length > 0;
    this._hasIcon = hasIcon;
    this.requestUpdate();
  }

  private _hasIcon = false;

  /**
   * Handles click event
   */
  private _handleClick(event: MouseEvent) {
    if (this.disabled) {
      event.preventDefault();
      return;
    }

    const { eventClick } = this.constructor as typeof CDSContainedListItem;
    this.dispatchEvent(
      new CustomEvent(eventClick, {
        bubbles: true,
        composed: true,
        detail: { item: this },
      })
    );
  }

  connectedCallback() {
    super.connectedCallback();
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'listitem');
    }
  }

  render() {
    const { disabled, clickable, _hasIcon } = this;

    const classes = classMap({
      [`${prefix}--contained-list-item`]: true,
      [`${prefix}--contained-list-item--clickable`]: clickable,
      [`${prefix}--contained-list-item--with-icon`]: _hasIcon,
    });

    const contentClasses = `${prefix}--contained-list-item__content`;

    const content = html`
      <slot name="icon" @slotchange="${this._handleIconSlotChange}"></slot>
      <slot></slot>
    `;

    return html`
      <div class="${classes}">
        ${clickable
          ? html`
              <button
                class="${contentClasses}"
                type="button"
                ?disabled="${disabled}"
                @click="${this._handleClick}">
                ${content}
              </button>
            `
          : html`<div class="${contentClasses}">${content}</div>`}
        <div class="${prefix}--contained-list-item__action">
          <slot name="action"></slot>
        </div>
      </div>
    `;
  }

  /**
   * The name of the custom event fired when a clickable item is clicked
   */
  static get eventClick() {
    return `${prefix}-contained-list-item-click`;
  }

  static styles = styles;
}

export default CDSContainedListItem;
