// web-components/packages/carbon-web-components/src/components/tooltip/tooltip-definition.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { LitElement, html } from 'lit';
import { property, customElement } from 'lit/decorators.js';
import settings from 'carbon-components/es/globals/js/settings';
import FocusMixin from '../../globals/mixins/focus';
import { TOOLTIP_ALIGNMENT, TOOLTIP_DIRECTION } from './defs';
import styles from './tooltip.scss';

export { TOOLTIP_ALIGNMENT, TOOLTIP_DIRECTION };

const { prefix } = settings;

/**
 * Definition tooltip.
 *
 * @element bx-tooltip-definition
 * @slot body - The tooltip body content.
 */
@customElement(`${prefix}-tooltip-definition`)
class BXTooltipDefinition extends FocusMixin(LitElement) {
  /**
   * How the tooltip is aligned to the trigger button.
   */
  @property()
  alignment = TOOLTIP_ALIGNMENT.CENTER;

  /**
   * The text for the tooltip body.
   */
  @property({ attribute: 'body-text' })
  bodyText = '';

  /**
   * The tooltip direction.
   */
  @property()
  direction = TOOLTIP_DIRECTION.BOTTOM;

  render() {
    const { alignment, bodyText, direction } = this;
    const classes = classMap({
      [`${prefix}--tooltip__trigger`]: true,
      [`${prefix}--tooltip--a11y`]: true,
      [`${prefix}--tooltip__trigger--definition`]: true,
      [`${prefix}--tooltip--${direction}`]: direction,
      [`${prefix}--tooltip--align-${alignment}`]: alignment,
    });
    return html`
      <button class="${classes}" aria-describedby="tooltip-body">
        <slot></slot>
      </button>
      <div class="${prefix}--assistive-text" id="tooltip-body" role="tooltip">
        <slot name="body">${bodyText}</slot>
      </div>
    `;
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static styles = styles;
}

export default BXTooltipDefinition;

// packages/react/src/components/Tooltip/next/TooltipDefinition.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { settings } from 'carbon-components';
import setupGetInstanceId from '../../../tools/setupGetInstanceId';
import debounce from 'lodash.debounce';
import { composeEventHandlers } from '../../../tools/events';
import { keys, matches } from '../../../internal/keyboard';

const { prefix } = settings;
const getInstanceId = setupGetInstanceId();
const TooltipDefinition = ({
  align,
  children,
  className,
  direction,
  id,
  content,
  triggerClassName,
  onFocus,
  onBlur,
  onMouseEnter,
  onMouseLeave,
  ...rest
}) => {
  const [allowTooltipVisibility, setAllowTooltipVisibility] = useState(true);
  const [tooltipVisible, setTooltipVisible] = useState(false);
  const tooltipId = id || `definition-tooltip-${getInstanceId()}`;

  const tooltipClassName = cx(
    `${prefix}--tooltip--definition`,
    `${prefix}--tooltip--a11y`,
    className
  );
  const tooltipTriggerClasses = cx(
    `${prefix}--tooltip__trigger`,
    `${prefix}--tooltip--a11y`,
    `${prefix}--tooltip__trigger--definition`,
    triggerClassName,
    {
      [`${prefix}--tooltip--${direction}`]: direction,
      [`${prefix}--tooltip--align-${align}`]: align,
      [`${prefix}--tooltip--hidden`]: !allowTooltipVisibility,
      [`${prefix}--tooltip--visible`]: tooltipVisible,
    }
  );

  const debounceTooltipVisible = debounce(() => setTooltipVisible(false), 100);

  const handleFocus = () => {
    debounceTooltipVisible.cancel();
    setAllowTooltipVisibility(true);
    setTooltipVisible(true);
  };

  const handleBlur = debounceTooltipVisible;

  const handleMouseEnter = () => {
    debounceTooltipVisible.cancel();
    setAllowTooltipVisibility(true);
    setTooltipVisible(true);
  };

  const handleMouseLeave = debounceTooltipVisible;

  useEffect(() => {
    const handleEscKeyDown = (event) => {
      if (matches(event, [keys.Escape])) {
        setAllowTooltipVisibility(false);
      }
    };
    document.addEventListener('keydown', handleEscKeyDown);
    return () => document.removeEventListener('keydown', handleEscKeyDown);
  }, []);

  return (
    <div
      {...rest}
      className={tooltipClassName}
      onMouseEnter={composeEventHandlers([onMouseEnter, handleMouseEnter])}
      onMouseLeave={composeEventHandlers([onMouseLeave, handleMouseLeave])}>
      <button
        type="button"
        className={tooltipTriggerClasses}
        aria-describedby={tooltipId}
        onFocus={composeEventHandlers([onFocus, handleFocus])}
        onBlur={composeEventHandlers([onBlur, handleBlur])}>
        {children}
      </button>
      <div
        className={`${prefix}--assistive-text`}
        id={tooltipId}
        role="tooltip">
        {content}
      </div>
    </div>
  );
};

TooltipDefinition.propTypes = {
  /**
   * Specify the alignment (to the trigger button) of the tooltip.
   * Can be one of: start, center, or end.
   */
  align: PropTypes.oneOf(['start', 'center', 'end']),

  /**
   * Specify the tooltip trigger text that is rendered to the UI for the user to
   * interact with in order to display the tooltip.
   */
  children: PropTypes.node.isRequired,

  /**
   * Specify an optional className to be applied to the container node
   */
  className: PropTypes.string,

  /**
   * Provide the text that will be displayed in the tooltip when it is rendered.
   */
  content: PropTypes.node.isRequired,

  /**
   * Specify the direction of the tooltip. Can be either top or bottom.
   */
  direction: PropTypes.oneOf(['top', 'bottom']),

  /**
   * Optionally specify a custom id for the tooltip. If one is not provided, we
   * generate a unique id for you.
   */
  id: PropTypes.string,

  /**
   * The event handler for the `blur` event.
   */
  onBlur: PropTypes.func,

  /**
   * The event handler for the `focus` event.
   */
  onFocus: PropTypes.func,

  /**
   * The event handler for the `mouseenter` event.
   */
  onMouseEnter: PropTypes.func,

  /**
   * The event handler for the `mouseleave` event.
   */
  onMouseLeave: PropTypes.func,

  /**
   * The CSS class name of the trigger element
   */
  triggerClassName: PropTypes.string,
};

TooltipDefinition.defaultProps = {
  direction: 'bottom',
  align: 'start',
};

export { TooltipDefinition };
