// web-components/packages/carbon-web-components/src/components/select/select-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { ifDefined } from 'lit/directives/if-defined.js';
import { action } from '@storybook/addon-actions';
import { boolean, select } from '@storybook/addon-knobs';
import textNullable from '../../../.storybook/knob-text-nullable';
// Below path will be there when an application installs `carbon-web-components` package.
// In our dev env, we auto-generate the file and re-map below path to to point to the generated file.
// @ts-ignore
import { prefix } from '../../globals/settings';
import { INPUT_SIZE } from '../text-input/text-input';
import './select';
import './select-item-group';
import './select-item';
import './select-skeleton';
import '../form/form-item';
import '../layer';
import '../../../.storybook/templates/with-layer';

import storyDocs from './select-story.mdx';

const sizes = {
  [`Small size (${INPUT_SIZE.SMALL})`]: INPUT_SIZE.SMALL,
  [`Medium size (${INPUT_SIZE.MEDIUM})`]: INPUT_SIZE.MEDIUM,
  [`Large size (${INPUT_SIZE.LARGE})`]: INPUT_SIZE.LARGE,
};

export const Default = () => {
  return html`
    <cds-form-item>
      <cds-select
        helper-text="Optional helper text"
        label-text="Select an option"
        placeholder="Choose an option">
        <cds-select-item-group label="Category 1">
          <cds-select-item value="all">Option 1</cds-select-item>
          <cds-select-item value="cloudFoundry">Option 2</cds-select-item>
        </cds-select-item-group>
        <cds-select-item-group label="Category 2">
          <cds-select-item value="staging">Option 3</cds-select-item>
          <cds-select-item value="dea">Option 4</cds-select-item>
          <cds-select-item value="router">Option 5</cds-select-item>
        </cds-select-item-group>
      </cds-select>
    </cds-form-item>
  `;
};

export const Inline = () => {
  return html`
    <cds-form-item>
      <cds-select
        inline
        helper-text="Optional helper text"
        label-text="Select an option"
        placeholder="Choose an option">
        <cds-select-item-group label="Category 1">
          <cds-select-item value="all">Option 1</cds-select-item>
          <cds-select-item value="cloudFoundry">Option 2</cds-select-item>
        </cds-select-item-group>
        <cds-select-item-group label="Category 2">
          <cds-select-item value="staging">Option 3</cds-select-item>
          <cds-select-item value="dea">Option 4</cds-select-item>
          <cds-select-item value="router">Option 5</cds-select-item>
        </cds-select-item-group>
      </cds-select>
    </cds-form-item>
  `;
};

export const skeleton = () =>
  html` <cds-select-skeleton></cds-select-skeleton> `;

skeleton.parameters = {
  percy: {
    skip: true,
  },
};

export const WithLayer = () => {
  return html`
    <sb-template-layers>
      <cds-select
        helper-text="Optional helper text"
        placeholder="Choose an option">
        <cds-select-item-group label="Category 1">
          <cds-select-item value="all">Option 1</cds-select-item>
          <cds-select-item value="cloudFoundry">Option 2</cds-select-item>
        </cds-select-item-group>
        <cds-select-item-group label="Category 2">
          <cds-select-item value="staging">Option 3</cds-select-item>
          <cds-select-item value="dea">Option 4</cds-select-item>
          <cds-select-item value="router">Option 5</cds-select-item>
        </cds-select-item-group>
      </cds-select>
    </sb-template-layers>
  `;
};

export const Playground = (args) => {
  const {
    disabled,
    helperText,
    hideLabel,
    inline,
    invalid,
    invalidText,
    labelText,
    name,
    placeholder,
    size,
    readonly,
    warn,
    warnText,
    value,
    children = html`
      <cds-select-item-group label="Category 1">
        <cds-select-item value="all">Option 1</cds-select-item>
        <cds-select-item value="cloudFoundry">Option 2</cds-select-item>
      </cds-select-item-group>
      <cds-select-item-group label="Category 2">
        <cds-select-item value="staging">Option 3</cds-select-item>
        <cds-select-item value="dea">Option 4</cds-select-item>
        <cds-select-item value="router">Option 5</cds-select-item>
      </cds-select-item-group>
    `,
    onInput,
  } = args?.[`${prefix}-select`] ?? {};
  return html`
    <cds-form-item>
      <cds-select
        ?inline="${inline}"
        ?disabled="${disabled}"
        helper-text="${ifDefined(helperText)}"
        ?hide-label="${hideLabel}"
        ?invalid="${invalid}"
        invalid-text="${ifDefined(invalidText)}"
        label-text="${ifDefined(labelText)}"
        name="${ifDefined(name)}"
        placeholder="${ifDefined(placeholder)}"
        size="${ifDefined(size)}"
        ?readonly="${readonly}"
        ?warn="${warn}"
        warn-text="${ifDefined(warnText)}"
        value="${ifDefined(value)}"
        @cds-select-selected="${ifDefined(onInput)}">
        ${children}
      </cds-select>
    </cds-form-item>
  `;
};

Playground.parameters = {
  knobs: {
    [`${prefix}-select`]: () => ({
      disabled: boolean('Disabled (disabled)', false),
      helperText: textNullable(
        'Helper text (helper-text)',
        'Optional helper text'
      ),
      hideLabel: boolean('Hide label (hide-label)', false),
      inline: boolean('Inline (inline)', false),
      invalid: boolean('Invalid (invalid)', false),
      invalidText: textNullable('Invalid text (invalid-text)', 'Error message'),
      labelText: textNullable('Label text (label-text)', 'Select an option'),
      placeholder: textNullable(
        'Placeholder (placeholder)',
        'Choose an option'
      ),
      size: select('Dropdown size (size)', sizes, INPUT_SIZE.MEDIUM),
      readonly: boolean('Read only (readonly)', false),
      warn: boolean('Warn (warn)', false),
      warnText: textNullable('Warn text (warn-text)', 'Warning message'),
      value: textNullable('The value of the selected item (value)', ''),
      onInput: action(`${prefix}-select-selected`),
    }),
  },
};

export default {
  title: 'Components/Select',
  parameters: {
    ...storyDocs.parameters,
  },
  decorators: [
    (story) => {
      return html`<div style="width: 400px">${story()}</div>`;
    },
  ],
};

// packages/react/src/components/Select/Select-story.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { action } from '@storybook/addon-actions';

import { withKnobs, boolean, text, select } from '@storybook/addon-knobs';
import Select from '../Select';
import SelectItem from '../SelectItem';
import SelectItemGroup from '../SelectItemGroup';
import SelectSkeleton from '../Select/Select.Skeleton';
import mdx from './Select.mdx';

const sizes = {
  'Extra large size (xl)': 'xl',
  'Default size': undefined,
  'Small size (sm)': 'sm',
};

const props = {
  select: () => ({
    className: 'some-class',
    light: boolean('Light variant (light in <Select>)', false),
    inline: boolean(
      'Put control in-line with label (inline in <Select>)',
      false
    ),
    size: select('Field size (size)', sizes, undefined) || undefined,
    disabled: boolean('Disabled (disabled in <Select>)', false),
    hideLabel: boolean('No label (hideLabel in <Select>)', false),
    invalid: boolean('Show form validation UI (invalid in <Select>)', false),
    invalidText: text(
      'Form validation UI content (invalidText in <Select>)',
      'A valid value is required'
    ),
    labelText: text('Label text (labelText)', 'Select'),
    helperText: text('Helper text (helperText)', 'Optional helper text.'),
    onChange: action('onChange'),
    warn: boolean('Show warning state (warn)', false),
    warnText: text(
      'Warning state text (warnText)',
      'This will overwrite your current settings'
    ),
  }),
  group: () => ({
    disabled: boolean('Disabled (disabled in <SelectItemGroup>)', false),
  }),
};

export default {
  title: 'Components/Select',
  decorators: [withKnobs],

  parameters: {
    component: Select,
    docs: {
      page: mdx,
    },

    subcomponents: {
      SelectItem,
      SelectItemGroup,
      SelectSkeleton,
    },
  },
};

export const Default = () => {
  const groupProps = props.group();
  return (
    <div style={{ width: 400 }}>
      <Select {...props.select()} id="select-1" defaultValue="placeholder-item">
        <SelectItem
          disabled
          hidden
          value="placeholder-item"
          text="Choose an option"
        />
        <SelectItemGroup label="Category 1" {...groupProps}>
          <SelectItem value="option-1" text="Option 1" />
          <SelectItem value="option-2" text="Option 2" />
        </SelectItemGroup>
        <SelectItemGroup label="Category 2" {...groupProps}>
          <SelectItem value="option-3" text="Option 3" />
          <SelectItem value="option-4" text="Option 4" />
        </SelectItemGroup>
      </Select>
    </div>
  );
};

Default.parameters = {
  info: {
    text: `
        Select displays a list below its title when selected. They are used primarily in forms,
        where a user chooses one option from a list. Once the user selects an item, the dropdown will
        disappear and the field will reflect the user's choice. Create Select Item components for each
        option in the list. The example below shows an enabled Select component with three items.
      `,
  },
};

export const Skeleton = () => (
  <div
    style={{ width: '300px' }}
    aria-label="loading select"
    aria-live="assertive"
    role="status"
    tabIndex="0" // eslint-disable-line jsx-a11y/no-noninteractive-tabindex
  >
    <SelectSkeleton />
  </div>
);

Skeleton.storyName = 'skeleton';

Skeleton.parameters = {
  info: {
    text: `
        Placeholder skeleton state to use when content is loading.
      `,
  },
};
