// packages/web-components/src/components/number-input/number-input-skeleton.ts
/**
 * Copyright IBM Corp. 2019, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import styles from './number-input.scss?lit';
import { INPUT_SIZE } from '../text-input/text-input';

/**
 * Skeleton of number input.
 */
class CDSNumberInputSkeleton extends LitElement {
  static is = `${prefix}-number-input-skeleton`;

  /**
   * `true` if the label should be hidden. Corresponds to the attribute with the same name.
   */
  @property({ type: Boolean, reflect: true, attribute: 'hide-label' })
  hideLabel = false;

  /**
   * Specify the size of the Number Input skeleton.
   */
  @property({ reflect: true })
  size = INPUT_SIZE.MEDIUM;

  render() {
    const { hideLabel, size } = this;
    return html`
      ${hideLabel
        ? ''
        : html` <span class="${prefix}--label ${prefix}--skeleton"></span> `}
      <div
        class="${prefix}--number ${prefix}--skeleton ${prefix}--number--${size}"></div>
    `;
  }

  static styles = styles;
}

export default CDSNumberInputSkeleton;

// packages/react/src/components/NumberInput/NumberInput.Skeleton.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React, { HTMLAttributes } from 'react';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';

export interface NumberInputSkeletonProps
  extends HTMLAttributes<HTMLDivElement> {
  /**
   * Specify an optional className to add to the form item wrapper.
   */
  className?: string;

  /**
   * Specify whether the label should be hidden, or not
   */
  hideLabel?: boolean;

  /**
   * Specify the size of the Number Input.
   */
  size?: 'sm' | 'md' | 'lg';
}
function NumberInputSkeleton({
  hideLabel,
  className,
  size = 'md',
  ...rest
}: NumberInputSkeletonProps) {
  const prefix = usePrefix();
  return (
    <div className={cx(`${prefix}--form-item`, className)} {...rest}>
      {!hideLabel && (
        <span className={`${prefix}--label ${prefix}--skeleton`} />
      )}
      <div
        className={`${prefix}--number ${prefix}--skeleton ${prefix}--number--${size}`}
      />
    </div>
  );
}

NumberInputSkeleton.propTypes = {
  /**
   * Specify an optional className to add to the form item wrapper.
   */
  className: PropTypes.string,

  /**
   * Specify whether the label should be hidden, or not
   */
  hideLabel: PropTypes.bool,

  /**
   * Specify the size of the Number Input.
   */
  size: PropTypes.oneOf(['sm', 'md', 'lg']),
};

export default NumberInputSkeleton;
