// packages/react/src/components/Tabs/Tabs.Skeleton.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';

function Tab() {
  const prefix = usePrefix();
  return (
    <li className={`${prefix}--tabs__nav-item`}>
      <div className={`${prefix}--tabs__nav-link`}>
        <span></span>
      </div>
    </li>
  );
}

function TabsSkeleton({ className, contained, ...rest }) {
  const prefix = usePrefix();
  const tabClasses = cx(className, `${prefix}--tabs`, `${prefix}--skeleton`, {
    [`${prefix}--tabs--contained`]: contained,
  });
  return (
    <div className={tabClasses} {...rest}>
      <ul className={`${prefix}--tabs__nav`}>
        {Tab()}
        {Tab()}
        {Tab()}
        {Tab()}
        {Tab()}
      </ul>
    </div>
  );
}

TabsSkeleton.propTypes = {
  /**
   * Specify an optional className to add.
   */
  className: PropTypes.string,

  /**
   * Provide the type of Tab
   */
  contained: PropTypes.bool,
};

export default TabsSkeleton;
export { TabsSkeleton };

// packages/web-components/src/components/tabs/tabs-skeleton.ts
/**
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './tabs.scss?lit';
import { property } from 'lit/decorators.js';

/**
 * Skeleton of tabs.
 *
 * @element cds-tabs-skeleton
 */
export default class CDSTabsSkeleton extends LitElement {
  static is = `${prefix}-tabs-skeleton`;

  /**
   * Provide the type of Tab
   */
  @property({ type: Boolean, reflect: true })
  contained = false;
  render() {
    return html`
      <ul class="${prefix}--tabs__nav">
        <slot></slot>
      </ul>
    `;
  }

  static styles = styles;
}
