// web-components/packages/carbon-web-components/src/components/data-table/table-toolbar.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import styles from './data-table.scss';

/**
 * Table toolbar.
 *
 * @element cds-table-toolbar
 */
@customElement(`${prefix}-table-toolbar`)
class BXTableToolbar extends LitElement {
  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'section');
    }
    super.connectedCallback();
  }

  render() {
    return html` <slot></slot> `;
  }

  static styles = styles;
}

export default BXTableToolbar;

// packages/react/src/components/DataTable/TableToolbar.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import PropTypes from 'prop-types';
import React from 'react';
import { usePrefix } from '../../internal/usePrefix';
import { AriaLabelPropType } from '../../prop-types/AriaPropTypes';

export interface TableToolbarProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Pass in the children that will be rendered inside the TableToolbar
   */
  children: React.ReactNode;

  /**
   * `lg` Change the row height of table
   */
  size?: 'sm' | 'lg';
}

const TableToolbar: React.FC<TableToolbarProps> = ({ children, size, ...rest }) => {
  const prefix = usePrefix();
  const className = cx({
    [`${prefix}--table-toolbar`]: true,
    [`${prefix}--table-toolbar--${size}`]: size,
  });
  return (
    <section {...rest} className={className}>
      {children}
    </section>
  );
};

TableToolbar.propTypes = {
  /**
   * Required props for the accessibility label of the TableToolbar
   */
  ...AriaLabelPropType,

  /**
   * Pass in the children that will be rendered inside the TableToolbar
   */
  children: PropTypes.node,

  /**
   * `lg` Change the row height of table
   */
  size: PropTypes.oneOf(['sm', 'lg']),
};

TableToolbar.defaultProps = {
  'aria-label': 'data table toolbar',
};

export default TableToolbar;
