// packages/web-components/src/components/heading/heading.ts
/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, LitElement } from 'lit';
import { property, customElement } from 'lit/decorators.js';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
import styles from './heading.scss?lit';
import { HeadingLevel } from './defs';
import { prefix } from '../../globals/settings';

@customElement(`${prefix}-section`)
class CDSSection extends LitElement {
  @property({ type: Number }) level?: HeadingLevel;
  private _currentLevel: HeadingLevel = 1;

  private getParentLevel(): HeadingLevel {
    const parentSection = this.parentElement?.closest(
      `${prefix}-section`
    ) as CDSSection;
    return parentSection ? parentSection.getCurrentLevel() : 1;
  }

  connectedCallback() {
    super.connectedCallback();
    const parentLevel = this.getParentLevel();
    this._currentLevel =
      this.level ?? (Math.min(parentLevel + 1, 6) as HeadingLevel);
  }

  getCurrentLevel(): HeadingLevel {
    return this._currentLevel;
  }

  render() {
    return html`<slot></slot>`;
  }
}

/**
 * The heading component
 *
 * @element cds-heading
 */
@customElement(`${prefix}-heading`)
class CDSHeading extends LitElement {
  private level: HeadingLevel = 1;

  connectedCallback() {
    super.connectedCallback();
    const section = this.closest(`${prefix}-section`) as CDSSection;
    this.level = section ? section.getCurrentLevel() : 1;
  }

  render() {
    const headingElement = `
      <h${this.level}>
        <slot></slot>
      </h${this.level}>
    `;

    return html`${unsafeHTML(headingElement)}`;
  }

  static styles = styles;
}

export default CDSHeading;

// packages/react/src/components/Heading/index.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React, { type ElementType } from 'react';
import type { PolymorphicProps } from '../../types/common';

type HeadingLevel = 1 | 2 | 3 | 4 | 5 | 6;

const HeadingContext = React.createContext<HeadingLevel>(1);

type SectionBaseProps = {
  level?: HeadingLevel;
};

type SectionProps<E extends ElementType> = PolymorphicProps<
  E,
  SectionBaseProps
>;

export function Section<E extends ElementType>({
  as: BaseComponent = 'section' as E,
  level: levelOverride,
  ...rest
}: SectionProps<E>) {
  const parentLevel = React.useContext(HeadingContext);
  const level = levelOverride ?? parentLevel + 1;
  const BaseComponentAsAny = BaseComponent as any;

  return (
    <HeadingContext.Provider value={Math.min(level, 6) as HeadingLevel}>
      <BaseComponentAsAny {...rest} />
    </HeadingContext.Provider>
  );
}

Section.propTypes = {
  /**
   * Provide an alternative tag or component to use instead of the default
   * <section> element
   */
  as: PropTypes.elementType,

  /**
   * Specify the content that will be placed in the component
   */
  children: PropTypes.node,

  /**
   * Specify a class name for the outermost node of the component
   */
  className: PropTypes.string,

  /**
   * Overrides the level of the section
   */
  level: PropTypes.number,
};

type HeadingProps = JSX.IntrinsicElements[`h${HeadingLevel}`];

export function Heading(props: HeadingProps) {
  const HeadingIntrinsic = `h${React.useContext(HeadingContext)}` as const;
  return <HeadingIntrinsic {...props} />;
}

Heading.propTypes = {
  /**
   * Specify the content that will be placed in the component
   */
  children: PropTypes.node,

  /**
   * Specify a class name for the outermost node of the component
   */
  className: PropTypes.string,
};
