// web-components/packages/carbon-web-components/src/components/structured-list/structured-list-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { boolean } from '@storybook/addon-knobs';
import { ifDefined } from 'lit/directives/if-defined.js';
import './structured-list';
import './structured-list-head';
import './structured-list-header-row';
import './structured-list-header-cell';
import './structured-list-body';
import './structured-list-row';
import './structured-list-cell';
import './structured-list-header-cell-skeleton';
import storyDocs from './structured-list-story.mdx';
import styles from './structured-list-story.scss';
import { prefix } from '../../globals/settings';

export const Default = (args) => {
  const { hasSelection } = args?.[`${prefix}-structured-list`] ?? {};
  const selectionName = !hasSelection ? undefined : 'structured-list-selection';
  const selectionValues = !hasSelection
    ? []
    : [
        'structured-list-selection-0',
        'structured-list-selection-1',
        'structured-list-selection-2',
      ];
  return html`
    <cds-structured-list selection-name=${ifDefined(selectionName)}>
      <cds-structured-list-head>
        <cds-structured-list-header-row>
          <cds-structured-list-header-cell
            >ColumnA</cds-structured-list-header-cell
          >
          <cds-structured-list-header-cell
            >ColumnB</cds-structured-list-header-cell
          >
          <cds-structured-list-header-cell
            >ColumnC</cds-structured-list-header-cell
          >
        </cds-structured-list-header-row>
      </cds-structured-list-head>
      <cds-structured-list-body>
        <cds-structured-list-row
          selection-value=${ifDefined(selectionValues[0])}>
          <cds-structured-list-cell>Row 1</cds-structured-list-cell>
          <cds-structured-list-cell>Row 1</cds-structured-list-cell>
          <cds-structured-list-cell
            >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
            magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
            sem vel euismod dignissim.</cds-structured-list-cell
          >
        </cds-structured-list-row>
        <cds-structured-list-row
          selection-value=${ifDefined(selectionValues[1])}>
          <cds-structured-list-cell>Row 2</cds-structured-list-cell>
          <cds-structured-list-cell>Row 2</cds-structured-list-cell>
          <cds-structured-list-cell
            >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
            magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
            sem vel euismod dignissim.</cds-structured-list-cell
          >
        </cds-structured-list-row>
        <cds-structured-list-row
          selection-value=${ifDefined(selectionValues[2])}>
          <cds-structured-list-cell>Row 3</cds-structured-list-cell>
          <cds-structured-list-cell>Row 3</cds-structured-list-cell>
          <cds-structured-list-cell
            >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
            magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
            sem vel euismod dignissim.</cds-structured-list-cell
          >
        </cds-structured-list-row>
      </cds-structured-list-body>
    </cds-structured-list>
  `;
};

Default.storyName = 'Default';

Default.parameters = {
  knobs: {
    [`${prefix}-structured-list`]: () => ({
      hasSelection: boolean(
        'Supports selection feature (has-selection)',
        false
      ),
    }),
  },
};

export const skeleton = () => html`
  <style>
    ${styles}
  </style>
  <cds-structured-list>
    <cds-structured-list-head>
      <cds-structured-list-header-row>
        <cds-structured-list-header-cell-skeleton></cds-structured-list-header-cell-skeleton>
        <cds-structured-list-header-cell-skeleton></cds-structured-list-header-cell-skeleton>
        <cds-structured-list-header-cell-skeleton></cds-structured-list-header-cell-skeleton>
      </cds-structured-list-header-row>
    </cds-structured-list-head>
    <cds-structured-list-body>
      <cds-structured-list-row>
        <cds-structured-list-cell></cds-structured-list-cell>
        <cds-structured-list-cell></cds-structured-list-cell>
        <cds-structured-list-cell></cds-structured-list-cell>
      </cds-structured-list-row>
      <cds-structured-list-row>
        <cds-structured-list-cell></cds-structured-list-cell>
        <cds-structured-list-cell></cds-structured-list-cell>
        <cds-structured-list-cell></cds-structured-list-cell>
      </cds-structured-list-row>
      <cds-structured-list-row>
        <cds-structured-list-cell></cds-structured-list-cell>
        <cds-structured-list-cell></cds-structured-list-cell>
        <cds-structured-list-cell></cds-structured-list-cell>
      </cds-structured-list-row>
    </cds-structured-list-body>
  </cds-structured-list>
`;

skeleton.parameters = {
  percy: {
    skip: true,
  },
};

export default {
  title: 'Components/Structured list',
  parameters: {
    ...storyDocs.parameters,
  },
};

// packages/react/src/components/StructuredList/StructuredList-story.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { CheckmarkFilled } from '@carbon/icons-react';
import { withKnobs, boolean } from '@storybook/addon-knobs';

import {
  StructuredListWrapper,
  StructuredListHead,
  StructuredListBody,
  StructuredListRow,
  StructuredListInput,
  StructuredListCell,
} from './StructuredList';
import StructuredListSkeleton from '../StructuredList/StructuredList.Skeleton';
import mdx from './StructuredList.mdx';

const prefix = 'cds';

const props = () => ({
  isCondensed: boolean('Condensed', false),
  isFlush: boolean('Flush alignment', false),
});

export default {
  title: 'Components/StructuredList',
  component: StructuredListWrapper,
  decorators: [withKnobs],
  subcomponents: {
    StructuredListHead,
    StructuredListBody,
    StructuredListRow,
    StructuredListInput,
    StructuredListCell,
  },
  parameters: {
    docs: {
      page: mdx,
    },
  },
};

export const Simple = () => (
  <StructuredListWrapper>
    <StructuredListHead>
      <StructuredListRow head>
        <StructuredListCell head>ColumnA</StructuredListCell>
        <StructuredListCell head>ColumnB</StructuredListCell>
        <StructuredListCell head>ColumnC</StructuredListCell>
      </StructuredListRow>
    </StructuredListHead>
    <StructuredListBody>
      <StructuredListRow>
        <StructuredListCell noWrap>Row 1</StructuredListCell>
        <StructuredListCell>Row 1</StructuredListCell>
        <StructuredListCell>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
          magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
          sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque
          vulputate nisl a porttitor interdum.
        </StructuredListCell>
      </StructuredListRow>
      <StructuredListRow>
        <StructuredListCell noWrap>Row 2</StructuredListCell>
        <StructuredListCell>Row 2</StructuredListCell>
        <StructuredListCell>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
          magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
          sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque
          vulputate nisl a porttitor interdum.
        </StructuredListCell>
      </StructuredListRow>
    </StructuredListBody>
  </StructuredListWrapper>
);

Simple.parameters = {
  info: {
    text: `
        Structured Lists group content that is similar or related, such as terms or definitions.
      `,
  },
};

export const Playground = () => (
  <StructuredListWrapper {...props()}>
    <StructuredListHead>
      <StructuredListRow head>
        <StructuredListCell head>ColumnA</StructuredListCell>
        <StructuredListCell head>ColumnB</StructuredListCell>
        <StructuredListCell head>ColumnC</StructuredListCell>
      </StructuredListRow>
    </StructuredListHead>
    <StructuredListBody>
      <StructuredListRow>
        <StructuredListCell noWrap>Row 1</StructuredListCell>
        <StructuredListCell>Row 1</StructuredListCell>
        <StructuredListCell>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
          magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
          sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque
          vulputate nisl a porttitor interdum.
        </StructuredListCell>
      </StructuredListRow>
      <StructuredListRow>
        <StructuredListCell noWrap>Row 2</StructuredListCell>
        <StructuredListCell>Row 2</StructuredListCell>
        <StructuredListCell>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
          magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
          sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque
          vulputate nisl a porttitor interdum.
        </StructuredListCell>
      </StructuredListRow>
    </StructuredListBody>
  </StructuredListWrapper>
);

Playground.parameters = {
  info: {
    text: `
        Structured Lists group content that is similar or related, such as terms or definitions.
      `,
  },
};

export const Selection = () => {
  const structuredListBodyRowGenerator = (numRows) => {
    return Array.apply(null, Array(numRows)).map((n, i) => (
      <StructuredListRow label key={`row-${i}`}>
        <StructuredListCell>Row {i}</StructuredListCell>
        <StructuredListCell>Row {i}</StructuredListCell>
        <StructuredListCell>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
          magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
          sem vel euismod dignissim. Nulla ut cursus dolor. Pellentesque
          vulputate nisl a porttitor interdum.
        </StructuredListCell>
        <StructuredListInput
          id={`row-${i}`}
          value={`row-${i}`}
          title={`row-${i}`}
          name="row-0"
          defaultChecked={!i || null}
        />
        <StructuredListCell>
          <CheckmarkFilled
            className={`${prefix}--structured-list-svg`}
            aria-label="select an option">
            <title>select an option</title>
          </CheckmarkFilled>
        </StructuredListCell>
      </StructuredListRow>
    ));
  };
  return (
    <StructuredListWrapper selection {...props()}>
      <StructuredListHead>
        <StructuredListRow head>
          <StructuredListCell head>ColumnA</StructuredListCell>
          <StructuredListCell head>ColumnB</StructuredListCell>
          <StructuredListCell head>ColumnC</StructuredListCell>
          <StructuredListCell head>{''}</StructuredListCell>
        </StructuredListRow>
      </StructuredListHead>
      <StructuredListBody>
        {structuredListBodyRowGenerator(4)}
      </StructuredListBody>
    </StructuredListWrapper>
  );
};

Selection.parameters = {
  info: {
    text: `
    Structured Lists with selection allow a row of list content to be selected.
  `,
  },
};

export const Skeleton = () => (
  <div style={{ width: '800px' }}>
    <StructuredListSkeleton />
    <StructuredListSkeleton />
  </div>
);

Skeleton.storyName = 'skeleton';

Skeleton.parameters = {
  info: {
    text: `
        Placeholder skeleton state to use when content is loading.
      `,
  },
};
