// web-components/packages/carbon-web-components/src/components/select/select-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { action } from '@storybook/addon-actions';
import { boolean, select } from '@storybook/addon-knobs';
import textNullable from '../../../.storybook/knob-text-nullable';
// Below path will be there when an application installs `carbon-web-components` package.
// In our dev env, we auto-generate the file and re-map below path to to point to the generated file.
// @ts-ignore
import { ifDefined } from 'lit/directives/if-defined.js';
import { INPUT_COLOR_SCHEME, INPUT_SIZE } from '../input/input';
import './select';
import storyDocs from './select-story.mdx';

const colorSchemes = {
  [`Regular`]: null,
  [`Light (${INPUT_COLOR_SCHEME.LIGHT})`]: INPUT_COLOR_SCHEME.LIGHT,
};

const sizes = {
  'Regular size': null,
  [`Small size (${INPUT_SIZE.SMALL})`]: INPUT_SIZE.SMALL,
  [`Extra large size (${INPUT_SIZE.EXTRA_LARGE})`]: INPUT_SIZE.EXTRA_LARGE,
};

export const Default = (args) => {
  const {
    autofocus,
    colorScheme,
    disabled,
    helperText,
    invalid,
    labelText,
    name,
    placeholder,
    size,
    validityMessage,
    value,
    children = html`
      <bx-select-item-group label="Category 1">
        <bx-select-item value="all">Option 1</bx-select-item>
        <bx-select-item value="cloudFoundry">Option 2</bx-select-item>
      </bx-select-item-group>
      <bx-select-item-group label="Category 2">
        <bx-select-item value="staging">Option 3</bx-select-item>
        <bx-select-item value="dea">Option 4</bx-select-item>
        <bx-select-item value="router">Option 5</bx-select-item>
      </bx-select-item-group>
    `,
    onInput,
  } = args?.['bx-select'] ?? {};
  return html`
    <bx-select
      ?autofocus="${autofocus}"
      color-scheme="${ifDefined(colorScheme)}"
      ?disabled="${disabled}"
      helper-text="${ifDefined(helperText)}"
      ?invalid="${invalid}"
      label-text="${ifDefined(labelText)}"
      name="${ifDefined(name)}"
      placeholder="${ifDefined(placeholder)}"
      size="${ifDefined(size)}"
      validity-message="${ifDefined(validityMessage)}"
      value="${ifDefined(value)}"
      @bx-select-selected="${ifDefined(onInput)}">
      ${children}
    </bx-select>
  `;
};

Default.parameters = {
  knobs: {
    'bx-select': () => ({
      colorScheme: select('Color scheme (color-scheme)', colorSchemes, null),
      disabled: boolean('Disabled (disabled)', false),
      helperText: textNullable(
        'Helper text (helper-text)',
        'Optional helper text'
      ),
      invalid: boolean('Invalid (invalid)', false),
      labelText: textNullable('Label text (label-text)', 'Select'),
      placeholder: textNullable(
        'Placeholder text (placeholder)',
        'Optional placeholder text'
      ),
      size: select('Dropdown size (size)', sizes, null),
      validityMessage: textNullable(
        'The validity message (validity-message)',
        ''
      ),
      value: textNullable('The value of the selected item (value)', ''),
      onInput: action('bx-select-selected'),
    }),
  },
};

export default {
  title: 'Components/Select',
  parameters: {
    ...storyDocs.parameters,
  },
};

// web-components/packages/carbon-web-components/src/components/select/select-story-react.tsx
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
// Below path will be there when an application installs `carbon-web-components` package.
// In our dev env, we auto-generate the file and re-map below path to to point to the generated file.
// @ts-ignore
import BXSelect from 'carbon-web-components/es/components-react/select/select';
// @ts-ignore
import BXSelectItem from 'carbon-web-components/es/components-react/select/select-item';
// @ts-ignore
import BXSelectItemGroup from 'carbon-web-components/es/components-react/select/select-item-group';
import { Default as baseDefault } from './select-story';

export { default } from './select-story';

export const Default = args => {
  const {
    autofocus,
    colorScheme,
    disabled,
    helperText,
    invalid,
    labelText,
    name,
    placeholder,
    size,
    validityMessage,
    value,
    onInput,
  } = args?.['bx-select'] ?? {};
  return (
    <BXSelect
      autofocus={autofocus}
      colorScheme={colorScheme}
      disabled={disabled}
      helperText={helperText}
      invalid={invalid}
      labelText={labelText}
      name={name}
      placeholder={placeholder}
      size={size}
      validityMessage={validityMessage}
      value={value}
      onInput={onInput}>
      <BXSelectItemGroup label="Category 1">
        <BXSelectItem value="all">Option 1</BXSelectItem>
        <BXSelectItem value="cloudFoundry">Option 2</BXSelectItem>
      </BXSelectItemGroup>
      <BXSelectItemGroup label="Category 2">
        <BXSelectItem value="staging">Option 3</BXSelectItem>
        <BXSelectItem value="dea">Option 4</BXSelectItem>
        <BXSelectItem value="router">Option 5</BXSelectItem>
      </BXSelectItemGroup>
    </BXSelect>
  );
};

Object.assign(Default, baseDefault);
