// packages/react/src/components/UIShell/SkipToContent.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import React, { ComponentProps } from 'react';
import PropTypes from 'prop-types';
import { usePrefix } from '../../internal/usePrefix';

type SkipToContentProps = ComponentProps<'a'>;

export default function SkipToContent({
  children = 'Skip to main content',
  className: customClassName,
  href = '#main-content',
  tabIndex = 0,
  ...rest
}: SkipToContentProps) {
  const prefix = usePrefix();
  const className = cx(`${prefix}--skip-to-content`, customClassName);
  return (
    <a {...rest} className={className} href={href} tabIndex={tabIndex}>
      {children}
    </a>
  );
}

SkipToContent.propTypes = {
  /**
   * A ReactNode to display in the SkipToContent `a` tag.
   * `'Skip to main content'` by default.
   */
  children: PropTypes.node,

  className: PropTypes.string,

  /**
   * Provide the `href` to the id of the element on your package that is the
   * main content. `#main-content` by default.
   */
  href: PropTypes.string,

  /**
   * Optionally override the default tabindex of 0
   */
  tabIndex: PropTypes.string,
};

// packages/web-components/src/components/skip-to-content/skip-to-content.ts
/**
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import { ifDefined } from 'lit/directives/if-defined.js';
import FocusMixin from '../../globals/mixins/focus';
import styles from './skip-to-content.scss?lit';

/**
 * Skip-to-content link.
 *
 * @element cds-skip-to-content
 */
class CDSSkipToContent extends FocusMixin(LitElement) {
  static is = `${prefix}-skip-to-content`;

  /**
   * The assistive text for the link,
   */
  @property({ attribute: 'link-assistive-text' })
  linkAssisstiveText = 'Skip to main content';

  /**
   * The skip link href.
   */
  @property()
  href?: string;

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'navigation');
    }
    super.connectedCallback();
  }

  render() {
    const { linkAssisstiveText } = this;
    return html`
      <a class="${prefix}--skip-to-content" href="${ifDefined(this.href)}"
        ><slot>${linkAssisstiveText}</slot></a
      >
    `;
  }

  updated(changedProperties) {
    if (changedProperties.has('linkAssisstiveText')) {
      const { linkAssisstiveText } = this;
      this.setAttribute('aria-label', linkAssisstiveText);
    }
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static styles = styles;
}

export default CDSSkipToContent;
