// packages/web-components/src/components/card/card-header.ts
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { state } from 'lit/decorators.js';
import { consume } from '@lit/context';
import { prefix } from '../../globals/settings';
import {
  cardContext,
  cardDefaultContext,
  type CardContextValue,
} from './card-context';
import styles from './card.scss?lit';

/**
 * Card header — header section of the card.
 *
 * @element cds-card-header
 * @slot - Default slot for cds-card-title, cds-card-title-media, cds-card-actions.
 * @slot decorator - Slot for cds-ai-label or other decorator element.
 */
class CDSCardHeader extends LitElement {
  static is = `${prefix}-card-header`;

  @consume({ context: cardContext, subscribe: true })
  @state()
  private _cardContext: CardContextValue = cardDefaultContext;

  private _handleDefaultSlotChange({ target }: Event) {
    const slot = target as HTMLSlotElement;
    const hasTitleMedia = slot
      .assignedElements({ flatten: true })
      .some((el) => el.matches(`${prefix}-card-title-media`));

    if (hasTitleMedia) {
      this.setAttribute('has-title-media', '');
    } else {
      this.removeAttribute('has-title-media');
    }
  }

  private _handleDecoratorInteraction(e: Event) {
    e.stopPropagation();
  }

  render() {
    void this._cardContext;

    return html`
      <div class="${prefix}--card__header">
        <slot @slotchange=${this._handleDefaultSlotChange}></slot>
        <div
          class="${prefix}--card__decorator"
          role="presentation"
          @click=${this._handleDecoratorInteraction}
          @keydown=${this._handleDecoratorInteraction}>
          <slot name="decorator"></slot>
        </div>
      </div>
    `;
  }

  static styles = styles;
}

export default CDSCardHeader;

// packages/react/src/components/Card/CardHeader.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { forwardRef, useCallback } from 'react';
import cx from 'classnames';
import { CardHeaderProps } from './Card.types';
import { useCardContext } from './CardContext';
import { usePrefix } from '../../internal/usePrefix';

const componentName = 'CardHeader';

/**
 * CardHeader — header section of the card.
 */
export const CardHeader = forwardRef<HTMLDivElement, CardHeaderProps>(
  ({ className, children, ...rest }, ref) => {
    const prefix = usePrefix();
    const blockClass = `${prefix}--card`;
    const context = useCardContext();

    const handleDecoratorClick = useCallback(
      (e: React.MouseEvent) => e.stopPropagation(),
      []
    );

    const handleDecoratorKeyDown = useCallback(
      (e: React.KeyboardEvent) => e.stopPropagation(),
      []
    );

    return (
      <div
        {...rest}
        ref={ref}
        className={cx(`${blockClass}__header`, className)}>
        {children}
        {context.decorator && (
          <div
            className={`${blockClass}__decorator`}
            role="presentation"
            onClick={handleDecoratorClick}
            onKeyDown={handleDecoratorKeyDown}>
            {context.decorator}
          </div>
        )}
      </div>
    );
  }
);

CardHeader.displayName = componentName;
