// packages/react/src/components/PaginationNav/PaginationNav.js
/**
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React, { useState, useEffect, useRef } from 'react';
import classnames from 'classnames';
import {
  CaretRight16,
  CaretLeft16,
  OverflowMenuHorizontal16,
} from '@carbon/icons-react';
import { settings } from 'carbon-components';
import Button from '../Button';

const { prefix } = settings;

const translationIds = {
  'carbon.pagination-nav.next': 'Next',
  'carbon.pagination-nav.previous': 'Previous',
  'carbon.pagination-nav.item': 'Page',
  'carbon.pagination-nav.active': 'Active',
  'carbon.pagination-nav.of': 'of',
};

function translateWithId(messageId) {
  return translationIds[messageId];
}

// https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state
function usePrevious(value) {
  const ref = useRef();

  useEffect(() => {
    ref.current = value;
  });

  return ref.current;
}

function getCuts(page, totalItems, itemsThatFit, splitPoint = null) {
  if (itemsThatFit >= totalItems) {
    return {
      front: 0,
      back: 0,
    };
  }

  const split = splitPoint || Math.ceil(itemsThatFit / 2) - 1;

  let frontHidden = page + 1 - split;
  let backHidden = totalItems - page - (itemsThatFit - split) + 1;

  if (frontHidden <= 1) {
    backHidden -= frontHidden <= 0 ? Math.abs(frontHidden) + 1 : 0;
    frontHidden = 0;
  }

  if (backHidden <= 1) {
    frontHidden -= backHidden <= 0 ? Math.abs(backHidden) + 1 : 0;
    backHidden = 0;
  }

  return {
    front: frontHidden,
    back: backHidden,
  };
}

function DirectionButton({ direction, label, disabled, onClick }) {
  const icon = direction === 'forward' ? CaretRight16 : CaretLeft16;

  return (
    <li className={`${prefix}--pagination-nav__list-item`}>
      <Button
        disabled={disabled}
        renderIcon={icon}
        kind="ghost"
        hasIconOnly
        iconDescription={label}
        tooltipAlignment="center"
        tooltipPosition="bottom"
        onClick={onClick}
      />
    </li>
  );
}

function PaginationItem({
  page,
  isActive,
  onClick,
  translateWithId: t = translateWithId,
}) {
  const itemLabel = t('carbon.pagination-nav.item');

  return (
    <li className={`${prefix}--pagination-nav__list-item`}>
      <button
        type="button"
        className={classnames(`${prefix}--pagination-nav__page`, {
          [`${prefix}--pagination-nav__page--active`]: isActive,
        })}
        onClick={onClick}
        data-page={page}
        aria-current={isActive ? 'page' : null}>
        <span className={`${prefix}--pagination-nav__accessibility-label`}>
          {isActive
            ? `${t('carbon.pagination-nav.active')}, ${itemLabel}`
            : itemLabel}
        </span>
        {page}
      </button>
    </li>
  );
}

function PaginationOverflow({
  fromIndex,
  count,
  onSelect,
  translateWithId: t = translateWithId,
}) {
  if (count > 1) {
    return (
      <li className={`${prefix}--pagination-nav__list-item`}>
        <div className={`${prefix}--pagination-nav__select`}>
          {/* eslint-disable-next-line jsx-a11y/no-onchange */}
          <select
            className={`${prefix}--pagination-nav__page ${prefix}--pagination-nav__page--select`}
            aria-label={`Select ${t('carbon.pagination-nav.item')} number`}
            onChange={(e) => {
              const index = Number(e.target.value);
              onSelect(index);
            }}>
            {/* eslint-disable-next-line jsx-a11y/control-has-associated-label */}
            <option value="" hidden />
            {[...Array(count)].map((e, i) => (
              <option
                value={(fromIndex + i).toString()}
                data-page={fromIndex + i + 1}
                key={`overflow-${fromIndex + i}`}>
                {fromIndex + i + 1}
              </option>
            ))}
          </select>
          <div className={`${prefix}--pagination-nav__select-icon-wrapper`}>
            <OverflowMenuHorizontal16
              className={`${prefix}--pagination-nav__select-icon`}
            />
          </div>
        </div>
      </li>
    );
  }

  if (count === 1) {
    return (
      <PaginationItem
        page={fromIndex + 1}
        translateWithId={t}
        onClick={() => {
          onSelect(fromIndex);
        }}
      />
    );
  }

  return null;
}

export default function PaginationNav({
  className,
  onChange = () => {},
  totalItems,
  itemsShown = 10,
  page = 0,
  loop = false,
  translateWithId: t = translateWithId,
  ...rest
}) {
  const [currentPage, setCurrentPage] = useState(page);
  const [itemsThatFit, setItemsThatFit] = useState(
    itemsShown >= 4 ? itemsShown : 4
  );
  const [cuts, setCuts] = useState(
    getCuts(currentPage, totalItems, itemsThatFit)
  );
  const prevPage = usePrevious(currentPage);

  function jumpToItem(index) {
    if (index >= 0 && index < totalItems) {
      setCurrentPage(index);
      onChange(index);
    }
  }

  function jumpToNext() {
    const nextIndex = currentPage + 1;

    if (nextIndex >= totalItems) {
      if (loop) {
        jumpToItem(0);
      }
    } else {
      jumpToItem(nextIndex);
    }
  }

  function jumpToPrevious() {
    const previousIndex = currentPage - 1;

    if (previousIndex < 0) {
      if (loop) {
        jumpToItem(totalItems - 1);
      }
    } else {
      jumpToItem(previousIndex);
    }
  }

  function pageWouldBeHidden(page) {
    const startOffset = itemsThatFit <= 4 && page > 1 ? 0 : 1;

    const wouldBeHiddenInFront = page >= startOffset && page <= cuts.front;
    const wouldBeHiddenInBack =
      page >= totalItems - cuts.back - 1 && page <= totalItems - 2;

    return wouldBeHiddenInFront || wouldBeHiddenInBack;
  }

  // jump to new page if props.page is updated
  useEffect(() => {
    setCurrentPage(page);
  }, [page]);

  // re-calculate cuts if props.totalItems or props.itemsShown change
  useEffect(() => {
    setItemsThatFit(itemsShown >= 4 ? itemsShown : 4);
    setCuts(getCuts(currentPage, totalItems, itemsShown));
  }, [totalItems, itemsShown]); // eslint-disable-line react-hooks/exhaustive-deps

  // update cuts if necessary whenever currentPage changes
  useEffect(() => {
    if (pageWouldBeHidden(currentPage)) {
      const delta = currentPage - prevPage || 0;

      if (delta > 0) {
        const splitPoint = itemsThatFit - 3;
        setCuts(getCuts(currentPage, totalItems, itemsThatFit, splitPoint));
      } else {
        const splitPoint = itemsThatFit > 4 ? 2 : 1;
        setCuts(getCuts(currentPage, totalItems, itemsThatFit, splitPoint));
      }
    }
  }, [currentPage]); // eslint-disable-line react-hooks/exhaustive-deps

  const classNames = classnames(`${prefix}--pagination-nav`, className);

  const backwardButtonDisabled = !loop && currentPage === 0;
  const forwardButtonDisabled = !loop && currentPage === totalItems - 1;

  const startOffset = itemsThatFit <= 4 && currentPage > 1 ? 0 : 1;

  return (
    <nav className={classNames} {...rest} aria-label="pagination">
      <ul className={`${prefix}--pagination-nav__list`}>
        <DirectionButton
          direction="backward"
          label={t('carbon.pagination-nav.previous')}
          disabled={backwardButtonDisabled}
          onClick={jumpToPrevious}
        />

        {
          // render first item if at least 5 items can be displayed or
          // 4 items can be displayed and the current page is either 0 or 1
          (itemsThatFit >= 5 || (itemsThatFit <= 4 && currentPage <= 1)) && (
            <PaginationItem
              page={1}
              translateWithId={t}
              isActive={currentPage === 0}
              onClick={() => {
                jumpToItem(0);
              }}
            />
          )
        }

        {/* render first overflow */}
        <PaginationOverflow
          fromIndex={startOffset}
          count={cuts.front}
          onSelect={jumpToItem}
        />

        {
          // render items between overflows
          [...Array(totalItems)]
            .map((e, i) => i)
            .slice(startOffset + cuts.front, (1 + cuts.back) * -1)
            .map((item) => (
              <PaginationItem
                key={`item-${item}`}
                page={item + 1}
                translateWithId={t}
                isActive={currentPage === item}
                onClick={() => {
                  jumpToItem(item);
                }}
              />
            ))
        }

        {/* render second overflow */}
        <PaginationOverflow
          fromIndex={totalItems - cuts.back - 1}
          count={cuts.back}
          onSelect={jumpToItem}
        />

        {
          // render last item unless there is only one in total
          totalItems > 1 && (
            <PaginationItem
              page={totalItems}
              translateWithId={t}
              isActive={currentPage === totalItems - 1}
              onClick={() => {
                jumpToItem(totalItems - 1);
              }}
            />
          )
        }

        <DirectionButton
          direction="forward"
          label={t('carbon.pagination-nav.next')}
          disabled={forwardButtonDisabled}
          onClick={jumpToNext}
        />
      </ul>
      <div
        aria-live="polite"
        aria-atomic="true"
        className={`${prefix}--pagination-nav__accessibility-label`}>
        {`${t('carbon.pagination-nav.item')} ${currentPage + 1} ${t(
          'carbon.pagination-nav.of'
        )} ${totalItems}`}
      </div>
    </nav>
  );
}

DirectionButton.propTypes = {
  /**
   * The direction this button represents ("forward" or "backward").
   */
  direction: PropTypes.oneOf(['forward', 'backward']),

  /**
   * The label shown in the button's tooltip.
   */
  label: PropTypes.string,

  /**
   * Whether or not the button should be disabled.
   */
  disabled: PropTypes.bool,

  /**
   * The callback function called when the button is clicked.
   */
  onClick: PropTypes.func,
};

PaginationItem.propTypes = {
  /**
   * The page number this item represents.
   */
  page: PropTypes.number,

  /**
   * Whether or not this is the currently active page.
   */
  isActive: PropTypes.bool,

  /**
   * The callback function called when the item is clicked.
   */
  onClick: PropTypes.func,

  /**
   * Specify a custom translation function that takes in a message identifier
   * and returns the localized string for the message
   */
  translateWithId: PropTypes.func,
};

PaginationOverflow.propTypes = {
  /**
   * From which index on this overflow should start displaying pages.
   */
  fromIndex: PropTypes.number,

  /**
   * How many items to display in this overflow.
   */
  count: PropTypes.number,

  /**
   * The callback function called when the user selects a page from the overflow.
   */
  onSelect: PropTypes.func,

  /**
   * Specify a custom translation function that takes in a message identifier
   * and returns the localized string for the message
   */
  translateWithId: PropTypes.func,
};

PaginationNav.propTypes = {
  /**
   * Additional CSS class names.
   */
  className: PropTypes.string,

  /**
   * The callback function called when the current page changes.
   */
  onChange: PropTypes.func,

  /**
   * The total number of items.
   */
  totalItems: PropTypes.number,

  /**
   * The number of items to be shown.
   */
  itemsShown: PropTypes.number,

  /**
   * The current page.
   */
  page: PropTypes.number,

  /**
   * Whether user should be able to loop through the items when reaching first / last.
   */
  loop: PropTypes.bool,

  /**
   * Specify a custom translation function that takes in a message identifier
   * and returns the localized string for the message
   */
  translateWithId: PropTypes.func,
};

// packages/web-components/src/components/pagination-nav/pagination-nav.ts
/**
 * Copyright IBM Corp. 2019, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property, state } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import CaretLeft16 from '@carbon/icons/es/caret--left/16.js';
import CaretRight16 from '@carbon/icons/es/caret--right/16.js';
import OverflowMenuHorizontal16 from '@carbon/icons/es/overflow-menu--horizontal/16.js';
import FocusMixin from '../../globals/mixins/focus';
import HostListenerMixin from '../../globals/mixins/host-listener';
import styles from './pagination-nav.scss?lit';
import { PAGINATION_NAV_SIZE } from './defs';
import { iconLoader } from '../../globals/internal/icon-loader';
import '../icon-button/index';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Translation IDs
 */
const translationIds = {
  'carbon.pagination-nav.next': 'Next',
  'carbon.pagination-nav.previous': 'Previous',
  'carbon.pagination-nav.item': 'Page',
  'carbon.pagination-nav.active': 'Active',
  'carbon.pagination-nav.of': 'of',
};

/**
 * Pagination navigation component
 *
 * @element cds-pagination-nav
 * @fires cds-pagination-nav-changed - The custom event fired when the current page changes
 */
@customElement(`${prefix}-pagination-nav`)
class CDSPaginationNav extends FocusMixin(HostListenerMixin(LitElement)) {
  /**
   * Calculate cuts for pagination display
   */
  private _calculateCuts(
    page: number,
    totalItems: number,
    itemsDisplayedOnPage: number,
    splitPoint: number | null = null
  ) {
    if (itemsDisplayedOnPage >= totalItems) {
      return { front: 0, back: 0 };
    }

    const split = splitPoint || Math.ceil(itemsDisplayedOnPage / 2) - 1;

    let frontHidden = page + 1 - split;
    let backHidden = totalItems - page - (itemsDisplayedOnPage - split) + 1;

    if (frontHidden <= 1) {
      backHidden -= frontHidden <= 0 ? Math.abs(frontHidden) + 1 : 0;
      frontHidden = 0;
    }

    if (backHidden <= 1) {
      frontHidden -= backHidden <= 0 ? Math.abs(backHidden) + 1 : 0;
      backHidden = 0;
    }

    return { front: frontHidden, back: backHidden };
  }

  /**
   * Jump to a specific page
   */
  private _jumpToItem(index: number) {
    if (index >= 0 && index < this.totalItems) {
      this.page = index;
      this.dispatchEvent(
        new CustomEvent(
          (this.constructor as typeof CDSPaginationNav).eventChange,
          {
            bubbles: true,
            composed: true,
            detail: {
              page: index,
            },
          }
        )
      );
    }
  }

  /**
   * Jump to the next page
   */
  private _jumpToNext() {
    const nextIndex = this.page + 1;

    if (nextIndex >= this.totalItems) {
      if (this.loop) {
        this._jumpToItem(0);
      }
    } else {
      this._jumpToItem(nextIndex);
    }
  }

  /**
   * Jump to the previous page
   */
  private _jumpToPrevious() {
    const previousIndex = this.page - 1;

    if (previousIndex < 0) {
      if (this.loop) {
        this._jumpToItem(this.totalItems - 1);
      }
    } else {
      this._jumpToItem(previousIndex);
    }
  }

  /**
   * Check if a page would be hidden in the current view
   */
  private _pageWouldBeHidden(page: number) {
    const startOffset = this.itemsDisplayedOnPage <= 4 && this.page > 1 ? 0 : 1;

    const wouldBeHiddenInFront =
      (page >= startOffset && page <= this.cuts.front) || page === 0;
    const wouldBeHiddenInBack =
      page >= this.totalItems - this.cuts.back - 1 &&
      page <= this.totalItems - 2;

    return wouldBeHiddenInFront || wouldBeHiddenInBack;
  }

  /**
   * If true, the '...' pagination overflow will not render page links between the first and last rendered buttons.
   */
  @property({ type: Boolean, reflect: true })
  disableOverflow = false;

  /**
   * The number of items to be shown (minimum of 4 unless props.items < 4).
   */
  @property({ type: Number, attribute: 'items-shown' })
  itemsShown = 10;

  /**
   * Whether user should be able to loop through the items when reaching first / last.
   */
  @property({ type: Boolean, reflect: true })
  loop = false;

  /**
   * The index of current page.
   */
  @property({ type: Number, reflect: true })
  page = 0;

  /**
   * Specify the size of the PaginationNav.
   */
  @property({ reflect: true })
  size = PAGINATION_NAV_SIZE.LARGE;

  /**
   * Specify the alignment of the tooltip for the icon-only next/prev buttons.
   */
  @property({ attribute: 'tooltip-alignment' })
  tooltipAlignment = 'center';

  /**
   * Specify the position of the tooltip for the icon-only next/prev buttons.
   */
  @property({ attribute: 'tooltip-position' })
  tooltipPosition = 'bottom';

  /**
   * The total number of items.
   */
  @property({ type: Number, attribute: 'total-items' })
  totalItems = 10;

  /**
   * Internal state for items displayed on page
   */
  @state()
  private itemsDisplayedOnPage = 10;

  /**
   * Internal state for cuts
   */
  @state()
  private cuts = { front: 0, back: 0 };

  /**
   * Internal state for previous page
   */
  @state()
  private prevPage: number | null = null;

  /**
   * Translate function for i18n
   */
  private _translate(key: string): string {
    return translationIds[key] || key;
  }

  updated(changedProperties) {
    if (changedProperties.has('page')) {
      this.prevPage = changedProperties.get('page');
    }

    if (
      changedProperties.has('totalItems') ||
      changedProperties.has('itemsShown') ||
      changedProperties.has('size')
    ) {
      let numberOfPages;
      switch (this.size) {
        case PAGINATION_NAV_SIZE.MEDIUM:
          numberOfPages = this.itemsShown === 4 ? this.itemsShown : 5;
          break;
        case PAGINATION_NAV_SIZE.SMALL:
          numberOfPages = Math.min(Math.max(this.itemsShown, 4), 7);
          break;
        default:
          numberOfPages = 4;
          break;
      }

      this.itemsDisplayedOnPage = Math.max(
        this.itemsShown >= 4 ? this.itemsShown : numberOfPages,
        4
      );
      this.cuts = this._calculateCuts(
        this.page,
        this.totalItems,
        this.itemsDisplayedOnPage
      );
    }

    if (changedProperties.has('page') && this._pageWouldBeHidden(this.page)) {
      const delta = this.page - (this.prevPage || 0);

      if (delta > 0) {
        const splitPoint = this.itemsDisplayedOnPage - 3;
        this.cuts = this._calculateCuts(
          this.page,
          this.totalItems,
          this.itemsDisplayedOnPage,
          splitPoint
        );
      } else {
        const splitPoint = this.itemsDisplayedOnPage > 4 ? 2 : 1;
        this.cuts = this._calculateCuts(
          this.page,
          this.totalItems,
          this.itemsDisplayedOnPage,
          splitPoint
        );
      }
    }
  }

  /**
   * Render a pagination item
   */
  private _renderPaginationItem(itemPage: number, isActive = false) {
    const itemLabel = this._translate('carbon.pagination-nav.item');

    return html`
      <li class="${prefix}--pagination-nav__list-item">
        <button
          type="button"
          class="${prefix}--pagination-nav__page ${isActive
            ? `${prefix}--pagination-nav__page--active`
            : ''}"
          @click="${() => this._jumpToItem(itemPage)}"
          data-page="${itemPage + 1}"
          ?aria-current="${isActive ? 'page' : false}">
          <span class="${prefix}--pagination-nav__accessibility-label">
            ${isActive
              ? `${this._translate('carbon.pagination-nav.active')}, ${itemLabel}`
              : itemLabel}
          </span>
          ${itemPage + 1}
        </button>
      </li>
    `;
  }

  /**
   * Render a pagination overflow
   */
  private _renderPaginationOverflow(fromIndex: number, count: number) {
    if (count <= 0) {
      return html``;
    }

    if (this.disableOverflow === true && count > 1) {
      return html`
        <li class="${prefix}--pagination-nav__list-item">
          <div class="${prefix}--pagination-nav__select">
            <select
              class="${prefix}--pagination-nav__page ${prefix}--pagination-nav__page--select"
              aria-label="Select ${this._translate(
                'carbon.pagination-nav.item'
              )} number"
              disabled></select>
            <div class="${prefix}--pagination-nav__select-icon-wrapper">
              ${iconLoader(OverflowMenuHorizontal16)}
            </div>
          </div>
        </li>
      `;
    }

    if (count > 1) {
      return html`
        <li class="${prefix}--pagination-nav__list-item">
          <div class="${prefix}--pagination-nav__select">
            <select
              class="${prefix}--pagination-nav__page ${prefix}--pagination-nav__page--select"
              aria-label="Select ${this._translate(
                'carbon.pagination-nav.item'
              )} number"
              @change="${(e: Event) => {
                const index = Number((e.target as HTMLSelectElement).value);
                this._jumpToItem(index);
              }}">
              <option value="" hidden></option>
              ${Array.from({ length: count }).map(
                (_, i) => html`
                  <option
                    value="${fromIndex + i}"
                    data-page="${fromIndex + i + 1}"
                    key="overflow-${fromIndex + i}">
                    ${fromIndex + i + 1}
                  </option>
                `
              )}
            </select>
            <div class="${prefix}--pagination-nav__select-icon-wrapper">
              ${iconLoader(OverflowMenuHorizontal16)}
            </div>
          </div>
        </li>
      `;
    }

    if (count === 1) {
      return this._renderPaginationItem(fromIndex);
    }

    return html``;
  }

  /**
   * Render a direction button (next/previous)
   */
  private _renderDirectionButton(
    direction: 'forward' | 'backward',
    disabled: boolean,
    onClick: () => void
  ) {
    const label =
      direction === 'forward'
        ? this._translate('carbon.pagination-nav.next')
        : this._translate('carbon.pagination-nav.previous');

    const align =
      this.tooltipAlignment === 'center'
        ? this.tooltipPosition
        : `${this.tooltipPosition}-${this.tooltipAlignment}`;

    return html`
      <li class="${prefix}--pagination-nav__list-item">
        <cds-icon-button
          align="${align}"
          ?disabled="${disabled}"
          kind="ghost"
          label="${label}"
          @click="${onClick}">
          ${direction === 'forward'
            ? iconLoader(CaretRight16)
            : iconLoader(CaretLeft16)}
        </cds-icon-button>
      </li>
    `;
  }

  render() {
    const backwardButtonDisabled = !this.loop && this.page === 0;
    const forwardButtonDisabled =
      !this.loop && this.page === this.totalItems - 1;
    const startOffset = this.itemsDisplayedOnPage <= 4 && this.page > 1 ? 0 : 1;

    const classNames = {
      [`${prefix}--pagination-nav`]: true,
      [`${prefix}--layout--size-${this.size}`]: !!this.size,
    };

    const finalClassNames = Object.entries(classNames)
      .filter(([, value]) => value)
      .map(([key]) => key)
      .join(' ');

    return html`
      <nav class="${finalClassNames}" aria-label="pagination">
        <ul class="${prefix}--pagination-nav__list">
          ${this._renderDirectionButton(
            'backward',
            backwardButtonDisabled,
            this._jumpToPrevious.bind(this)
          )}
          ${
            // render first item if at least 5 items can be displayed or
            // 4 items can be displayed and the current page is either 0 or 1
            (this.itemsDisplayedOnPage >= 5 ||
              (this.itemsDisplayedOnPage <= 4 && this.page <= 1)) &&
            this._renderPaginationItem(0, this.page === 0)
          }
          ${
            /* render first overflow */
            this._renderPaginationOverflow(startOffset, this.cuts.front)
          }
          ${
            // render items between overflows
            Array.from({ length: this.totalItems })
              .map((_, i) => i)
              .slice(startOffset + this.cuts.front, (1 + this.cuts.back) * -1)
              .map((item) =>
                this._renderPaginationItem(item, this.page === item)
              )
          }
          ${
            /* render second overflow */
            this._renderPaginationOverflow(
              this.totalItems - this.cuts.back - 1,
              this.cuts.back
            )
          }
          ${
            // render last item unless there is only one in total
            this.totalItems > 1 &&
            this._renderPaginationItem(
              this.totalItems - 1,
              this.page === this.totalItems - 1
            )
          }
          ${this._renderDirectionButton(
            'forward',
            forwardButtonDisabled,
            this._jumpToNext.bind(this)
          )}
        </ul>
        <div
          aria-live="polite"
          aria-atomic="true"
          class="${prefix}--pagination-nav__accessibility-label">
          ${`${this._translate('carbon.pagination-nav.item')} ${
            this.page + 1
          } ${this._translate('carbon.pagination-nav.of')} ${this.totalItems}`}
        </div>
      </nav>
    `;
  }

  /**
   * The name of the custom event fired when the current page changes.
   */
  static get eventChange() {
    return `${prefix}-pagination-nav-changed`;
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static styles = styles;
}

export default CDSPaginationNav;
