// packages/web-components/src/components/fluid-time-picker/fluid-time-picker-skeleton.ts
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, LitElement } from 'lit';
import { classMap } from 'lit/directives/class-map.js';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import styles from './fluid-time-picker.scss?lit';
import '../fluid-text-input/fluid-text-input-skeleton';
import '../fluid-select/fluid-select-skeleton';

/**
 * Fluid time picker skeleton.
 *
 * @element cds-fluid-time-picker-skeleton
 */
class CDSFluidTimePickerSkeleton extends LitElement {
  static is = `${prefix}-fluid-time-picker-skeleton`;

  /**
   * Specify if there are only two TimePicker elements.
   */
  @property({ type: Boolean, attribute: 'is-only-two', reflect: true })
  isOnlyTwo = false;

  render() {
    const wrapperClasses = classMap({
      [`${prefix}--time-picker--fluid--skeleton`]: true,
      [`${prefix}--time-picker--equal-width`]: this.isOnlyTwo,
    });

    return html`
      <div class="${wrapperClasses}">
        <cds-fluid-text-input-skeleton></cds-fluid-text-input-skeleton>
        <cds-fluid-select-skeleton></cds-fluid-select-skeleton>
        ${this.isOnlyTwo
          ? null
          : html`<cds-fluid-select-skeleton></cds-fluid-select-skeleton>`}
      </div>
    `;
  }

  static styles = styles;
}

export default CDSFluidTimePickerSkeleton;

// packages/react/src/components/FluidTimePicker/FluidTimePicker.Skeleton.tsx
/**
 * Copyright IBM Corp. 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';
import { FluidTextInputSkeleton } from '../FluidTextInput';
import { FluidSelectSkeleton } from '../FluidSelect';

export interface FluidTimePickerSkeletonProps {
  /**
   * Specify an optional className to add.
   */
  className?: string;
  /**
   * Specify if there are only two TimePicker elements
   */
  isOnlyTwo?: boolean;
}

const FluidTimePickerSkeleton = ({ className, isOnlyTwo, ...rest }) => {
  const prefix = usePrefix();
  const wrapperClasses = cx(
    className,
    `${prefix}--time-picker--fluid--skeleton`,
    {
      [`${prefix}--time-picker--equal-width`]: isOnlyTwo,
    }
  );

  return (
    <div className={wrapperClasses} {...rest}>
      <FluidTextInputSkeleton />
      <FluidSelectSkeleton />
      {!isOnlyTwo ? <FluidSelectSkeleton /> : null}
    </div>
  );
};

FluidTimePickerSkeleton.propTypes = {
  /**
   * Specify an optional className to add.
   */
  className: PropTypes.string,

  /**
   * Specify if there are only two TimePicker elements
   */
  isOnlyTwo: PropTypes.bool,
};

export default FluidTimePickerSkeleton;
