// packages/web-components/src/components/add-select/add-select-row.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { property, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import '../checkbox/index';
import '../radio-button/index';
import '../skeleton-text/index';
import '../skeleton-icon/index';
import '../icon-button/index';
import { iconLoader } from '../../globals/internal/icon-loader';
import ChevronRight16 from '@carbon/icons/es/chevron--right/16';
import View16 from '@carbon/icons/es/view/16';

import { prefix } from '../../globals/settings';
import styles from './add-select-row.scss?lit';

const blockClass = `${prefix}--add-select__next-row`;

/**
 * Add Select Row component - represents a single selectable row
 * @element cds-add-select-row
 * @slot default - Custom content to render after the title/subtitle section.
 * @slot icon - Optional icon slot
 * @slot meta - Optional metadata slot
 * @fires cds-add-select-row-select - Fired when row is selected/deselected
 * @fires cds-add-select-row-navigate - Fired when navigating to children
 * @fires cds-add-select-row-item-panel-click - Fired when the item panel icon button is clicked
 */
@customElement(`${prefix}-add-select-row`)
class CDSAddSelectRow extends LitElement {
  /**
   * Whether this row renders a checkbox (multi) or radio button (single).
   * Set by the parent cds-add-select-column via the _column-multi attribute.
   * Falls back to reading the nearest cds-add-select wrapper when not set.
   */
  @property({ type: Boolean, attribute: '_column-multi', reflect: true })
  private _columnMulti = false;

  private get _multi(): boolean {
    if (this.hasAttribute('_column-multi')) {
      return this._columnMulti;
    }
    const parent = this.closest(`${prefix}-add-select`) as HTMLElement & {
      multi?: boolean;
    };
    return parent?.multi ?? false;
  }

  /**
   * Unique identifier for the item
   */
  @property({ type: String, attribute: 'item-id' })
  itemId = '';

  /**
   * Item title
   */
  @property({ type: String })
  title = '';

  /**
   * Item subtitle
   */
  @property({ type: String })
  subtitle = '';

  /**
   * Item value
   */
  @property({ type: String })
  value = '';

  /**
   * Whether the item is selected
   */
  @property({ type: Boolean, reflect: true })
  selected = false;

  /**
   * Whether the checkbox is in an indeterminate state (multi hierarchical)
   */
  @property({ type: Boolean, reflect: true })
  indeterminate = false;

  /**
   * Whether the item is disabled
   */
  @property({ type: Boolean })
  disabled = false;

  /**
   * Whether to render the row as a skeleton (loading) state
   */
  @property({ type: Boolean, reflect: true })
  skeleton = false;

  /** Whether the icon slot has assigned content */
  @state()
  private _hasIconSlot = false;

  private _handleIconSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this._hasIconSlot = slot.assignedElements({ flatten: true }).length > 0;
  }

  /** Whether the rowContent slot has assigned content */
  @state()
  private _hasRowContentSlot = false;

  private _handleRowContentSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this._hasRowContentSlot =
      slot.assignedElements({ flatten: true }).length > 0;
  }

  /**
   * Whether to show the item details icon button
   */
  @property({ type: Boolean, attribute: 'has-item-panel' })
  hasItemPanel = false;

  /**
   * Whether the item panel is currently open for this item
   */
  @property({ type: Boolean, attribute: 'item-panel-open', reflect: true })
  itemPanelOpen = false;

  /**
   * Accessible label for the item panel icon button
   */
  @property({ type: String, attribute: 'item-panel-icon-description' })
  itemPanelIconDescription = 'View details';

  /**
   * Whether the item has children (for navigation)
   */
  @property({ type: Boolean, attribute: 'has-children' })
  hasChildren = false;

  /**
   * Parent ID for hierarchical navigation
   */
  @property({ type: String, attribute: 'parent-id' })
  parentId = '';

  /**
   * Handle item panel icon button click
   */
  private _handleItemPanelClick(event: Event) {
    event.stopPropagation();
    const init = {
      bubbles: true,
      cancelable: true,
      composed: true,
      detail: { itemId: this.itemId },
    };
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectRow).eventItemPanelClick,
        init
      )
    );
  }

  /**
   * Handle navigation to children
   */
  private _handleNavigate(event: Event) {
    event.stopPropagation();

    if (!this.hasChildren) {
      return;
    }

    const init = {
      bubbles: true,
      cancelable: true,
      composed: true,
      detail: {
        itemId: this.itemId,
        title: this.title,
        parentId: this.parentId,
      },
    };
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectRow).eventNavigate,
        init
      )
    );
  }

  /**
   * Handle selection change from checkbox/radio button
   */
  private _handleSelect(event: Event) {
    if (this.disabled) {
      event.preventDefault();
      return;
    }

    const target = event.target as HTMLElement & { checked?: boolean };
    this.selected = target.checked || false;

    this._emitSelectionEvent();
  }

  /**
   * Emit selection event
   */
  _emitSelectionEvent() {
    const init = {
      bubbles: true,
      cancelable: true,
      composed: true,
      detail: {
        itemId: this.itemId,
        selected: this.selected,
        value: this.value,
      },
    };
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectRow).eventSelect,
        init
      )
    );
  }

  render() {
    const {
      itemId,
      title,
      subtitle,
      selected,
      indeterminate,
      disabled,
      hasChildren,
      hasItemPanel,
      itemPanelOpen,
      itemPanelIconDescription,
      skeleton,
      _handleSelect: handleSelect,
    } = this;

    const rowClasses = classMap({
      [`${blockClass}`]: true,
      [`${blockClass}--selected`]: selected,
      [`${blockClass}--disabled`]: disabled,
      [`${blockClass}--skeleton`]: skeleton,
    });

    // Skeleton state — non-interactive placeholder
    if (skeleton) {
      return html`
        <div class=${rowClasses} aria-hidden="true">
          <div class="${blockClass}__cell">
            <div class="${blockClass}__cell-wrapper">
              <div class="${blockClass}__skeleton-control"></div>
              <div class="${blockClass}__content">
                <!-- Hidden slot kept so slotchange fires and _hasIconSlot is accurate -->
                <slot
                  name="icon"
                  style="display:none"
                  @slotchange=${this._handleIconSlotChange}></slot>
                ${this._hasIconSlot
                  ? html`
                      <div class="${blockClass}__icon">
                        <cds-skeleton-icon></cds-skeleton-icon>
                      </div>
                    `
                  : nothing}
                <div class="${blockClass}__text">
                  <cds-skeleton-text
                    class="${blockClass}__skeleton-title"></cds-skeleton-text>
                </div>
              </div>
            </div>
          </div>
        </div>
      `;
    }

    return html`
      <div
        class=${rowClasses}
        role="row"
        aria-selected=${selected}
        tabindex="-1"
        ?data-has-children=${hasChildren}>
        <div class="${blockClass}__cell" role="gridcell">
          <div class="${blockClass}__cell-wrapper">
            ${this._multi
              ? html`
                  <cds-checkbox
                    class="${blockClass}__checkbox"
                    ?checked=${selected}
                    ?indeterminate=${indeterminate}
                    ?disabled=${disabled}
                    @cds-checkbox-changed=${handleSelect}
                    label-text=${title}
                    ?hide-label=${true}
                    tabindex="-1"></cds-checkbox>
                `
              : html`
                  <cds-radio-button
                    class="${blockClass}__radio"
                    ?checked=${selected}
                    ?disabled=${disabled}
                    @cds-radio-button-changed=${handleSelect}
                    label-text=" "
                    aria-label=${title}
                    value=${itemId}
                    tabindex="-1"></cds-radio-button>
                `}

            <div class="${blockClass}__content">
              <slot
                name="icon"
                class="${blockClass}__icon"
                @slotchange=${this._handleIconSlotChange}></slot>
              ${this._hasRowContentSlot
                ? nothing
                : html`
                    <div class="${blockClass}__text">
                      <div class="${blockClass}__title">${title}</div>
                      ${subtitle
                        ? html`<div class="${blockClass}__subtitle">
                            ${subtitle}
                          </div>`
                        : nothing}
                    </div>
                    <slot></slot>
                  `}
              <slot
                name="row-content"
                @slotchange=${this._handleRowContentSlotChange}></slot>
              <slot name="meta"></slot>
            </div>

            ${hasItemPanel
              ? html`
                  <cds-icon-button
                    class="${blockClass}__view-item-panel"
                    kind="ghost"
                    size="sm"
                    autoalign
                    ?aria-pressed=${itemPanelOpen}
                    @click=${this._handleItemPanelClick}>
                    ${iconLoader(View16, { slot: 'icon' })}
                    <span slot="tooltip-content"
                      >${itemPanelIconDescription}</span
                    >
                  </cds-icon-button>
                `
              : nothing}
            ${hasChildren
              ? html`
                  <div
                    class="${blockClass}__nav-indicator"
                    @click=${this._handleNavigate}
                    role="button"
                    tabindex="-1"
                    aria-label="Navigate into ${title}">
                    <slot name="nav-icon">
                      ${iconLoader(ChevronRight16, {
                        slot: 'icon',
                      })}
                    </slot>
                  </div>
                `
              : nothing}
          </div>
        </div>
      </div>
    `;
  }

  /**
   * The name of the custom event fired when row is selected/deselected
   */
  static get eventSelect() {
    return `${prefix}-add-select-row-select`;
  }

  /**
   * The name of the custom event fired when navigating to children
   */
  static get eventNavigate() {
    return `${prefix}-add-select-row-navigate`;
  }

  /**
   * The name of the custom event fired when item panel icon button is clicked
   */
  static get eventItemPanelClick() {
    return `${prefix}-add-select-row-item-panel-click`;
  }

  static styles = styles;
}

export default CDSAddSelectRow;

// packages/react/src/components/AddSelect/AddSelectRow.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, {
  forwardRef,
  ForwardedRef,
  ReactNode,
  useContext,
  MouseEvent,
} from 'react';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';
import Checkbox, { type CheckboxProps } from '../Checkbox';
import { RadioButton, type RadioButtonProps } from '../RadioButton';
import { IconButton, type IconButtonProps } from '../IconButton';
import { SkeletonText } from '../SkeletonText';
import { SkeletonIcon } from '../SkeletonIcon';
import { ChevronRight, View } from '@carbon/icons-react';
import { AddSelectContext } from './context';

/**
 * ----------------
 * AddSelectRow
 * ----------------
 */

export interface AddSelectRowProps {
  /**
   * Unique identifier for the item
   */
  itemId: string;
  /**
   * Item title
   */
  title: string;
  /**
   * Item subtitle
   */
  subtitle?: string;
  /**
   * Item value
   */
  value: string;
  /**
   * Whether the item is selected
   */
  selected?: boolean;
  /**
   * Whether the item is in an indeterminate state (for hierarchical selections)
   */
  indeterminate?: boolean;
  /**
   * Whether the item is disabled
   */
  disabled?: boolean;
  /**
   * Whether the item has children (for navigation)
   */
  hasChildren?: boolean;
  /**
   * Parent ID for hierarchical navigation
   */
  parentId?: string;
  /**
   * Optional icon slot
   */
  icon?: ReactNode;
  /**
   * Custom content to render after the title/subtitle section.
   * Useful for adding badges, tags, or other metadata to the row.
   */
  children?: ReactNode;
  /**
   * Custom row content (slot) - replaces the entire row content section
   * (title, subtitle, and children).
   * When provided, only the selection control and navigation indicators remain.
   */
  rowContent?: ReactNode;
  /**
   * Whether to show the item panel view icon for this item
   */
  hasItemPanel?: boolean;
  /**
   * Callback when item panel view icon is clicked
   */
  onItemPanelClick?: (itemId: string) => void;
  /**
   * Description for the item panel icon button
   */
  itemPanelIconDescription?: string;
  /**
   * Whether the item panel is currently open for this item
   */
  itemPanelOpen?: boolean;
  /**
   * Whether to render the row as a skeleton (loading state).
   * When true, real content is replaced with Carbon skeleton placeholders.
   * The row is non-interactive and hidden from assistive technology.
   */
  skeleton?: boolean;
  /**
   * Optional class name
   */
  className?: string;
  /**
   * Additional props to pass to the Checkbox component (when multi=true)
   */
  checkboxProps?: Omit<
    CheckboxProps,
    | 'id'
    | 'className'
    | 'checked'
    | 'disabled'
    | 'labelText'
    | 'hideLabel'
    | 'onChange'
  >;
  /**
   * Additional props to pass to the RadioButton component (when multi=false)
   */
  radioButtonProps?: Omit<
    RadioButtonProps,
    | 'id'
    | 'className'
    | 'checked'
    | 'disabled'
    | 'labelText'
    | 'hideLabel'
    | 'value'
    | 'onChange'
  >;
  /**
   * Accessible label for the navigation indicator button.
   * Defaults to `Navigate into <title>` when not provided.
   * Override this prop to localize the label.
   */
  navIndicatorLabel?: string;
  /**
   * Additional props to pass to the IconButton component (info panel)
   */
  itemPanelIconButtonProps?: Omit<
    IconButtonProps,
    'label' | 'onClick' | 'kind' | 'size' | 'className' | 'children'
  >;
}

const AddSelectRow = forwardRef<HTMLDivElement, AddSelectRowProps>(
  (
    {
      itemId,
      title,
      subtitle,
      value,
      selected = false,
      indeterminate = false,
      disabled = false,
      hasChildren = false,
      parentId = '',
      icon,
      children,
      rowContent,
      hasItemPanel = false,
      onItemPanelClick,
      itemPanelIconDescription = 'View details',
      itemPanelOpen = false,
      skeleton = false,
      className,
      checkboxProps,
      radioButtonProps,
      navIndicatorLabel,
      itemPanelIconButtonProps,
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const prefix = usePrefix();
    const blockClass = `${prefix}--add-select`;
    const { multi, onItemSelect, onNavigate, selectedItems } =
      useContext(AddSelectContext);

    // Use context's selected state if available
    const isSelected = selectedItems?.has(itemId) ?? selected;

    if (process.env.NODE_ENV !== 'production') {
      if (selectedItems !== undefined && selected !== false) {
        // eslint-disable-next-line no-console
        console.warn(
          `[AddSelectRow] Both the \`selected\` prop and \`selectedItems\` context are set ` +
            `on row "${itemId}". The context value takes precedence. ` +
            `Remove the \`selected\` prop when using controlled mode via AddSelect.`
        );
      }
    }

    const handleSelect = () => {
      if (disabled) {
        return;
      }
      const newSelected = !isSelected;
      onItemSelect?.(itemId, newSelected, value);
    };

    const handleNavigate = (event: MouseEvent<HTMLDivElement>) => {
      event.stopPropagation();
      if (!hasChildren) {
        return;
      }
      onNavigate?.(itemId, title, parentId);
    };

    const handleItemPanelClick = (event: MouseEvent<HTMLButtonElement>) => {
      event.stopPropagation();
      onItemPanelClick?.(itemId);
    };

    const rowClasses = cx(`${blockClass}-row`, className, {
      [`${blockClass}-row--selected`]: isSelected,
      [`${blockClass}-row--disabled`]: disabled,
      [`${blockClass}-row-item-panel--selected`]: itemPanelOpen,
      [`${blockClass}-row--skeleton`]: skeleton,
    });

    // Skeleton (loading) state
    if (skeleton) {
      return (
        <div className={rowClasses} aria-hidden="true" ref={ref}>
          <div className={`${blockClass}-row__cell`}>
            <div className={`${blockClass}-row__cell-wrapper`}>
              {/* Skeleton checkbox/radio placeholder */}
              <div className={`${blockClass}-row__skeleton-control`} />

              <div className={`${blockClass}-row__content`}>
                {/* Skeleton icon circle — only if row has an icon */}
                {icon && (
                  <div className={`${blockClass}-row__icon`}>
                    <SkeletonIcon />
                  </div>
                )}

                {/* Skeleton text lines */}
                <div className={`${blockClass}-row__text`}>
                  <SkeletonText
                    className={`${blockClass}-row__skeleton-title`}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      );
    }

    return (
      <div
        className={rowClasses}
        role="row"
        aria-selected={isSelected}
        tabIndex={-1}
        data-has-children={hasChildren || undefined}
        ref={ref}
        {...rest}>
        <div className={`${blockClass}-row__cell`} role="gridcell">
          <div className={`${blockClass}-row__cell-wrapper`}>
            {multi ? (
              <Checkbox
                id={`checkbox-${itemId}`}
                className={`${blockClass}-row__checkbox`}
                checked={isSelected}
                indeterminate={indeterminate}
                disabled={disabled}
                labelText={title}
                hideLabel
                onChange={handleSelect}
                {...checkboxProps}
              />
            ) : (
              <RadioButton
                id={`radio-${itemId}`}
                className={`${blockClass}-row__radio`}
                checked={isSelected}
                disabled={disabled}
                labelText={title}
                hideLabel
                value={itemId}
                onChange={handleSelect}
                {...radioButtonProps}
              />
            )}

            <div className={`${blockClass}-row__content`}>
              {icon && <div className={`${blockClass}-row__icon`}>{icon}</div>}
              {rowContent || (
                <>
                  <div className={`${blockClass}-row__text`}>
                    <div className={`${blockClass}-row__title`}>{title}</div>
                    {subtitle && (
                      <div className={`${blockClass}-row__subtitle`}>
                        {subtitle}
                      </div>
                    )}
                  </div>
                  {children}
                </>
              )}
            </div>

            {hasItemPanel && (
              <IconButton
                label={itemPanelIconDescription}
                onClick={handleItemPanelClick}
                kind="ghost"
                size="sm"
                autoAlign
                className={`${blockClass}-row__view-item-panel`}
                {...itemPanelIconButtonProps}>
                <View size={16} />
              </IconButton>
            )}

            {hasChildren && (
              <div
                className={`${blockClass}-row__nav-indicator`}
                onClick={handleNavigate}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    e.stopPropagation();
                    if (hasChildren) {
                      onNavigate?.(itemId, title, parentId);
                    }
                  }
                }}
                role="button"
                tabIndex={-1}
                aria-label={navIndicatorLabel ?? `Navigate into ${title}`}>
                <ChevronRight size={16} />
              </div>
            )}
          </div>
        </div>
      </div>
    );
  }
);

AddSelectRow.displayName = 'AddSelectRow';

export default AddSelectRow;
