// packages/web-components/src/components/add-select/add-select-body.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { property, state } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import '../button/index';
import '../search/index';
import '../tag/index';
import '../breadcrumb/index';
import '../link/index';
import { prefix } from '../../globals/settings';
import styles from './add-select-body.scss?lit';

const blockClass = `${prefix}--add-select__next`;

/**
 * Add Select Body component - contains the main content area
 * @element cds-add-select-body
 * @slot default - The main content area containing cds-add-select-column or rows
 * @slot header - Replaces the entire header section
 * @slot actions - Custom actions (filter/sort) rendered next to the search input
 * @slot sub-header-actions - Custom content rendered after breadcrumbs and item count
 * @fires cds-add-select-body-search - Fired when search term changes; detail: { searchTerm }
 * @fires cds-add-select-body-breadcrumb-click - Fired when a breadcrumb link is clicked; detail: { index }
 */
@customElement(`${prefix}-add-select-body`)
class CDSAddSelectBody extends LitElement {
  /**
   * Label for items section
   */
  @property({ type: String, attribute: 'items-label' })
  itemsLabel = '';

  /**
   * Global search label
   */
  @property({ type: String, attribute: 'global-search-label' })
  globalSearchLabel = '';

  /**
   * Global search placeholder
   */
  @property({ type: String, attribute: 'global-search-placeholder' })
  globalSearchPlaceholder = 'Search';

  /**
   * Search results title
   */
  @property({ type: String, attribute: 'search-results-title' })
  searchResultsTitle = 'Search results';

  /**
   * Current search term
   */
  @state()
  private _searchTerm = '';

  /**
   * Item count for display. When undefined, no count badge is rendered.
   */
  @property({ type: Number, attribute: 'item-count' })
  itemCount: number | undefined = undefined;

  /**
   * Whether to hide the search input
   */
  @property({ type: Boolean, attribute: 'hide-search', reflect: true })
  hideSearch = false;

  /**
   * Layout direction for the list body: 'vertical' (default) or 'horizontal' (for hierarchy)
   */
  @property({ type: String, reflect: true })
  layout: 'vertical' | 'horizontal' = 'vertical';

  /**
   * Navigation path for breadcrumbs
   */
  @property({ type: Array })
  path: Array<{ id: string; title: string }> = [];

  /**
   * Handle search input
   */
  private _handleSearch(event: CustomEvent) {
    this._searchTerm = event.detail.value || '';
    const init = {
      bubbles: true,
      cancelable: true,
      composed: true,
      detail: { searchTerm: this._searchTerm },
    };
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectBody).eventSearch,
        init
      )
    );
  }

  /** Tracks whether the header slot has been filled by the consumer */
  @state()
  private _hasHeaderSlot = false;

  private _handleHeaderSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this._hasHeaderSlot = slot.assignedElements({ flatten: true }).length > 0;
  }

  /** Index of the currently focused row for grid keyboard navigation */
  private _focusedRowIndex = 0;

  /** Reference to the shadow div[role="grid"] — set after first render */
  private _gridEl: HTMLElement | null = null;

  /**
   * Returns all cds-add-select-row host elements in document order.
   * These are in the light DOM of this element, so querySelectorAll finds them.
   */
  private _getRowHosts(): HTMLElement[] {
    return Array.from(
      this.querySelectorAll<HTMLElement>(`${prefix}-add-select-row`)
    );
  }

  /**
   * Keyboard navigation for role="grid" (WAI-ARIA grid pattern).
   * Mirrors the React AddSelectBody handleKeyDown implementation exactly:
   * keydown is on the grid div, focused row has tabindex="0", others "-1".
   */
  private _handleGridKeydown = (event: KeyboardEvent) => {
    const rows = this._getRowHosts();
    if (rows.length === 0) {
      return;
    }

    let handled = false;
    const currentRow = rows[this._focusedRowIndex];

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        this._updateRowFocus(this._focusedRowIndex + 1);
        handled = true;
        break;

      case 'ArrowUp':
        event.preventDefault();
        this._updateRowFocus(this._focusedRowIndex - 1);
        handled = true;
        break;

      case 'ArrowRight':
        // Navigate into children if the focused row has them
        if (currentRow && currentRow.hasAttribute('has-children')) {
          event.preventDefault();
          // Trigger navigate by clicking the nav-indicator inside the shadow root
          const navIndicator =
            currentRow.shadowRoot?.querySelector<HTMLElement>(
              '[class*="nav-indicator"]'
            );
          navIndicator?.click();
          handled = true;
        }
        break;

      case 'Enter':
      case ' ':
        event.preventDefault();
        if (currentRow) {
          // The checkbox/radio is inside the row's shadow DOM
          const input = currentRow.shadowRoot?.querySelector<HTMLInputElement>(
            'input[type="checkbox"], input[type="radio"]'
          );
          input?.click();
        }
        handled = true;
        break;

      case 'Home':
        if (event.ctrlKey) {
          event.preventDefault();
          this._updateRowFocus(0);
          handled = true;
        }
        break;

      case 'End':
        if (event.ctrlKey) {
          event.preventDefault();
          this._updateRowFocus(rows.length - 1);
          handled = true;
        }
        break;
    }

    if (handled) {
      event.stopPropagation();
    }
  };

  /**
   * Mirrors React's updateItemFocus:
   * - Sets tabindex="0" on the target row host so it is the Tab stop inside
   *   the grid (Tab into grid → focused row, Tab out → next element after grid).
   * - Sets tabindex="-1" on all other row hosts.
   * - Calls .focus() on the target row host when shouldFocus is true.
   *
   * We set tabindex on the cds-add-select-row host elements (light DOM) rather
   * than their inner shadow divs because host elements are real browser Tab
   * stops; shadow-internal elements are not reachable by Tab from outside.
   */
  private _updateRowFocus(targetIndex: number, shouldFocus = true) {
    const rows = this._getRowHosts();
    if (rows.length === 0) {
      return;
    }
    this._focusedRowIndex = Math.max(0, Math.min(targetIndex, rows.length - 1));
    rows.forEach((row, idx) => {
      if (idx === this._focusedRowIndex) {
        row.setAttribute('tabindex', '0');
        if (shouldFocus) {
          row.focus();
        }
      } else {
        row.setAttribute('tabindex', '-1');
      }
    });
  }

  /**
   * After first render, wire the shadow div[role="grid"] as the Tab stop and
   * attach the keydown listener to it (mirrors React: tabIndex={0} + onKeyDown
   * on the grid div).
   */
  protected firstUpdated() {
    const gridEl = this.renderRoot.querySelector<HTMLElement>('[role="grid"]');
    if (gridEl) {
      this._gridEl = gridEl;
      gridEl.setAttribute('tabindex', '0');
      gridEl.addEventListener('keydown', this._handleGridKeydown);
    }
    // Initialise row tabindices without stealing focus (mirrors React useEffect)
    this._updateRowFocus(0, false);
  }

  /**
   * Re-initialise row tabindices when the default slot's content changes
   * (i.e. when rows are added/removed). Called from the default slot's
   * slotchange handler in the template.
   */
  private _handleContentSlotChange = () => {
    this._focusedRowIndex = 0;
    this._updateRowFocus(0, false);
  };

  disconnectedCallback() {
    super.disconnectedCallback();
    if (this._gridEl) {
      this._gridEl.removeEventListener('keydown', this._handleGridKeydown);
      this._gridEl = null;
    }
  }

  render() {
    const {
      itemsLabel,
      globalSearchLabel,
      globalSearchPlaceholder,
      searchResultsTitle,
      itemCount,
      hideSearch,
      layout,
      path,
      _searchTerm: searchTerm,
      _handleSearch: handleSearch,
    } = this;

    // Only render the __header div when it has visible content.
    const hasHeader =
      !hideSearch ||
      this._hasHeaderSlot ||
      itemCount !== undefined ||
      (path && path.length > 0);

    return html`
      <div class="${blockClass}__body">
        ${hasHeader
          ? html`
              <div class="${blockClass}__header">
                <!-- Named slot: consumer can replace the entire header -->
                <slot
                  name="header"
                  @slotchange=${this._handleHeaderSlotChange}></slot>

                ${!this._hasHeaderSlot
                  ? html`
                      <!-- Search + optional actions -->
                      ${!hideSearch
                        ? html`
                            <div
                              class="${blockClass}__search ${blockClass}__search--with-actions">
                              <div class="${blockClass}__search-input">
                                <cds-search
                                  label-text=${globalSearchLabel}
                                  placeholder=${globalSearchPlaceholder}
                                  size="lg"
                                  @cds-search-input=${handleSearch}></cds-search>
                              </div>
                              <div class="${blockClass}__global-actions">
                                <slot name="actions"></slot>
                              </div>
                            </div>
                          `
                        : nothing}

                      <!-- Sub-header: breadcrumbs / label + item count + optional actions -->
                      <div class="${blockClass}__sub-header">
                        <div class="${blockClass}__tags">
                          ${searchTerm
                            ? html`
                                <p class="${blockClass}__tags-label">
                                  ${searchResultsTitle}
                                </p>
                              `
                            : path && path.length > 0
                              ? html`
                                  <cds-breadcrumb
                                    no-trailing-slash
                                    class="${blockClass}__breadcrumbs">
                                    ${path.map((entry, idx) => {
                                      const isCurrentPage =
                                        idx === path.length - 1;
                                      return html`
                                        <cds-breadcrumb-item
                                          ?is-current-page=${isCurrentPage}>
                                          ${isCurrentPage
                                            ? entry.title
                                            : html`
                                                <cds-link
                                                  href="#"
                                                  @click=${(e: Event) => {
                                                    e.preventDefault();
                                                    this.dispatchEvent(
                                                      new CustomEvent(
                                                        (
                                                          this
                                                            .constructor as typeof CDSAddSelectBody
                                                        ).eventBreadcrumbClick,
                                                        {
                                                          bubbles: true,
                                                          cancelable: true,
                                                          composed: true,
                                                          detail: {
                                                            index: idx,
                                                          },
                                                        }
                                                      )
                                                    );
                                                  }}>
                                                  ${entry.title}
                                                </cds-link>
                                              `}
                                        </cds-breadcrumb-item>
                                      `;
                                    })}
                                  </cds-breadcrumb>
                                `
                              : html`
                                  <p class="${blockClass}__tags-label">
                                    ${itemsLabel}
                                  </p>
                                `}
                          ${itemCount !== undefined
                            ? html`<cds-tag type="gray" size="sm"
                                >${itemCount}</cds-tag
                              >`
                            : nothing}
                        </div>
                        <slot name="sub-header-actions"></slot>
                      </div>
                    `
                  : nothing}
              </div>
            `
          : nothing}

        <!-- Body Content -->
        <div class="${blockClass}__content" role="grid">
          <div
            class="${blockClass}-list-body${layout === 'horizontal'
              ? ` ${blockClass}-list-body--horizontal`
              : ''}"
            role="rowgroup">
            <slot @slotchange=${this._handleContentSlotChange}></slot>
          </div>
        </div>
      </div>
    `;
  }

  /**
   * The name of the custom event fired when search term changes
   */
  static get eventSearch() {
    return `${prefix}-add-select-body-search`;
  }

  /**
   * The name of the custom event fired when breadcrumb is clicked
   */
  static get eventBreadcrumbClick() {
    return `${prefix}-add-select-body-breadcrumb-click`;
  }

  static styles = styles;
}

export default CDSAddSelectBody;

// packages/react/src/components/AddSelect/AddSelectBody.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, {
  forwardRef,
  ForwardedRef,
  ReactNode,
  useState,
  MouseEvent,
  useRef,
  useEffect,
  KeyboardEvent,
} from 'react';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';
import Search, { type SearchProps } from '../Search';
import { Tag } from '../Tag';
import type { TagProps } from '../Tag/Tag';
import { Breadcrumb, BreadcrumbItem } from '../Breadcrumb';
import type { BreadcrumbProps } from '../Breadcrumb/Breadcrumb';
import type { BreadcrumbItemProps } from '../Breadcrumb/BreadcrumbItem';
import Link from '../Link';
import type { LinkProps } from '../Link/Link';

/**
 * ----------------
 * AddSelectBody
 * ----------------
 */

export interface AddSelectBodyProps {
  /**
   * Optional children
   */
  children?: ReactNode;
  /**
   * Optional class name
   */
  className?: string;
  /**
   * Layout direction for columns: 'vertical' (default) or 'horizontal' (for hierarchy)
   */
  layout?: 'vertical' | 'horizontal';
  /**
   * Label for items section
   */
  itemsLabel?: string;
  /**
   * Global search label
   */
  globalSearchLabel?: string;
  /**
   * Global search placeholder
   */
  globalSearchPlaceholder?: string;
  /**
   * Search results title
   */
  searchResultsTitle?: string;
  /**
   * Item count for display
   */
  itemCount?: number;
  /**
   * Navigation path for breadcrumbs
   */
  path?: Array<{ id: string; title: string }>;
  /**
   * Called when the global search input value changes.
   * Intended to filter across ALL columns/rows in the Body.
   * Independent of any per-column search in AddSelectColumn.
   */
  onSearch?: (searchTerm: string) => void;
  /**
   * Callback when breadcrumb is clicked
   */
  onBreadcrumbClick?: (index: number) => void;
  /**
   * Custom header content (slot) - replaces entire header
   */
  headerContent?: ReactNode;
  /**
   * Actions slot - adds custom actions (filter/sort) next to default search
   */
  actionsSlot?: ReactNode;
  /**
   * Sub-header actions - custom content/actions rendered after breadcrumbs and item count
   */
  subHeaderActions?: ReactNode;
  /**
   * Whether to hide the search input
   */
  hideSearch?: boolean;
  /**
   * Additional props to pass to the Search component
   */
  searchProps?: Omit<
    SearchProps,
    'labelText' | 'placeholder' | 'size' | 'onChange' | 'value'
  >;
  /**
   * Additional props to pass to the Tag component (for item count)
   */
  tagProps?: Omit<TagProps<'div'>, 'type' | 'size' | 'children'>;
  /**
   * Additional props to pass to the Breadcrumb component
   */
  breadcrumbProps?: Omit<
    BreadcrumbProps,
    'noTrailingSlash' | 'className' | 'children'
  >;
  /**
   * Additional props to pass to BreadcrumbItem components
   */
  breadcrumbItemProps?: Omit<
    BreadcrumbItemProps,
    'key' | 'isCurrentPage' | 'children'
  >;
  /**
   * Additional props to pass to Link components in breadcrumbs
   */
  linkProps?: Omit<LinkProps<'a'>, 'href' | 'onClick' | 'children'>;
}

const AddSelectBody = forwardRef<HTMLDivElement, AddSelectBodyProps>(
  (
    {
      children,
      className,
      layout = 'vertical',
      itemsLabel = '',
      globalSearchLabel = 'Search',
      globalSearchPlaceholder = 'Search',
      searchResultsTitle = 'Search results',
      itemCount,
      path = [],
      onSearch,
      onBreadcrumbClick,
      headerContent,
      actionsSlot,
      subHeaderActions,
      hideSearch = false,
      searchProps,
      tagProps,
      breadcrumbProps,
      breadcrumbItemProps,
      linkProps,
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const prefix = usePrefix();
    const blockClass = `${prefix}--add-select`;

    const [globalSearchTerm, setGlobalSearchTerm] = useState('');
    const listRef = useRef<HTMLDivElement | null>(null);
    const focusedIndexRef = useRef(0);
    // Cache of querySelectorAll('[role="row"]') — invalidated when children change
    const rowsCacheRef = useRef<HTMLElement[] | null>(null);

    // Get all item elements — uses cache; refreshes after children change
    const getItems = (): HTMLElement[] => {
      if (!listRef.current) {
        return [];
      }
      if (rowsCacheRef.current === null) {
        rowsCacheRef.current = Array.from(
          listRef.current.querySelectorAll('[role="row"]')
        ) as HTMLElement[];
      }
      return rowsCacheRef.current;
    };

    // Update focus on items - only one item should have tabindex="0"
    const updateItemFocus = (focusIndex: number, shouldFocus = true) => {
      const items = getItems();
      if (items.length === 0) {
        return;
      }

      // Ensure focusIndex is within bounds
      focusedIndexRef.current = Math.max(
        0,
        Math.min(focusIndex, items.length - 1)
      );

      items.forEach((item, index) => {
        if (index === focusedIndexRef.current) {
          item.setAttribute('tabindex', '0');
          if (shouldFocus) {
            item.focus();
          }
        } else {
          item.setAttribute('tabindex', '-1');
        }
      });
    };

    // Handle keyboard navigation
    const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>) => {
      const items = getItems();
      if (items.length === 0) {
        return;
      }

      const currentItem = items[focusedIndexRef.current];
      let handled = false;

      switch (event.key) {
        case 'ArrowDown':
          event.preventDefault();
          updateItemFocus(focusedIndexRef.current + 1);
          handled = true;
          break;

        case 'ArrowUp':
          event.preventDefault();
          updateItemFocus(focusedIndexRef.current - 1);
          handled = true;
          break;

        case 'ArrowRight':
          // Check if current item has children
          if (currentItem && currentItem.hasAttribute('data-has-children')) {
            event.preventDefault();
            // Trigger navigation by clicking the nav indicator
            const navIndicator = currentItem.querySelector(
              `.${blockClass}-row__nav-indicator`
            ) as HTMLElement;
            navIndicator?.click();
            handled = true;
          }
          break;

        case 'Enter':
        case ' ':
          event.preventDefault();
          // Trigger the item's selection by clicking the checkbox/radio
          if (currentItem) {
            const input = currentItem.querySelector(
              'input[type="checkbox"], input[type="radio"]'
            ) as HTMLInputElement;
            input?.click();
          }
          handled = true;
          break;

        case 'Home':
          if (event.ctrlKey) {
            event.preventDefault();
            updateItemFocus(0);
            handled = true;
          }
          break;

        case 'End':
          if (event.ctrlKey) {
            event.preventDefault();
            updateItemFocus(items.length - 1);
            handled = true;
          }
          break;
      }

      if (handled) {
        event.stopPropagation();
      }
    };

    // Invalidate cache and re-initialize focus whenever children change
    useEffect(() => {
      rowsCacheRef.current = null;
      updateItemFocus(0, false);
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [children]);

    const handleSearch = (event: React.ChangeEvent<HTMLInputElement>) => {
      const value = event.target.value;
      setGlobalSearchTerm(value);
      onSearch?.(value);
    };

    const bodyClasses = cx(`${blockClass}__body`, className);

    return (
      <div className={bodyClasses} ref={ref} {...rest}>
        {/* Header Section */}
        <div className={`${blockClass}__header`}>
          {headerContent || (
            <>
              {/* Search with optional actions */}
              {(!hideSearch || actionsSlot) && (
                <div
                  className={cx(`${blockClass}__search`, {
                    [`${blockClass}__search--with-actions`]: actionsSlot,
                  })}>
                  {!hideSearch && (
                    <div
                      className={
                        actionsSlot ? `${blockClass}__search-input` : ''
                      }>
                      <Search
                        labelText={globalSearchLabel}
                        placeholder={globalSearchPlaceholder}
                        size="lg"
                        onChange={handleSearch}
                        value={globalSearchTerm}
                        {...searchProps}
                      />
                    </div>
                  )}
                  {actionsSlot && (
                    <div className={`${blockClass}__global-actions`}>
                      {actionsSlot}
                    </div>
                  )}
                </div>
              )}

              {/* Sub-header with breadcrumbs or item label */}
              <div className={`${blockClass}__sub-header`}>
                <div className={`${blockClass}__tags`}>
                  {globalSearchTerm ? (
                    <p className={`${blockClass}__tags-label`}>
                      {searchResultsTitle}
                    </p>
                  ) : path && path.length > 0 ? (
                    <Breadcrumb
                      noTrailingSlash
                      className={`${blockClass}__breadcrumbs`}
                      {...breadcrumbProps}>
                      {path.map((entry, idx) => {
                        const isCurrentPage = idx === path.length - 1;
                        return (
                          <BreadcrumbItem
                            key={entry.id}
                            isCurrentPage={isCurrentPage}
                            {...breadcrumbItemProps}>
                            {isCurrentPage ? (
                              entry.title
                            ) : (
                              <Link
                                href="#"
                                onClick={(e: MouseEvent<HTMLAnchorElement>) => {
                                  e.preventDefault();
                                  onBreadcrumbClick?.(idx);
                                }}
                                {...linkProps}>
                                {entry.title}
                              </Link>
                            )}
                          </BreadcrumbItem>
                        );
                      })}
                    </Breadcrumb>
                  ) : (
                    <p className={`${blockClass}__tags-label`}>{itemsLabel}</p>
                  )}
                  {itemCount !== undefined && (
                    <Tag type="gray" size="sm" {...tagProps}>
                      {itemCount}
                    </Tag>
                  )}
                </div>
                {subHeaderActions && (
                  <div className={`${blockClass}__sub-header-actions`}>
                    {subHeaderActions}
                  </div>
                )}
              </div>
            </>
          )}
        </div>

        {/* Body Content */}
        <div
          className={`${blockClass}__content`}
          ref={listRef}
          role="grid"
          tabIndex={0}
          onKeyDown={handleKeyDown}>
          <div
            className={cx(`${blockClass}-list-body`, {
              [`${blockClass}-list-body--horizontal`]: layout === 'horizontal',
            })}
            role="rowgroup">
            {children}
          </div>
        </div>
      </div>
    );
  }
);

AddSelectBody.displayName = 'AddSelectBody';

export default AddSelectBody;
