// packages/react/src/components/NumberInput/NumberInput-story.jsx
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { action } from '@storybook/addon-actions';

import {
  withKnobs,
  boolean,
  number,
  text,
  object,
  select,
} from '@storybook/addon-knobs';
import NumberInput from '../NumberInput';
import { NumberInput as OGNumberInput } from './NumberInput';
import NumberInputSkeleton from '../NumberInput/NumberInput.Skeleton';
import mdx from './NumberInput.mdx';

const sizes = {
  'Small  (sm)': 'sm',
  'Medium (md) - default': undefined,
  'Large  (lg)': 'lg',
};

const props = () => ({
  className: 'some-class',
  id: 'tj-input',
  label: text('Label (label)', 'NumberInput label'),
  hideLabel: boolean('No label (hideLabel)', false),
  hideSteppers: boolean('No steppers (hideSteppers)', false),
  min: number('Minimum value (min)', 0),
  max: number('Maximum value (max)', 100),
  value: number('Value (value)', 50),
  step: number('Step of up/down arrow (step)', 10),
  size: select('Field size (size)', sizes, undefined) || undefined,
  disabled: boolean('Disabled (disabled)', false),
  readOnly: boolean('Read only (readOnly)', false),
  invalid: boolean('Show form validation UI (invalid)', false),
  invalidText: text(
    'Form validation UI content (invalidText)',
    'Number is not valid'
  ),
  warn: boolean('Show warning state (warn)', false),
  warnText: text(
    'Warning state text (warnText)',
    'A high threshold may impact performance'
  ),
  helperText: text('Helper text (helperText)', 'Optional helper text.'),
  light: boolean('Light variant (light)', false),
  onChange: action('onChange'),
  onClick: action('onClick'),
  allowEmpty: boolean('Allow empty value (allowEmpty)', false),
  numberInputArrowTranslationIds: object(
    'Number input arrow icon translation IDs (for translateWithId callback)',
    {
      'increment.number': 'Increment number',
      'decrement.number': 'Decrement number',
    }
  ),
});

export default {
  title: 'Components/NumberInput',
  component: OGNumberInput,
  decorators: [withKnobs],

  parameters: {
    docs: {
      page: mdx,
    },

    subcomponents: {
      NumberInputSkeleton,
    },
  },
};

export const Default = () => {
  return (
    <NumberInput
      id="carbon-number"
      min={0}
      max={100}
      value={50}
      label="NumberInput label"
      helperText="Optional helper text."
      invalidText="Number is not valid"
    />
  );
};

Default.story = {
  name: 'Number Input',
};

export const Playground = () => {
  const { numberInputArrowTranslationIds, ...rest } = props();
  return (
    <NumberInput
      translateWithId={(id) => numberInputArrowTranslationIds[id]}
      {...rest}
    />
  );
};

export const Skeleton = () => <NumberInputSkeleton />;

// web-components/packages/carbon-web-components/src/components/number-input/number-input-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import * as knobs from '@storybook/addon-knobs';
import { ifDefined } from 'lit/directives/if-defined.js';
import { INPUT_SIZE } from '../text-input/text-input';
import './number-input';
import './number-input-skeleton';
import '../form/form-item';
import createProps from './stories/helpers';
import storyDocs from './number-input-story.mdx';
import { prefix } from '../../globals/settings';

export const Default = () => {
  return html`
    <cds-form-item>
      <cds-number-input
        value="50"
        min="0"
        max="100"
        size="${ifDefined(INPUT_SIZE.MEDIUM)}"
        step="1"
        label="number-input label"
        helper-text="Optional helper text">
      </cds-number-input>
    </cds-form-item>
  `;
};

Default.storyName = 'Default';

export const skeleton = () =>
  html` <cds-number-input-skeleton></cds-number-input-skeleton> `;

skeleton.parameters = {
  percy: {
    skip: true,
  },
};

export const Playground = (args) => {
  const {
    allowEmpty,
    decrementButtonDescription,
    incrementButtonDescription,
    disabled,
    helperText,
    hideLabel,
    hideSteppers,
    invalid,
    invalidText,
    label,
    readonly,
    warn,
    warnText,
    value,
    min,
    max,
    size,
    step,
    onInput,
  } = args?.[`${prefix}-number-input`] ?? {};
  return html`
    <cds-form-item>
      <cds-number-input
        ?allow-empty="${allowEmpty}"
        decrement-button-assistive-text="${ifDefined(
          decrementButtonDescription
        )}"
        increment-button-assistive-text="${ifDefined(
          incrementButtonDescription
        )}"
        helper-text="${ifDefined(helperText)}"
        ?hide-steppers="${hideSteppers}"
        ?hide-label="${hideLabel}"
        ?invalid="${invalid}"
        invalid-text="${ifDefined(invalidText)}"
        label="${ifDefined(label)}"
        ?readonly="${readonly}"
        value="${ifDefined(value)}"
        ?warn="${warn}"
        warn-text="${ifDefined(warnText)}"
        ?disabled="${disabled}"
        min="${ifDefined(min)}"
        max="${ifDefined(max)}"
        size="${ifDefined(size)}"
        step="${ifDefined(step)}"
        @input="${onInput}">
      </cds-number-input>
    </cds-form-item>
  `;
};

Playground.storyName = 'Playground';

Playground.parameters = {
  knobs: {
    [`${prefix}-number-input`]: () => createProps({ ...knobs }),
  },
};

export default {
  title: 'Components/Number Input',
  parameters: {
    ...storyDocs.parameters,
  },
};
