// packages/react/src/components/Grid/Grid.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import { useFeatureFlag } from '../FeatureFlags';
import { CSSGrid } from './CSSGrid';
import { FlexGrid } from './FlexGrid';
import { GridComponent, GridProps } from './GridTypes';

function Grid<T extends React.ElementType>(props: GridProps<T>) {
  const enableCSSGrid = useFeatureFlag('enable-css-grid');
  if (enableCSSGrid) {
    return <CSSGrid {...props} />;
  }
  return <FlexGrid {...props} />;
}

Grid.propTypes = {
  /**
   * Specify grid alignment. Default is center
   */
  align: PropTypes.oneOf(['start', 'center', 'end']),

  /**
   * Provide a custom element to render instead of the default <div>
   */
  as: PropTypes.oneOfType([PropTypes.string, PropTypes.elementType]),

  /**
   * Pass in content that will be rendered within the `Grid`
   */
  children: PropTypes.node,

  /**
   * Specify a custom className to be applied to the `Grid`
   */
  className: PropTypes.string,

  /**
   * Collapse the gutter to 1px. Useful for fluid layouts.
   * Rows have 1px of margin between them to match gutter.
   */
  condensed: PropTypes.bool,

  /**
   * Remove the default max width that the grid has set
   */
  fullWidth: PropTypes.bool,

  /**
   * Container hangs 16px into the gutter. Useful for
   * typographic alignment with and without containers.
   */
  narrow: PropTypes.bool,
};

const GridAsGridComponent = Grid as GridComponent;

export { GridAsGridComponent as Grid };

// packages/web-components/src/components/grid/grid.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2024, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { prefix } from '../../globals/settings';
import styles from './grid.scss?lit';
import { GRID_ALIGNMENT } from './defs';

export { GRID_ALIGNMENT } from './defs';

@customElement(`${prefix}-grid`)
class CDSGrid extends LitElement {
  /**
   * Specify grid alignment. Default is center
   */
  @property({ attribute: 'align' })
  align = GRID_ALIGNMENT.CENTER;

  /**
   * Collapse the gutter to 1px. Useful for fluid layouts.
   * Rows have 1px of margin between them to match gutter.
   */
  @property({ attribute: 'condensed' })
  condensed = false;

  /**
   * Container hangs 16px into the gutter. Useful for
   * typographic alignment with and without containers.
   */
  @property({ attribute: 'narrow' })
  narrow = false;

  /**
   * Grid is nested within another grid
   */
  @property({ attribute: 'sub-grid' })
  subGrid = false;

  /**
   * Remove the default max width that the grid has set
   */
  @property({ reflect: true, attribute: 'wide' })
  wide = false;

  render() {
    const classes = 'cds--css-grid';

    // Grid styling added to contained components, allowing CSS Grid
    // to affect the it's own slot content.
    return html`<div class="${classes}" part="grid">
      <slot></slot>
    </div> `;
  }

  static styles = styles;
}

export default CDSGrid;
