// packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx
/**
 * Copyright IBM Corp. 2022, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {
  Checkmark,
  Close,
  Edit,
  WarningFilled,
  EditOff,
} from '@carbon/react/icons';
import React, {
  PropsWithChildren,
  forwardRef,
  useEffect,
  useRef,
  useState,
} from 'react';
import { pkg } from '../../settings';

import {
  IconButton,
  usePrefix,
  Toggletip,
  ToggletipButton,
  ToggletipContent,
} from '@carbon/react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { getDevtoolsProps } from '../../global/js/utils/devtools';

const componentName = 'EditInPlace';
const blockClass = `${pkg.prefix}--edit-in-place`;

const defaults = {
  tooltipAlignment: 'top',
  size: 'sm',
};

type Size = 'sm' | 'md' | 'lg';
type AlignPropType =
  | 'top'
  | 'top-left'
  | 'top-right'
  | 'bottom'
  | 'bottom-left'
  | 'bottom-right'
  | 'left'
  | 'right';
type Shape = {
  cancel: AlignPropType;
  edit: AlignPropType;
  save: AlignPropType;
};

export interface EditInplaceProps extends PropsWithChildren {
  /**
   * label for cancel button
   */
  cancelLabel: string;
  /**
   * By default the edit icon is shown on hover only.
   */
  editAlwaysVisible?: boolean;
  /**
   * label for edit button
   */
  editLabel: string;
  /**
   * Specify a custom id for the input
   */
  id: string;
  /**
   * inheritTypography - causes the text entry field to inherit typography settings
   * assigned to the container. This is useful when editing titles for instance.
   *
   * NOTE: The size property limits the vertical size of the input element.
   * Inherited font's should be selected to fit within the size selected.
   */
  inheritTypography?: boolean;
  /**
   * determines if the input is invalid
   */
  invalid?: boolean;
  /**
   * text that is displayed if the input is invalid
   */
  invalidText?: string;
  /**
   * Provide the text that will be read by a screen reader when visiting this control
   */
  labelText: string;

  /**
   * handler to add custom onBlur event
   */
  onBlur?: (value: string) => void;
  /**
   * handler that is called when the cancel button is pressed or when the user removes focus from the input and there is no new value
   */
  onCancel: (value: string) => void;
  /**
   * handler that is called when the input is updated
   */
  onChange: (value: string) => void;
  /**
   * handler that is called when the save button is pressed or when the user removes focus from the input if it has a new value
   */
  onSave: () => void;
  /**
   * determines if the input is in readOnly mode
   */
  readOnly?: boolean;
  /**
   * label for the edit off button that displays when in read only mode
   */
  readOnlyLabel?: string;
  /**
   * text for the toggletip that displays when in read only mode
   */
  readOnlyToggleTipText?: string;
  /**
   * label for save button
   */
  saveLabel: string;
  /**
   * alignment for the toggletip that displays when in read only mode
   */
  toggleTipAlignment?: AlignPropType;
  /**
   * vertical size of control
   */
  size?: Size;
  /**
   * tooltipAlignment from the standard tooltip. Default center.
   *
   * Can be passed either as one of tooltip options or as an object specifying cancel, edit and save separately
   */
  tooltipAlignment?: AlignPropType | Shape;
  /**
   * current value of the input
   */
  value: string;
  /**
   * placeholder for the input
   */
  placeholder?: string;
}

export const EditInPlace = forwardRef<HTMLDivElement, EditInplaceProps>(
  (
    {
      cancelLabel,
      editAlwaysVisible,
      editLabel,
      id,
      inheritTypography,
      invalid,
      invalidLabel: deprecated_invalidLabel = ' ',
      invalidText,
      labelText,
      onCancel,
      onChange,
      onSave,
      onBlur,
      readOnly,
      readOnlyLabel,
      readOnlyToggleTipText,
      saveLabel,
      size = 'sm',
      toggleTipAlignment,
      tooltipAlignment,
      value,
      placeholder,
      ...rest
    }: EditInplaceProps & { invalidLabel?: string },
    ref
  ) => {
    const [focused, setFocused] = useState(false);
    const [initialValue, setInitialValue] = useState<string>(value);
    const [dirtyInput, setDirtyInput] = useState(false);
    const inputRef = useRef<HTMLInputElement>(null);
    // Compare trimmed values to determine if there's a real change
    const hasValueChanged = value.trim() !== initialValue.trim();
    const canSave = hasValueChanged && !invalid;
    const canCancel = hasValueChanged;
    const escaping = useRef(false);
    const clickingWithin = useRef(false);
    const carbonPrefix = usePrefix();

    const tipAlignIsObject = typeof tooltipAlignment === 'object';
    const tipAlignments: { [key: string]: AlignPropType } = [
      'edit',
      'save',
      'cancel',
    ].reduce((acc, tips) => {
      acc[tips] =
        (tipAlignIsObject ? tooltipAlignment[tips] : tooltipAlignment) ??
        defaults.tooltipAlignment;

      return acc;
    }, {});

    // Note: We intentionally don't sync initialValue with value prop changes
    // initialValue represents the value when entering edit mode, not the current prop value
    // It's only updated on mount (via useState) and after successful save

    const isTargetingChild = ({ currentTarget, relatedTarget }) =>
      currentTarget.contains(relatedTarget);

    const onChangeHandler = ({ target }) => {
      if (!dirtyInput) {
        setDirtyInput(true);
      }

      onChange(target.value);
    };

    const onFocusHandler = (e) => {
      if (!isTargetingChild(e)) {
        inputRef.current?.focus();
      }
      // Always set focused when the input receives focus
      // The blur handler will manage exiting edit mode
      setFocused(true);
    };

    const onSaveHandler = (exitEditMode = false) => {
      setInitialValue(value);
      setDirtyInput(false);
      onSave();
      if (exitEditMode) {
        // Exit edit mode (for auto-save on blur)
        setFocused(false);
      } else {
        // Stay in edit mode (for manual save button click)
        requestAnimationFrame(() => {
          inputRef.current?.focus();
        });
      }
    };

    const onCancelHandler = (exitEditMode = false) => {
      setDirtyInput(false);
      onCancel(initialValue);
      if (exitEditMode) {
        // Exit edit mode (for auto-cancel on blur)
        setFocused(false);
      } else {
        // Stay in edit mode (for manual cancel button click)
        requestAnimationFrame(() => {
          if (inputRef.current) {
            inputRef.current.focus();
            // Set cursor to end of text
            const length = inputRef.current.value.length;
            inputRef.current.setSelectionRange(length, length);
          }
        });
      }
    };

    const onBlurHandler = (e: any) => {
      // Check if we clicked within (any button click)
      const clickedWithin = clickingWithin.current;

      // Check if targeting child (for tab navigation or clicking within)
      const targetingChild = isTargetingChild(e);

      // If clicked any button AND focus is staying within the component, don't exit edit mode
      // This handles clicking enabled buttons within the toolbar
      if (clickedWithin && targetingChild) {
        clickingWithin.current = false; // Reset for next interaction
        return;
      }

      // If clicked within but focus is leaving the component, exit edit mode
      // This handles clicking outside after clicking a disabled button
      if (clickedWithin && !targetingChild) {
        clickingWithin.current = false; // Reset the flag
        // Continue to exit edit mode below
      }

      // If tabbing to a button within the component, allow it (don't exit edit mode)
      if (!clickedWithin && targetingChild) {
        return;
      }

      // Use custom function provided if passed through
      if (typeof onBlur === 'function') {
        onBlur(initialValue);
        setFocused(false);
      } else {
        // Use Default behavior if no custom function provided
        if (escaping.current) {
          return;
        }
        if (canSave) {
          onSaveHandler(true); // Exit edit mode after auto-save
        } else {
          onCancelHandler(true); // Exit edit mode after auto-cancel
          setFocused(false);
        }
      }
    };

    const returnHandler = () => {
      if (canSave) {
        onSaveHandler();
      }
    };

    const escapeHandler = () => {
      onCancelHandler();
    };

    const removeFocus = () => {
      inputRef.current?.blur();
      setFocused(false);
    };

    const handleToolbarMouseDown = (e: React.MouseEvent<HTMLDivElement>) => {
      // Set flag when clicking any button to prevent blur handler from running
      const element = e.target as HTMLElement;
      let foundButton: HTMLElement | null = null;

      // First, try to traverse up to find a button
      let current = element;
      while (current && current !== e.currentTarget) {
        if (current.tagName === 'BUTTON') {
          foundButton = current;
          break;
        }
        current = current.parentElement as HTMLElement;
      }

      // If no button found by traversing up, search within the clicked element
      if (!foundButton) {
        foundButton = element.querySelector('button');
      }

      if (foundButton) {
        clickingWithin.current = true;

        // For disabled buttons, prevent default to stop blur from firing
        // This keeps the input focused when clicking disabled buttons
        const isDisabled =
          foundButton.hasAttribute('disabled') ||
          foundButton.getAttribute('aria-disabled') === 'true';
        if (isDisabled) {
          e.preventDefault();
        }
      }
    };

    const onKeyHandler = (e) => {
      // to prevent blur handler from being called twice add additional state to check if escape is being used
      escaping.current = true;
      switch (e.key) {
        case 'Escape':
          removeFocus();
          escapeHandler();
          break;
        case 'Enter':
          removeFocus();
          returnHandler();
          break;
        default:
          break;
      }
      escaping.current = false;
    };

    const inputElement = (
      <input
        id={id}
        className={cx(
          `${blockClass}__text-input`,
          `${carbonPrefix}--text-input`,
          `${carbonPrefix}--text-input--${size}`
        )}
        type="text"
        placeholder={placeholder}
        value={value}
        onChange={onChangeHandler}
        ref={inputRef}
        readOnly={readOnly}
        onKeyDown={onKeyHandler}
        aria-label={labelText}
        aria-invalid={invalid}
      />
    );

    const inputContainer = (
      <div
        className={cx(blockClass, `${blockClass}--${size}`, {
          [`${blockClass}--focused`]: focused,
          [`${blockClass}--invalid`]: invalid,
          [`${blockClass}--inherit-type`]: inheritTypography,
          [`${blockClass}--overflows`]:
            inputRef.current &&
            inputRef.current.scrollWidth > inputRef.current.offsetWidth,
          [`${blockClass}--readonly`]: readOnly,
        })}
        onFocus={onFocusHandler}
        onBlur={onBlurHandler}
      >
        {readOnly ? (
          <Toggletip
            align={toggleTipAlignment}
            className={`${blockClass}__toggletip-wrapper`}
          >
            <ToggletipButton label={readOnlyLabel || 'Edit off'}>
              {inputElement}
            </ToggletipButton>
            <ToggletipContent>
              <p>
                {readOnlyToggleTipText ||
                  'This field is read-only and cannot be edited'}
              </p>
            </ToggletipContent>
          </Toggletip>
        ) : (
          inputElement
        )}
        {/* eslint-disable-next-line jsx-a11y/no-static-element-interactions -- This div is not interactive; onMouseDown is used only to detect clicks on disabled buttons within to prevent blur */}
        <div
          className={`${blockClass}__toolbar`}
          onMouseDown={handleToolbarMouseDown}
        >
          {invalid && (
            <WarningFilled
              size={16}
              className={`${blockClass}__warning-icon`}
            />
          )}
          {readOnly ? (
            <IconButton
              className={`${blockClass}__btn-readonly`}
              size={size}
              label={readOnlyLabel || 'Edit off'}
              kind="ghost"
              key="readonly"
              onClick={onFocusHandler}
            >
              <EditOff size={16} />
            </IconButton>
          ) : focused ? (
            <>
              <IconButton
                align={tipAlignments.cancel}
                size={size}
                label={cancelLabel}
                onClick={() => onCancelHandler(false)}
                kind="ghost"
                key="cancel"
                className={`${blockClass}__btn ${blockClass}__btn-cancel`}
                disabled={!canCancel}
              >
                <Close size={16} />
              </IconButton>

              <IconButton
                align={tipAlignments.save}
                size={size}
                label={saveLabel}
                onClick={() => onSaveHandler(false)}
                kind="ghost"
                key="save"
                className={`${blockClass}__btn ${blockClass}__btn-save`}
                disabled={!canSave}
              >
                <Checkmark size={16} />
              </IconButton>
            </>
          ) : (
            <IconButton
              align={tipAlignments.edit}
              className={cx(`${blockClass}__btn`, `${blockClass}__btn-edit`, {
                [`${blockClass}__btn-edit--always-visible`]: editAlwaysVisible,
              })}
              size={size}
              label={editLabel}
              onClick={onFocusHandler}
              kind="ghost"
              key="edit"
            >
              <Edit size={16} />
            </IconButton>
          )}
        </div>
      </div>
    );

    return (
      <div {...rest} ref={ref} {...getDevtoolsProps(componentName)}>
        {inputContainer}
        {invalid && (
          <p className={`${blockClass}__warning-text`}>
            {invalidText ?? deprecated_invalidLabel}
          </p>
        )}
      </div>
    );
  }
);

EditInPlace.displayName = componentName;

export const deprecatedProps = {
  /**
   * **Deprecated**
   * invalidLabel was misnamed, using invalidText to match Carbon
   */
  invalidText: PropTypes.string,
};

const alignPropType = PropTypes.oneOf([
  'top',
  'top-left',
  'top-right',
  'bottom',
  'bottom-left',
  'bottom-right',
  'left',
  'right',
]);

EditInPlace.propTypes = {
  /**
   * label for cancel button
   */
  cancelLabel: PropTypes.string.isRequired,
  /**
   * By default the edit icon is shown on hover only.
   */
  editAlwaysVisible: PropTypes.bool,
  /**
   * label for edit button
   */
  editLabel: PropTypes.string.isRequired,
  /**
   * Specify a custom id for the input
   */
  id: PropTypes.string.isRequired,
  /**
   * inheritTypography - causes the text entry field to inherit typography settings
   * assigned to the container. This is useful when editing titles for instance.
   *
   * NOTE: The size property limits the vertical size of the input element.
   * Inherited font's should be selected to fit within the size selected.
   */
  inheritTypography: PropTypes.bool,
  /**
   * determines if the input is invalid
   */
  invalid: PropTypes.bool,
  /**
   * text that is displayed if the input is invalid
   */
  /**@ts-ignore*/
  invalidText: PropTypes.string,
  /**
   * Provide the text that will be read by a screen reader when visiting this control
   */
  labelText: PropTypes.string.isRequired,
  /**
   * handler to add custom onBlur event
   */
  onBlur: PropTypes.func,
  /**
   * handler that is called when the cancel button is pressed or when the user removes focus from the input and there is no new value
   */
  onCancel: PropTypes.func.isRequired,

  /**
   * handler that is called when the input is updated
   */
  onChange: PropTypes.func.isRequired,
  /**
   * handler that is called when the save button is pressed or when the user removes focus from the input if it has a new value
   */
  onSave: PropTypes.func.isRequired,
  /**
   * Placeholder for text input
   */
  placeholder: PropTypes.string,
  /**
   * determines if the input is in readOnly mode
   */
  readOnly: PropTypes.bool,
  /**
   * label for the edit off button that displays when in read only mode
   */
  readOnlyLabel: PropTypes.string,
  /**
   * text for the toggletip that displays when in read only mode
   */
  readOnlyToggleTipText: PropTypes.string,
  /**
   * label for save button
   */
  saveLabel: PropTypes.string.isRequired,
  /**
   * vertical size of control
   */
  size: PropTypes.oneOf(['sm', 'md', 'lg']),
  /**
   * alignment for the toggletip that displays when in read only mode
   */
  toggleTipAlignment: alignPropType,
  /**
   * tooltipAlignment from the standard tooltip. Default center.
   *
   * Can be passed either as one of tooltip options or as an object specifying cancel, edit and save separately
   */
  /**@ts-ignore*/
  tooltipAlignment: PropTypes.oneOfType([
    alignPropType,
    PropTypes.shape({
      cancel: alignPropType,
      edit: alignPropType,
      save: alignPropType,
    }),
  ]),
  /**
   * current value of the input
   */
  value: PropTypes.string.isRequired,

  ...deprecatedProps,
};

// packages/ibm-products-web-components/src/components/edit-in-place/edit-in-place.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property, state, query } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import { prefix, carbonPrefix } from '../../globals/settings';
import styles from './edit-in-place.scss?lit';
import '@carbon/web-components/es/components/icon-button/index.js';
import '@carbon/web-components/es/components/tooltip/index.js';
import Edit16 from '@carbon/icons/es/edit/16';
import EditOff16 from '@carbon/icons/es/edit--off/16';
import Checkmark16 from '@carbon/icons/es/checkmark/16';
import Close16 from '@carbon/icons/es/close/16';
import WarningFilled16 from '@carbon/icons/es/warning--filled/16';
import { iconLoader } from '@carbon/web-components/es/globals/internal/icon-loader.js';
import { EDIT_IN_PLACE_SIZE, TOOLTIP_ALIGNMENT } from './defs';

const blockClass = `${prefix}--edit-in-place`;

export type EditInPlaceSize = `${EDIT_IN_PLACE_SIZE}`;
export type TooltipAlignment = `${TOOLTIP_ALIGNMENT}`;

/**
 * EditInPlace component for inline text editing.
 *
 * @element c4p-edit-in-place
 * @csspart input - The input element
 * @csspart actions - The button container
 * @csspart invalid-text - The error message container
 * @fires c4p-edit-in-place-change - Fired when the input value changes
 * @fires c4p-edit-in-place-save - Fired when the save button is clicked or Enter is pressed
 * @fires c4p-edit-in-place-cancel - Fired when the cancel button is clicked or Escape is pressed
 * @fires c4p-edit-in-place-blur - Fired when the input loses focus (if onBlur handler is used)
 */
@customElement(`${prefix}-edit-in-place`)
class C4PEditInPlace extends LitElement {
  /**
   * Label for the cancel button
   */
  @property({ type: String, attribute: 'cancel-label' })
  cancelLabel = 'Cancel';

  /**
   * By default the edit icon is shown on hover only. Set to true to always show it.
   */
  @property({ type: Boolean, attribute: 'edit-always-visible' })
  editAlwaysVisible = false;

  /**
   * Label for the edit button
   */
  @property({ type: String, attribute: 'edit-label' })
  editLabel = 'Edit';

  /**
   * Specify a custom id for the input
   */
  @property({ type: String })
  id = '';

  /**
   * Causes the text entry field to inherit typography settings from the container
   */
  @property({ type: Boolean, attribute: 'inherit-typography' })
  inheritTypography = false;

  /**
   * Determines if the input is invalid
   */
  @property({ type: Boolean })
  invalid = false;

  /**
   * Text that is displayed if the input is invalid
   */
  @property({ type: String, attribute: 'invalid-text' })
  invalidText = '';

  /**
   * Text that will be read by a screen reader when visiting this control
   */
  @property({ type: String, attribute: 'label-text' })
  labelText = '';

  /**
   * Placeholder text for the input
   */
  @property({ type: String })
  placeholder = '';

  /**
   * Determines if the input is in readOnly mode
   */
  @property({ type: Boolean, attribute: 'read-only' })
  readOnly = false;

  /**
   * Label for the edit off button that displays when in read only mode
   */
  @property({ type: String, attribute: 'read-only-label' })
  readOnlyLabel = 'Edit off';

  /**
   * Text for the toggletip that displays when in read only mode
   */
  @property({ type: String, attribute: 'read-only-toggletip-text' })
  readOnlyToggleTipText = 'This field is read-only and cannot be edited';

  /**
   * Label for the save button
   */
  @property({ type: String, attribute: 'save-label' })
  saveLabel = 'Save';

  /**
   * Vertical size of control
   */
  @property({ type: String })
  size: EditInPlaceSize = 'sm';

  /**
   * Alignment for the toggletip that displays when in read only mode
   */
  @property({ type: String, attribute: 'toggletip-alignment' })
  toggleTipAlignment: TooltipAlignment = 'bottom';

  /**
   * Tooltip alignment for buttons
   */
  @property({ type: String, attribute: 'tooltip-alignment' })
  tooltipAlignment: TooltipAlignment = 'top';

  /**
   * Current value of the input (controlled mode)
   */
  @property({ type: String })
  value = '';

  /**
   * Default value for uncontrolled mode
   */
  @property({ type: String, attribute: 'default-value' })
  defaultValue = '';

  /**
   * Internal state for focused mode
   */
  @state()
  private _focused = false;

  /**
   * Internal value for managing state
   */
  @state()
  private _internalValue = '';

  /**
   * Internal state for initial value (when entering edit mode)
   */
  @state()
  private _initialValue = '';

  /**
   * Internal state to track if input has been modified
   */
  @state()
  private _dirtyInput = false;

  /**
   * Flag to track if we're handling escape key
   */
  private _escaping = false;

  /**
   * Flag to track if we're clicking within the component
   */
  private _clickingWithin = false;

  /**
   * Reference to the input element
   */
  @query('input')
  private _inputElement!: HTMLInputElement;

  /**
   * Bound handler for document clicks (for cleanup)
   */
  private _boundHandleDocumentClick: ((e: MouseEvent) => void) | null = null;

  /**
   * Check if value has changed from initial
   */
  private get _hasValueChanged(): boolean {
    return this._internalValue.trim() !== this._initialValue.trim();
  }

  /**
   * Check if we can save (value changed and not invalid)
   */
  private get _canSave(): boolean {
    return this._hasValueChanged && !this.invalid;
  }

  /**
   * Check if we can cancel (value has changed)
   */
  private get _canCancel(): boolean {
    return this._hasValueChanged;
  }

  /**
   * Handle input change
   */
  private _handleChange(e: Event) {
    const input = e.target as HTMLInputElement;
    if (!this._dirtyInput) {
      this._dirtyInput = true;
    }

    this._internalValue = input.value;

    const init = {
      bubbles: true,
      composed: true,
      detail: { value: this._internalValue },
    };
    this.dispatchEvent(new CustomEvent(`${prefix}-edit-in-place-change`, init));
  }

  /**
   * Handle focus
   */
  private _handleFocus(e: FocusEvent) {
    const relatedTarget = e.relatedTarget as Node;
    if (!this.contains(relatedTarget)) {
      requestAnimationFrame(() => {
        this._inputElement?.focus();
      });
    }
    this._focused = true;
  }

  /**
   * Handle save
   */
  private _handleSave(exitEditMode = false) {
    this._initialValue = this._internalValue;
    this._dirtyInput = false;

    const init = {
      bubbles: true,
      composed: true,
      detail: { value: this._internalValue },
    };
    this.dispatchEvent(new CustomEvent(`${prefix}-edit-in-place-save`, init));

    if (exitEditMode) {
      this._focused = false;
    } else {
      requestAnimationFrame(() => {
        this._inputElement?.focus();
      });
    }
  }

  /**
   * Handle cancel
   */
  private _handleCancel(exitEditMode = false) {
    this._dirtyInput = false;
    this._internalValue = this._initialValue;

    const init = {
      bubbles: true,
      composed: true,
      detail: { value: this._initialValue },
    };
    this.dispatchEvent(new CustomEvent(`${prefix}-edit-in-place-cancel`, init));

    if (exitEditMode) {
      this._focused = false;
    } else {
      requestAnimationFrame(() => {
        if (this._inputElement) {
          this._inputElement.focus();
          const length = this._inputElement.value.length;
          this._inputElement.setSelectionRange(length, length);
        }
      });
    }
  }

  /**
   * Handle blur
   */
  private _handleBlur(e: FocusEvent) {
    const relatedTarget = e.relatedTarget as Node;
    const clickedWithin = this._clickingWithin;
    const targetingChild = this.contains(relatedTarget);

    // Reset clicking flag if we clicked within
    if (clickedWithin) {
      this._clickingWithin = false;
      // If focus is staying within, don't exit edit mode
      if (targetingChild) {
        return;
      }
    }

    // If tabbing to a button within, allow it
    if (!clickedWithin && targetingChild) {
      return;
    }

    // Default behavior: auto-save or auto-cancel
    if (this._escaping) {
      return;
    }

    if (this._canSave) {
      this._handleSave(true);
    } else {
      this._handleCancel(true);
    }

    // Dispatch blur event
    const init = {
      bubbles: true,
      composed: true,
      detail: { value: this._initialValue },
    };
    this.dispatchEvent(new CustomEvent(`${prefix}-edit-in-place-blur`, init));
  }

  /**
   * Handle keyboard events
   */
  private _handleKeyDown(e: KeyboardEvent) {
    switch (e.key) {
      case 'Escape':
        this._escaping = true;
        this._inputElement?.blur();
        this._handleCancel(false);
        this._escaping = false;
        break;
      case 'Enter':
        this._escaping = true;
        this._inputElement?.blur();
        if (this._canSave) {
          this._handleSave(false);
        }
        this._escaping = false;
        break;
      case 'Tab':
        // When tabbing from input, check if we're going outside the component
        // If shift+tab, we're going backwards (let it handle naturally)
        // If tab forward and no changes, we should exit edit mode
        if (!e.shiftKey && !this._hasValueChanged) {
          // Exit edit mode when tabbing out without changes
          this._handleCancel(true);
        }
        break;
      default:
        break;
    }
  }

  /**
   * Handle toolbar mousedown to track button clicks
   * Uses composedPath() to properly handle Shadow DOM boundaries
   */
  private _handleToolbarMouseDown(e: MouseEvent) {
    const path = e.composedPath();
    const foundButton = path.find(
      (el) =>
        el instanceof HTMLElement &&
        (el.tagName === 'BUTTON' || el.tagName === 'CDS-ICON-BUTTON')
    ) as HTMLElement | undefined;

    if (foundButton) {
      this._clickingWithin = true;

      // For disabled buttons, prevent default to stop blur
      const isDisabled =
        foundButton.hasAttribute('disabled') ||
        foundButton.getAttribute('aria-disabled') === 'true';
      if (isDisabled) {
        e.preventDefault();
      }
    }
  }

  /**
   * Handle keydown on save button to exit edit mode on Tab
   */
  private _handleSaveButtonKeyDown(e: KeyboardEvent) {
    if (e.key === 'Tab' && !e.shiftKey) {
      // Tab forward from save button - exit edit mode
      this._focused = false;
      this._inputElement?.blur();
    }
  }

  /**
   * Handle clicks outside the component
   */
  private _handleDocumentClick(e: MouseEvent) {
    // Only handle if we're in focused mode
    if (!this._focused) {
      return;
    }

    // Check if click is outside the component
    const path = e.composedPath();
    const clickedInside = path.includes(this);

    if (!clickedInside) {
      // Click was outside - exit edit mode
      if (this._canSave) {
        this._handleSave(true);
      } else {
        this._handleCancel(true);
      }
    }
  }

  /**
   * Initialize component
   */
  connectedCallback() {
    super.connectedCallback();
    this._internalValue = this.value || this.defaultValue;
    this._initialValue = this._internalValue;

    // Set up document click listener
    this._boundHandleDocumentClick = this._handleDocumentClick.bind(this);
    document.addEventListener('click', this._boundHandleDocumentClick, true);
  }

  /**
   * Cleanup component state when removed from DOM
   */
  disconnectedCallback() {
    super.disconnectedCallback();
    this._escaping = false;
    this._clickingWithin = false;
    this._focused = false;

    // Clean up document click listener
    if (this._boundHandleDocumentClick) {
      document.removeEventListener(
        'click',
        this._boundHandleDocumentClick,
        true
      );
      this._boundHandleDocumentClick = null;
    }
  }

  /**
   * Render the input element
   */
  private _renderInput() {
    const inputClasses = {
      [`${blockClass}__text-input`]: true,
      [`${carbonPrefix}--text-input`]: true,
      [`${carbonPrefix}--text-input--${this.size}`]: true,
    };

    const inputElement = html`
      <input
        id=${this.id}
        class=${classMap(inputClasses)}
        type="text"
        part="input"
        placeholder=${this.placeholder}
        .value=${this._internalValue}
        @input=${this._handleChange}
        @focus=${this._handleFocus}
        @keydown=${this._handleKeyDown}
        aria-label=${this.labelText}
        aria-invalid=${this.invalid ? 'true' : 'false'}
        ?readonly=${this.readOnly}
      />
    `;

    if (this.readOnly) {
      return html`
        <cds-tooltip
          align=${this.toggleTipAlignment}
          class="${blockClass}__toggletip-wrapper"
        >
          ${inputElement}
          <cds-tooltip-content
            >${this.readOnlyToggleTipText}</cds-tooltip-content
          >
        </cds-tooltip>
      `;
    }

    return inputElement;
  }

  /**
   * Render action buttons
   */
  private _renderActions() {
    if (this.readOnly) {
      return html`
        <cds-icon-button
          class="${blockClass}__btn-readonly"
          size=${this.size}
          align=${this.tooltipAlignment}
          kind="ghost"
          @click=${this._handleFocus}
        >
          ${iconLoader(EditOff16, { slot: 'icon' })}
          <span slot="tooltip-content">${this.readOnlyLabel}</span>
        </cds-icon-button>
      `;
    }

    if (this._focused) {
      return html`
        <cds-icon-button
          class="${blockClass}__btn ${blockClass}__btn-cancel"
          size=${this.size}
          align=${this.tooltipAlignment}
          kind="ghost"
          ?disabled=${!this._canCancel}
          @click=${() => this._handleCancel(false)}
        >
          ${iconLoader(Close16, { slot: 'icon' })}
          <span slot="tooltip-content">${this.cancelLabel}</span>
        </cds-icon-button>
        <cds-icon-button
          class="${blockClass}__btn ${blockClass}__btn-save"
          size=${this.size}
          align=${this.tooltipAlignment}
          kind="ghost"
          ?disabled=${!this._canSave}
          @click=${() => this._handleSave(false)}
          @keydown=${this._handleSaveButtonKeyDown}
        >
          ${iconLoader(Checkmark16, { slot: 'icon' })}
          <span slot="tooltip-content">${this.saveLabel}</span>
        </cds-icon-button>
      `;
    }

    const editBtnClasses = {
      [`${blockClass}__btn`]: true,
      [`${blockClass}__btn-edit`]: true,
      [`${blockClass}__btn-edit--always-visible`]: this.editAlwaysVisible,
    };

    return html`
      <cds-icon-button
        class=${classMap(editBtnClasses)}
        size=${this.size}
        align=${this.tooltipAlignment}
        kind="ghost"
        @click=${this._handleFocus}
      >
        ${iconLoader(Edit16, { slot: 'icon' })}
        <span slot="tooltip-content">${this.editLabel}</span>
      </cds-icon-button>
    `;
  }

  render() {
    const containerClasses = {
      [`${blockClass}__container`]: true,
      [`${blockClass}--${this.size}`]: true,
      [`${blockClass}--focused`]: this._focused,
      [`${blockClass}--invalid`]: this.invalid,
      [`${blockClass}--inherit-type`]: this.inheritTypography,
      [`${blockClass}--readonly`]: this.readOnly,
    };

    return html`
      <div class=${classMap(containerClasses)} @blur=${this._handleBlur}>
        ${this._renderInput()}
        <div
          class="${blockClass}__toolbar"
          part="actions"
          @mousedown=${this._handleToolbarMouseDown}
        >
          ${this.invalid
            ? iconLoader(WarningFilled16, {
                class: `${blockClass}__warning-icon`,
              })
            : ''}
          ${this._renderActions()}
        </div>
      </div>
      ${this.invalid
        ? html`<p class="${blockClass}__warning-text" part="invalid-text">
            ${this.invalidText}
          </p>`
        : ''}
    `;
  }

  static styles = styles;
}

export default C4PEditInPlace;
