// packages/react/src/components/FileUploader/FileUploader.Skeleton.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import cx from 'classnames';
import SkeletonText from '../SkeletonText';
import ButtonSkeleton from '../Button/Button.Skeleton';
import { usePrefix } from '../../internal/usePrefix';

export interface FileUploaderSkeletonProps {
  /**
   * Specify an optional className to add.
   */
  className?: string;
}

function FileUploaderSkeleton(props: FileUploaderSkeletonProps) {
  const { className, ...rest } = props;
  const prefix = usePrefix();
  return (
    <div className={cx(`${prefix}--form-item`, className)} {...rest}>
      <SkeletonText heading width="100px" />
      <SkeletonText width="225px" className={`${prefix}--label-description`} />
      <ButtonSkeleton />
    </div>
  );
}

FileUploaderSkeleton.propTypes = {
  /**
   * Specify an optional className to add.
   */
  className: PropTypes.string,
};

export default FileUploaderSkeleton;
export { FileUploaderSkeleton };

// packages/web-components/src/components/file-uploader/file-uploader-skeleton.ts
/**
 * Copyright IBM Corp. 2019, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import '../skeleton-text/skeleton-text';
import { SKELETON_TEXT_TYPE } from '../skeleton-text/skeleton-text';
import '../button/button-skeleton';

/**
 * The File uploader skeleton.
 *
 * @element cds-file-uploader-skeleton
 */
class CDSFileUploaderSkeleton extends LitElement {
  static is = `${prefix}-file-uploader-skeleton`;

  render() {
    return html`
      <cds-skeleton-text
        type="${SKELETON_TEXT_TYPE.HEADING}"
        width="100px"></cds-skeleton-text>
      <cds-skeleton-text width="225px"></cds-skeleton-text>
      <cds-button-skeleton></cds-button-skeleton>
    `;
  }
}

export default CDSFileUploaderSkeleton;
