// web-components/packages/carbon-web-components/src/components/ai-skeleton/ai-skeleton-placeholder.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './ai-skeleton.scss';
import '../skeleton-placeholder/skeleton-placeholder';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * AI skeleton placeholder.
 *
 * @element cds-ai-skeleton-placeholder
 */
@customElement(`${prefix}-ai-skeleton-placeholder`)
class CDSAISkeletonPlaceholder extends LitElement {
  render() {
    return html`<cds-skeleton-placeholder
      optional-classes="${prefix}--skeleton__placeholder--ai"></cds-skeleton-placeholder>`;
  }

  static styles = styles;
}

export default CDSAISkeletonPlaceholder;

// packages/react/src/components/AISkeleton/AISkeletonPlaceholder.tsx
/**
 * Copyright IBM Corp. 2016, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import { usePrefix } from '../../internal/usePrefix';
import { SkeletonPlaceholder } from '../SkeletonPlaceholder';

export interface AISkeletonPlaceholderProps {
  /**
   * Add a custom class to the component to set the height and width
   */
  className?: string;
}

const AISkeletonPlaceholder = ({
  className,
  ...other
}: AISkeletonPlaceholderProps) => {
  const prefix = usePrefix();
  const AISkeletonPlaceholderClasses = classNames(
    { className, [`${prefix}--skeleton__placeholder--ai`]: true },
    className
  );

  return (
    <SkeletonPlaceholder className={AISkeletonPlaceholderClasses} {...other} />
  );
};

AISkeletonPlaceholder.propTypes = {
  /**
   * Add a custom class to the component
   * to set the height and width
   */
  className: PropTypes.string,
};

export default AISkeletonPlaceholder;
