// web-components/packages/carbon-web-components/src/components/inline-loading/inline-loading-story-react.tsx
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { Default as baseDefault } from './inline-loading-story';

export { default } from './inline-loading-story';

export const Default = args => {
  const { status } = args?.['bx-inline-loading'];
  return <bx-inline-loading status={status}>Loading data...</bx-inline-loading>;
};

Object.assign(Default, baseDefault);

// web-components/packages/carbon-web-components/src/components/inline-loading/inline-loading-story-angular.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { moduleMetadata } from '@storybook/angular';
import baseStory, { Default as baseDefault } from './inline-loading-story';

export const Default = args => ({
  template: `
    <bx-inline-loading [status]="status">Loading data...</bx-inline-loading>
  `,
  props: args?.['bx-inline-loading'],
});

Object.assign(Default, baseDefault);

export default Object.assign(baseStory, {
  decorators: [
    moduleMetadata({
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
    }),
  ],
});
