// web-components/packages/carbon-web-components/src/components/content-switcher/content-switcher-story-angular.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { moduleMetadata } from '@storybook/angular';
import baseStory, { Default as baseDefault } from './content-switcher-story';

export const Default = args => ({
  template: `
    <bx-content-switcher
      [value]="value"
      (bx-content-switcher-beingselected)="handleBeforeSelect($event)"
      (bx-content-switcher-selected)="handleAfterSelect($event)"
      [size]="size"
    >
      <bx-content-switcher-item value="all">Option 1</bx-content-switcher-item>
      <bx-content-switcher-item value="cloudFoundry" disabled>Option 2</bx-content-switcher-item>
      <bx-content-switcher-item value="staging">Option 3</bx-content-switcher-item>
      <bx-content-switcher-item value="dea">Option 4</bx-content-switcher-item>
      <bx-content-switcher-item value="router">Option 5</bx-content-switcher-item>
    </bx-content-switcher>
  `,
  props: (({ disableSelection, onBeforeSelect, onSelect, ...rest }) => {
    const handleBeforeSelect = (event: CustomEvent) => {
      onBeforeSelect(event);
      if (disableSelection) {
        event.preventDefault();
      }
    };
    return {
      ...rest,
      handleBeforeSelect,
      handleAfterSelect: onSelect,
    };
  })(args?.['bx-content-switcher']),
});

Object.assign(Default, baseDefault);

export default Object.assign(baseStory, {
  decorators: [
    moduleMetadata({
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
    }),
  ],
});

// web-components/packages/carbon-web-components/src/components/content-switcher/content-switcher-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { action } from '@storybook/addon-actions';
import { boolean, select } from '@storybook/addon-knobs';
import textNullable from '../../../.storybook/knob-text-nullable';
import { ifDefined } from 'lit/directives/if-defined.js';
import { CONTENT_SWITCHER_SIZE } from './content-switcher';
import './content-switcher-item';
import storyDocs from './content-switcher-story.mdx';

const noop = () => {};

const sizes = {
  'Regular size': null,
  [`Small size (${CONTENT_SWITCHER_SIZE.SMALL})`]: CONTENT_SWITCHER_SIZE.SMALL,
  [`XL size (${CONTENT_SWITCHER_SIZE.EXTRA_LARGE})`]:
    CONTENT_SWITCHER_SIZE.EXTRA_LARGE,
};

export const Default = (args) => {
  const {
    value,
    disableSelection,
    onBeforeSelect = noop,
    onSelect = noop,
    size,
  } = args?.['bx-content-switcher'] ?? {};
  const handleBeforeSelected = (event: CustomEvent) => {
    onBeforeSelect(event);
    if (disableSelection) {
      event.preventDefault();
    }
  };
  return html`
    <bx-content-switcher
      value="${ifDefined(value)}"
      @bx-content-switcher-beingselected="${handleBeforeSelected}"
      @bx-content-switcher-selected="${onSelect}"
      size="${size}">
      <bx-content-switcher-item value="all">Option 1</bx-content-switcher-item>
      <bx-content-switcher-item value="cloudFoundry" disabled
        >Option 2</bx-content-switcher-item
      >
      <bx-content-switcher-item value="staging"
        >Option 3</bx-content-switcher-item
      >
      <bx-content-switcher-item value="dea">Option 4</bx-content-switcher-item>
      <bx-content-switcher-item value="router"
        >Option 5</bx-content-switcher-item
      >
    </bx-content-switcher>
  `;
};

Default.storyName = 'Default';

export default {
  title: 'Components/Content switcher',
  parameters: {
    ...storyDocs.parameters,
    knobs: {
      'bx-content-switcher': () => ({
        value: textNullable('The value of the selected item (value)', ''),
        size: select('Button size (size)', sizes, null),
        disableSelection: boolean(
          'Disable user-initiated selection change (Call event.preventDefault() in bx-content-switcher-beingselected event)',
          false
        ),
        onBeforeSelect: action('bx-content-switcher-beingselected'),
        onSelect: action('bx-content-switcher-selected'),
      }),
    },
  },
};
