// web-components/packages/carbon-web-components/src/components/content-switcher/content-switcher-story-angular.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { moduleMetadata } from '@storybook/angular';
import baseStory, { Default as baseDefault } from './content-switcher-story';

export const Default = args => ({
  template: `
    <bx-content-switcher
      [value]="value"
      (bx-content-switcher-beingselected)="handleBeforeSelect($event)"
      (bx-content-switcher-selected)="handleAfterSelect($event)"
      [size]="size"
    >
      <bx-content-switcher-item value="all">Option 1</bx-content-switcher-item>
      <bx-content-switcher-item value="cloudFoundry" disabled>Option 2</bx-content-switcher-item>
      <bx-content-switcher-item value="staging">Option 3</bx-content-switcher-item>
      <bx-content-switcher-item value="dea">Option 4</bx-content-switcher-item>
      <bx-content-switcher-item value="router">Option 5</bx-content-switcher-item>
    </bx-content-switcher>
  `,
  props: (({ disableSelection, onBeforeSelect, onSelect, ...rest }) => {
    const handleBeforeSelect = (event: CustomEvent) => {
      onBeforeSelect(event);
      if (disableSelection) {
        event.preventDefault();
      }
    };
    return {
      ...rest,
      handleBeforeSelect,
      handleAfterSelect: onSelect,
    };
  })(args?.['bx-content-switcher']),
});

Object.assign(Default, baseDefault);

export default Object.assign(baseStory, {
  decorators: [
    moduleMetadata({
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
    }),
  ],
});

// web-components/packages/carbon-web-components/src/components/content-switcher/content-switcher-story-react.tsx
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
// Below path will be there when an application installs `carbon-web-components` package.
// In our dev env, we auto-generate the file and re-map below path to to point to the generated file.
// @ts-ignore
import BXContentSwitcher from 'carbon-web-components/es/components-react/content-switcher/content-switcher';
// @ts-ignore
import BXContentSwitcherItem from 'carbon-web-components/es/components-react/content-switcher/content-switcher-item';
import { Default as baseDefault } from './content-switcher-story';

export { default } from './content-switcher-story';

export const Default = args => {
  const { value, disableSelection, onBeforeSelect, onSelect, size } = args?.['bx-content-switcher'];
  const handleBeforeSelected = (event: CustomEvent) => {
    onBeforeSelect(event);
    if (disableSelection) {
      event.preventDefault();
    }
  };
  return (
    <BXContentSwitcher value={value} onBeforeSelect={handleBeforeSelected} onSelect={onSelect} size={size}>
      <BXContentSwitcherItem value="all">Option 1</BXContentSwitcherItem>
      <BXContentSwitcherItem value="cloudFoundry" disabled>
        Option 2
      </BXContentSwitcherItem>
      <BXContentSwitcherItem value="staging">Option 3</BXContentSwitcherItem>
      <BXContentSwitcherItem value="dea">Option 4</BXContentSwitcherItem>
      <BXContentSwitcherItem value="router">Option 5</BXContentSwitcherItem>
    </BXContentSwitcher>
  );
};

Object.assign(Default, baseDefault);
