// packages/react/src/components/Card/CardTitle.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { forwardRef, ReactNode } from 'react';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';

const componentName = 'CardTitle';

export interface CardTitleProps {
  /**
   * Provide the contents of the CardTitle.
   */
  children?: ReactNode;

  /**
   * Provide an optional class to be applied to the containing node.
   */
  className?: string;

  /**
   * Enable text truncation with ellipsis on the title text row.
   * - `true`: Single line truncation
   * - `number`: Multi-line truncation (line clamp)
   * @default false
   */
  titleTruncate?: boolean | number;

  /**
   * Maximum width applied to the title text row when truncation is active.
   * @default '100%'
   */
  maxWidth?: string;

  /**
   * Optional leading icon or content to display before the title text.
   * - Productive density: 16px icon recommended
   * - Expressive density: 24px icon recommended
   */
  titleStart?: ReactNode;

  /**
   * Optional trailing icon or content to display after the title text.
   * - Productive density: 16px icon recommended
   * - Expressive density: 24px icon recommended
   */
  titleEnd?: ReactNode;

  /**
   * Optional label rendered above the title text.
   * Uses $label-01 typography and $text-secondary color.
   */
  label?: ReactNode;

  /**
   * Enable truncation on the label text.
   * - `true`: Single line truncation
   * - `number`: Multi-line truncation (line clamp)
   * @default false
   */
  labelTruncate?: boolean | number;

  /**
   * Optional description rendered below the title text.
   * Uses $label-01 typography and $text-secondary color.
   */
  description?: ReactNode;

  /**
   * Enable truncation on the description text.
   * - `true`: Single line truncation
   * - `number`: Multi-line truncation (line clamp)
   * @default false
   */
  descriptionTruncate?: boolean | number;
}

/**
 * CardTitle displays the main title text in the card header.
 * Typography is driven by density on the parent Card:
 * - Productive: $heading-compact-02 (16px/22px)
 * - Expressive: $heading-03 (20px/28px)
 */
export const CardTitle = forwardRef<HTMLDivElement, CardTitleProps>(
  (
    {
      children,
      className,
      titleTruncate = false,
      maxWidth = '100%',
      titleStart,
      titleEnd,
      label,
      labelTruncate = false,
      description,
      descriptionTruncate = false,
      ...rest
    },
    ref
  ) => {
    const prefix = usePrefix();
    const blockClass = `${prefix}--card`;

    const isTitleMulti = typeof titleTruncate === 'number';
    const isLabelMulti = typeof labelTruncate === 'number';
    const isDescMulti = typeof descriptionTruncate === 'number';

    const containerClasses = cx(`${blockClass}__title`, className);

    // Truncation and icon classes live on the inner text-row so they never
    // override the outer container's display:flex flex-direction:column,
    // which keeps the label and description visible.
    const textRowClasses = cx(`${blockClass}__title-text-row`, {
      [`${blockClass}__title-text-row--truncate`]: titleTruncate === true,
      [`${blockClass}__title-text-row--truncate-multi`]: isTitleMulti,
      [`${blockClass}__title-text-row--with-start-icon`]: titleStart,
      [`${blockClass}__title-text-row--with-end-icon`]: titleEnd,
    });

    // Dynamic values passed as CSS custom properties so SCSS rules can read
    // them via var(). Avoids encoding presentation logic in inline styles.
    const titleVars =
      titleTruncate !== false
        ? {
            [`--${prefix}--card--title-max-width`]: maxWidth,
            ...(isTitleMulti && {
              [`--${prefix}--card--title-line-clamp`]: titleTruncate,
            }),
          }
        : undefined;

    const labelVars = isLabelMulti
      ? { [`--${prefix}--card--label-line-clamp`]: labelTruncate }
      : undefined;

    const descVars = isDescMulti
      ? { [`--${prefix}--card--description-line-clamp`]: descriptionTruncate }
      : undefined;

    return (
      <div {...rest} ref={ref} className={containerClasses}>
        {label && (
          <div
            className={cx(`${blockClass}__label`, {
              [`${blockClass}__label--truncate`]: labelTruncate === true,
              [`${blockClass}__label--truncate-multi`]: isLabelMulti,
            })}
            style={labelVars as React.CSSProperties}>
            {label}
          </div>
        )}
        <span
          className={textRowClasses}
          style={titleVars as React.CSSProperties}>
          {titleStart && (
            <span className={`${blockClass}__title-start-icon`}>
              {titleStart}
            </span>
          )}
          {children}
          {titleEnd && (
            <span className={`${blockClass}__title-end-icon`}>{titleEnd}</span>
          )}
        </span>
        {description && (
          <div
            className={cx(`${blockClass}__description`, {
              [`${blockClass}__description--truncate`]:
                descriptionTruncate === true,
              [`${blockClass}__description--truncate-multi`]: isDescMulti,
            })}
            style={descVars as React.CSSProperties}>
            {description}
          </div>
        )}
      </div>
    );
  }
);

CardTitle.displayName = componentName;

// packages/web-components/src/components/card/card-title.ts
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { styleMap } from 'lit/directives/style-map.js';
import { prefix } from '../../globals/settings';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import styles from './card.scss?lit';

/**
 * Card title — primary heading within cds-card-header.
 *
 * Typography is driven by the density set on the parent cds-card:
 * - `productive` (default): $heading-compact-02
 * - `expressive`: $heading-03
 *
 * Truncation is controlled via CSS custom properties that the shared
 * @carbon/styles card mixin reads with `var()`.
 *
 * @element cds-card-title
 * @slot - Title text (required).
 * @slot label - Rich label content rendered above the title (overrides `label` attr).
 * @slot title-start - Leading icon/content (16px productive, 24px expressive).
 * @slot title-end - Trailing icon/content.
 * @slot description - Rich description rendered below the title (overrides `description` attr).
 */
@customElement(`${prefix}-card-title`)
class CDSCardTitle extends LitElement {
  /**
   * Enable truncation on the title text row.
   * - Empty attribute / `true`: single-line ellipsis.
   * - Positive integer string: multi-line `-webkit-line-clamp` value.
   *
   * Stored as a raw string so the attribute value `"3"` is preserved
   * as-is for the CSS custom property.
   */
  @property({ attribute: 'title-truncate', reflect: true })
  titleTruncate: string | null = null;

  /**
   * Maximum width applied to the title text row when truncation is active.
   * @default '100%'
   */
  @property({ attribute: 'max-width', reflect: true })
  maxWidth = '100%';

  /**
   * Optional label text rendered above the title (plain string).
   * Slot `label` takes precedence when populated.
   */
  @property({ type: String, reflect: true })
  label!: string;

  /**
   * Enable truncation on the label.
   * Same semantics as `title-truncate`.
   */
  @property({ attribute: 'label-truncate', reflect: true })
  labelTruncate: string | null = null;

  /**
   * Optional description text rendered below the title (plain string).
   * Slot `description` takes precedence when populated.
   */
  @property({ type: String, reflect: true })
  description!: string;

  /**
   * Enable truncation on the description.
   * Same semantics as `title-truncate`.
   */
  @property({ attribute: 'description-truncate', reflect: true })
  descriptionTruncate: string | null = null;

  // ─── Helpers ─────────────────────────────────────────────────────────────

  /**
   * Parse a truncation attribute value:
   * - `null` / empty string → no truncation
   * - `""` (boolean attr present) | `"true"` → single-line
   * - numeric string → multi-line clamp
   */
  private _parseTruncate(value: string | null): false | true | number {
    if (value === null) return false;
    const num = Number(value);
    if (!isNaN(num) && num > 0) return num;
    return true; // boolean attr present
  }

  render() {
    const blockClass = `${prefix}--card`;

    const titleTruncate = this._parseTruncate(this.titleTruncate);
    const labelTruncate = this._parseTruncate(this.labelTruncate);
    const descTruncate = this._parseTruncate(this.descriptionTruncate);

    const isTitleMulti = typeof titleTruncate === 'number';
    const isLabelMulti = typeof labelTruncate === 'number';
    const isDescMulti = typeof descTruncate === 'number';

    // CSS custom properties for truncation — read by the shared SCSS mixin.
    const titleVars =
      titleTruncate !== false
        ? {
            [`--${prefix}--card--title-max-width`]: this.maxWidth,
            ...(isTitleMulti && {
              [`--${prefix}--card--title-line-clamp`]: String(titleTruncate),
            }),
          }
        : {};

    const labelVars = isLabelMulti
      ? { [`--${prefix}--card--label-line-clamp`]: String(labelTruncate) }
      : {};

    const descVars = isDescMulti
      ? {
          [`--${prefix}--card--description-line-clamp`]: String(descTruncate),
        }
      : {};

    const textRowClasses = classMap({
      [`${blockClass}__title-text-row`]: true,
      [`${blockClass}__title-text-row--truncate`]: titleTruncate === true,
      [`${blockClass}__title-text-row--truncate-multi`]: isTitleMulti,
    });

    const labelClasses = classMap({
      [`${blockClass}__label`]: true,
      [`${blockClass}__label--truncate`]: labelTruncate === true,
      [`${blockClass}__label--truncate-multi`]: isLabelMulti,
    });

    const descClasses = classMap({
      [`${blockClass}__description`]: true,
      [`${blockClass}__description--truncate`]: descTruncate === true,
      [`${blockClass}__description--truncate-multi`]: isDescMulti,
    });

    return html`
      <div class="${blockClass}__title">
        <!-- Label row (slot takes precedence over attr) -->
        <slot name="label">
          ${this.label
            ? html`<div class=${labelClasses} style=${styleMap(labelVars)}>
                ${this.label}
              </div>`
            : nothing}
        </slot>

        <!-- Title text row with optional leading/trailing icons -->
        <span class=${textRowClasses} style=${styleMap(titleVars)}>
          <slot name="title-start"></slot>
          <slot></slot>
          <slot name="title-end"></slot>
        </span>

        <!-- Description row (slot takes precedence over attr) -->
        <slot name="description">
          ${this.description
            ? html`<div class=${descClasses} style=${styleMap(descVars)}>
                ${this.description}
              </div>`
            : nothing}
        </slot>
      </div>
    `;
  }

  static styles = styles;
}

export default CDSCardTitle;
