// packages/web-components/src/components/slider/slider.ts
/**
 * Copyright IBM Corp. 2019, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property, query } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import throttle from 'lodash-es/throttle';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import FormMixin from '../../globals/mixins/form';
import HostListenerMixin from '../../globals/mixins/host-listener';
import HostListener from '../../globals/decorators/host-listener';
import CDSSliderInput from './slider-input';
import styles from './slider.scss?lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

interface Cancelable {
  cancel(): void;
}

/**
 * The direction to move the thumb, associated with key symbols.
 */
const THUMB_DIRECTION = {
  Left: -1,
  ArrowLeft: -1,
  Up: -1,
  ArrowUp: -1,
  Right: 1,
  ArrowRight: 1,
  Down: 1,
  ArrowDown: 1,
};

/**
 * Slider.
 *
 * @element cds-slider
 * @fires cds-slider-input-changed
 *   The name of the custom event fired after the value is changed in `<cds-slider-input>` by user gesture.
 * @slot label-text - The label text.
 * @slot max-text - The text for maximum value.
 * @slot min-text - The text for minimum value.
 * @fires cds-slider-changed - The custom event fired after the value is changed by user gesture.
 */
@customElement(`${prefix}-slider`)
class CDSSlider extends HostListenerMixin(FormMixin(FocusMixin(LitElement))) {
  /**
   * The internal value of `max` property.
   */
  private _max = '100';

  /**
   * The internal value of `min` property.
   */
  private _min = '0';

  /**
   * The internal value of `step` property.
   */
  private _step = '1';

  /**
   * The internal value of `stepMultiplier` property.
   */
  private _stepMultiplier = '4';

  /**
   * The handle for the throttled listener of `pointermove` event.
   */
  private _throttledHandlePointermoveImpl:
    | (((event: PointerEvent) => void) & Cancelable)
    | null = null;

  /**
   * `true` if dragging of thumb is in progress.
   */
  private _dragging = false;

  /**
   * The rate of the thumb position in the track.
   * When we try to set a new value, we adjust the value considering `step` property.
   */
  private get _rate() {
    const { max, min, value } = this;
    // Copes with out-of-range value coming programmatically or from `<cds-slider-input>`
    return (
      (Math.min(Number(max), Math.max(Number(min), value)) - Number(min)) /
      (Number(max) - Number(min))
    );
  }

  private set _rate(rate: number) {
    const { max, min, step } = this;
    this.value =
      Number(min) +
      Math.round(
        ((Number(max) - Number(min)) * Math.min(1, Math.max(0, rate))) /
          Number(step)
      ) *
        Number(step);
  }

  /**
   * The DOM element of the thumb.
   */
  @query('#thumb')
  private _thumbNode!: HTMLDivElement;

  /**
   * The DOM element of the track.
   */
  @query('#track')
  private _trackNode!: HTMLDivElement;

  /**
   * Handles `click` event on the `<label>` to focus on the thumb.
   */
  _handleClickLabel() {
    this._thumbNode?.focus();
  }

  _handleFormdata(event: FormDataEvent) {
    const { formData } = event;
    const { disabled, name, value } = this;
    if (!disabled) {
      formData.append(name, String(value));
    }
  }

  /**
   * Handles `keydown` event on the thumb to increase/decrease the value.
   */
  private _handleKeydown({ key, shiftKey }: KeyboardEvent) {
    if (!this.disabled) {
      if (key in THUMB_DIRECTION) {
        const {
          max: rawMax,
          min: rawMin,
          step: rawStep,
          stepMultiplier: rawstepMultiplier,
          value,
        } = this;
        const max = Number(rawMax);
        const min = Number(rawMin);
        const step = Number(rawStep);
        const stepMultiplier = Number(rawstepMultiplier);
        const diff =
          (!shiftKey ? step : (max - min) / stepMultiplier) *
          THUMB_DIRECTION[key];
        const stepCount = (value + diff) / step;
        // Snaps to next
        this.value = Math.min(
          max,
          Math.max(
            min,
            (diff >= 0 ? Math.floor(stepCount) : Math.ceil(stepCount)) * step
          )
        );
        this.dispatchEvent(
          new CustomEvent((this.constructor as typeof CDSSlider).eventChange, {
            bubbles: true,
            composed: true,
            detail: {
              value: this.value,
              intermediate: false,
            },
          })
        );
      }
    }
  }

  /**
   * Handles `pointerdown` event on the thumb to start dragging.
   */
  private _startDrag() {
    this._dragging = true;
    this._thumbNode.style.touchAction = 'none';
  }

  /**
   * Handles `pointerdown` event on the track to update the thumb position and the value as necessary.
   */
  private _handleClick(event: PointerEvent) {
    if (!this.disabled) {
      const { _trackNode: trackNode } = this;
      const isRtl =
        trackNode
          .ownerDocument!.defaultView!.getComputedStyle(trackNode)
          .getPropertyValue('direction') === 'rtl';
      const thumbPosition = event.clientX;
      const { left: trackLeft, width: trackWidth } =
        trackNode.getBoundingClientRect();
      this._rate =
        (isRtl
          ? trackLeft + trackWidth - thumbPosition
          : thumbPosition - trackLeft) / trackWidth;
      this.dispatchEvent(
        new CustomEvent((this.constructor as typeof CDSSlider).eventChange, {
          bubbles: true,
          composed: true,
          detail: {
            value: this.value,
          },
        })
      );
    }
  }

  /**
   * Handles `pointermove` to update the thumb position and the value as necessary.
   *
   * @param event The event.
   */
  @HostListener('document:pointermove')
  // @ts-ignore: The decorator refers to this method but TS thinks this method is not referred to
  private _handlePointermove = (event: PointerEvent) => {
    const { disabled, _dragging: dragging } = this;
    if (!disabled && dragging) {
      this._throttledHandlePointermoveImpl!(event);
    }
  };

  /**
   * Updates thumb position and value upon user's `pointermove` gesture.
   *
   * @param event The event.
   */
  private _handlePointermoveImpl(event: PointerEvent) {
    const { disabled, _dragging: dragging, _trackNode: trackNode } = this;
    if (!disabled && dragging) {
      const isRtl =
        trackNode
          .ownerDocument!.defaultView!.getComputedStyle(trackNode)
          .getPropertyValue('direction') === 'rtl';
      const thumbPosition = event.clientX;
      const { left: trackLeft, width: trackWidth } =
        this._trackNode.getBoundingClientRect();
      this._rate =
        (isRtl
          ? trackLeft + trackWidth - thumbPosition
          : thumbPosition - trackLeft) / trackWidth;
      this.dispatchEvent(
        new CustomEvent((this.constructor as typeof CDSSlider).eventChange, {
          bubbles: true,
          composed: true,
          detail: {
            value: this.value,
            intermediate: true,
          },
        })
      );
    }
  }

  /**
   * Handles `pointerup` and `pointerleave` event to finishing dragging.
   */
  private _endDrag = () => {
    if (this._dragging) {
      this.dispatchEvent(
        new CustomEvent((this.constructor as typeof CDSSlider).eventChange, {
          bubbles: true,
          composed: true,
          detail: {
            value: this.value,
          },
        })
      );
      this._dragging = false;
      this._thumbNode.style.touchAction = '';
    }
  };

  /**
   * Handles `${prefix}-slider-input-changed` event to update the value.
   */
  @HostListener('eventChangeInput')
  // @ts-ignore: The decorator refers to this method but TS thinks this method is not referred to
  private _handleChangeInput = ({ detail }: CustomEvent) => {
    const { intermediate, value } = detail;
    this.value = value;
    this.dispatchEvent(
      new CustomEvent((this.constructor as typeof CDSSlider).eventChange, {
        bubbles: true,
        composed: true,
        detail: {
          value,
          intermediate,
        },
      })
    );
  };

  /**
   * `true` if the check box should be disabled.
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /**
   * 	true to specify if the control is required.
   */
  @property({ type: Boolean, reflect: true })
  required = false;

  /**
   * 	Whether the slider should be read-only
   */
  @property({ type: Boolean, reflect: true })
  readonly = false;

  /**
   * The label text.
   */
  @property({ attribute: 'label-text' })
  labelText = '';

  /**
   * The label associated with the maximum value.
   */
  @property({ attribute: 'max-label', reflect: true })
  maxLabel = '';

  /**
   * The label associated with the minimum value.
   */
  @property({ attribute: 'min-label', reflect: true })
  minLabel = '';

  /**
   * Specify whether you want the underlying label to be visually hidden
   */
  @property({ attribute: 'hide-label', type: Boolean, reflect: true })
  hideLabel = false;

  /**
   * The formatter for the text for maximum value.
   * Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatMaxText = (max: string, maxLabel: string | undefined) =>
    `${max}${maxLabel}`;

  /**
   * The formatter for the text for min/max value.
   * Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatMinText = (min: string, minLabel: string | undefined) =>
    `${min}${minLabel}`;

  /**
   * The maximum value.
   */
  @property({ type: Number, reflect: true })
  get max() {
    return this._max.toString();
  }

  set max(value) {
    const { max: oldMax } = this;
    this._max = value;
    this.requestUpdate('max', oldMax);
  }

  /**
   * The minimum value.
   */
  @property({ type: Number, reflect: true })
  get min() {
    return this._min.toString();
  }

  set min(value) {
    const { min: oldMin } = this;
    this._min = value;
    this.requestUpdate('min', oldMin);
  }

  /**
   * The form name.
   */
  @property()
  name!: string;

  /**
   * true to specify if the control is invalid.
   */
  @property({ type: Boolean, reflect: true })
  invalid = false;

  /**
   * Message which is displayed if the value is invalid.
   */
  @property({ attribute: 'invalid-text' })
  invalidText = '';

  /**
   * true to specify if the control should display warn icon and text.
   */
  @property({ type: Boolean, reflect: true })
  warn = false;

  /**
   * Provide the text that is displayed when the control is in warning state
   */
  @property({ attribute: 'warn-text' })
  warnText = '';

  /**
   * The snapping step of the value.
   */
  @property({ type: Number, reflect: true })
  get step() {
    return this._step.toString();
  }

  set step(value) {
    const { step: oldStep } = this;
    this._step = value;
    this.requestUpdate('step', oldStep);
  }

  /**
   * A value determining how much the value should increase/decrease by Shift+arrow keys,
   * which will be `(max - min) / stepMultiplier`.
   */
  @property({ type: Number, reflect: true, attribute: 'step-multiplier' })
  get stepMultiplier() {
    return this._stepMultiplier.toString();
  }

  set stepMultiplier(value) {
    const { stepMultiplier: oldstepMultiplier } = this;
    this._stepMultiplier = value;
    this.requestUpdate('stepMultiplier', oldstepMultiplier);
  }

  /**
   * The value.
   */
  @property({ type: Number })
  value;

  /**
   * is slide input valid
   */
  @property({ type: Boolean })
  isValid;

  _getInputValidity(input) {
    if (this.invalid) {
      return false;
    }

    if (
      input?.valueAsNumber > Number(this.max) ||
      input?.valueAsNumber < Number(this.min)
    ) {
      return false;
    }
    return true;
  }

  connectedCallback() {
    super.connectedCallback();
    if (!this._throttledHandlePointermoveImpl) {
      this._throttledHandlePointermoveImpl = throttle(
        this._handlePointermoveImpl,
        10
      );
    }
  }

  disconnectedCallback() {
    if (this._throttledHandlePointermoveImpl) {
      this._throttledHandlePointermoveImpl.cancel();
      this._throttledHandlePointermoveImpl = null;
    }
    super.disconnectedCallback();
  }

  shouldUpdate(changedProperties) {
    const input = this.querySelector(
      (this.constructor as typeof CDSSlider).selectorInput
    ) as CDSSliderInput;
    if (changedProperties.has('disabled')) {
      if (input) {
        input.disabled = this.disabled;
      }
      if (this.disabled) {
        this._dragging = false;
      }
    }
    if (changedProperties.has('readonly')) {
      if (input) {
        input.readonly = this.readonly;
      }
      if (this.readonly) {
        this._dragging = false;
      }
    }
    if (input) {
      ['max', 'min', 'step', 'value'].forEach((name) => {
        if (changedProperties.has(name)) {
          input[name] = this[name];
        }
      });

      if (
        changedProperties.has('value') ||
        changedProperties.has('invalid') ||
        changedProperties.has('warn') ||
        changedProperties.has('readonly')
      ) {
        const innerInput = input?.shadowRoot?.querySelector('input');

        this.isValid = this._getInputValidity(innerInput);

        if (!this.readonly && !this.isValid) {
          input.invalid = true;
        } else {
          input.invalid = false;
        }

        if (!this.readonly && !this.invalid && this.warn && this.isValid) {
          input.warn = true;
        } else {
          input.warn = false;
        }
      }
    }
    return true;
  }

  render() {
    const {
      disabled,
      formatMaxText,
      formatMinText,
      labelText,
      hideLabel,
      max,
      min,
      maxLabel,
      minLabel,
      readonly,
      invalidText,
      isValid,
      warn,
      warnText,
      value,
      _rate: rate,
      _handleClickLabel: handleClickLabel,
      _handleKeydown: handleKeydown,
      _handleClick: handleClick,
      _startDrag: startDrag,
      _endDrag: endDrag,
    } = this;

    const labelClasses = classMap({
      [`${prefix}--label`]: true,
      [`${prefix}--visually-hidden`]: hideLabel,
      [`${prefix}--label--disabled`]: disabled,
    });
    const sliderClasses = classMap({
      [`${prefix}--slider`]: true,
      [`${prefix}--slider--disabled`]: disabled,
      [`${prefix}--slider--readonly`]: readonly,
    });

    return html`
      <label class="${labelClasses}" @click="${handleClickLabel}">
        <slot name="label-text">${labelText}</slot>
      </label>
      <div class="${prefix}--slider-container">
        <span class="${prefix}--slider__range-label">
          <slot name="min-text">${formatMinText(min, minLabel)}</slot>
        </span>
        <div
          @keydown="${handleKeydown}"
          @click="${handleClick}"
          @pointerup="${endDrag}"
          @pointerleave="${endDrag}"
          class="${sliderClasses}"
          tabindex="-1"
          role="presentation">
          <div
            id="thumb"
            class="${prefix}--slider__thumb"
            role="slider"
            tabindex="${!readonly ? 0 : -1}"
            aria-valuemax="${max}"
            aria-valuemin="${min}"
            aria-valuenow="${value}"
            style="left: ${rate * 100}%"
            @pointerdown="${startDrag}"></div>
          <div id="track" class="${prefix}--slider__track"></div>
          <div class="${prefix}-ce--slider__filled-track-container">
            <div
              class="${prefix}--slider__filled-track"
              style="transform: translate(0%, -50%) scaleX(${rate})"></div>
          </div>
        </div>
        <span class="${prefix}--slider__range-label">
          <slot name="max-text">${formatMaxText(max, maxLabel)}</slot>
        </span>
        <slot></slot>
      </div>

      ${!readonly && !isValid
        ? html`
            <div
              class="${prefix}--slider__validation-msg ${prefix}--slider__validation-msg--invalid ${prefix}--form-requirement">
              ${invalidText}
            </div>
          `
        : null}
      ${!readonly && warn && isValid
        ? html`<div
            class="${prefix}--slider__validation-msg ${prefix}--form-requirement">
            ${warnText}
          </div>`
        : null}
    `;
  }

  /**
   * A selector that will return the `<input>` box got entering the value directly.
   */
  static get selectorInput() {
    return `${prefix}-slider-input`;
  }

  /**
   * The name of the custom event fired after the value is changed by user gesture.
   */
  static get eventChange() {
    return `${prefix}-slider-changed`;
  }

  /**
   * The name of the custom event fired after the value is changed in `<cds-slider-input>` by user gesture.
   */
  static get eventChangeInput() {
    return `${prefix}-slider-input-changed`;
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static styles = styles;
}

export default CDSSlider;

// packages/react/src/components/Slider/Slider.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { KeyboardEventHandler, PureComponent } from 'react';
import PropTypes, { ReactNodeLike } from 'prop-types';

import classNames from 'classnames';
import throttle from 'lodash.throttle';

import * as keys from '../../internal/keyboard/keys';
import { matches } from '../../internal/keyboard/match';
import { PrefixContext } from '../../internal/usePrefix';
import deprecate from '../../prop-types/deprecate';
import { FeatureFlagContext } from '../FeatureFlags';
import { WarningFilled, WarningAltFilled } from '@carbon/icons-react';

const defaultFormatLabel = (value, label) => {
  return typeof label === 'function' ? label(value) : `${value}${label}`;
};

/**
 * Minimum time between processed "drag" events.
 */
const EVENT_THROTTLE = 16; // ms

/**
 * Event types that trigger "drags".
 */
const DRAG_EVENT_TYPES = new Set(['mousemove', 'touchmove']);

/**
 * Event types that trigger a "drag" to stop.
 */
const DRAG_STOP_EVENT_TYPES = new Set(['mouseup', 'touchend', 'touchcancel']);

type ExcludedAttributes = 'onChange' | 'onBlur';
export interface SliderProps
  extends Omit<
    React.InputHTMLAttributes<HTMLInputElement>,
    ExcludedAttributes
  > {
  /**
   * The `ariaLabel` for the `<input>`.
   */
  ariaLabelInput?: string;

  /**
   * The child nodes.
   */
  children?: ReactNodeLike;

  /**
   * The CSS class name for the slider, set on the wrapping div.
   */
  className?: string;

  /**
   * `true` to disable this slider.
   */
  disabled?: boolean;

  /**
   * The callback to format the label associated with the minimum/maximum value.
   */
  formatLabel?: (value: number, label: string | undefined) => string;

  /**
   * `true` to hide the number input box.
   */
  hideTextInput?: boolean;

  /**
   * The ID of the `<input>`.
   */
  id?: string;

  /**
   * The `type` attribute of the `<input>`.
   */
  inputType?: string;

  /**
   * `Specify whether the Slider is currently invalid
   */
  invalid?: boolean;

  /**
   * Provide the text that is displayed when the Slider is in an invalid state
   */
  invalidText?: React.ReactNode;

  /**
   * The label for the slider.
   */
  labelText?: ReactNodeLike;

  /**
   * @deprecated
   * `true` to use the light version.
   */
  light?: boolean;

  /**
   * The maximum value.
   */
  max: number;

  /**
   * The label associated with the maximum value.
   */
  maxLabel?: string;

  /**
   * The minimum value.
   */
  min: number;

  /**
   * The label associated with the minimum value.
   */
  minLabel?: string;

  /**
   * The `name` attribute of the `<input>`.
   */
  name?: string;

  /**
   * Provide an optional function to be called when the input element
   * loses focus
   */
  onBlur?: (data: { value: string }) => void;

  /**
   * The callback to get notified of change in value.
   * `({ value}) => void`
  //  * @param {{ value }}
   */
  onChange?: (data: { value: SliderProps['value'] }) => void;

  /**
   * Provide an optional function to be called when a key is pressed in the number input
   */
  onInputKeyUp?: KeyboardEventHandler<HTMLInputElement>;

  /**
   * The callback to get notified of value on handle release.
   */
  onRelease?: (data: { value: SliderProps['value'] }) => void;

  /**
   * Whether the slider should be read-only
   */
  readOnly?: boolean;

  /**
   * `true` to specify if the control is required.
   */
  required?: boolean;

  /**
   * A value determining how much the value should increase/decrease by moving the thumb by mouse. If a value other than 1 is provided and the input is *not* hidden, the new step requirement should be added to a visible label. Values outside of the `step` increment will be considered invalid.
   */
  step?: number;

  /**
   * A value determining how much the value should increase/decrease by Shift+arrow keys,
   * which will be `(max - min) / stepMultiplier`.
   */
  stepMultiplier?: number;

  /**
   * Turn the slider into a range slider.
   */
  twoHandles?: boolean;

  /**
   * The value.
   */
  value: number;

  /**
   * Specify whether the control is currently in warning state
   */
  warn?: boolean;

  /**
   * Provide the text that is displayed when the control is in warning state
   */
  warnText?: React.ReactNode;
}

interface CalcValueProps {
  clientX?: number;
  value?: number;
  useRawValue?: boolean;
}

export default class Slider extends PureComponent<SliderProps> {
  static propTypes = {
    /**
     * The `ariaLabel` for the `<input>`.
     */
    ariaLabelInput: PropTypes.string,

    /**
     * The child nodes.
     */
    children: PropTypes.node,

    /**
     * The CSS class name for the slider.
     */
    className: PropTypes.string,

    /**
     * `true` to disable this slider.
     */
    disabled: PropTypes.bool,

    /**
     * The callback to format the label associated with the minimum/maximum value.
     */
    formatLabel: PropTypes.func,

    /**
     * `true` to hide the number input box.
     */
    hideTextInput: PropTypes.bool,

    /**
     * The ID of the `<input>`.
     */
    id: PropTypes.string,

    /**
     * The `type` attribute of the `<input>`.
     */
    inputType: PropTypes.string,

    /**
     * `Specify whether the Slider is currently invalid
     */
    invalid: PropTypes.bool,

    /**
     * Provide the text that is displayed when the Slider is in an invalid state
     */
    invalidText: PropTypes.node,

    /**
     * The label for the slider.
     */
    labelText: PropTypes.node,

    /**
     * `true` to use the light version.
     */
    light: deprecate(
      PropTypes.bool,
      'The `light` prop for `Slider` is no longer needed and has ' +
        'been deprecated in v11 in favor of the new `Layer` component. It will be moved in the next major release.'
    ),

    /**
     * The maximum value.
     */
    max: PropTypes.number.isRequired,

    /**
     * The label associated with the maximum value.
     */
    maxLabel: PropTypes.string,

    /**
     * The minimum value.
     */
    min: PropTypes.number.isRequired,

    /**
     * The label associated with the minimum value.
     */
    minLabel: PropTypes.string,

    /**
     * The `name` attribute of the `<input>`.
     */
    name: PropTypes.string,

    /**
     * Provide an optional function to be called when the input element
     * loses focus
     */
    onBlur: PropTypes.func,

    /**
     * The callback to get notified of change in value.
     */
    onChange: PropTypes.func,

    /**
     * Provide an optional function to be called when a key is pressed in the number input
     */
    onInputKeyUp: PropTypes.func,

    /**
     * The callback to get notified of value on handle release.
     */
    onRelease: PropTypes.func,

    /**
     * Whether the slider should be read-only
     */
    readOnly: PropTypes.bool,

    /**
     * `true` to specify if the control is required.
     */
    required: PropTypes.bool,

    /**
     * A value determining how much the value should increase/decrease by moving the thumb by mouse. If a value other than 1 is provided and the input is *not* hidden, the new step requirement should be added to a visible label. Values outside of the `step` increment will be considered invalid.
     */
    step: PropTypes.number,

    /**
     * A value determining how much the value should increase/decrease by Shift+arrow keys,
     * which will be `(max - min) / stepMultiplier`.
     */
    stepMultiplier: PropTypes.number,

    twoHandles: PropTypes.bool,

    /**
     * The value.
     */
    value: PropTypes.number.isRequired,

    /**
     * `Specify whether the Slider is in a warn state
     */
    warn: PropTypes.bool,

    /**
     * Provide the text that is displayed when the Slider is in an warn state
     */
    warnText: PropTypes.node,
  };

  static defaultProps = {
    hideTextInput: false,
    step: 1,
    stepMultiplier: 4,
    disabled: false,
    minLabel: '',
    maxLabel: '',
    inputType: 'number',
    readOnly: false,
    twoHandles: false,
  };

  static contextType = FeatureFlagContext;

  state = {
    value: this.props.value,
    left: 0,
    needsOnRelease: false,
    isValid: true,
  };

  thumbRef: React.RefObject<HTMLDivElement>;
  filledTrackRef: React.RefObject<HTMLDivElement>;
  element: HTMLDivElement | null = null;
  inputId = '';
  track: HTMLDivElement | null | undefined;

  constructor(props) {
    super(props);
    this.thumbRef = React.createRef<HTMLDivElement>();
    this.filledTrackRef = React.createRef<HTMLDivElement>();
  }

  /**
   * Sets up initial slider position and value in response to component mount.
   */
  componentDidMount() {
    if (this.element) {
      const { value, left } = this.calcValue({
        useRawValue: true,
      });
      this.setState({ value, left });
    }
  }

  /**
   * Handles firing of `onChange` and `onRelease` callbacks to parent in
   * response to state changes.
   *
   * @param {*} prevProps prevProps
   * @param {*} prevState The previous Slider state, used to see if callbacks
   * should be called.
   */
  componentDidUpdate(prevProps, prevState) {
    // Fire onChange event handler if present, if there's a usable value, and
    // if the value is different from the last one

    if (this.thumbRef.current) {
      this.thumbRef.current.style.left = `${this.state.left}%`;
    }
    if (this.filledTrackRef.current) {
      this.filledTrackRef.current.style.transform = `translate(0%, -50%) scaleX(${
        this.state.left / 100
      })`;
    }
    if (
      prevState.value !== this.state.value &&
      typeof this.props.onChange === 'function'
    ) {
      this.props.onChange({ value: this.state.value });
    }

    // Fire onRelease event handler if present and if needed
    if (
      this.state.needsOnRelease &&
      typeof this.props.onRelease === 'function'
    ) {
      this.props.onRelease({ value: this.state.value });
      // Reset the flag
      this.setState({ needsOnRelease: false });
    }

    // If value from props does not change, do nothing here.
    // Otherwise, do prop -> state sync without "value capping".
    if (
      prevProps.value === this.props.value &&
      prevProps.max === this.props.max &&
      prevProps.min === this.props.min
    ) {
      return;
    }
    this.setState(
      this.calcValue({
        value: this.props.value,
        useRawValue: true,
      })
    );
  }

  /**
   * Synonymous to ECMA2017+ `Math.clamp`.
   *
   * @param {number} val
   * @param {number} min
   * @param {number} max
   *
   * @returns `val` if `max>=val>=min`; `min` if `val<min`; `max` if `val>max`.
   */
  clamp(val, min, max) {
    return Math.max(min, Math.min(val, max));
  }

  /**
   * Sets up "drag" event handlers and calls `this.onDrag` in case dragging
   * started on somewhere other than the thumb without a corresponding "move"
   * event.
   *
   * @param {Event} evt The event.
   */
  onDragStart = (evt) => {
    // Do nothing if component is disabled
    if (this.props.disabled || this.props.readOnly) {
      return;
    }

    // Register drag stop handlers
    DRAG_STOP_EVENT_TYPES.forEach((element) => {
      this.element?.ownerDocument.addEventListener(element, this.onDragStop);
    });

    // Register drag handlers
    DRAG_EVENT_TYPES.forEach((element) => {
      this.element?.ownerDocument.addEventListener(element, this.onDrag);
    });

    // Perform first recalculation since we probably didn't click exactly in the
    // middle of the thumb
    this.onDrag(evt);
  };

  /**
   * Unregisters "drag" and "drag stop" event handlers and calls sets the flag
   * indicating that the `onRelease` callback should be called.
   */
  onDragStop = () => {
    // Do nothing if component is disabled
    if (this.props.disabled || this.props.readOnly) {
      return;
    }

    // Remove drag stop handlers
    DRAG_STOP_EVENT_TYPES.forEach((element) => {
      this.element?.ownerDocument.removeEventListener(element, this.onDragStop);
    });

    // Remove drag handlers
    DRAG_EVENT_TYPES.forEach((element) => {
      this.element?.ownerDocument.removeEventListener(element, this.onDrag);
    });

    // Set needsOnRelease flag so event fires on next update
    this.setState({ needsOnRelease: true, isValid: true });
  };

  /**
   * Handles a "drag" event by recalculating the value/thumb and setting state
   * accordingly.
   *
   * @param {Event} evt The event.
   */
  _onDrag = (evt) => {
    // Do nothing if component is disabled or we have no event
    if (this.props.disabled || this.props.readOnly || !evt) {
      return;
    }

    let clientX;
    if ('clientX' in evt) {
      clientX = evt.clientX;
    } else if (
      'touches' in evt &&
      0 in evt.touches &&
      'clientX' in evt.touches[0]
    ) {
      clientX = evt.touches[0].clientX;
    } else {
      // Do nothing if we have no valid clientX
      return;
    }

    const { value, left } = this.calcValue({ clientX });
    this.setState({ value, left, isValid: true });
  };

  /**
   * Throttles calls to `this._onDrag` by limiting events to being processed at
   * most once every `EVENT_THROTTLE` milliseconds.
   */
  onDrag = throttle(this._onDrag, EVENT_THROTTLE, {
    leading: true,
    trailing: false,
  });

  /**
   * Handles a `keydown` event by recalculating the value/thumb and setting
   * state accordingly.
   *
   * @param {Event} evt The event.
   */
  onKeyDown = (evt) => {
    // Do nothing if component is disabled or we don't have a valid event
    if (this.props.disabled || this.props.readOnly || !('which' in evt)) {
      return;
    }

    let delta = 0;
    if (matches(evt.which, [keys.ArrowDown, keys.ArrowLeft])) {
      delta = -(this.props.step ?? Slider.defaultProps.step);
    } else if (matches(evt.which, [keys.ArrowUp, keys.ArrowRight])) {
      delta = this.props.step ?? Slider.defaultProps.step;
    } else {
      // Ignore keys we don't want to handle
      return;
    }

    // If shift was held, account for the stepMultiplier
    if (evt.shiftKey) {
      const stepMultiplier = this.props.stepMultiplier;
      delta *= stepMultiplier ?? Slider.defaultProps.stepMultiplier;
    }

    Math.floor(
      this.state.value / (this.props.step ?? Slider.defaultProps.step)
    ) * (this.props.step ?? Slider.defaultProps.step);
    const { value, left } = this.calcValue({
      // Ensures custom value from `<input>` won't cause skipping next stepping point with right arrow key,
      // e.g. Typing 51 in `<input>`, moving focus onto the thumb and the hitting right arrow key should yield 52 instead of 54
      value:
        (delta > 0
          ? Math.floor(
              this.state.value / (this.props.step ?? Slider.defaultProps.step)
            ) * (this.props.step ?? Slider.defaultProps.step)
          : this.state.value) + delta,
    });

    this.setState({ value, left, isValid: true });
  };

  /**
   * Provides the two-way binding for the input field of the Slider. It also
   * Handles a change to the input field by recalculating the value/thumb and
   * setting state accordingly.
   *
   * @param {Event} evt The event.
   */

  onChange = (evt) => {
    // Do nothing if component is disabled
    if (this.props.disabled || this.props.readOnly) {
      return;
    }

    // Do nothing if we have no valid event, target, or value
    if (!evt || !('target' in evt) || typeof evt.target.value !== 'string') {
      return;
    }

    const targetValue = Number.parseFloat(evt.target.value);

    // Avoid calling calcValue for invalid numbers, but still update the state
    if (isNaN(targetValue)) {
      this.setState({ value: evt.target.value });
    } else {
      const { value, left } = this.calcValue({
        value: targetValue,
        useRawValue: true,
      });
      this.setState({
        value,
        left,
      });
    }
  };

  /**
   * Checks for validity of input value after clicking out of the input. It also
   * Handles state change to isValid state.
   *
   * @param {Event} evt The event.
   */
  onBlur = (evt: React.FocusEvent<HTMLInputElement>) => {
    // Do nothing if we have no valid event, target, or value
    if (!evt || !('target' in evt) || typeof evt.target.value !== 'string') {
      return;
    }

    // determine validity of input change after clicking out of input
    const validity = evt.target.checkValidity();
    const { value } = evt.target;

    this.setState({ isValid: validity });
    this.props.onBlur?.({ value });
  };

  /**
   * Calculates a new Slider `value` and `left` (thumb offset) given a `clientX`,
   * `value`, or neither of those.
   * - If `clientX` is specified, it will be used in
   *   conjunction with the Slider's bounding rectangle to calculate the new
   *   values.
   * - If `clientX` is not specified and `value` is, it will be used to
   *   calculate new values as though it were the current value of the Slider.
   * - If neither `clientX` nor `value` are specified, `this.props.value` will
   *   be used to calculate the new values as though it were the current value
   *   of the Slider.
   *
   * @param {object} params
   * @param {number} [params.clientX] Optional clientX value expected to be from
   *   an event fired by one of the Slider's `DRAG_EVENT_TYPES` events.
   * @param {number} [params.value] Optional value use during calculations if
   *   clientX is not provided.
   * @param {boolean} [params.useRawValue=false] `true` to use the given value as-is.
   */

  calcValue = ({ clientX, value, useRawValue = false }: CalcValueProps) => {
    const range = this.props.max - this.props.min;
    const boundingRect = this.element?.getBoundingClientRect?.();
    const totalSteps = range / (this.props.step ?? Slider.defaultProps.step);
    let width = boundingRect ? boundingRect.right - boundingRect.left : 0;

    // Enforce a minimum width of at least 1 for calculations
    if (width <= 0) {
      width = 1;
    }

    // If a clientX is specified, use it to calculate the leftPercent. If not,
    // use the provided value or state's value to calculate it instead.
    let leftPercent;
    if (clientX != null) {
      const leftOffset = clientX - (boundingRect?.left ?? 0);
      leftPercent = leftOffset / width;
    } else {
      if (value == null) {
        value = this.state.value;
      }
      // prevent NaN calculation if the range is 0
      leftPercent = range === 0 ? 0 : (value - this.props.min) / range;
    }

    if (useRawValue) {
      // Adjusts only for min/max of thumb position
      return {
        value,
        left: Math.min(1, Math.max(0, leftPercent)) * 100,
      };
    }

    let steppedValue =
      Math.round(leftPercent * totalSteps) *
      (this.props.step ?? Slider.defaultProps.step);
    const steppedPercent = this.clamp(steppedValue / range, 0, 1);

    steppedValue = this.clamp(
      steppedValue + this.props.min,
      this.props.min,
      this.props.max
    );

    return { value: steppedValue, left: steppedPercent * 100 };
  };

  // syncs invalid state and prop
  static getDerivedStateFromProps(props, state) {
    const { isValid } = state;
    // will override state in favor of invalid prop
    if (props.invalid === true && isValid === true) {
      return {
        isValid: false,
      };
    }

    if (props.invalid === false && isValid === false) {
      return {
        isValid: true,
      };
    }
    //if invalid prop is not provided, state will remain the same
    return null;
  }

  render() {
    const {
      ariaLabelInput,
      className,
      hideTextInput,
      id = (this.inputId =
        this.inputId ||
        `__carbon-slider_${Math.random().toString(36).substr(2)}`),
      min,
      minLabel,
      max,
      maxLabel,
      formatLabel = defaultFormatLabel,
      labelText,
      step,
      stepMultiplier: _stepMultiplier,
      inputType,
      invalidText,
      required,
      disabled,
      name,
      light,
      readOnly,
      warn,
      warnText,
      twoHandles,
      ...other
    } = this.props;

    delete other.onRelease;
    delete other.invalid;

    const { value, isValid } = this.state;

    return (
      <PrefixContext.Consumer>
        {(prefix) => {
          const labelId = `${id}-label`;
          const labelClasses = classNames(`${prefix}--label`, {
            [`${prefix}--label--disabled`]: disabled,
          });

          const sliderClasses = classNames(
            `${prefix}--slider`,
            { [`${prefix}--slider--disabled`]: disabled },
            { [`${prefix}--slider--readonly`]: readOnly }
          );

          const inputClasses = classNames(
            `${prefix}--text-input`,
            `${prefix}--slider-text-input`,
            {
              [`${prefix}--text-input--light`]: light,
              [`${prefix}--text-input--invalid`]:
                !readOnly && isValid === false,
              [`${prefix}--slider-text-input--hidden`]: hideTextInput,
              [`${prefix}--slider-text-input--warn`]: !readOnly && warn,
            }
          );

          return (
            <div className={classNames(`${prefix}--form-item`, className)}>
              <label htmlFor={id} className={labelClasses} id={labelId}>
                {labelText}
              </label>
              <div className={`${prefix}--slider-container`}>
                <span className={`${prefix}--slider__range-label`}>
                  {formatLabel(min, minLabel)}
                </span>
                {/* @ts-ignore onBlur + onChange types are incompatible*/}
                <div
                  className={sliderClasses}
                  ref={(node) => {
                    this.element = node;
                  }}
                  onMouseDown={this.onDragStart}
                  onTouchStart={this.onDragStart}
                  onKeyDown={this.onKeyDown}
                  role="presentation"
                  tabIndex={-1}
                  data-invalid={!isValid && !readOnly ? true : null}
                  {...other}>
                  <div
                    className={`${prefix}--slider__thumb ${prefix}--slider__thumb--lower`}
                    role="slider"
                    id={id}
                    tabIndex={!readOnly ? 0 : -1}
                    aria-valuemax={max}
                    aria-valuemin={min}
                    aria-valuenow={value}
                    aria-labelledby={labelId}
                    ref={this.thumbRef}
                  />
                  {twoHandles ? (
                    <div
                      className={`${prefix}--slider__thumb ${prefix}--slider__thumb--upper`}
                      role="slider"
                      id={id}
                      tabIndex={!readOnly ? 0 : -1}
                      aria-valuemax={max}
                      aria-valuemin={min}
                      aria-valuenow={value}
                      aria-labelledby={labelId}
                    />
                  ) : null}
                  <div
                    className={`${prefix}--slider__track`}
                    ref={(node) => {
                      this.track = node;
                    }}
                  />
                  <div
                    className={`${prefix}--slider__filled-track`}
                    ref={this.filledTrackRef}
                  />
                </div>
                <span className={`${prefix}--slider__range-label`}>
                  {formatLabel(max, maxLabel)}
                </span>
                <input
                  type={hideTextInput ? 'hidden' : inputType}
                  id={`${id}-input-for-slider`}
                  name={name}
                  className={inputClasses}
                  value={value}
                  aria-labelledby={!ariaLabelInput ? labelId : undefined}
                  aria-label={ariaLabelInput ? ariaLabelInput : undefined}
                  disabled={disabled}
                  required={required}
                  min={min}
                  max={max}
                  step={step}
                  onChange={this.onChange}
                  onBlur={this.onBlur}
                  onKeyUp={this.props.onInputKeyUp}
                  data-invalid={!isValid && !readOnly ? true : null}
                  aria-invalid={!isValid && !readOnly ? true : undefined}
                  readOnly={readOnly}
                />
                {!readOnly && isValid === false && (
                  <WarningFilled
                    className={`${prefix}--slider__invalid-icon`}
                  />
                )}

                {!readOnly && warn && isValid && (
                  <WarningAltFilled
                    className={`${prefix}--slider__invalid-icon ${prefix}--slider__invalid-icon--warning`}
                  />
                )}
              </div>
              {!readOnly && isValid === false && (
                <div
                  className={classNames(
                    `${prefix}--slider__validation-msg`,
                    `${prefix}--slider__validation-msg--invalid`,
                    `${prefix}--form-requirement`
                  )}>
                  {invalidText}
                </div>
              )}
              {!readOnly && warn && isValid && (
                <div
                  className={classNames(
                    `${prefix}--slider__validation-msg`,
                    `${prefix}--form-requirement`
                  )}>
                  {warnText}
                </div>
              )}
            </div>
          );
        }}
      </PrefixContext.Consumer>
    );
  }
}
