// packages/react/src/components/UserAvatar/UserAvatar.tsx
/**
 * Copyright IBM Corp. 2024, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Import portions of React that are needed.
import React from 'react';

// Other standard imports.
import cx from 'classnames';

import { usePrefix } from '../../internal/usePrefix';
import { Tooltip } from '../Tooltip';
import { PopoverAlignment } from '../Popover';
import { User } from '@carbon/icons-react';

// NOTE: the component SCSS is not imported here: it is rolled up separately.

const componentName = 'UserAvatar';

type BackgroundColor =
  | 'order-1-cyan'
  | 'order-2-gray'
  | 'order-3-green'
  | 'order-4-magenta'
  | 'order-5-purple'
  | 'order-6-teal'
  | 'order-7-cyan'
  | 'order-8-gray'
  | 'order-9-green'
  | 'order-10-magenta'
  | 'order-11-purple'
  | 'order-12-teal';
type Size = 'xl' | 'lg' | 'md' | 'sm';
type ImageProps =
  | {
      /**
       * When passing the image prop, supply a full path to the image to be displayed.
       */
      image: string;
      /**
       * When passing the image prop use the imageDescription prop to describe the image for screen reader.
       */
      imageDescription: string;
    }
  | {
      image?: never;
      imageDescription?: never;
    };

export type UserAvatarProps = {
  /**
   * Provide the background color need to be set for UserAvatar.
   */
  backgroundColor?: BackgroundColor;
  /**
   * Provide an optional class to be applied to the containing node.
   */
  className?: string;
  /**
   * When passing the name prop, either send the initials to be used or the
   * user's full name. The first two capital letters of the user's name will be
   * used as the name.
   */
  name?: string;
  /**
   * Provide a custom icon to use if you need to use an icon other than the
   * default one
   */
  renderIcon?: React.ElementType;
  /**
   * Set the size of the avatar circle
   */
  size?: Size;
  /**
   * Specify how the trigger should align with the tooltip
   */
  tooltipAlignment?: PopoverAlignment;
  /**
   * Pass in the display name to have it shown on hover
   */
  tooltipText?: string;
} & ImageProps;

export const UserAvatar = React.forwardRef<HTMLDivElement, UserAvatarProps>(
  (props, ref) => {
    const {
      backgroundColor = 'order-1-cyan',
      className,
      image,
      imageDescription,
      name,
      renderIcon: RenderIcon,
      size = 'md',
      tooltipAlignment = 'bottom',
      tooltipText,
      ...rest
    } = props;

    const prefix = usePrefix();
    const blockClass = `${prefix}--user-avatar`;

    const iconSize = {
      sm: 16,
      md: 20,
      lg: 24,
      xl: 32,
    };

    const formatInitials = () => {
      const parts = name?.split(' ') || [];
      const firstChar = parts[0].charAt(0).toUpperCase();
      const secondChar = parts[0].charAt(1).toUpperCase();
      if (parts.length === 1) {
        return firstChar + secondChar;
      }
      const lastChar = parts[parts.length - 1].charAt(0).toUpperCase();
      const initials = [firstChar];
      if (lastChar) {
        initials.push(lastChar);
      }
      return ''.concat(...initials);
    };

    const getItem = () => {
      const iconProps = { size: iconSize[size] };
      if (image) {
        return (
          <img
            alt={imageDescription}
            src={image}
            className={`${blockClass}__photo ${blockClass}__photo--${size}`}
          />
        );
      }
      if (RenderIcon) {
        return <RenderIcon {...iconProps} />;
      }
      if (name) {
        return formatInitials();
      }
      return <User {...iconProps} />;
    };

    const avatarNode = (
      <div
        {...rest}
        className={cx(
          blockClass,
          className,
          `${blockClass}--${backgroundColor}`,
          `${blockClass}--${size}`
        )}
        ref={ref}
        data-component-name={componentName}>
        {getItem()}
      </div>
    );

    if (tooltipText) {
      return (
        <Tooltip
          align={tooltipAlignment}
          label={tooltipText}
          className={`${blockClass}__tooltip ${prefix}--icon-tooltip`}>
          <button
            type="button"
            aria-label={tooltipText}
            className={`${blockClass}__tooltip-trigger`}>
            {avatarNode}
          </button>
        </Tooltip>
      );
    }
    return avatarNode;
  }
);

UserAvatar.displayName = componentName;

// packages/ibm-products-web-components/src/components/user-avatar/user-avatar.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { prefix, carbonPrefix } from '../../globals/settings';
import HostListenerMixin from '@carbon/web-components/es/globals/mixins/host-listener.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import styles from './user-avatar.scss?lit';
import '@carbon/web-components/es/components/tooltip/index.js';
import User from '@carbon/icons/es/user/16';
import { iconLoader } from '@carbon/web-components/es/globals/internal/icon-loader.js';

const blockClass = `${prefix}--user-avatar`;

/**
 * Useravatar.
 *
 * @element c4p-user-avatar
 * */

@customElement(`${prefix}-user-avatar`)
class CDSUseravatar extends HostListenerMixin(LitElement) {
  /**
   * Specify the text of the tooltip.
   * Can be string
   */
  @property({ reflect: true, attribute: 'tooltip-text' })
  tooltipText;

  /**
   * Specify the alignment of the tooltip.
   */
  @property({ reflect: true, attribute: 'tooltip-alignment' })
  tooltipAlignment = 'bottom';

  /**
   * When passing the name prop, either send the initials to be used or the user's full name. The first two capital letters of the user's name will be used as the name.
   */
  @property({ reflect: true })
  name;

  /**
   * Set the size of the avatar circle
   */
  @property({ reflect: true })
  size;

  /**
   * When passing the image prop, supply a full path to the image to be displayed.
   */
  @property({ reflect: true })
  image;
  /**
   * When passing the image prop use the imageDescription prop to describe the image for screen reader.
   */
  @property({ reflect: true, attribute: 'image-description' })
  imageDescription;

  /**
   * Provide the background color need to be set for UserAvatar.
   */
  @property({ reflect: true, attribute: 'background-color' })
  backgroundColor = 'order-1-cyan';

  /**
   * Set theme in which the component will be rendered.
   */
  @property({ reflect: true })
  theme;

  render() {
    const getItem = () => {
      if (this.image) {
        const imageClasses = classMap({
          [`${blockClass}__photo`]: true,
          [`${blockClass}__photo--${this.size}`]: this.size,
        });
        return html` <img
          alt="${this.imageDescription}"
          src="${this.image}"
          class="${imageClasses}"
        />`;
      }
      if (this.querySelector('[slot="rendericon"]')) {
        return html`<slot name="rendericon"></slot>`;
      }
      if (this.name) {
        const parts = this.name?.split(' ') || [];
        const firstChar = parts[0].charAt(0).toUpperCase();
        const secondChar = parts[0].charAt(1).toUpperCase();
        if (parts.length === 1) {
          return firstChar + secondChar;
        }
        const lastChar = parts[parts.length - 1].charAt(0).toUpperCase();
        const initials = [firstChar];
        if (lastChar) {
          initials.push(lastChar);
        }

        return ''.concat(...initials);
      }
      return html`${iconLoader(User, { slot: 'rendericon' })} `;
    };

    const { tooltipText, tooltipAlignment, size, backgroundColor, theme } =
      this;
    const classes = classMap({
      [`${blockClass}`]: true,
      [`${blockClass}--${size}`]: size,
      [`${blockClass}--${backgroundColor}`]: backgroundColor,
      [`${blockClass}--${theme}`]: theme,
    });

    const Avatar = () => html`<div class="${classes}">${getItem()}</div>`;

    if (tooltipText) {
      return html`<cds-tooltip
        align=${tooltipAlignment}
        aria-label=${tooltipText}
        class=${`${blockClass}__tooltip ${carbonPrefix}--icon-tooltip`}
      >
        <button class=${`${blockClass}__tooltip-trigger`} role="button">
          ${Avatar()}
        </button>
        <cds-tooltip-content
          class=${`${blockClass}__tooltip-content`}
          id="content"
        >
          ${tooltipText}
        </cds-tooltip-content>
      </cds-tooltip>`;
    } else {
      return html` ${Avatar()}`;
    }
  }
  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static styles = styles;
}
export default CDSUseravatar;
