// web-components/packages/carbon-web-components/src/components/loading/loading-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { boolean, select } from '@storybook/addon-knobs';
import { ifDefined } from 'lit/directives/if-defined.js';
import { LOADING_TYPE } from './loading';
import storyDocs from './loading-story.mdx';

const types = {
  [`Regular (${LOADING_TYPE.REGULAR})`]: null,
  [`Small (${LOADING_TYPE.SMALL})`]: LOADING_TYPE.SMALL,
  [`With overlay (${LOADING_TYPE.OVERLAY})`]: LOADING_TYPE.OVERLAY,
};

export const Default = (args) => {
  const { inactive, type } = args?.['bx-loading'] ?? {};
  return html`
    <bx-loading ?inactive=${inactive} type=${ifDefined(type)}></bx-loading>
  `;
};

Default.storyName = 'Default';

export default {
  title: 'Components/Loading',
  parameters: {
    ...storyDocs.parameters,
    knobs: {
      'bx-loading': () => ({
        inactive: boolean('Inactive (inactive)', false),
        type: select('The spinner type (type)', types, null),
      }),
    },
  },
};

// packages/react/src/components/Loading/Loading-story.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { withKnobs, boolean, text } from '@storybook/addon-knobs';
import Loading from '../Loading';

const props = () => ({
  active: boolean('Active (active)', true),
  withOverlay: boolean('With overlay (withOverlay)', false),
  small: boolean('Small (small)', false),
  description: text('Description (description)', 'Loading'),
});

export default {
  title: 'Components/Loading',
  component: Loading,
  decorators: [withKnobs],
};

export const Default = () => {
  return <Loading {...props()} className={'some-class'} />;
};

export const Playground = (args) => <Loading {...args} />;

Playground.args = {
  ...props(),
};

Playground.argTypes = {
  active: {
    control: {
      type: 'boolean',
    },
    defaultValue: false,
  },
  withOverlay: {
    control: {
      type: 'boolean',
    },
    defaultValue: false,
  },
  small: {
    control: {
      type: 'boolean',
    },
    defaultValue: true,
  },
  description: {
    control: {
      type: 'text',
    },
  },
  id: {
    control: {
      type: 'text',
    },
  },
};
