// packages/web-components/src/components/checkbox/checkbox-skeleton.ts
/**
 * Copyright IBM Corp. 2019, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './checkbox.scss?lit';

/**
 * Skeleton of number input.
 */
class CDSCheckboxSkeleton extends LitElement {
  static is = `${prefix}-checkbox-skeleton`;

  render() {
    return html`
      <label class="${prefix}--checkbox-label" for="checkbox" part="label">
        <span class="${prefix}--checkbox-label-text ${prefix}--skeleton"
          ><slot></slot
        ></span>
      </label>
    `;
  }

  static styles = styles;
}

export default CDSCheckboxSkeleton;

// packages/react/src/components/Checkbox/Checkbox.Skeleton.jsx
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';

const CheckboxSkeleton = ({ className, ...rest }) => {
  const prefix = usePrefix();
  return (
    <div
      className={cx(
        `${prefix}--form-item`,
        `${prefix}--checkbox-wrapper`,
        `${prefix}--checkbox-label`,
        className
      )}
      {...rest}>
      <span className={`${prefix}--checkbox-label-text ${prefix}--skeleton`} />
    </div>
  );
};

CheckboxSkeleton.propTypes = {
  /**
   * Specify an optional className to add.
   */
  className: PropTypes.string,
};

export default CheckboxSkeleton;
