// web-components/packages/carbon-web-components/src/components/skeleton-placeholder/skeleton-placeholder-story-angular.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { moduleMetadata } from '@storybook/angular';
import baseStory, { Default as baseDefault } from './skeleton-placeholder-story';

export const Default = () => ({
  template: `
    <bx-skeleton-placeholder></bx-skeleton-placeholder>
  `,
});

Object.assign(Default, baseDefault);

export default Object.assign(baseStory, {
  decorators: [
    moduleMetadata({
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
    }),
  ],
});

// web-components/packages/carbon-web-components/src/components/skeleton-placeholder/skeleton-placeholder-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import './skeleton-placeholder';
import storyDocs from './skeleton-placeholder-story.mdx';

export const Default = () =>
  html` <bx-skeleton-placeholder></bx-skeleton-placeholder> `;

Default.storyName = 'Default';

Default.parameters = {
  percy: {
    skip: true,
  },
};

export default {
  title: 'Components/Skeleton placeholder',
  parameters: {
    ...storyDocs.parameters,
  },
};
