// web-components/packages/carbon-web-components/src/components/tabs/tabs-skeleton.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import settings from 'carbon-components/es/globals/js/settings';
import styles from './tabs.scss';

const { prefix } = settings;

/**
 * Skeleton of tabs.
 */
@customElement(`${prefix}-tabs-skeleton`)
class BXTabsSkeleton extends LitElement {
  render() {
    return html`
      <div class="${prefix}--tabs-trigger">
        <span class="${prefix}--tabs-trigger-text"></span>
      </div>
      <ul class="${prefix}--tabs__nav">
        <slot></slot>
      </ul>
    `;
  }

  static styles = styles;
}

export default BXTabsSkeleton;

// packages/react/src/components/Tabs/Tabs.Skeleton.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { settings } from '@rocketsoftware/carbon-components';

const { prefix } = settings;

export default class TabsSkeleton extends React.Component {
  render() {
    const tab = (
      <li className={`${prefix}--tabs__nav-item`}>
        <div className={`${prefix}--tabs__nav-link`}>&nbsp;</div>
      </li>
    );
    return (
      <div className={`${prefix}--tabs ${prefix}--skeleton`}>
        <div className={`${prefix}--tabs-trigger`}>
          <div className={`${prefix}--tabs-trigger-text`}>&nbsp;</div>
          <svg width="10" height="5" viewBox="0 0 10 5" fillRule="evenodd">
            <path d="M10 0L5 5 0 0z" />
          </svg>
        </div>
        <ul className={`${prefix}--tabs__nav ${prefix}--tabs__nav--hidden`}>
          <li
            className={`${prefix}--tabs__nav-item ${prefix}--tabs__nav-item--selected`}>
            <div className={`${prefix}--tabs__nav-link`}> &nbsp;</div>
          </li>
          {tab}
          {tab}
          {tab}
        </ul>
      </div>
    );
  }
}
