// web-components/packages/carbon-web-components/src/components/date-picker/date-picker-story.ts
/**
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { action } from '@storybook/addon-actions';
import { boolean, select } from '@storybook/addon-knobs';
import { prefix } from '../../globals/settings';
import textNullable from '../../../.storybook/knob-text-nullable';
import { INPUT_SIZE } from '../text-input/text-input';
import './date-picker';
import storyDocs from './date-picker-story.mdx';
import './date-picker-input-skeleton';
import '../layer/index';

const sizes = {
  [`Small (${INPUT_SIZE.SMALL})`]: INPUT_SIZE.SMALL,
  [`Medium (${INPUT_SIZE.MEDIUM})`]: INPUT_SIZE.MEDIUM,
  [`Large (${INPUT_SIZE.LARGE})`]: INPUT_SIZE.LARGE,
};

const knobs = {
  [`${prefix}-date-picker`]: () => ({
    dateFormat: textNullable('Date format (date-format)', 'm/d/Y'),
    disabled: boolean('Disabled (disabled)', false),
    allowInput: boolean('Allow input (allow-input)', true),
    closeOnSelect: boolean('Close on select (close-on-select)', true),
    minDate: textNullable('Minimum date in ISO8601 date format (min-date)', ''),
    maxDate: textNullable('Maximum date in ISO8601 date format (max-date)', ''),
    onChange: action(`${prefix}-date-picker-changed`),
  }),
  [`${prefix}-date-picker-input`]: () => ({
    datePickerType: select(
      'Date picker type (date-picker-type)',
      { Single: 'single', Simple: 'simple', Range: 'range' },
      'single'
    ),
    readonly: boolean('ReadOnly (readonly)', false),
    short: boolean('Short (short)', false),
    helperText: textNullable('Helper text (helper-text)', ''),
    warning: boolean('Warning  (warning)', false),
    warningText: textNullable('Warning text (warning-text)', ''),
    invalid: boolean('Invalid  (invalid)', false),
    invalidText: textNullable('Invalid text (invalid-text)', ''),
    placeholder: textNullable('Placeholder text (placeholder)', 'mm/dd/yyyy'),
    size: select('Size (size)', sizes, INPUT_SIZE.MEDIUM),
    onInput: action('input'),
  }),
};
export const Simple = () => {
  return html`
    <cds-date-picker>
      <cds-date-picker-input
        label-text="Date Picker label"
        placeholder="mm/dd/yyyy">
      </cds-date-picker-input>
    </cds-date-picker>
  `;
};

export const SimpleWithLayer = () => {
  return html`
  <sb-template-layers>
    <cds-date-picker>
    <cds-date-picker-input
      label-text="Date Picker label"
      placeholder="mm/dd/yyyy">
    </cds-date-picker-input>
  </sb-template-layers>
  `;
};

export const singleWithCalendar = () => {
  return html`
    <cds-date-picker>
      <cds-date-picker-input
        kind="single"
        label-text="Date Picker label"
        placeholder="mm/dd/yyyy">
      </cds-date-picker-input>
    </cds-date-picker>
  `;
};

singleWithCalendar.storyName = 'Single with calendar';

export const singleWithCalendarWithLayer = () => {
  return html`
    <sb-template-layers>
      <cds-date-picker>
        <cds-date-picker-input
          kind="single"
          label-text="Date Picker label"
          placeholder="mm/dd/yyyy">
        </cds-date-picker-input>
      </cds-date-picker>
    </sb-template-layers>
  `;
};

singleWithCalendarWithLayer.storyName = 'Single with calendar with layer';

export const rangeWithCalendar = () => {
  return html`
    <cds-date-picker>
      <cds-date-picker-input
        kind="from"
        label-text="Start date"
        placeholder="mm/dd/yyyy">
      </cds-date-picker-input>
      <cds-date-picker-input
        kind="to"
        label-text="End date"
        placeholder="mm/dd/yyyy">
      </cds-date-picker-input>
    </cds-date-picker>
  `;
};

rangeWithCalendar.storyName = 'Range with calendar';

export const rangeWithCalendarWithLayer = () => {
  return html`
    <cds-layer>
      <cds-date-picker>
        <cds-date-picker-input
          kind="from"
          label-text="Start date"
          placeholder="mm/dd/yyyy">
        </cds-date-picker-input>
        <cds-date-picker-input
          kind="to"
          label-text="End date"
          placeholder="mm/dd/yyyy">
        </cds-date-picker-input>
      </cds-date-picker>
      <cds-layer>
        <cds-date-picker>
          <cds-date-picker-input
            kind="from"
            label-text="Start date"
            placeholder="mm/dd/yyyy">
          </cds-date-picker-input>
          <cds-date-picker-input
            kind="to"
            label-text="End date"
            placeholder="mm/dd/yyyy">
          </cds-date-picker-input>
        </cds-date-picker>
        <cds-layer>
          <cds-date-picker>
            <cds-date-picker-input
              kind="from"
              label-text="Start date"
              placeholder="mm/dd/yyyy">
            </cds-date-picker-input>
            <cds-date-picker-input
              kind="to"
              label-text="End date"
              placeholder="mm/dd/yyyy">
            </cds-date-picker-input>
          </cds-date-picker>
        </cds-layer>
      </cds-layer>
    </cds-layer>
  `;
};

rangeWithCalendarWithLayer.storyName = 'Range with calendar with layer';

export const Skeleton = () =>
  html`
    <cds-date-picker-input-skeleton
      kind="from"></cds-date-picker-input-skeleton>
    <cds-date-picker-input-skeleton kind="to"></cds-date-picker-input-skeleton>
  `;

Skeleton.storyName = 'Skeleton';

Skeleton.decorators = [(story) => html` <div>${story()}</div> `];

Skeleton.parameters = {
  percy: {
    skip: true,
  },
};

export const Playground = (args) => {
  const { disabled, dateFormat, onChange, minDate, maxDate } =
    args?.['cds-date-picker'] || {};
  const {
    size,
    helperText,
    placeholder,
    invalid,
    invalidText,
    warning,
    warningText,
    short,
    datePickerType,
    readonly,
    onInput,
  } = args?.['cds-date-picker-input'] || {};

  return html`
    <cds-date-picker
      ?disabled="${disabled}"
      date-format="${dateFormat}"
      ?readonly="${readonly}"
      min-date="${minDate}"
      max-date="${maxDate}"
      @cds-date-picker-changed="${onChange}">
      ${datePickerType === 'range'
        ? html`
            <cds-date-picker-input
              kind="from"
              label-text="Date Picker label"
              size="${size}"
              placeholder="${placeholder}"
              ?invalid="${invalid}"
              invalid-text="${invalidText}"
              ?short="${short}"
              ?warn="${warning}"
              warn-text="${warningText}"
              @input="${onInput}">
              ${helperText
                ? html`<span slot="helper-text">${helperText}</span>`
                : html``}
            </cds-date-picker-input>
            <cds-date-picker-input
              kind="to"
              label-text="Date Picker label"
              size="${size}"
              placeholder="${placeholder}"
              ?invalid="${invalid}"
              invalid-text="${invalidText}"
              ?short="${short}"
              ?warn="${warning}"
              warn-text="${warningText}"
              @input="${onInput}">
              ${helperText
                ? html`<span slot="helper-text">${helperText}</span>`
                : html``}
            </cds-date-picker-input>
          `
        : html`
            <cds-date-picker-input
              kind="${datePickerType}"
              label-text="Date Picker label"
              size="${size}"
              placeholder="${placeholder}"
              ?invalid="${invalid}"
              invalid-text="${invalidText}"
              ?short="${short}"
              ?warn="${warning}"
              warn-text="${warningText}"
              @input="${onInput}">
              ${helperText
                ? html`<span slot="helper-text">${helperText}</span>`
                : html``}
            </cds-date-picker-input>
          `}
    </cds-date-picker>
  `;
};

Playground.storyName = 'Playground';

Playground.decorators = [(story) => html` <div>${story()}</div> `];

Playground.parameters = {
  knobs,
};

export default {
  title: 'Components/Date picker',
  parameters: {
    ...storyDocs.parameters,
  },
};

// packages/react/src/components/DatePicker/next/DatePicker-story.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import {
  withKnobs,
  boolean,
  select,
  text,
  array,
} from '@storybook/addon-knobs';
import { action } from '@storybook/addon-actions';
import DatePicker from '../DatePicker';
import DatePickerInput from '../DatePickerInput';
import DatePickerSkeleton from '../DatePicker/DatePicker.Skeleton';
import mdx from './DatePicker.mdx';

const patterns = {
  'Short (d{1,2}/d{4})': '\\d{1,2}/\\d{4}',
  'Regular (d{1,2}/d{1,2}/d{4})': '\\d{1,2}/\\d{1,2}/\\d{4}',
};

const sizes = {
  'Small  (sm)': 'sm',
  'Medium (md) - default': undefined,
  'Large  (lg)': 'lg',
};

const types = {
  Simple: 'simple',
  Single: 'single',
  Range: 'range',
};

const props = {
  datePicker: () => ({
    dateFormat: text('The date format (dateFormat in <DatePicker>)', 'm/d/Y'),
    id: 'date-picker',
    light: boolean('Light variant (light in <DatePicker>)', false),
    datePickerType: select(
      'Date Picker Type (datePickerType)',
      types,
      'single'
    ),
    minDate: text('Disable dates before this date (minDate)', '11/15/2020'),
    maxDate: text('Disabled dates after this date (maxDate)', '11/01/2040'),
    disable: array('Disable specific dates (disable)', ['07/15/2021'], ','),
    onClose: action('onClose'),
    onOpen: action('onOpen'),
    onChange: action('onChange'),
  }),
  datePickerInput: () => ({
    id: 'date-picker-input-id',
    className: 'some-class',
    size: select('Field size (size)', sizes, undefined) || undefined,
    labelText: text(
      'Label text (labelText in <DatePickerInput>)',
      'Date Picker label'
    ),
    pattern: select(
      'The date format (pattern in <DatePickerInput>)',
      patterns,
      'd{1,2}/d{4}'
    ),
    placeholder: text(
      'Placeholder text (placeholder in <DatePickerInput>)',
      'mm/dd/yyyy'
    ),
    disabled: boolean('Disabled (disabled in <DatePickerInput>)', false),
    helperText: text('Helper text (helperText)', 'Optional help text'),
    invalid: boolean(
      'Show form validation UI (invalid in <DatePickerInput>)',
      false
    ),
    invalidText: text(
      'Form validation UI content (invalidText in <DatePickerInput>)',
      'A valid date is required'
    ),
    warn: boolean('Show warning state (warn)', false),
    warnText: text(
      'Warning state text (warnText)',
      'Selected dates may cause conflicts'
    ),
    iconDescription: text(
      'Icon description (iconDescription in <DatePickerInput>)',
      'Icon description'
    ),
    onChange: action('onChange'),
  }),
};

export default {
  title: 'Components/DatePicker',
  decorators: [withKnobs],

  parameters: {
    component: DatePicker,

    subcomponents: {
      DatePickerInput,
      DatePickerSkeleton,
    },
    docs: {
      page: mdx,
    },
  },
};

export const Simple = () => (
  <DatePicker datePickerType="simple">
    <DatePickerInput
      placeholder="mm/dd/yyyy"
      labelText="Date Picker label"
      id="date-picker-simple"
    />
  </DatePicker>
);

Simple.storyName = 'simple';

export const Single = () => (
  <DatePicker datePickerType="single">
    <DatePickerInput
      placeholder="mm/dd/yyyy"
      labelText="Date Picker label"
      id="date-picker-single"
    />
  </DatePicker>
);

Single.storyName = 'single with calendar';

export const Range = () => {
  return (
    <DatePicker datePickerType="range">
      <DatePickerInput
        id="date-picker-input-id-start"
        placeholder="mm/dd/yyyy"
        labelText="Start date"
      />
      <DatePickerInput
        id="date-picker-input-id-finish"
        placeholder="mm/dd/yyyy"
        labelText="End date"
      />
    </DatePicker>
  );
};

Range.storyName = 'range with calendar';

export const DatePickerPlayground = () => (
  <DatePicker {...props.datePicker()}>
    <DatePickerInput {...props.datePickerInput()} />
    {props.datePicker().datePickerType === 'range' && (
      <DatePickerInput {...props.datePickerInput()} id="date-picker-input-2" />
    )}
  </DatePicker>
);

export const Skeleton = () => <DatePickerSkeleton range />;

Skeleton.storyName = 'skeleton';
