// web-components/packages/carbon-web-components/src/components/toggle/toggle-story-react.tsx
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
// Below path will be there when an application installs `carbon-web-components` package.
// In our dev env, we auto-generate the file and re-map below path to to point to the generated file.
// @ts-ignore
import BXToggle from 'carbon-web-components/es/components-react/toggle/toggle';
import { Default as baseDefault } from './toggle-story';

export { default } from './toggle-story';

export const Default = args => {
  const { checked, checkedText, disabled, labelText, name, size, uncheckedText, value, onChange } = args?.['bx-toggle'];
  return (
    <BXToggle
      checked={checked}
      checkedText={checkedText}
      disabled={disabled}
      labelText={labelText}
      name={name}
      size={size}
      uncheckedText={uncheckedText}
      value={value}
      onChange={onChange}
    />
  );
};

Object.assign(Default, baseDefault);

// web-components/packages/carbon-web-components/src/components/toggle/toggle-story-angular.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { moduleMetadata } from '@storybook/angular';
import baseStory, { Default as baseDefault } from './toggle-story';

export const Default = args => ({
  template: `
    <bx-toggle
      [checked]="checked"
      [checkedText]="checkedText"
      [disabled]="disabled"
      [labelText]="labelText"
      [name]="name"
      [size]="size"
      [uncheckedText]="uncheckedText"
      [value]="value"
      (bx-toggle-changed)="onChange($event)"
    ></bx-toggle>
  `,
  props: args?.['bx-toggle'],
  moduleMetadata: {
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
  },
});

Object.assign(Default, baseDefault);

export default Object.assign(baseStory, {
  decorators: [
    moduleMetadata({
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
    }),
  ],
});
