// packages/react/src/components/FluidNumberInput/FluidNumberInput.Skeleton.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import classnames from 'classnames';
import { usePrefix } from '../../internal/usePrefix';
import { FormContext } from '../FluidForm/FormContext';

function FluidNumberInputSkeleton({ className, ...other }) {
  const prefix = usePrefix();

  return (
    <FormContext.Provider value={{ isFluid: true }}>
      <div
        className={classnames(
          `${prefix}--form-item ${prefix}--text-input--fluid__skeleton`,
          className
        )}
        {...other}>
        <span className={`${prefix}--label ${prefix}--skeleton`} />
        <div className={`${prefix}--skeleton ${prefix}--text-input`} />
      </div>
    </FormContext.Provider>
  );
}

FluidNumberInputSkeleton.propTypes = {
  /**
   * Specify an optional className to be applied to the outer FluidForm wrapper
   */
  className: PropTypes.string,
};

export default FluidNumberInputSkeleton;

// packages/web-components/src/components/fluid-number-input/fluid-number-input-skeleton.ts
/**
 * Copyright IBM Corp.2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { prefix } from '../../globals/settings';
import { html } from 'lit';
import styles from './fluid-number-input.scss?lit';
import CDSNumberInputSkeleton from '../number-input/number-input-skeleton';

/**
 * Fluid number input.
 *
 * @element cds-fluid-number-input-skeleton
 */
class CDSFluidNumberInputSkeleton extends CDSNumberInputSkeleton {
  static is = `${prefix}-fluid-number-input-skeleton`;

  render() {
    return html` ${super.render()} `;
  }

  static styles = [CDSNumberInputSkeleton.styles, styles];
}

export default CDSFluidNumberInputSkeleton;
