// packages/web-components/src/components/fluid-search/fluid-search-skeleton.ts
/**
 * Copyright IBM Corp.2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { prefix } from '../../globals/settings';
import { html } from 'lit';
import styles from './fluid-search.scss?lit';
import CDSSearchSkeleton from '../search/search-skeleton';

/**
 * Fluid Search.
 *
 * @element cds-fluid-search-skeleton
 */
class CDSFluidSearchSkeleton extends CDSSearchSkeleton {
  static is = `${prefix}-fluid-search-skeleton`;

  render() {
    return html`${super.render()}`;
  }

  static styles = [CDSSearchSkeleton.styles, styles];
}

export default CDSFluidSearchSkeleton;

// packages/react/src/components/FluidSearch/FluidSearch.Skeleton.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import classnames from 'classnames';
import { usePrefix } from '../../internal/usePrefix';
import { FormContext } from '../FluidForm/FormContext';

export interface FluidSearchSkeletonProps {
  /**
   * Specify an optional className to be applied to the outer FluidForm wrapper
   */
  className?: string;
}

const FluidSearchSkeleton: React.FC<FluidSearchSkeletonProps> = ({
  className,
  ...other
}) => {
  const prefix = usePrefix();
  return (
    <FormContext.Provider value={{ isFluid: true }}>
      <div
        className={classnames(
          `${prefix}--form-item ${prefix}--text-input--fluid__skeleton`,
          className
        )}
        {...other}>
        <span className={`${prefix}--label ${prefix}--skeleton`} />
        <div className={`${prefix}--skeleton ${prefix}--text-input`} />
      </div>
    </FormContext.Provider>
  );
};

FluidSearchSkeleton.propTypes = {
  /**
   * Specify an optional className to be applied to the outer FluidForm wrapper
   */
  className: PropTypes.string,
};

export default FluidSearchSkeleton;
