// web-components/packages/carbon-web-components/src/components/modal/modal-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { boolean, select, text } from '@storybook/addon-knobs';
import '../button/button';
import { MODAL_SIZE } from './modal';
import './index';
import storyDocs from './modal-story.mdx';

const toggleButton = () => {
  document.querySelector('cds-modal')?.toggleAttribute('open');
};

const sizes = {
  [`Extra small size (${MODAL_SIZE.EXTRA_SMALL})`]: MODAL_SIZE.EXTRA_SMALL,
  [`Small size (${MODAL_SIZE.SMALL})`]: MODAL_SIZE.SMALL,
  [`Medium size (${MODAL_SIZE.MEDIUM})`]: MODAL_SIZE.MEDIUM,
  [`Large size (${MODAL_SIZE.LARGE})`]: MODAL_SIZE.LARGE,
};

const buttons = {
  'One (1)': 1,
  'Two (2)': 2,
  'Three (3)': 3,
};

export const Default = () => {
  return html`
    <cds-modal open prevent-close>
      <cds-modal-header>
        <cds-modal-close-button></cds-modal-close-button>
        <cds-modal-label>Account resources</cds-modal-label>
        <cds-modal-heading>Add a custom domain</cds-modal-heading>
      </cds-modal-header>
      <cds-modal-body>
        <cds-modal-body-content description>
          Custom domains direct requests for your apps in this Cloud Foundry
          organization to a URL that you own. A custom domain can be a shared
          domain, a shared subdomain, or a shared domain and host.
        </cds-modal-body-content>
        <cds-form-item>
          <cds-text-input placeholder="e.g. github.com" label="Domain name">
          </cds-text-input>
        </cds-form-item>

        <cds-form-item>
          <cds-select placeholder="US South" label-text="Region">
            <cds-select-item value="us-south">US South</cds-select-item>
            <cds-select-item value="us-east">US East</cds-select-item>
          </cds-select>
        </cds-form-item>

        <cds-dropdown label="Dropdown" title-text="Dropdown">
          <cds-dropdown-item value="one">One</cds-dropdown-item>
          <cds-dropdown-item value="two">Two</cds-dropdown-item>
        </cds-dropdown>

        <cds-multi-select label="Multiselect" title-text="Multiselect">
          <cds-multi-select-item value="option-1"
            >Option 1</cds-multi-select-item
          >
          <cds-multi-select-item value="option-2"
            >Option 2</cds-multi-select-item
          >
        </cds-multi-select>
      </cds-modal-body>
      <cds-modal-footer>
        <cds-modal-footer-button kind="secondary"
          >Cancel</cds-modal-footer-button
        >
        <cds-modal-footer-button>Add</cds-modal-footer-button>
      </cds-modal-footer>
    </cds-modal>
  `;
};

export const DangerModal = () => {
  return html`
    <cds-modal open prevent-close>
      <cds-modal-header>
        <cds-modal-close-button></cds-modal-close-button>
        <cds-modal-label>Account resources</cds-modal-label>
        <cds-modal-heading
          >Are you sure you want to delete this custom
          domain?</cds-modal-heading
        >
      </cds-modal-header>
      <cds-modal-footer>
        <cds-modal-footer-button kind="secondary"
          >Cancel</cds-modal-footer-button
        >
        <cds-modal-footer-button kind="danger">Delete</cds-modal-footer-button>
      </cds-modal-footer>
    </cds-modal>
  `;
};

export const FullWidth = () => {
  return html`
    <cds-modal open full-width prevent-close>
      <cds-modal-header>
        <cds-modal-close-button></cds-modal-close-button>
        <cds-modal-label>An example of a modal with no padding</cds-modal-label>
        <cds-modal-heading>Full Width Modal</cds-modal-heading>
      </cds-modal-header>
      <cds-modal-body>
        <cds-structured-list>
          <cds-structured-list-head>
            <cds-structured-list-header-row>
              <cds-structured-list-header-cell
                >Column A</cds-structured-list-header-cell
              >
              <cds-structured-list-header-cell
                >Column B</cds-structured-list-header-cell
              >
              <cds-structured-list-header-cell
                >Column C</cds-structured-list-header-cell
              >
            </cds-structured-list-header-row>
          </cds-structured-list-head>
          <cds-structured-list-body>
            <cds-structured-list-row>
              <cds-structured-list-cell>Row 1</cds-structured-list-cell>
              <cds-structured-list-cell>Row 1</cds-structured-list-cell>
              <cds-structured-list-cell
                >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
                dui magna, finibus id tortor sed, aliquet bibendum augue. Aenean
                posuere sem vel euismod dignissim. Nulla ut cursus dolor.
                Pellentesque vulputate nisl a porttitor interdum.
              </cds-structured-list-cell>
            </cds-structured-list-row>
            <cds-structured-list-row>
              <cds-structured-list-cell>Row 2</cds-structured-list-cell>
              <cds-structured-list-cell>Row 2</cds-structured-list-cell>
              <cds-structured-list-cell
                >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
                dui magna, finibus id tortor sed, aliquet bibendum augue. Aenean
                posuere sem vel euismod dignissim. Nulla ut cursus dolor.
                Pellentesque vulputate nisl a porttitor interdum.
              </cds-structured-list-cell>
            </cds-structured-list-row>
            <cds-structured-list-row>
              <cds-structured-list-cell>Row 3</cds-structured-list-cell>
              <cds-structured-list-cell>Row 3</cds-structured-list-cell>
              <cds-structured-list-cell
                >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
                dui magna, finibus id tortor sed, aliquet bibendum augue. Aenean
                posuere sem vel euismod dignissim. Nulla ut cursus dolor.
                Pellentesque vulputate nisl a porttitor interdum.
              </cds-structured-list-cell>
            </cds-structured-list-row>
          </cds-structured-list-body>
        </cds-structured-list>
      </cds-modal-body>
      <cds-modal-footer>
        <cds-modal-footer-button kind="secondary"
          >Cancel</cds-modal-footer-button
        >
        <cds-modal-footer-button>Add</cds-modal-footer-button>
      </cds-modal-footer>
    </cds-modal>
  `;
};

export const PassiveModal = () => {
  return html`
    <cds-modal open prevent-close>
      <cds-modal-header>
        <cds-modal-close-button></cds-modal-close-button>
        <cds-modal-heading
          >You have been successfully signed out</cds-modal-heading
        >
      </cds-modal-header>
      <cds-modal-body></cds-modal-body>
    </cds-modal>
  `;
};

export const WithStateManager = () => {
  return html`
    <cds-modal>
      <cds-modal-header>
        <cds-modal-close-button></cds-modal-close-button>
        <cds-modal-label>Account resources</cds-modal-label>
        <cds-modal-heading>Add a custom domain</cds-modal-heading>
      </cds-modal-header>
      <cds-modal-body>
        <cds-modal-body-content description>
          Custom domains direct requests for your apps in this Cloud Foundry
          organization to a URL that you own. A custom domain can be a shared
          domain, a shared subdomain, or a shared domain and host.
        </cds-modal-body-content>
        <cds-form-item>
          <cds-text-input placeholder="e.g. github.com" label="Domain name">
          </cds-text-input>
        </cds-form-item>
        <cds-select label-text="Domain name" placeholder="US South">
          <cds-select-item value="us-south">Option 1</cds-select-item>
          <cds-select-item value="us-east">Option 2</cds-select-item>
        </cds-select>
      </cds-modal-body>
      <cds-modal-footer>
        <cds-modal-footer-button kind="secondary" data-modal-close
          >Cancel</cds-modal-footer-button
        >
        <cds-modal-footer-button>Add</cds-modal-footer-button>
      </cds-modal-footer>
    </cds-modal>
    <cds-button @click="${toggleButton}">Launch modal</cds-button>
  `;
};

export const Playground = (args) => {
  const {
    alert,
    ariaLabel,
    danger,
    open,
    closeButtonLabel,
    hasScrollingContent,
    fullWidth,
    modalHeading,
    modalLabel,
    numberOfButtons,
    passiveModal,
    preventCloseOnClickOutside,
    primaryButtonDisabled,
    size,
  } = args?.['cds-modal'] ?? {};
  return html`
    <cds-modal
      aria-label=${ariaLabel}
      ?prevent-close-on-click-outside=${preventCloseOnClickOutside}
      ?alert=${alert}
      size="${size}"
      ?open=${open}
      ?full-width=${fullWidth}
      prevent-close
      ?has-scrolling-content="${hasScrollingContent}">
      <cds-modal-header>
        <cds-modal-close-button
          close-button-label=${closeButtonLabel}></cds-modal-close-button>
        <cds-modal-label>${modalLabel}</cds-modal-label>
        <cds-modal-heading>${modalHeading}</cds-modal-heading>
      </cds-modal-header>
      <cds-modal-body>
        <cds-modal-body-content description>
          Custom domains direct requests for your apps in this Cloud Foundry
          organization to a URL that you own. A custom domain can be a shared
          domain, a shared subdomain, or a shared domain and host.
        </cds-modal-body-content>
        <cds-form-item>
          <cds-text-input placeholder="e.g. github.com" label="Domain name">
          </cds-text-input>
        </cds-form-item>
        <cds-select label-text="Region" placeholder="US South">
          <cds-select-item value="us-south">Option 1</cds-select-item>
          <cds-select-item value="us-east">Option 2</cds-select-item>
        </cds-select>

        ${hasScrollingContent
          ? html` <cds-modal-body-content>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean
                id accumsan augue. Phasellus consequat augue vitae tellus
                tincidunt posuere. Curabitur justo urna, consectetur vel elit
                iaculis, ultrices condimentum risus. Nulla facilisi. Etiam
                venenatis molestie tellus. Quisque consectetur non risus eu
                rutrum.
              </cds-modal-body-content>
              <cds-modal-body-content>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean
                id accumsan augue. Phasellus consequat augue vitae tellus
                tincidunt posuere. Curabitur justo urna, consectetur vel elit
                iaculis, ultrices condimentum risus. Nulla facilisi. Etiam
                venenatis molestie tellus. Quisque consectetur non risus eu
                rutrum.
              </cds-modal-body-content>
              <cds-modal-body-content>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean
                id accumsan augue. Phasellus consequat augue vitae tellus
                tincidunt posuere. Curabitur justo urna, consectetur vel elit
                iaculis, ultrices condimentum risus. Nulla facilisi. Etiam
                venenatis molestie tellus. Quisque consectetur non risus eu
                rutrum.
              </cds-modal-body-content>
              <h3>Lorem ipsum</h3>
              <cds-modal-body-content>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean
                id accumsan augue. Phasellus consequat augue vitae tellus
                tincidunt posuere. Curabitur justo urna, consectetur vel elit
                iaculis, ultrices condimentum risus. Nulla facilisi. Etiam
                venenatis molestie tellus. Quisque consectetur non risus eu
                rutrum.
              </cds-modal-body-content>
              <cds-modal-body-content>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean
                id accumsan augue. Phasellus consequat augue vitae tellus
                tincidunt posuere. Curabitur justo urna, consectetur vel elit
                iaculis, ultrices condimentum risus. Nulla facilisi. Etiam
                venenatis molestie tellus. Quisque consectetur non risus eu
                rutrum.
              </cds-modal-body-content>
              <cds-modal-body-content>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean
                id accumsan augue. Phasellus consequat augue vitae tellus
                tincidunt posuere. Curabitur justo urna, consectetur vel elit
                iaculis, ultrices condimentum risus. Nulla facilisi. Etiam
                venenatis molestie tellus. Quisque consectetur non risus eu
                rutrum.
              </cds-modal-body-content>
              <cds-modal-body-content>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean
                id accumsan augue. Phasellus consequat augue vitae tellus
                tincidunt posuere. Curabitur justo urna, consectetur vel elit
                iaculis, ultrices condimentum risus. Nulla facilisi. Etiam
                venenatis molestie tellus. Quisque consectetur non risus eu
                rutrum.
              </cds-modal-body-content>`
          : ``}
      </cds-modal-body>

      ${passiveModal
        ? ``
        : html` <cds-modal-footer>
            ${numberOfButtons > 2
              ? html` <cds-modal-footer-button kind="secondary"
                  >Keep both</cds-modal-footer-button
                >`
              : ``}
            ${numberOfButtons >= 2
              ? html` <cds-modal-footer-button kind="secondary"
                  >${numberOfButtons === 2
                    ? html`Cancel`
                    : 'Rename'}</cds-modal-footer-button
                >`
              : ``}

            <cds-modal-footer-button
              ?disabled=${primaryButtonDisabled}
              kind="${danger ? 'danger' : 'primary'}"
              >Add</cds-modal-footer-button
            >
          </cds-modal-footer>`}
    </cds-modal>
  `;
};

Playground.parameters = {
  ...storyDocs.parameters,
  knobs: {
    'cds-modal': () => ({
      alert: boolean('Alert (alert)', false),
      ariaLabel: text('Aria label (aria-label)', ''),
      closeButtonLabel: text(
        'Close button label (close-button-label)',
        'Close'
      ),
      danger: boolean('Danger mode (danger)', false),
      fullWidth: boolean('Full width (full-width)', false),
      hasScrollingContent: boolean(
        'Has scrolling content (has-scrolling-content)',
        false
      ),
      modalHeading: text('Modal heading', 'Add a custom domain'),
      modalLabel: text('Modal label', ''),
      numberOfButtons: select('Number of buttons', buttons, 2),
      open: boolean('Open (open)', true),
      passiveModal: boolean('Passive modal (passive-modal)', false),
      preventCloseOnClickOutside: boolean(
        'Prevent close on click outside',
        false
      ),
      primaryButtonDisabled: boolean('Primary button disabled', false),
      size: select('Modal size (size)', sizes, null),
    }),
  },
};

export default {
  title: 'Components/Modal',
  decorators: [(story) => html` ${story()} `],
  parameters: {
    ...storyDocs.parameters,
  },
};

// packages/react/src/components/Modal/Modal-story.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useState } from 'react';
import ReactDOM from 'react-dom';
import { action } from '@storybook/addon-actions';
import {
  boolean,
  object,
  optionsKnob as options,
  select,
  text,
  withKnobs,
} from '@storybook/addon-knobs';
import Modal from '../Modal';
import Button from '../Button';
import Select from '../Select';
import SelectItem from '../SelectItem';
import TextInput from '../TextInput';
import mdx from './Modal.mdx';

const sizes = {
  'Extra small (xs)': 'xs',
  'Small (sm)': 'sm',
  'Medium (md)': 'md',
  'Large (lg)': 'lg',
};

const buttons = {
  'None (0)': '0',
  'One (1)': '1',
  'Two (2)': '2',
  'Three (3)': '3',
};

const props = {
  modal: () => ({
    numberOfButtons: options('Number of Buttons', buttons, '2', {
      display: 'inline-radio',
    }),
    className: 'some-class',
    open: boolean('Open (open)', true),
    danger: boolean('Danger mode (danger)', false),
    alert: boolean('Alert mode (alert)', false),
    shouldSubmitOnEnter: boolean(
      'Enter key to submit (shouldSubmitOnEnter)',
      false
    ),
    hasScrollingContent: boolean(
      'Modal contains scrollable content (hasScrollingContent)',
      false
    ),
    hasForm: boolean('Modal contains a form (hasForm)', false),
    modalHeading: text('Modal heading (modalHeading)', 'Modal heading'),
    modalLabel: text('Optional label (modalLabel)', 'Label'),
    modalAriaLabel: text(
      'ARIA label, used only if modalLabel not provided (modalAriaLabel)',
      'A label to be read by screen readers on the modal root node'
    ),
    selectorPrimaryFocus: text(
      'Primary focus element selector (selectorPrimaryFocus)',
      '[data-modal-primary-focus]'
    ),
    size: select('Size (size)', sizes, 'md'),
    iconDescription: text('Close icon description (iconDescription)', 'Close'),
    onBlur: action('onBlur'),
    onClick: action('onClick'),
    onFocus: action('onFocus'),
    onRequestClose: action('onRequestClose'),
    onRequestSubmit: action('onRequestSubmit'),
    onSecondarySubmit: action('onSecondarySubmit'),
    preventCloseOnClickOutside: boolean(
      'Prevent closing on click outside of modal (preventCloseOnClickOutside)',
      true
    ),
    primaryButtonDisabled: boolean(
      'Disable primary button (primaryButtonDisabled)',
      false
    ),
    primaryButtonText: text(
      'Primary button text (primaryButtonText)',
      'Primary button'
    ),
  }),
  modalFooter: (numberOfButtons) => {
    const secondaryButtons = () => {
      switch (numberOfButtons) {
        case '2':
          return {
            secondaryButtonText: text(
              'Secondary button text (secondaryButtonText in <ModalFooter>)',
              'Secondary button'
            ),
          };
        case '3':
          return {
            secondaryButtons: object(
              'Secondary button config array (secondaryButtons)',
              [
                {
                  buttonText: 'Keep both',
                  onClick: action('onClick'),
                },
                {
                  buttonText: 'Rename',
                  onClick: action('onClick'),
                },
              ]
            ),
          };
        default:
          return null;
      }
    };
    return {
      passiveModal: boolean(
        'Without footer (passiveModal)',
        false || numberOfButtons === '0'
      ),
      ...secondaryButtons(),
    };
  },
};

export default {
  title: 'Components/Modal',
  decorators: [withKnobs],
  parameters: {
    component: Modal,
    docs: {
      page: mdx,
    },
  },
};

export const Default = () => {
  return (
    <Modal
      open
      modalHeading="Add a custom domain"
      modalLabel="Account resources"
      primaryButtonText="Add"
      secondaryButtonText="Cancel">
      <p style={{ marginBottom: '1rem' }}>
        Custom domains direct requests for your apps in this Cloud Foundry
        organization to a URL that you own. A custom domain can be a shared
        domain, a shared subdomain, or a shared domain and host.
      </p>
      <TextInput
        data-modal-primary-focus
        id="text-input-1"
        labelText="Domain name"
        placeholder="e.g. github.com"
        style={{ marginBottom: '1rem' }}
      />
      <Select id="select-1" defaultValue="us-south" labelText="Region">
        <SelectItem value="us-south" text="US South" />
        <SelectItem value="us-east" text="US East" />
      </Select>
    </Modal>
  );
};

export const Playground = () => {
  const {
    size,
    numberOfButtons,
    hasScrollingContent,
    ...modalProps
  } = props.modal();
  const { passiveModal, ...footerProps } = props.modalFooter(numberOfButtons);
  return (
    <Modal
      passiveModal={numberOfButtons === '0' || passiveModal}
      size={size || undefined}
      hasScrollingContent={hasScrollingContent}
      aria-label={hasScrollingContent ? 'Modal content' : undefined}
      {...modalProps}
      {...footerProps}>
      <p style={{ marginBottom: '1rem' }}>
        Custom domains direct requests for your apps in this Cloud Foundry
        organization to a URL that you own. A custom domain can be a shared
        domain, a shared subdomain, or a shared domain and host.
      </p>
      <TextInput
        data-modal-primary-focus
        id="text-input-1"
        labelText="Domain name"
        placeholder="e.g. github.com"
        style={{ marginBottom: '1rem' }}
      />
      <Select id="select-1" defaultValue="us-south" labelText="Region">
        <SelectItem value="us-south" text="US South" />
        <SelectItem value="us-east" text="US East" />
      </Select>
      <br />
      {hasScrollingContent && (
        <>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id
            accumsan augue. Phasellus consequat augue vitae tellus tincidunt
            posuere. Curabitur justo urna, consectetur vel elit iaculis,
            ultrices condimentum risus. Nulla facilisi. Etiam venenatis molestie
            tellus. Quisque consectetur non risus eu rutrum.{' '}
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id
            accumsan augue. Phasellus consequat augue vitae tellus tincidunt
            posuere. Curabitur justo urna, consectetur vel elit iaculis,
            ultrices condimentum risus. Nulla facilisi. Etiam venenatis molestie
            tellus. Quisque consectetur non risus eu rutrum.{' '}
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id
            accumsan augue. Phasellus consequat augue vitae tellus tincidunt
            posuere. Curabitur justo urna, consectetur vel elit iaculis,
            ultrices condimentum risus. Nulla facilisi. Etiam venenatis molestie
            tellus. Quisque consectetur non risus eu rutrum.{' '}
          </p>
          <h3>Lorem ipsum</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id
            accumsan augue. Phasellus consequat augue vitae tellus tincidunt
            posuere. Curabitur justo urna, consectetur vel elit iaculis,
            ultrices condimentum risus. Nulla facilisi. Etiam venenatis molestie
            tellus. Quisque consectetur non risus eu rutrum.{' '}
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id
            accumsan augue. Phasellus consequat augue vitae tellus tincidunt
            posuere. Curabitur justo urna, consectetur vel elit iaculis,
            ultrices condimentum risus. Nulla facilisi. Etiam venenatis molestie
            tellus. Quisque consectetur non risus eu rutrum.{' '}
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id
            accumsan augue. Phasellus consequat augue vitae tellus tincidunt
            posuere. Curabitur justo urna, consectetur vel elit iaculis,
            ultrices condimentum risus. Nulla facilisi. Etiam venenatis molestie
            tellus. Quisque consectetur non risus eu rutrum.{' '}
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id
            accumsan augue. Phasellus consequat augue vitae tellus tincidunt
            posuere. Curabitur justo urna, consectetur vel elit iaculis,
            ultrices condimentum risus. Nulla facilisi. Etiam venenatis molestie
            tellus. Quisque consectetur non risus eu rutrum.{' '}
          </p>
        </>
      )}
    </Modal>
  );
};

export const WithStateManager = () => {
  /**
   * Simple state manager for modals.
   */
  const ModalStateManager = ({
    renderLauncher: LauncherContent,
    children: ModalContent,
  }) => {
    const [open, setOpen] = useState(false);
    return (
      <>
        {!ModalContent || typeof document === 'undefined'
          ? null
          : ReactDOM.createPortal(
              <ModalContent open={open} setOpen={setOpen} />,
              document.body
            )}
        {LauncherContent && <LauncherContent open={open} setOpen={setOpen} />}
      </>
    );
  };
  return (
    <ModalStateManager
      renderLauncher={({ setOpen }) => (
        <Button onClick={() => setOpen(true)}>Launch modal</Button>
      )}>
      {({ open, setOpen }) => (
        <Modal
          modalHeading="Add a custom domain"
          modalLabel="Account resources"
          primaryButtonText="Add"
          secondaryButtonText="Cancel"
          open={open}
          onRequestClose={() => setOpen(false)}>
          <p style={{ marginBottom: '1rem' }}>
            Custom domains direct requests for your apps in this Cloud Foundry
            organization to a URL that you own. A custom domain can be a shared
            domain, a shared subdomain, or a shared domain and host.
          </p>
          <TextInput
            data-modal-primary-focus
            id="text-input-1"
            labelText="Domain name"
            placeholder="e.g. github.com"
            style={{ marginBottom: '1rem' }}
          />
          <Select id="select-1" defaultValue="us-south" labelText="Region">
            <SelectItem value="us-south" text="US South" />
            <SelectItem value="us-east" text="US East" />
          </Select>
        </Modal>
      )}
    </ModalStateManager>
  );
};

export const PassiveModal = () => {
  return (
    <Modal
      open
      passiveModal
      modalHeading="You have been successfully signed out"></Modal>
  );
};
