// packages/web-components/src/components/big-number/big-number-skeleton.ts
/**
 * Copyright IBM Corp. 2025, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import '../skeleton-text/index';
import '../skeleton-placeholder/index';

import { prefix } from '../../globals/settings';
import { BigNumberSize, BigNumberSizeValues } from './constants';
import styles from './big-number-skeleton.scss?lit';

const blockClass = `${prefix}--big-number-skeleton`;

/**
 * @element cds-big-number-skeleton
 * Note: This component is only used within cds-big-number. It displays a skeleton version while content is loading (handled by the cds-big-number prop `loading`).
 */

class CDSBigNumberSkeleton extends LitElement {
  static is = `${prefix}-big-number-skeleton`;

  @property({ type: String, reflect: true })
  size?: BigNumberSizeValues = BigNumberSize.Default;

  render() {
    const { size } = this;

    const bigNumberSkeletonClasses = classMap({
      [`${blockClass}`]: true,
      [`${blockClass}--lg`]: size === BigNumberSize.Large,
      [`${blockClass}--xl`]: size === BigNumberSize.XLarge,
    });

    return html`
      <div class=${bigNumberSkeletonClasses}>
        <cds-skeleton-text class="${blockClass}__label"></cds-skeleton-text>
        <cds-skeleton-placeholder
          class="${blockClass}__value"></cds-skeleton-placeholder>
      </div>
    `;
  }

  static styles = styles;
}

export default CDSBigNumberSkeleton;

// packages/react/src/components/BigNumber/BigNumberSkeleton.tsx
/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { forwardRef } from 'react';
import cx from 'classnames';

import { usePrefix } from '../../internal/usePrefix';
import SkeletonText from '../SkeletonText';
import { BigNumberProps } from './BigNumber';
import { BigNumberSize } from './constants';

const componentName = 'BigNumberSkeleton';

/**
 * BigNumberSkeleton is used to display a skeleton version while
 * content is loading (handled by the BigNumber prop `loading`).
 *
 * Note: This component is only used within BigNumber.
 */

// Use the same properties and values as parent BigNumberProps
export type BigNumberSkeletonProps = Pick<
  BigNumberProps,
  'className' | 'size'
> &
  React.HTMLAttributes<HTMLDivElement>;

export const BigNumberSkeleton = forwardRef<
  HTMLDivElement,
  BigNumberSkeletonProps
>(({ className, size, ...rest }, ref) => {
  const prefix = usePrefix();
  const blockClass = `${prefix}--big-number-skeleton`;

  const bigNumberSkeletonClasses = cx(blockClass, className, {
    [`${blockClass}--lg`]: size === BigNumberSize.Large,
    [`${blockClass}--xl`]: size === BigNumberSize.XLarge,
  });

  return (
    <div
      {...rest}
      className={bigNumberSkeletonClasses}
      ref={ref}
      data-component-name={componentName}>
      <SkeletonText className={`${blockClass}__label`} />
      <SkeletonText heading className={`${blockClass}__value`} width="80%" />
    </div>
  );
});

BigNumberSkeleton.displayName = componentName;
