// packages/web-components/src/components/progress-indicator/progress-indicator-skeleton.ts
/**
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import { forEach } from '../../globals/internal/collection-helpers';
import type CDSProgressStepSkeleton from './progress-step-skeleton';
import styles from './progress-indicator.scss?lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Skeleton of progress indicator.
 */
@customElement(`${prefix}-progress-indicator-skeleton`)
export default class CDSProgressIndicatorSkeleton extends LitElement {
  /**
   * `true` if the progress indicator should be vertical. Corresponds to the attribute with the same name.
   */
  @property({ type: Boolean, reflect: true })
  vertical = false;

  updated(changedProperties) {
    if (changedProperties.has('vertical')) {
      // Propagate `vertical` attribute to descendants until `:host-context()` gets supported in all major browsers
      forEach(
        this.querySelectorAll(
          (this.constructor as typeof CDSProgressIndicatorSkeleton).selectorStep
        ),
        (item) => {
          (item as CDSProgressStepSkeleton).vertical = this.vertical;
        }
      );
    }
  }

  render() {
    return html`<slot></slot>`;
  }

  /**
   * A selector that will return progress steps.
   */
  static get selectorStep() {
    return `${prefix}-progress-step-skeleton`;
  }

  static styles = styles;
}

// packages/react/src/components/ProgressIndicator/ProgressIndicator.Skeleton.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { settings } from 'carbon-components';

const { prefix } = settings;

export default class ProgressIndicatorSkeleton extends React.Component {
  render() {
    const currentSvg = (
      <svg>
        <path d="M 7, 7 m -7, 0 a 7,7 0 1,0 14,0 a 7,7 0 1,0 -14,0" />
      </svg>
    );

    const step = (
      <li
        className={`${prefix}--progress-step ${prefix}--progress-step--incomplete`}>
        <div
          className={`${prefix}--progress-step-button ${prefix}--progress-step-button--unclickable`}>
          {currentSvg}
          <p className={`${prefix}--progress-label`} />
          <span className={`${prefix}--progress-line`} />
        </div>
      </li>
    );

    return (
      <ul className={`${prefix}--progress ${prefix}--skeleton`}>
        {step}
        {step}
        {step}
        {step}
      </ul>
    );
  }
}
