// packages/web-components/src/components/badge-indicator/badge-indicator.ts
/**
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';

import styles from './badge-indicator.scss?lit';

/**
 * Badge Indicator.
 *
 * @element cds-badge-indicator
 */
class CDSBadgeIndicator extends LitElement {
  static is = `${prefix}-badge-indicator`;

  /**
   * Count of badge indicator
   */
  @property({ type: Number })
  count;

  /**
   * The shadow slot the badge-indicator should be in.
   */
  @property({ reflect: true })
  slot = 'badge-indicator';

  render() {
    const displayCount = this.count && this.count > 999 ? '999+' : this.count;
    return html`${displayCount}`;
  }

  static styles = styles;
}

export default CDSBadgeIndicator;

// packages/react/src/components/BadgeIndicator/index.tsx
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';

interface BadgeIndicatorProps {
  /**
   * Specify an optional className to add.
   */
  className?: string;

  /**
   * Count of badge indicator
   */
  count?: number;
}

export const BadgeIndicator = React.forwardRef(function BadgeIndicatorContent(
  { className: customClassName, count, ...rest }: BadgeIndicatorProps,
  ref: React.Ref<HTMLDivElement>
) {
  const prefix = usePrefix();
  const classNames = cx(`${prefix}--badge-indicator`, customClassName, {
    [`${prefix}--badge-indicator--count`]: count,
  });
  const displayCount = count && count > 199 ? '199+' : count;

  return (
    <div className={classNames} ref={ref}>
      {displayCount}
    </div>
  );
});

BadgeIndicator.propTypes = {
  /**
   * Specify an optional className to add.
   */
  className: PropTypes.string,

  /**
   *  Count of badge indicator
   */
  count: PropTypes.number,
};

export default BadgeIndicator;
