// web-components/packages/carbon-web-components/src/components/text-input/text-input-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { ifDefined } from 'lit/directives/if-defined.js';
import { boolean, select, number } from '@storybook/addon-knobs';
import textNullable from '../../../.storybook/knob-text-nullable';
import storyDocs from './text-input-story.mdx';
import { prefix } from '../../globals/settings';
import './index';
import '../layer';
import '../form/form-item';
import '../../../.storybook/templates/with-layer';

import { action } from '@storybook/addon-actions';
import { INPUT_SIZE } from './text-input';

const sizes = {
  [`Small size (${INPUT_SIZE.SMALL})`]: INPUT_SIZE.SMALL,
  [`Medium size (${INPUT_SIZE.MEDIUM})`]: INPUT_SIZE.MEDIUM,
  [`Large size (${INPUT_SIZE.LARGE})`]: INPUT_SIZE.LARGE,
};

export const Default = () => {
  return html`
    <cds-text-input label="Text input label" helper-text="Optional help text">
    </cds-text-input>
  `;
};

Default.storyName = 'Default';

export const ReadOnly = () => {
  return html`
    <cds-text-input
      value="This is read only, you can't type more."
      readonly="true"
      label="Text input label"
      helper-text="Optional help text">
    </cds-text-input>
  `;
};

export const Skeleton = () => {
  return html` <cds-text-input-skeleton></cds-text-input-skeleton> `;
};

export const TogglePasswordVisibility = () => {
  return html`
    <cds-text-input
      type="password"
      show-password-visibility-toggle
      label="Text input label"
      helper-text="Optional help text">
    </cds-text-input>
  `;
};

export const WithLayer = () => {
  return html`
    <sb-template-layers>
      <cds-text-input label="Text input label" helper-text="Optional help text">
      </cds-text-input>
    </sb-template-layers>
  `;
};

export const Playground = (args) => {
  const {
    disabled,
    enableCounter,
    helperText,
    hideLabel,
    inline,
    invalid,
    invalidText,
    labelText,
    maxCount,
    placeholder,
    playgroundWidth,
    readonly,
    size,
    type,
    value,
    warn,
    warnText,
    onInput,
  } = args?.[`${prefix}-input`] ?? {};
  return html`
    <div style="width: ${playgroundWidth}px;">
      <cds-text-input
        ?disabled="${disabled}"
        ?enable-counter="${ifDefined(enableCounter)}"
        helper-text="${ifDefined(helperText)}"
        ?hide-label="${hideLabel}"
        ?inline="${inline}"
        ?invalid="${invalid}"
        invalid-text="${ifDefined(invalidText)}"
        label="${ifDefined(labelText)}"
        max-count="${ifDefined(maxCount)}"
        placeholder="${ifDefined(placeholder)}"
        ?readonly="${ifDefined(readonly)}"
        size="${ifDefined(size)}"
        type="${ifDefined(type)}"
        value="${ifDefined(value)}"
        ?warn="${ifDefined(warn)}"
        warn-text="${ifDefined(warnText)}"
        @input="${onInput}">
      </cds-text-input>
    </div>
  `;
};

Playground.parameters = {
  knobs: {
    [`${prefix}-input`]: () => ({
      disabled: boolean('Disabled (disabled)', false),
      enableCounter: boolean('Enable counter (enable-counter)', false),
      helperText: textNullable('Helper text (helper-text)', 'Helper text'),
      hideLabel: boolean('Hide label (hide-label)', false),
      inline: boolean('Inline (inline)', false),
      invalid: boolean('Invalid (invalid)', false),
      invalidText: textNullable(
        'Invalid text (invalid-text)',
        'Error message goes here'
      ),
      labelText: textNullable('Label text (label)', 'Label text'),
      maxCount: textNullable('Max count (max-count)', '100'),
      placeholder: textNullable(
        'Placeholder (placeholder)',
        'Placeholder text'
      ),
      playgroundWidth: number('Playground width', 300, {
        range: true,
        min: 300,
        max: 800,
        step: 50,
      }),
      size: select('Size (size)', sizes, INPUT_SIZE.MEDIUM),
      readonly: boolean('Read only (readonly)', false),
      type: textNullable('Type (type)', 'text'),
      warn: boolean('Warn (warn)', false),
      warnText: textNullable(
        'Warn text (warn-text)',
        'Warning message that is really long can wrap to more lines but should not be excessively long.'
      ),
      value: textNullable('Value of input (value)', ''),
      onInput: action(`${prefix}-select-selected`),
    }),
  },
};

export default {
  title: 'Components/Text Input',
  parameters: {
    ...storyDocs.parameters,
  },
};

// packages/react/src/components/TextInput/TextInput-story.js
/*
 * Copyright IBM Corp. 2016, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
*/

import React, { useState } from 'react';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { withKnobs, boolean, select, text } from '@storybook/addon-knobs';
import TextInput from '../TextInput';
import TextInputSkeleton from '../TextInput/TextInput.Skeleton';
import FluidForm from '../FluidForm/FluidForm';

const types = {
  None: '',
  'Text (text)': 'text',
  'For email (email)': 'email',
  'For password (password)': 'password',
};

const sizes = {
  'Extra large size (xl)': 'xl',
  'Default size': undefined,
  'Small size (sm)': 'sm',
};

const ControlledPasswordInputApp = React.forwardRef(
  function ControlledPasswordInputApp(props, ref) {
    const [type, setType] = useState('password');
    const togglePasswordVisibility = () => {
      setType(type === 'password' ? 'text' : 'password');
    };
    return (
      <>
        <TextInput.ControlledPasswordInput
          type={type}
          togglePasswordVisibility={togglePasswordVisibility}
          ref={ref}
          {...props}
        />
        <button onClick={() => setType('text')}>Show password</button>
        <button onClick={() => setType('password')}>Hide password</button>
      </>
    );
  }
);

const props = {
  TextInputProps: () => ({
    className: 'some-class',
    id: 'test2',
    defaultValue: text(
      'Default value (defaultValue)',
      'This is not a default value'
    ),
    size: select('Field size (size)', sizes, undefined) || undefined,
    labelText: text('Label text (labelText)', 'Text input label'),
    placeholder: text('Placeholder text (placeholder)', 'Placeholder text'),
    light: boolean('Light variant (light)', false),
    disabled: boolean('Disabled (disabled)', false),
    hideLabel: boolean('No label (hideLabel)', false),
    invalid: boolean('Show form validation UI (invalid)', false),
    invalidText: text(
      'Form validation UI content (invalidText)',
      'A valid value is required'
    ),
    warn: boolean('Show warning state (warn)', false),
    warnText: text(
      'Warning state text (warnText)',
      'This will overwrite your current settings'
    ),
    helperText: text('Helper text (helperText)', 'Optional help text'),
    inline: boolean('Inline variant (inline)', false),
    onClick: action('onClick'),
    onChange: action('onChange'),
  }),
  PasswordInputProps: () => ({
    tooltipPosition: select(
      'Tooltip position (tooltipPosition)',
      ['top', 'right', 'bottom', 'left'],
      'bottom'
    ),
    tooltipAlignment: select(
      'Tooltip alignment (tooltipAlignment)',
      ['start', 'center', 'end'],
      'center'
    ),
    hidePasswordLabel: text(
      '"Hide password" tooltip label for password visibility toggle (hidePasswordLabel)',
      'Hide password'
    ),
    showPasswordLabel: text(
      '"Show password" tooltip label for password visibility toggle (showPasswordLabel)',
      'Show password'
    ),
  }),
};

TextInput.displayName = 'TextInput';

storiesOf('TextInput', module)
  .addParameters({
    component: TextInput,
    subcomponents: {
      TextInputSkeleton,
      'TextInput.ControlledPasswordInput': TextInput.ControlledPasswordInput,
    },
  })
  .addDecorator(withKnobs)
  .add(
    'Default',
    () => (
      <TextInput
        type={select('Form control type (type)', types, 'text')}
        {...props.TextInputProps()}
      />
    ),
    {
      info: {
        text: `
            Text fields enable the user to interact with and input data. A single line
            field is used when the input anticipated by the user is a single line of
            text as opposed to a paragraph.
            The default type is 'text' and its value can be either 'string' or 'number'.
          `,
      },
    }
  )
  .add(
    'Fluid',
    () => (
      <FluidForm>
        <TextInput
          type={select('Form control type (type)', types, 'text')}
          {...props.TextInputProps()}
        />
      </FluidForm>
    ),
    {
      info: {
        text: `
            Text fields enable the user to interact with and input data. A single line
            field is used when the input anticipated by the user is a single line of
            text as opposed to a paragraph.
            The default type is 'text' and its value can be either 'string' or 'number'.
          `,
      },
    }
  )
  .add(
    'Toggle password visibility',
    () => {
      return (
        <TextInput.PasswordInput
          {...props.TextInputProps()}
          {...props.PasswordInputProps()}
        />
      );
    },
    {
      info: {
        text: `
          Text field with password visibility toggle.
        `,
      },
    }
  )
  .add(
    'Fully controlled toggle password visibility',
    () => {
      ControlledPasswordInputApp.__docgenInfo = {
        ...TextInput.PasswordInput.__docgenInfo,
        props: {
          ...TextInput.PasswordInput.__docgenInfo.props,
        },
      };

      return (
        <ControlledPasswordInputApp
          {...props.TextInputProps()}
          {...props.PasswordInputProps()}
        />
      );
    },
    {
      info: {
        text: `
        Fully controlled text field with password visibility toggle.
      `,
      },
    }
  )
  .add(
    'skeleton',
    () => (
      <div
        aria-label="loading text input"
        aria-live="assertive"
        role="status"
        tabIndex="0" // eslint-disable-line jsx-a11y/no-noninteractive-tabindex
      >
        <TextInputSkeleton />
        <br />
        <TextInputSkeleton hideLabel />
      </div>
    ),
    {
      info: {
        text: `
            Placeholder skeleton state to use when content is loading.
            `,
      },
    }
  );
