// packages/react/src/components/Tooltip/DefinitionTooltip.js
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import PropTypes from 'prop-types';
import React, { useState } from 'react';
import { Popover, PopoverContent } from '../Popover';
import { match, keys } from '../../internal/keyboard';
import { useFallbackId } from '../../internal/useId';
import { usePrefix } from '../../internal/usePrefix';
import deprecate from '../../prop-types/deprecate';

function DefinitionTooltip({
  align = 'bottom-left',
  className,
  children,
  definition,
  defaultOpen = false,
  id,
  openOnHover,
  tooltipText,
  triggerClassName,
  ...rest
}) {
  const [isOpen, setOpen] = useState(defaultOpen);
  const prefix = usePrefix();
  const tooltipId = useFallbackId(id);

  function onKeyDown(event) {
    if (isOpen && match(event, keys.Escape)) {
      event.stopPropagation();
      setOpen(false);
    }
  }

  return (
    <Popover
      align={align}
      className={className}
      dropShadow={false}
      highContrast
      onMouseLeave={() => {
        setOpen(false);
      }}
      onMouseEnter={() => {
        openOnHover ? setOpen(true) : null;
      }}
      open={isOpen}>
      <button
        {...rest}
        className={cx(`${prefix}--definition-term`, triggerClassName)}
        aria-controls={tooltipId}
        aria-expanded={isOpen}
        onBlur={() => {
          setOpen(false);
        }}
        onClick={() => {
          setOpen(!isOpen);
        }}
        onKeyDown={onKeyDown}
        type="button">
        {children}
      </button>
      <PopoverContent
        className={`${prefix}--definition-tooltip`}
        id={tooltipId}>
        {tooltipText ?? definition}
      </PopoverContent>
    </Popover>
  );
}

DefinitionTooltip.propTypes = {
  /**
   * Specify how the trigger should align with the tooltip
   */
  align: PropTypes.oneOf([
    'top',
    'top-left',
    'top-right',

    'bottom',
    'bottom-left',
    'bottom-right',

    'left',
    'left-bottom',
    'left-top',

    'right',
    'right-bottom',
    'right-top',
  ]),

  /**
   * The `children` prop will be used as the value that is being defined
   */
  children: PropTypes.node.isRequired,

  /**
   * Specify an optional className to be applied to the container node
   */
  className: PropTypes.string,

  /**
   * Specify whether the tooltip should be open when it first renders
   */
  defaultOpen: PropTypes.bool,

  /**
   * The `definition` prop is used as the content inside of the tooltip that
   * appears when a user interacts with the element rendered by the `children`
   * prop
   */
  definition: PropTypes.node.isRequired,

  /**
   * Provide a value that will be assigned as the id of the tooltip
   */
  id: PropTypes.string,

  /**
   * Specifies whether or not the `DefinitionTooltip` should open on hover or not
   */
  openOnHover: PropTypes.bool,

  /**
   * [Deprecated in v11] Please use the `definition` prop instead.
   *
   * Provide the text that will be displayed in the tooltip when it is rendered.
   */
  tooltipText: deprecate(
    PropTypes.node,
    'The tooltipText prop has been deprecated. Please use the `definition` prop instead.'
  ),

  /**
   * The CSS class name of the trigger element
   */
  triggerClassName: PropTypes.string,
};

export { DefinitionTooltip };

// packages/web-components/src/components/tooltip/definition-tooltip.ts
/**
 * Copyright IBM Corp. 2019, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, LitElement } from 'lit';
import { property, state } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import { POPOVER_ALIGNMENT } from '../popover/defs';
import '../popover/index';
import styles from './tooltip.scss?lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Definition tooltip.
 *
 * @element cds-definition-tooltip
 */
@customElement(`${prefix}-definition-tooltip`)
class CDSDefinitionTooltip extends LitElement {
  /**
   * Specify how the trigger should align with the tooltip
   */
  @property({ reflect: true, type: POPOVER_ALIGNMENT })
  align = 'bottom';

  /**
   * Will auto-align Definition Tooltip. This prop is currently experimental and is subject to future changes.
   */
  @property({ type: Boolean, reflect: true })
  autoalign = false;

  /**
   * Specify whether the tooltip should be open when it first renders
   */
  @property({ type: Boolean, reflect: true, attribute: 'default-open' })
  defaultOpen = false;

  /**
   * Specifies whether or not the `DefinitionTooltip` should open on hover or not
   */
  @property({ reflect: true, type: Boolean, attribute: 'open-on-hover' })
  openOnHover = false;

  @state()
  open = false;

  connectedCallback() {
    super.connectedCallback();

    if (this.hasAttribute('default-open')) {
      this.open = true;
    }
  }

  _handleBlur() {
    this.open = false;
  }

  _handleMouseDown() {
    this.open = !this.open;
  }

  _handleKeyDown(event: KeyboardEvent) {
    const { key } = event;

    if (this.open && (key === 'Esc' || key === 'Escape')) {
      event.stopPropagation();
      this.open = false;
    }
  }

  _handleHover() {
    if (this.openOnHover && !this.open) {
      this.open = true;
    } else {
      this.open = false;
    }
  }

  _handleFocus() {
    this.open = true;
  }

  render() {
    const { align, open } = this;

    return html`
      <cds-popover
        @mouseenter=${this._handleHover}
        @mouseleave=${this._handleHover}
        highContrast
        dropShadow=${false}
        align=${align}
        .open=${open}>
        <button
          @focus=${this._handleFocus}
          @blur=${this._handleBlur}
          @mousedown=${this._handleMouseDown}
          @keydown=${this._handleKeyDown}
          aria-expanded=${open}
          class="${prefix}--definition-term">
          <slot></slot>
        </button>
        <cds-popover-content>
          <slot name="definition"></slot>
        </cds-popover-content>
      </cds-popover>
    `;
  }

  static styles = styles;
}

export default CDSDefinitionTooltip;
