// packages/react/src/components/Checkbox/Checkbox.Skeleton.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { settings } from '@rocketsoftware/carbon-components';

const { prefix } = settings;

const CheckboxSkeleton = () => (
  <div className={`${prefix}--form-item ${prefix}--checkbox-wrapper`}>
    <span className={`${prefix}--checkbox-label ${prefix}--skeleton`} />
  </div>
);

export default CheckboxSkeleton;

// packages/web-components/src/components/checkbox/checkbox-skeleton.ts
/**
 * Copyright IBM Corp. 2019, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './checkbox.scss?lit';

/**
 * Skeleton of number input.
 */
class CDSCheckboxSkeleton extends LitElement {
  static is = `${prefix}-checkbox-skeleton`;

  render() {
    return html`
      <label class="${prefix}--checkbox-label" for="checkbox" part="label">
        <span class="${prefix}--checkbox-label-text ${prefix}--skeleton"
          ><slot></slot
        ></span>
      </label>
    `;
  }

  static styles = styles;
}

export default CDSCheckboxSkeleton;
