// packages/web-components/src/components/file-uploader/file-uploader-drop-container.ts
/**
 * Copyright IBM Corp. 2020, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import HostListenerMixin from '../../globals/mixins/host-listener';
import HostListener from '../../globals/decorators/host-listener';
import ifNonEmpty from '../../globals/directives/if-non-empty';
import styles from './file-uploader.scss?lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

export { FORM_ELEMENT_COLOR_SCHEME as TILE_COLOR_SCHEME } from '../../globals/shared-enums';

/**
 * The value to set to `event.dataTransfer.dropEffect`, keyed by the event nane.
 */
const dropEffects = {
  dragover: 'copy',
  dragleave: 'move',
};

/**
 * File uploader drop container.
 *
 * @element cds-file-uploader-drop-container
 * @fires cds-file-uploader-drop-container-changed The custom event fired when there is a user gesture to select files to upload.
 */
@customElement(`${prefix}-file-uploader-drop-container`)
class CDSFileUploaderDropContainer extends HostListenerMixin(LitElement) {
  /**
   * `true` to show the active state of this UI.
   */
  private _active = false;

  /**
   * Handles user gesture to select files to upload.
   *
   * @param event The event.
   */
  private _handleChange(event: Event | DragEvent) {
    const { eventChange, selectorInput } = this
      .constructor as typeof CDSFileUploaderDropContainer;
    const { files } =
      (event.type === 'drop'
        ? (event as DragEvent).dataTransfer
        : (event.target as HTMLInputElement)) ?? {};
    const addedFiles = this._getFiles(event, files);

    this.dispatchEvent(
      new CustomEvent(eventChange, {
        bubbles: true,
        composed: true,
        detail: {
          addedFiles,
        },
      })
    );

    const fileInput = this?.shadowRoot?.querySelector(selectorInput);
    if (fileInput) {
      (fileInput as HTMLInputElement).value = ''; // carbon-web-components#904
    }
  }

  /**
   * Handles `dragover`, `dragleave` and `drop` events.
   *
   * @param event The event.
   */
  @HostListener('dragover')
  @HostListener('dragleave')
  @HostListener('drop')
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment -- https://github.com/carbon-design-system/carbon/issues/20452
  // @ts-ignore: The decorator refers to this method but TS thinks this method is not referred to
  private _handleDrag(event: DragEvent) {
    event.preventDefault(); // Prevents page navigation upon dropping
    if (this.disabled) {
      return;
    }
    const { dataTransfer, type } = event;
    const dropEffect = dropEffects[type];
    if (dataTransfer && dropEffect) {
      dataTransfer.dropEffect = dropEffect;
    }
    this._active = type === 'dragover';
    if (type === 'drop') {
      this._handleChange(event);
    }
    this.requestUpdate();
  }

  /**
   * @param event The event.
   * @returns The list of files user chose to upload.
   */
  private _getFiles(event, files) {
    const { accept } = this;
    if (!accept || !/^(change|drop)$/.test(event.type)) {
      return Array.from(files ?? []);
    }
    const acceptedTypes = new Set(accept.split(' '));
    return Array.prototype.filter.call(
      files,
      ({ name, type: mimeType = '' }) => {
        const fileExtensionRegExp = /\.[^.]+$/;
        const hasFileExtension = fileExtensionRegExp.test(name);
        const [fileExtension] = !hasFileExtension
          ? [undefined]
          : (fileExtensionRegExp.exec(name) ?? []);

        return (
          acceptedTypes.has(mimeType) ||
          (fileExtension && acceptedTypes.has(fileExtension))
        );
      }
    ) as File[];
  }

  /**
   * The file types the file input should accept, separated by space.
   */
  @property()
  accept = '';

  /**
   * `true` if this drop container should be disabled.
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /**
   * `true` if this drop container should accept more than one files at once.
   * Note that even with `false` set here, user _can_ select multiple files one by one.
   */
  @property({ type: Boolean, reflect: true })
  multiple = false;

  /**
   * The name of the input.
   */
  @property({ reflect: true })
  name = '';

  /**
   * The shadow DOM slot to put this drop container in.
   */
  @property({ reflect: true })
  slot = 'drop-container';

  render() {
    const {
      accept,
      disabled,
      multiple,
      name,
      _active: active,
      _handleChange: handleChange,
    } = this;
    const labelClasses = classMap({
      [`${prefix}--file-browse-btn`]: true,
      [`${prefix}--file-browse-btn--disabled`]: disabled,
    });
    const dropareaClasses = classMap({
      [`${prefix}--file__drop-container`]: true,
      [`${prefix}--file__drop-container--drag-over`]: active,
    });
    return html`
      <label class="${labelClasses}" for="file" tabindex="0">
        <div class="${dropareaClasses}" role="button">
          <slot></slot>
          <input
            id="file"
            type="file"
            name="${ifNonEmpty(name)}"
            class="${prefix}--file-input"
            tabindex="-1"
            accept="${ifNonEmpty(accept)}"
            ?disabled="${disabled}"
            ?multiple="${multiple}"
            @change="${handleChange}" />
        </div>
      </label>
    `;
  }

  /**
   * The name of the custom event fired when there is a user gesture to select files to upload.
   */
  static get eventChange() {
    return `${prefix}-file-uploader-drop-container-changed`;
  }

  /**
   * A selector that will return the file `input`.
   */
  static get selectorInput() {
    return `.${prefix}--file-input`;
  }

  static styles = styles;
}

export default CDSFileUploaderDropContainer;

// packages/react/src/components/FileUploader/FileUploaderDropContainer.tsx
/**
 * Copyright IBM Corp. 2016, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useRef, useState, type HTMLAttributes } from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import { keys, matches } from '../../internal/keyboard';
import { useId } from '../../internal/useId';
import { usePrefix } from '../../internal/usePrefix';
import { composeEventHandlers } from '../../tools/events';
import { deprecate } from '../../prop-types/deprecate';
import { noopFn } from '../../internal/noopFn';

export interface FileUploaderDropContainerProps
  extends Omit<HTMLAttributes<HTMLButtonElement>, 'tabIndex'> {
  /**
   * Specify the types of files that this input should be able to receive
   */
  accept?: string[];

  /**
   * Provide a custom className to be applied to the container node
   */
  className?: string;

  /**
   * Specify whether file input is disabled
   */
  disabled?: boolean;

  /**
   * Provide a unique id for the underlying `<input>` node
   */
  id?: string;

  /**
   * Provide the label text to be read by screen readers when interacting with
   * this control
   */
  labelText?: string;

  /**
   * Maximum file size allowed in bytes. Files larger than this will be marked invalid
   */
  maxFileSize?: number;

  /**
   * Specify if the component should accept multiple files to upload
   */
  multiple?: boolean;

  /**
   * Provide a name for the underlying `<input>` node
   */
  name?: string;

  /**
   * Event handler that is called after files are added to the uploader
   */
  onAddFiles?: (
    event: React.SyntheticEvent<HTMLElement>,
    content: { addedFiles: AddedFile[] }
  ) => void;

  /**
   * Provide an optional function to be called when the button element
   * is clicked
   */
  onClick?: () => void;

  /**
   * Provide a custom regex pattern for the acceptedTypes
   */
  pattern?: string;

  /**
   * Ref to pass to the inner button element
   */
  innerRef?: React.Ref<HTMLButtonElement>;

  /**
   * @deprecated The `role` prop for `FileUploaderButton` has been deprecated since it now renders a button element by default, and has an implicit role of button.
   */
  role?: string;

  /**
   * @deprecated The `tabIndex` prop for `FileUploaderButton` has been deprecated since it now renders a button element by default.
   */
  tabIndex?: number | string;
}

interface AddedFile extends File {
  invalidFileType?: boolean;
}

function FileUploaderDropContainer({
  accept = [],
  className,
  id,
  disabled,
  labelText = 'Add file',
  maxFileSize,
  multiple = false,
  name,
  onAddFiles = noopFn,
  onClick,
  pattern = '.[0-9a-z]+$',

  innerRef,
  ...rest
}: FileUploaderDropContainerProps) {
  const prefix = usePrefix();
  const inputRef = useRef<HTMLInputElement>(null);
  // eslint-disable-next-line  react-hooks/rules-of-hooks -- https://github.com/carbon-design-system/carbon/issues/20452
  const { current: uid } = useRef(id || useId());
  const [isActive, setActive] = useState(false);
  const dropareaClasses = classNames(
    `${prefix}--file__drop-container`,
    `${prefix}--file-browse-btn`,
    {
      [`${prefix}--file__drop-container--drag-over`]: isActive,
      [`${prefix}--file-browse-btn--disabled`]: disabled,
    },
    className
  );

  /**
   * Filters the array of added files based on file type and size restrictions
   */
  function validateFiles(transferredFiles: AddedFile[]) {
    const acceptedTypes = new Set(accept);
    return transferredFiles.reduce<AddedFile[]>((acc, curr) => {
      const { name, type: mimeType = '' } = curr;
      const fileExtensionRegExp = new RegExp(pattern, 'i');
      const [fileExtension] = name.match(fileExtensionRegExp) ?? [];

      if (maxFileSize && curr.size > maxFileSize) {
        curr.invalidFileType = true;
        return acc.concat([curr]);
      }

      if (!accept.length) {
        return acc.concat([curr]);
      }

      if (fileExtension === undefined) {
        return acc;
      }
      if (
        acceptedTypes.has(mimeType) ||
        acceptedTypes.has(fileExtension.toLowerCase())
      ) {
        return acc.concat([curr]);
      }
      curr.invalidFileType = true;
      return acc.concat([curr]);
    }, []);
  }

  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    const files = [...(event.target.files ?? [])];
    const filesToValidate = multiple ? files : [files[0]];
    const addedFiles = validateFiles(filesToValidate);
    return onAddFiles(event, { addedFiles });
  }

  function handleDrop(event: React.DragEvent<HTMLDivElement>) {
    const files = [...event.dataTransfer.files];
    const filesToValidate = multiple ? files : [files[0]];
    const addedFiles = validateFiles(filesToValidate);
    return onAddFiles(event, { addedFiles });
  }

  const handleClick = () => {
    if (!disabled) {
      inputRef.current?.click();
    }
  };

  return (
    <div
      className={`${prefix}--file`}
      onDragOver={(evt) => {
        evt.stopPropagation();
        evt.preventDefault();
        if (disabled) {
          return;
        }
        setActive(true);
        evt.dataTransfer.dropEffect = 'copy';
      }}
      onDragLeave={(evt) => {
        evt.stopPropagation();
        evt.preventDefault();
        if (disabled) {
          return;
        }
        setActive(false);
        evt.dataTransfer.dropEffect = 'move';
      }}
      onDrop={(evt) => {
        evt.stopPropagation();
        evt.preventDefault();
        if (disabled) {
          return;
        }
        setActive(false);
        handleDrop(evt);
      }}>
      {/* @ts-expect-error remove this ignore line when the explicit tabIndex prop is deleted */}
      <button
        type="button"
        className={dropareaClasses}
        ref={innerRef}
        onKeyDown={(evt) => {
          if (matches(evt, [keys.Enter, keys.Space])) {
            evt.preventDefault();
            inputRef.current?.click();
          }
        }}
        onClick={composeEventHandlers([onClick, handleClick])}
        {...rest}>
        {labelText}
      </button>
      <label htmlFor={uid} className={`${prefix}--visually-hidden`}>
        {labelText}
      </label>
      <input
        type="file"
        id={uid}
        className={`${prefix}--file-input`}
        ref={inputRef}
        tabIndex={-1}
        disabled={disabled}
        accept={accept.join(',')}
        name={name}
        multiple={multiple}
        onChange={handleChange}
        onClick={(evt) => {
          (evt.target as HTMLInputElement).value = '';
        }}
      />
    </div>
  );
}

FileUploaderDropContainer.propTypes = {
  /**
   * Specify the types of files that this input should be able to receive
   */
  accept: PropTypes.arrayOf(PropTypes.string),

  /**
   * Provide a custom className to be applied to the container node
   */
  className: PropTypes.string,

  /**
   * Specify whether file input is disabled
   */
  disabled: PropTypes.bool,

  /**
   * Provide a unique id for the underlying `<input>` node
   */
  id: PropTypes.string,

  /**
   * Provide the label text to be read by screen readers when interacting with
   * this control
   */
  labelText: PropTypes.string.isRequired,

  /**
   * Maximum file size allowed in bytes. Files larger than this will be marked invalid
   */
  maxFileSize: PropTypes.number,

  /**
   * Specify if the component should accept multiple files to upload
   */
  multiple: PropTypes.bool,

  /**
   * Provide a name for the underlying `<input>` node
   */
  name: PropTypes.string,

  /**
   * Event handler that is called after files are added to the uploader
   * The event handler signature looks like `onAddFiles(evt, { addedFiles })`
   */
  onAddFiles: PropTypes.func,

  /**
   * Provide an optional function to be called when the button element
   * is clicked
   */
  onClick: PropTypes.func,

  /**
   * Provide a custom regex pattern for the acceptedTypes
   */
  pattern: PropTypes.string,

  /**
   * Provide an accessibility role for the `<FileUploaderButton>`
   */
  role: deprecate(
    PropTypes.number,
    'The `role` prop for `FileUploaderButton` has ' +
      'been deprecated since it now renders a button element by default, and has an implicit role of button.'
  ),

  /**
   * Provide a custom tabIndex value for the `<FileUploaderButton>`
   */
  tabIndex: deprecate(
    PropTypes.number,
    'The `tabIndex` prop for `FileUploaderButton` has ' +
      'been deprecated since it now renders a button element by default.'
  ),
};

export default FileUploaderDropContainer;
