// web-components/packages/carbon-web-components/src/components/tag/tag-story-angular.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { moduleMetadata } from '@storybook/angular';
import baseStory, { Default as baseDefault, filter as baseFilter } from './tag-story';

export const Default = args => ({
  template: `
    <bx-tag [size]="size" [type]="type" [title]="title" [disabled]="disabled">
      This is a tag
    </bx-tag>
  `,
  props: args?.['bx-tag'],
});

Object.assign(Default, baseDefault);

export const filter = args => ({
  template: `
    <bx-filter-tag
      [open]="open"
      [size]="size"
      [type]="type"
      [title]="title"
      [disabled]="disabled"
      (click)="onClick($event)"
      (bx-filter-tag-beingclosed)="handleBeforeClose($event)"
      (bx-filter-tag-closed)="handleClose($event)"
    >
      This is a tag
    </bx-filter-tag>
  `,
  props: (({ disableClose, onBeforeClose, onClose, ...rest }) => ({
    ...rest,
    handleBeforeClose: (event: CustomEvent) => {
      onBeforeClose(event);
      if (disableClose) {
        event.preventDefault();
      }
    },
    handleClose: onClose,
  }))(args?.['bx-filter-tag']),
});

Object.assign(filter, baseFilter);

export default Object.assign(baseStory, {
  decorators: [
    moduleMetadata({
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
    }),
  ],
});

// web-components/packages/carbon-web-components/src/components/tag/tag-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { action } from '@storybook/addon-actions';
import { boolean, select } from '@storybook/addon-knobs';
import textNullable from '../../../.storybook/knob-text-nullable';
import { ifDefined } from 'lit/directives/if-defined.js';
import { TAG_SIZE, TAG_TYPE } from './tag';
import './filter-tag';
import storyDocs from './tag-story.mdx';

const noop = () => {};

const sizes = {
  'Regular size': null,
  [`Small size (${TAG_SIZE.SMALL})`]: TAG_SIZE.SMALL,
};

export const Default = (args) => {
  const { size, type, title, disabled } = args?.['bx-tag'] ?? {};
  return html`
    <bx-tag
      size="${ifDefined(size)}"
      type="${ifDefined(type)}"
      title="${ifDefined(title)}"
      ?disabled="${disabled}">
      This is a tag
    </bx-tag>
  `;
};

Default.storyName = 'Default';

Default.parameters = {
  knobs: {
    'bx-tag': () => ({
      disabled: boolean('Disabled (disabled)', false),
      title: textNullable('Title (title)', 'Clear Selection'),
      size: select('Tag size (size)', sizes, null),
      type: select(
        'Tag type (type)',
        Object.values(TAG_TYPE).reduce(
          (acc, type) => ({
            ...acc,
            [`${type} (${type})`]: type,
          }),
          {}
        ),
        'gray'
      ),
    }),
  },
};

export const filter = (args) => {
  const {
    open,
    size,
    type,
    title,
    disabled,
    disableClose,
    onClick,
    onBeforeClose = noop,
    onClose = noop,
  } = args?.['bx-filter-tag'] ?? {};
  const handleBeforeClose = (event: CustomEvent) => {
    onBeforeClose(event);
    if (disableClose) {
      event.preventDefault();
    }
  };
  return html`
    <bx-filter-tag
      ?open="${open}"
      size="${ifDefined(size)}"
      type="${ifDefined(type)}"
      title="${ifDefined(title)}"
      ?disabled="${disabled}"
      @click="${onClick}"
      @bx-filter-tag-beingclosed="${handleBeforeClose}"
      @bx-filter-tag-closed="${onClose}">
      This is a tag
    </bx-filter-tag>
  `;
};

filter.parameters = {
  knobs: {
    'bx-filter-tag': () => ({
      ...Default.parameters.knobs['bx-tag'](),
      open: boolean('Open (open)', true),
      disableClose: boolean(
        'Disable user-initiated close action (Call event.preventDefault() in bx-filter-tag-beingclosed event)',
        false
      ),
      onClick: action('click'),
      onBeforeClose: action('bx-filter-tag-beingclosed'),
      onClose: action('bx-filter-tag-closed'),
    }),
  },
};

export default {
  parameters: {
    ...storyDocs.parameters,
  },
  title: 'Components/Tag',
};
