// packages/react/src/components/Popover/Popover-story.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './story.scss';
import {
  CaretDown32,
  CaretLeft32,
  CaretRight32,
  CaretUp32,
} from '@carbon/icons-react';
import { withKnobs, boolean, select } from '@storybook/addon-knobs';
import React from 'react';
import { Popover, PopoverContent } from '../Popover';
import Button from '../Button';
import mdx from './Popover.mdx';
import { useOutsideClick } from '../../internal/useOutsideClick';

export default {
  title: 'Experimental/unstable_Popover',
  component: Popover,
  subcomponents: {
    PopoverContent,
  },
  decorators: [withKnobs],
  parameters: {
    docs: {
      page: mdx,
    },
  },
  includeStories: ['Playground'],
};

export const Default = () => {
  function PopoverDemo() {
    const [align, setAlign] = React.useState('top');
    const [open, setOpen] = React.useState(true);
    const choices = [
      'top',
      'top-left',
      'top-right',

      'bottom',
      'bottom-left',
      'bottom-right',

      'left',
      'left-bottom',
      'left-top',

      'right',
      'right-bottom',
      'right-top',
    ];

    return (
      <>
        <section>
          <h2>Caret Position</h2>
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(3, auto)',
              gridGap: 8,
            }}>
            {choices.map((choice) => {
              return (
                <label key={choice}>
                  <input
                    type="radio"
                    name="align"
                    value={choice}
                    checked={choice === align}
                    onChange={() => {
                      setAlign(choice);
                    }}
                  />
                  {choice}
                </label>
              );
            })}
          </div>
        </section>
        <section>
          <h2>Popover Visibility</h2>
          <div>
            <label>
              <input
                type="checkbox"
                value={open}
                checked={open}
                onChange={() => {
                  setOpen(!open);
                }}
              />
              Open
            </label>
          </div>
        </section>
        <div style={{ marginTop: '2rem' }}>
          <Popover open={open} align={align} relative>
            <PopoverContent className="p-3">Hello</PopoverContent>
          </Popover>
        </div>
      </>
    );
  }

  return <PopoverDemo />;
};

export const Playground = () => {
  const options = [
    'top',
    'top-left',
    'top-right',

    'bottom',
    'bottom-left',
    'bottom-right',

    'left',
    'left-bottom',
    'left-top',

    'right',
    'right-bottom',
    'right-top',
  ];

  return (
    <Popover
      align={select('Specify the caret alignment (align)', options, 'top')}
      caret={boolean(
        'Specify whether the caret should be visible (caret)',
        true
      )}
      highContrast={boolean(
        'Specify whether the high-contrast variant should render (highContrast)',
        false
      )}
      light={boolean(
        'Specify whether the light variant should render (light)',
        false
      )}
      open={boolean(
        'Specify whether the popover is open or closed (open)',
        true
      )}>
      <PopoverContent className="p-3">Sample content</PopoverContent>
    </Popover>
  );
};

Playground.story = {
  decorators: [
    (story) => (
      <div className="mt-9">
        <div className="position-relative">{story()}</div>
      </div>
    ),
  ],
};

export const Examples = () => {
  function Example({
    children,
    align,
    relative = false,
    icon,
    size,
    flip = false,
    ...rest
  }) {
    const ref = React.useRef(null);
    const [open, setOpen] = React.useState(false);

    useOutsideClick(ref, () => {
      if (open === true) {
        setOpen(false);
      }
    });

    if (flip) {
      return (
        <div ref={ref} {...rest}>
          <Popover align={align} open={open} relative={relative}>
            <PopoverContent className="p-3">{children}</PopoverContent>
          </Popover>
          <Button
            iconDescription="Toggle"
            hasIconOnly
            onClick={() => {
              setOpen(!open);
            }}
            renderIcon={icon}
            size={size}
          />
        </div>
      );
    }

    return (
      <div ref={ref} {...rest}>
        <Button
          iconDescription="Toggle"
          hasIconOnly
          onClick={() => {
            setOpen(!open);
          }}
          renderIcon={icon}
          size={size}
        />
        <Popover align={align} open={open} relative={relative}>
          <PopoverContent className="p-3">{children}</PopoverContent>
        </Popover>
      </div>
    );
  }

  return (
    <>
      <Example
        className="position-relative mb-3"
        icon={CaretDown32}
        align="top-left">
        This is some text
      </Example>

      <Example
        className="position-relative mb-3"
        icon={CaretDown32}
        align="top-left"
        size="sm">
        This is some text
      </Example>

      <Example
        className="flex justify-center position-relative mb-3"
        icon={CaretDown32}
        align="top">
        This is some text
      </Example>

      <Example
        className="flex justify-center position-relative mb-3"
        icon={CaretDown32}
        align="top"
        size="sm">
        This is some text
      </Example>

      <Example
        className="flex justify-end position-relative mb-3"
        icon={CaretDown32}
        align="top-right">
        This is some text
      </Example>

      <Example
        className="flex justify-end position-relative mb-3"
        icon={CaretDown32}
        align="top-right"
        size="sm">
        This is some text
      </Example>

      <Example
        className="position-relative mb-3"
        icon={CaretUp32}
        align="bottom-left">
        This is some text
      </Example>

      <Example
        className="position-relative mb-3"
        icon={CaretUp32}
        align="bottom-left"
        size="sm">
        This is some text
      </Example>

      <Example
        className="flex justify-center position-relative mb-3"
        icon={CaretUp32}
        align="bottom">
        This is some text
      </Example>

      <Example
        className="flex justify-center position-relative mb-3"
        icon={CaretUp32}
        align="bottom"
        size="sm">
        This is some text
      </Example>

      <Example
        className="flex justify-end position-relative mb-3"
        icon={CaretUp32}
        align="bottom-right">
        This is some text
      </Example>

      <Example
        className="flex justify-end position-relative mb-3"
        icon={CaretUp32}
        align="bottom-right"
        size="sm">
        This is some text
      </Example>

      <div className="grid grid-cols-3 mb-3">
        <div>
          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretRight32}
            align="left"
            relative>
            This is some text
          </Example>

          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretRight32}
            align="left"
            size="sm"
            relative>
            This is some text
          </Example>
        </div>

        <div>
          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretRight32}
            align="left-top"
            relative>
            This is some text
          </Example>

          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretRight32}
            align="left-top"
            size="sm"
            relative>
            This is some text
          </Example>
        </div>

        <div>
          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretRight32}
            align="left-bottom"
            relative>
            This is some text
          </Example>

          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretRight32}
            align="left-bottom"
            size="sm"
            relative>
            This is some text
          </Example>
        </div>
      </div>

      <div className="grid grid-cols-3 justify-items-end mb-3">
        <div>
          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretLeft32}
            align="right"
            relative
            flip>
            This is some text
          </Example>

          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretLeft32}
            align="right"
            size="sm"
            relative
            flip>
            This is some text
          </Example>
        </div>

        <div>
          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretLeft32}
            align="right-top"
            relative
            flip>
            This is some text
          </Example>

          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretLeft32}
            align="right-top"
            size="sm"
            relative
            flip>
            This is some text
          </Example>
        </div>

        <div>
          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretLeft32}
            align="right-bottom"
            relative
            flip>
            This is some text
          </Example>

          <Example
            className="position-relative flex align-center mb-3"
            icon={CaretLeft32}
            align="right-bottom"
            size="sm"
            relative
            flip>
            This is some text
          </Example>
        </div>
      </div>

      <Example
        className="position-relative mb-3"
        icon={CaretDown32}
        align="top-left">
        Consectetur et sit accusamus laboriosam pariatur. Asperiores eius
        expedita eligendi beatae vero commodi harum Illo hic accusamus fugit
        commodi cupiditate Explicabo distinctio quisquam culpa fugit eius
        Provident voluptatum ipsam quo.
      </Example>
    </>
  );
};

// web-components/packages/carbon-web-components/src/components/popover/popover-story.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { boolean, select } from '@storybook/addon-knobs';
import './popover';
import './popover-content';
import '../radio-button/index';
import { POPOVER_ALIGNMENT } from './defs';
import storyDocs from './popover-story.mdx';
import { prefix } from '../../globals/settings';
import Checkbox16 from '@carbon/icons/lib/checkbox/16';
import Settings16 from '@carbon/icons/lib/settings/16';

import styles from './popover-story.scss?lit';

const popoverAlignments = {
  [`top`]: POPOVER_ALIGNMENT.TOP,
  [`top-left`]: POPOVER_ALIGNMENT.TOP_LEFT,
  [`top-right`]: POPOVER_ALIGNMENT.TOP_RIGHT,
  [`bottom`]: POPOVER_ALIGNMENT.BOTTOM,
  [`bottom-left`]: POPOVER_ALIGNMENT.BOTTOM_LEFT,
  [`bottom-right`]: POPOVER_ALIGNMENT.BOTTOM_RIGHT,
  [`left`]: POPOVER_ALIGNMENT.LEFT,
  [`left-bottom`]: POPOVER_ALIGNMENT.LEFT_BOTTOM,
  [`left-top`]: POPOVER_ALIGNMENT.LEFT_TOP,
  [`right`]: POPOVER_ALIGNMENT.RIGHT,
  [`right-bottom`]: POPOVER_ALIGNMENT.RIGHT_BOTTOM,
  [`right-top`]: POPOVER_ALIGNMENT.RIGHT_TOP,
};

export const Playground = (args) => {
  const { caret, highContrast, align, dropShadow, open } =
    args?.[`${prefix}-popover`] ?? {};
  return html`
    <style>
      ${styles}
    </style>
    <cds-popover
      ?open=${open}
      ?caret=${caret}
      ?highContrast=${highContrast}
      align=${align}
      ?dropShadow=${dropShadow}>
      <div class="playground-trigger">${Checkbox16()}</div>
      <cds-popover-content>
        <div class="p-3">
          <p class="popover-title">Available storage</p>
          <p class="popover-details">
            This server has 150 GB of block storage remaining.
          </p>
        </div>
      </cds-popover-content>
    </cds-popover>
  `;
};

Playground.storyName = 'Playground';

export const TabTip = () => {
  const handleClick = (id) => {
    const popover = document.querySelector(id);
    const open = popover?.hasAttribute('open');
    open ? popover?.removeAttribute('open') : popover?.setAttribute('open', '');
  };

  return html`
    <style>
      ${styles}
    </style>
    <div class="popover-tabtip-story" style="display: 'flex'">
      <cds-popover open tabTip id="popover-one">
        <button
          aria-label="Settings"
          type="button"
          @click="${() => handleClick('#popover-one')}">
          ${Settings16()}
        </button>
        <cds-popover-content>
          <div class="p-3">
            <cds-form-item>
              <cds-radio-button-group
                legend-text="Row height"
                name="radio-button-group"
                value="small"
                style="align-items: flex-start; flex-direction: column">
                <cds-radio-button
                  label-text="Small"
                  value="small"
                  id="radio-small"></cds-radio-button>
                <cds-radio-button
                  label-text="Large"
                  value="large"
                  id="radio-large"></cds-radio-button>
              </cds-radio-button-group>
            </cds-form-item>
            <hr />
            <fieldset class="${prefix}--fieldset">
              <legend class="${prefix}--label">Edit columns</legend>
              <cds-checkbox
                checked
                label-text="Name"
                id="checkbox-label-1"></cds-checkbox>
              <cds-checkbox
                checked
                label-text="Type"
                id="checkbox-label-2"></cds-checkbox>
              <cds-checkbox
                checked
                label-text="Location"
                id="checkbox-label-3"></cds-checkbox>
            </fieldset>
          </div>
        </cds-popover-content>
      </cds-popover>
      <cds-popover tabTip id="popover-two" align="bottom-right">
        <button
          aria-label="Settings"
          type="button"
          @click="${() => handleClick('#popover-two')}">
          ${Settings16()}
        </button>
        <cds-popover-content>
          <div class="p-3">
            <cds-form-item>
              <cds-radio-button-group
                legend-text="Row height"
                name="radio-button-group"
                value="small"
                style="align-items: flex-start; flex-direction: column">
                <cds-radio-button
                  label-text="Small"
                  value="small"
                  id="radio-small"></cds-radio-button>
                <cds-radio-button
                  label-text="Large"
                  value="large"
                  id="radio-large"></cds-radio-button>
              </cds-radio-button-group>
            </cds-form-item>
            <hr />
            <fieldset class="${prefix}--fieldset">
              <legend class="${prefix}--label">Edit columns</legend>
              <cds-checkbox
                checked
                label-text="Name"
                id="checkbox-label-1"></cds-checkbox>
              <cds-checkbox
                checked
                label-text="Type"
                id="checkbox-label-2"></cds-checkbox>
              <cds-checkbox
                checked
                label-text="Location"
                id="checkbox-label-3"></cds-checkbox>
            </fieldset>
          </div>
        </cds-popover-content>
      </cds-popover>
    </div>
  `;
};

Playground.parameters = {
  knobs: {
    [`${prefix}-popover`]: () => ({
      caret: boolean('caret (caret)', true),
      highContrast: boolean('high contrast (highContrast)', false),
      align: select(
        'Align (align)',
        popoverAlignments,
        popoverAlignments.bottom
      ),
      dropShadow: boolean('drop shadow (dropShadow)', true),
      open: boolean('open (open)', true),
    }),
  },
};

Playground.decorators = [
  (story) => html`<div class="mt-10 flex justify-center">${story()}</div>`,
];

export default {
  parameters: {
    ...storyDocs.parameters,
  },
  title: 'Components/Popover',
};
