// packages/react/src/components/Toggle/Toggle.Skeleton.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { settings } from 'carbon-components';

const { prefix } = settings;

export default class ToggleSkeleton extends React.Component {
  render() {
    const { id } = this.props;
    return (
      <div className={`${prefix}--form-item`}>
        <input
          type="checkbox"
          id={id}
          className={`${prefix}--toggle ${prefix}--skeleton`}
        />

        <label
          className={`${prefix}--toggle__label ${prefix}--skeleton`}
          htmlFor={id}>
          <span className={`${prefix}--toggle__text--left`} />
          <span className={`${prefix}--toggle__appearance`} />
          <span className={`${prefix}--toggle__text--right`} />
        </label>
      </div>
    );
  }
}

// packages/web-components/src/components/toggle/toggle-skeleton.ts
/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { classMap } from 'lit/directives/class-map.js';
import { prefix } from '../../globals/settings';
import styles from './toggle.scss?lit';

/**
 * @element cds-toggle-skeleton
 *
 * Skeleton of toggle.
 */
class CDSToggleSkeleton extends LitElement {
  static is = `${prefix}-toggle-skeleton`;

  render() {
    const skeletonClasses = classMap({
      [`${prefix}--toggle`]: true,
      [`${prefix}--toggle--skeleton`]: true,
    });

    return html`
      <div class=${skeletonClasses}>
        <div class="${prefix}--toggle__skeleton-circle"></div>
        <div class="${prefix}--toggle__skeleton-rectangle"></div>
      </div>
    `;
  }

  static styles = styles;
}

export default CDSToggleSkeleton;
