// packages/react/src/components/CodeSnippet/CodeSnippet.Skeleton.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React, { Component } from 'react';
import classNames from 'classnames';
import { settings } from 'carbon-components';

const { prefix } = settings;

export default class CodeSnippetSkeleton extends Component {
  static propTypes = {
    /**
     * The type of code snippet
     * can be single or multi
     */
    type: PropTypes.oneOf(['single', 'multi']),

    /**
     * Specify an optional className to be applied to the container node
     */
    className: PropTypes.string,
  };

  static defaultProps = {
    type: 'single',
  };

  render() {
    const { className, type, ...other } = this.props;

    const codeSnippetClasses = classNames(className, {
      [`${prefix}--snippet`]: true,
      [`${prefix}--skeleton`]: true,
      [`${prefix}--snippet--single`]: type === 'single',
      [`${prefix}--snippet--multi`]: type === 'multi',
    });

    if (type === 'single') {
      return (
        <div className={codeSnippetClasses} {...other}>
          <div className={`${prefix}--snippet-container`}>
            <span />
          </div>
        </div>
      );
    }

    if (type === 'multi') {
      return (
        <div className={codeSnippetClasses} {...other}>
          <div className={`${prefix}--snippet-container`}>
            <span />
            <span />
            <span />
          </div>
        </div>
      );
    }
  }
}

// web-components/packages/carbon-web-components/src/components/code-snippet/code-snippet-skeleton.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import { CODE_SNIPPET_TYPE } from './code-snippet';
import styles from './code-snippet.scss';

const { prefix } = settings;

/**
 * Skeleton of code snippet.
 */
@customElement(`${prefix}-code-snippet-skeleton`)
class BXCodeSnippetSkeleton extends LitElement {
  /**
   * The type of code snippet. Corresponds to the attribute with the same name.
   */
  @property({ reflect: true })
  type = CODE_SNIPPET_TYPE.SINGLE;

  render() {
    return html`
      <div class="${prefix}--snippet-container">
        ${this.type !== CODE_SNIPPET_TYPE.MULTI
          ? html` <span></span> `
          : html` <span></span><span></span><span></span> `}
      </div>
    `;
  }

  static styles = styles;
}

export default BXCodeSnippetSkeleton;
