// packages/web-components/src/components/add-select/add-select-selection-summary.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import '../tag/index';
import '../icon-button/index';
import { iconLoader } from '../../globals/internal/icon-loader';
import Edit16 from '@carbon/icons/es/edit/16';
import { prefix } from '../../globals/settings';
import styles from './add-select-selection-summary.scss?lit';

const blockClass = `${prefix}--add-select__next`;

/**
 * Add Select Selection Summary — displays the list of selected items.
 * @element cds-add-select-selection-summary
 * @slot default - SelectionSummaryItem components or custom body content
 * @slot header - Replaces the entire header section
 * @slot header-actions - Custom actions alongside the edit icon
 * @slot empty-state - Shown when selectedItemCount is 0 or not set
 * @fires cds-add-select-selection-summary-edit - Fired when edit icon is clicked
 */
@customElement(`${prefix}-add-select-selection-summary`)
class CDSAddSelectSelectionSummary extends LitElement {
  /**
   * Panel title
   */
  @property({ type: String })
  title = 'Selected items';

  /**
   * Number of selected items — shown as a badge next to the title when provided.
   * Badge is hidden when this is omitted/undefined.
   */
  @property({ type: Number, attribute: 'selected-item-count' })
  selectedItemCount: number | undefined = undefined;

  /**
   * Show edit icon next to title
   */
  @property({ type: Boolean, attribute: 'show-edit-icon', reflect: true })
  showEditIcon = false;

  /**
   * Accessible label for the edit icon button
   */
  @property({ type: String, attribute: 'edit-icon-description' })
  editIconDescription = 'Edit selections';

  private _handleEdit() {
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectSelectionSummary).eventEdit,
        { bubbles: true, cancelable: true, composed: true }
      )
    );
  }

  render() {
    const { title, selectedItemCount, showEditIcon, editIconDescription } =
      this;

    const showBody = selectedItemCount !== undefined && selectedItemCount > 0;

    return html`
      <div class="${blockClass}__selection-summary">
        <!-- Header -->
        <div class="${blockClass}__selection-summary-header">
          <slot name="header">
            <p class="${blockClass}__selection-summary-title">${title}</p>
            ${selectedItemCount !== undefined
              ? html`<cds-tag type="gray" size="sm"
                  >${selectedItemCount}</cds-tag
                >`
              : nothing}
            ${showEditIcon
              ? html`
                  <div class="${blockClass}__selection-summary-header-actions">
                    <slot name="header-actions"></slot>
                    <cds-icon-button
                      kind="ghost"
                      size="sm"
                      autoalign
                      class="${blockClass}__selection-summary-edit-button"
                      @click=${this._handleEdit}>
                      ${iconLoader(Edit16, { slot: 'icon' })}
                      <span slot="tooltip-content">${editIconDescription}</span>
                    </cds-icon-button>
                  </div>
                `
              : html`<slot name="header-actions"></slot>`}
          </slot>
        </div>

        <!-- Body: empty state or items -->
        <div class="${blockClass}__selection-summary-body">
          ${showBody
            ? html`<slot></slot>`
            : html`<slot name="empty-state"></slot>`}
        </div>
      </div>
    `;
  }

  /**
   * The name of the custom event fired when the edit icon is clicked.
   */
  static get eventEdit() {
    return `${prefix}-add-select-selection-summary-edit`;
  }

  static styles = styles;
}

export default CDSAddSelectSelectionSummary;

// packages/ibm-products/src/components/AddSelect/next/AddSelectSelectionSummary.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { forwardRef, ForwardedRef, ReactNode } from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import {
  Tag,
  IconButton,
  type TagProps,
  type IconButtonProps,
} from '@carbon/react';
import { Edit } from '@carbon/react/icons';
import type { AddSelectItem } from '@carbon/ibm-products';
import { blockClass } from './context';

/**
 * ----------------
 * AddSelectSelectionSummary
 * ----------------
 */

export interface AddSelectSelectionSummaryProps {
  /**
   * Panel title
   */
  title?: string;
  /**
   * Array of selected items
   */
  selectedItems?: AddSelectItem[];
  /**
   * Custom content or SelectionSummaryPanelItem components
   */
  children?: ReactNode;
  /**
   * Custom empty state component (user provides)
   */
  emptyState?: ReactNode;
  /**
   * Show count badge
   */
  showCount?: boolean;
  /**
   * Show edit icon next to count
   */
  showEditIcon?: boolean;
  /**
   * Edit icon click handler
   */
  onEdit?: () => void;
  /**
   * Edit icon aria-label
   */
  editIconDescription?: string;
  /**
   * Optional class name
   */
  className?: string;
  /**
   * Custom item renderer
   */
  renderItem?: (item: AddSelectItem) => ReactNode;
  /**
   * Custom header content (slot) - replaces entire header section
   */
  headerContent?: ReactNode;
  /**
   * Header actions slot - adds custom actions alongside the edit icon
   */
  headerActions?: ReactNode;
  /**
   * Additional props to pass to the Tag component
   */
  tagProps?: Omit<TagProps<'div'>, 'type' | 'size' | 'children'>;
  /**
   * Additional props to pass to the edit IconButton
   */
  editIconButtonProps?: Omit<
    IconButtonProps,
    'label' | 'onClick' | 'kind' | 'size' | 'className' | 'children'
  >;
}

/**
 * AddSelectSelectionSummary - Displays list of selected items
 * @example
 * Basic usage:
 * ```jsx
 * <AddSelect.SelectionSummaryPanel
 *   title="Selected items"
 *   selectedItems={items}
 *   showCount
 *   showEditIcon
 *   onEdit={handleEdit}
 * />
 * ```
 *
 * With custom header actions:
 * ```jsx
 * <AddSelect.SelectionSummaryPanel
 *   title="Selected items"
 *   selectedItems={items}
 *   showCount
 *   headerActions={
 *     <>
 *       <IconButton label="Filter" kind="ghost" size="sm">
 *         <Filter />
 *       </IconButton>
 *       <IconButton label="Sort" kind="ghost" size="sm">
 *         <Sort />
 *       </IconButton>
 *     </>
 *   }
 * />
 * ```
 *
 * With fully custom header:
 * ```jsx
 * <AddSelect.SelectionSummaryPanel
 *   selectedItems={items}
 *   headerContent={
 *     <div className="custom-header">
 *       <h3>My Custom Header</h3>
 *       <Button>Custom Action</Button>
 *     </div>
 *   }
 * />
 * ```
 */
const AddSelectSelectionSummary = forwardRef<
  HTMLDivElement,
  AddSelectSelectionSummaryProps
>(
  (
    {
      title = 'Selected items',
      selectedItems = [],
      children,
      emptyState,
      showCount = true,
      showEditIcon = false,
      onEdit,
      editIconDescription = 'Edit selections',
      className,
      renderItem,
      headerContent,
      headerActions,
      tagProps,
      editIconButtonProps,
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const panelClasses = cx(`${blockClass}__selection-summary`, className);

    const hasSelections = selectedItems.length > 0;

    return (
      <div className={panelClasses} ref={ref} {...rest}>
        {/* Header with title, count, and optional edit icon */}
        <div className={`${blockClass}__selection-summary-header`}>
          {headerContent || (
            <>
              <p className={`${blockClass}__selection-summary-title`}>
                {title}
              </p>
              {showCount && (
                <Tag type="gray" size="sm" {...tagProps}>
                  {selectedItems.length}
                </Tag>
              )}
              {(showEditIcon || headerActions) && (
                <div
                  className={`${blockClass}__selection-summary-header-actions`}
                >
                  {headerActions}
                  {showEditIcon && (
                    <IconButton
                      label={editIconDescription}
                      onClick={onEdit}
                      kind="ghost"
                      size="sm"
                      autoAlign
                      className={`${blockClass}__selection-summary-edit-button`}
                      {...editIconButtonProps}
                    >
                      <Edit size={16} />
                    </IconButton>
                  )}
                </div>
              )}
            </>
          )}
        </div>

        {/* Body content */}
        <div className={`${blockClass}__selection-summary-body`}>
          {hasSelections ? (
            children ? (
              children
            ) : renderItem ? (
              selectedItems.map((item) => (
                <div key={item.id}>{renderItem(item)}</div>
              ))
            ) : (
              // Default rendering - simple list
              <div>
                {selectedItems.map((item) => (
                  <div
                    key={item.id}
                    className={`${blockClass}__selection-summary-item-default`}
                  >
                    <div
                      className={`${blockClass}__selection-summary-item-default-title`}
                    >
                      {item.title}
                    </div>
                    {item.subtitle && (
                      <div
                        className={`${blockClass}__selection-summary-item-default-subtitle`}
                      >
                        {item.subtitle}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )
          ) : (
            emptyState
          )}
        </div>
      </div>
    );
  }
);

AddSelectSelectionSummary.propTypes = {
  children: PropTypes.node,
  className: PropTypes.string,
  /**@ts-ignore */
  editIconButtonProps: PropTypes.object,
  editIconDescription: PropTypes.string,
  emptyState: PropTypes.node,
  headerActions: PropTypes.node,
  headerContent: PropTypes.node,
  /**@ts-ignore */
  onEdit: PropTypes.func,
  /**@ts-ignore */
  renderItem: PropTypes.func,
  /**@ts-ignore */
  selectedItems: PropTypes.arrayOf(PropTypes.object),
  showCount: PropTypes.bool,
  showEditIcon: PropTypes.bool,
  /**@ts-ignore */
  tagProps: PropTypes.object,
  title: PropTypes.string,
};

AddSelectSelectionSummary.displayName = 'AddSelectSelectionSummary';

export default AddSelectSelectionSummary;
