// packages/web-components/src/components/add-select/add-select-item-panel.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { property, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import '../icon-button/index';
import { iconLoader } from '../../globals/internal/icon-loader';
import Close16 from '@carbon/icons/es/close/16';
import { prefix } from '../../globals/settings';
import type { AddSelectItem } from '@carbon/utilities';
import styles from './add-select-item-panel.scss?lit';

const blockClass = `${prefix}--add-select__next`;

/**
 * Add Select Item Panel — side panel displaying detailed information about an item.
 * CSS modifier `${blockClass}__item-summary-panel--open` is added when `open` is true,
 * enabling CSS-driven slide-in/out transitions.
 * @element cds-add-select-item-panel
 * @slot default - Highest priority: replaces all body rendering when populated
 * @slot render-item - Medium priority: receives item for custom rendering
 * @fires cds-add-select-item-panel-close - Fired when close icon is clicked
 */
@customElement(`${prefix}-add-select-item-panel`)
class CDSAddSelectItemPanel extends LitElement {
  /**
   * Panel title
   */
  @property({ type: String })
  title = 'Item details';

  /**
   * Item data (set via JS property)
   */
  @property({ attribute: false })
  item: AddSelectItem | null = null;

  /**
   * Controls panel visibility via CSS modifier class (enables CSS transitions)
   */
  @property({ type: Boolean, reflect: true })
  open = false;

  /**
   * Accessible label for the close icon button
   */
  @property({ type: String, attribute: 'close-icon-description' })
  closeIconDescription = 'Close';

  /**
   * Whether to show the close button
   */
  @property({ type: Boolean, attribute: 'show-close-button', reflect: true })
  showCloseButton = true;

  private _handleClose() {
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectItemPanel).eventClose,
        { bubbles: true, cancelable: true, composed: true }
      )
    );
  }

  private _renderDefaultContent() {
    const { item } = this;
    if (!item) {
      return nothing;
    }
    const { itemDetails } = item;
    if (
      !itemDetails ||
      !Array.isArray(itemDetails) ||
      itemDetails.length === 0
    ) {
      return nothing;
    }
    return html`
      ${(itemDetails as Array<{ label: string; value: unknown }>).map(
        ({ label, value: val }) => html`
          <div class="${blockClass}__item-summary-panel-entry">
            <p class="${blockClass}__item-summary-panel-entry-title">
              ${label}
            </p>
            <p class="${blockClass}__item-summary-panel-entry-body">
              ${String(val)}
            </p>
          </div>
        `
      )}
    `;
  }

  /** Whether the default slot has assigned elements */
  @state()
  private _hasDefaultSlot = false;

  /** Whether the render-item slot has assigned elements */
  @state()
  private _hasRenderItemSlot = false;

  private _handleDefaultSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this._hasDefaultSlot = slot.assignedElements({ flatten: true }).length > 0;
  }

  private _handleRenderItemSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this._hasRenderItemSlot =
      slot.assignedElements({ flatten: true }).length > 0;
  }

  render() {
    const { title, open, closeIconDescription, showCloseButton } = this;

    const panelClasses = classMap({
      [`${blockClass}__item-summary-panel`]: true,
      [`${blockClass}__item-summary-panel--open`]: open,
    });

    // Priority: default slot > render-item slot > default item details
    const showDefault = this._hasDefaultSlot;
    const showRenderItem = !showDefault && this._hasRenderItemSlot;
    const showItemDetails = !showDefault && !showRenderItem;

    return html`
      <div class=${panelClasses}>
        <!-- Header -->
        <div class="${blockClass}__item-summary-panel-header">
          <p class="${blockClass}__item-summary-panel-title">${title}</p>
          ${showCloseButton
            ? html`
                <cds-icon-button
                  kind="ghost"
                  size="sm"
                  autoalign
                  class="${blockClass}__item-summary-panel-close"
                  @click=${this._handleClose}>
                  ${iconLoader(Close16, { slot: 'icon' })}
                  <span slot="tooltip-content">${closeIconDescription}</span>
                </cds-icon-button>
              `
            : nothing}
        </div>

        <!-- Body: each slot exists once; wrappers hide/show via display:none -->
        <div class="${blockClass}__item-summary-panel-body">
          <!-- default slot — always in DOM -->
          <div style=${showDefault ? '' : 'display:none'}>
            <slot @slotchange=${this._handleDefaultSlotChange}></slot>
          </div>
          <!-- render-item slot — always in DOM -->
          <div style=${showRenderItem ? '' : 'display:none'}>
            <slot
              name="render-item"
              @slotchange=${this._handleRenderItemSlotChange}></slot>
          </div>
          <!-- default item details — shown when no slot content -->
          <div style=${showItemDetails ? '' : 'display:none'}>
            ${this._renderDefaultContent()}
          </div>
        </div>
      </div>
    `;
  }

  /**
   * The name of the custom event fired when the close icon is clicked.
   */
  static get eventClose() {
    return `${prefix}-add-select-item-panel-close`;
  }

  static styles = styles;
}

export default CDSAddSelectItemPanel;

// packages/ibm-products/src/components/AddSelect/next/AddSelectItemPanel.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, {
  forwardRef,
  ForwardedRef,
  ReactNode,
  isValidElement,
} from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { IconButton, type IconButtonProps } from '@carbon/react';
import { Close } from '@carbon/react/icons';
import type { AddSelectItem } from '@carbon/ibm-products';
import { blockClass } from './context';

/**
 * ----------------
 * AddSelectItemPanel
 * ----------------
 */

export interface AddSelectItemPanelProps {
  /**
   * Panel title
   */
  title?: string;
  /**
   * Item data
   */
  item?: AddSelectItem;
  /**
   * Close button handler
   */
  onClose?: () => void;
  /**
   * Close button aria-label
   */
  closeIconDescription?: string;
  /**
   * Custom content - takes highest priority
   */
  children?: ReactNode;
  /**
   * Custom template for rendering the entire panel body content
   * Takes precedence over default rendering
   */
  renderItem?: (item: AddSelectItem) => ReactNode;
  /**
   * Optional class name
   */
  className?: string;
  /**
   * Additional props to pass to the close IconButton
   */
  closeIconButtonProps?: Omit<
    IconButtonProps,
    'label' | 'onClick' | 'kind' | 'size' | 'className' | 'children'
  >;
}

/**
 * AddSelectItemPanel - Displays detailed information about a specific item
 * @example
 * ```jsx
 * <AddSelect.ItemPanel
 *   title="Item details"
 *   item={item}
 *   onClose={handleClose}
 *   closeIconDescription="Close details"
 * />
 * ```
 */
const AddSelectItemPanel = forwardRef<HTMLDivElement, AddSelectItemPanelProps>(
  (
    {
      title = 'Item details',
      item,
      onClose,
      closeIconDescription = 'Close',
      children,
      renderItem,
      className,
      closeIconButtonProps,
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const panelClasses = cx(`${blockClass}__item-summary-panel`, className);

    // Default content rendering - show all key-value data from itemDetails
    const defaultContent = () => {
      if (!item) {
        return null;
      }

      const { itemDetails } = item;

      if (!itemDetails || Object.keys(itemDetails).length === 0) {
        return null;
      }

      const entries = Object.entries(itemDetails);

      return (
        <>
          {entries.map(([key, val]) => (
            <div
              key={key}
              className={`${blockClass}__item-summary-panel-entry`}
            >
              <p className={`${blockClass}__item-summary-panel-entry-title`}>
                {key}
              </p>
              <p className={`${blockClass}__item-summary-panel-entry-body`}>
                {String(val)}
              </p>
            </div>
          ))}
        </>
      );
    };

    // Render content based on priority
    const renderItemContent = () => {
      // Priority 1: children takes highest precedence
      if (children) {
        return children;
      }

      // Priority 2: renderItem
      if (renderItem && item) {
        return renderItem(item);
      }

      // Priority 3: default template
      return defaultContent();
    };

    return (
      <div className={panelClasses} ref={ref} {...rest}>
        {/* Header with title and close button */}
        <div className={`${blockClass}__item-summary-panel-header`}>
          <p className={`${blockClass}__item-summary-panel-title`}>{title}</p>
          {onClose && (
            <IconButton
              label={closeIconDescription}
              onClick={onClose}
              kind="ghost"
              size="sm"
              autoAlign
              className={`${blockClass}__item-summary-panel-close`}
              {...closeIconButtonProps}
            >
              <Close size={16} />
            </IconButton>
          )}
        </div>

        {/* Body content */}
        <div className={`${blockClass}__item-summary-panel-body`}>
          {renderItemContent()}
        </div>
      </div>
    );
  }
);

AddSelectItemPanel.propTypes = {
  children: PropTypes.node,
  className: PropTypes.string,
  /**@ts-ignore */
  closeIconButtonProps: PropTypes.object,
  closeIconDescription: PropTypes.string,
  /**@ts-ignore */
  item: PropTypes.object,
  /**@ts-ignore */
  onClose: PropTypes.func,
  /**@ts-ignore */
  renderItem: PropTypes.func,
  title: PropTypes.string,
};

AddSelectItemPanel.displayName = 'AddSelectItemPanel';

export default AddSelectItemPanel;
