// packages/web-components/src/components/slug/slug.ts
/**
 * Copyright IBM Corp. 2019, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import CDSToggleTip from '../toggle-tip/toggletip';
import styles from './slug.scss?lit';
import { SLUG_SIZE, SLUG_KIND } from './defs';
import Undo16 from '@carbon/icons/es/undo/16.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { cdsIcon } from '../../globals/internal/icon-loader';

/**
 * Basic slug.
 *
 * @deprecated This component has been deprecated, please use the <cds-ai-label> component instead.
 * @element cds-slug
 */
@customElement(`${prefix}-slug`)
export default class CDSSlug extends CDSToggleTip {
  @property({ reflect: true })
  slot = 'slug';
  /**
   * Specify the correct translation of the AI text
   */
  @property({ attribute: 'ai-text' })
  aiText = 'AI';

  /**
   * Specify additional text to be rendered next to the AI label in the inline variant
   */
  @property({ attribute: 'ai-text-label' })
  aiTextLabel = '';

  /**
   * Specify the type of Slug, from the following list of types: (default, inline)
   */
  @property({ reflect: true })
  kind = SLUG_KIND.DEFAULT;

  /**
   * Specify whether the revert button should be visible
   */
  @property({ type: Boolean, attribute: 'revert-active' })
  revertActive = false;

  /**
   * Specify whether the revert button should be visible
   */
  @property({ attribute: 'revert-label' })
  revertLabel = 'Revert to AI input';

  /**
   * Slug size should be mini, 2xs, xs, sm, md, lg, xl.
   */
  @property({ reflect: true })
  size = SLUG_SIZE.EXTRA_SMALL;

  /**
   * Specify the text that will be provided to the aria-label of the `Slug` button
   */
  @property({ attribute: 'slug-label' })
  slugLabel = 'Show information';

  @property()
  previousValue;

  protected _handleClick = () => {
    if (this.revertActive) {
      this.revertActive = false;
      this.removeAttribute('revert-active');
    } else {
      this.open = !this.open;
    }
  };

  protected _renderToggleTipLabel = () => {
    return html``;
  };

  protected _renderTooltipButton = () => {
    const { size, kind, aiText, aiTextLabel, slugLabel } = this;
    const ariaLabel = `${aiText} - ${slugLabel}`;
    const classes = classMap({
      [`${prefix}--toggletip-button`]: true,
      [`${prefix}--slug__button`]: true,
      [`${prefix}--slug__button--${size}`]: size,
      [`${prefix}--slug__button--${kind}`]: kind,
      [`${prefix}--slug__button--inline-with-content`]:
        kind === SLUG_KIND.INLINE && aiTextLabel,
    });
    return html`
      <button
        aria-controls="${this.id}"
        @click="${this._handleClick}"
        class=${classes}
        aria-label="${ariaLabel}">
        <span class="${prefix}--slug__text">${aiText}</span>
        ${aiTextLabel && kind === SLUG_KIND.INLINE
          ? html`
              <span class="${prefix}--slug__additional-text">
                ${aiTextLabel}
              </span>
            `
          : ``}
      </button>
    `;
  };

  protected _renderInnerContent = () => {
    const { autoalign, revertActive, revertLabel } = this;
    return html`
      ${revertActive
        ? html`
            <cds-icon-button
              ?autoalign=${autoalign}
              kind="ghost"
              size="sm"
              @click="${this._handleClick}">
              <span slot="tooltip-content"> ${revertLabel} </span>
              ${cdsIcon(Undo16, { slot: 'icon' })}
            </cds-icon-button>
          `
        : html`
            ${this._renderTooltipButton()} ${this._renderTooltipContent()}
          `}
    `;
  };

  attributeChangedCallback(name, old, newValue) {
    super.attributeChangedCallback(name, old, newValue);

    //@ts-ignore typescript does not think requestUpdate() exists on parentElement
    name === 'revert-active' ? this.parentElement?.requestUpdate() : ``;
  }

  static styles = styles;
}

// packages/react/src/components/Slug/index.js
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import PropTypes from 'prop-types';
import React from 'react';

import { usePrefix } from '../../internal/usePrefix';
import {
  Toggletip,
  ToggletipButton,
  ToggletipContent,
  ToggletipActions,
} from '../Toggletip';
import { IconButton } from '../IconButton';
import { Undo } from '@carbon/icons-react';
import { useId } from '../../internal/useId';

export const SlugContent = React.forwardRef(function SlugContent(
  { children, className },
  ref
) {
  const prefix = usePrefix();

  const hasSlugActions = React.Children.toArray(children).some(
    (child) => child.type?.displayName === 'SlugActions'
  );

  const slugContentClasses = cx(className, {
    [`${prefix}--slug-content`]: true,
    [`${prefix}--slug-content--with-actions`]: hasSlugActions,
  });

  return (
    <ToggletipContent className={slugContentClasses} ref={ref}>
      {children}
    </ToggletipContent>
  );
});

SlugContent.displayName = 'SlugContent';
SlugContent.propTypes = {
  /**
   * Specify the content you want rendered inside the slug ToggleTip
   */
  children: PropTypes.node,

  /**
   * Specify an optional className to be added to the AI slug callout
   */
  className: PropTypes.string,
};

export const SlugActions = React.forwardRef(function SlugActions(
  { children, className },
  ref
) {
  const prefix = usePrefix();

  const slugActionBarClasses = cx(className, {
    [`${prefix}--slug-actions`]: true,
  });

  return (
    <ToggletipActions className={slugActionBarClasses} ref={ref}>
      {children}
    </ToggletipActions>
  );
});

SlugActions.displayName = 'SlugActions';
SlugActions.propTypes = {
  /**
   * Specify the content you want rendered inside the slug callout toolbar
   */
  children: PropTypes.node,

  /**
   * Specify an optional className to be added to the AI slug toolbar
   */
  className: PropTypes.string,
};

export const Slug = React.forwardRef(function Slug(
  {
    aiText = 'AI',
    aiTextLabel,
    align,
    autoAlign = true,
    children,
    className,
    kind = 'default',
    onRevertClick,
    revertActive,
    revertLabel = 'Revert to AI input',
    slugLabel = 'Show information',
    size = 'xs',
    ...rest
  },
  ref
) {
  const prefix = usePrefix();
  const id = useId('slug');

  const slugClasses = cx(className, {
    [`${prefix}--slug`]: true,
    [`${prefix}--slug--revert`]: revertActive,
  });

  const slugButtonClasses = cx({
    [`${prefix}--slug__button`]: true,
    [`${prefix}--slug__button--${size}`]: size,
    [`${prefix}--slug__button--${kind}`]: kind,
    [`${prefix}--slug__button--inline-with-content`]:
      kind === 'inline' && aiTextLabel,
  });

  const handleOnRevertClick = (evt) => {
    if (onRevertClick) {
      onRevertClick(evt);
    }
  };

  const ariaLabel = !aiTextLabel
    ? `${aiText} - ${slugLabel}`
    : `${aiText} - ${aiTextLabel}`;

  return (
    <div className={slugClasses} ref={ref} id={id}>
      {revertActive ? (
        <IconButton
          onClick={handleOnRevertClick}
          kind="ghost"
          size="sm"
          label={revertLabel}
          {...rest}>
          <Undo />
        </IconButton>
      ) : (
        <Toggletip align={align} autoAlign={autoAlign} {...rest}>
          <ToggletipButton className={slugButtonClasses} label={ariaLabel}>
            <span className={`${prefix}--slug__text`}>{aiText}</span>
            {aiTextLabel && (
              <span className={`${prefix}--slug__additional-text`}>
                {aiTextLabel}
              </span>
            )}
          </ToggletipButton>
          {children}
        </Toggletip>
      )}
    </div>
  );
});

Slug.displayName = 'Slug';
Slug.propTypes = {
  /**
   * Specify the correct translation of the AI text
   */
  aiText: PropTypes.string,

  /**
   * Specify additional text to be rendered next to the AI label in the inline variant
   */
  aiTextLabel: PropTypes.string,

  /**
   * Specify how the popover should align with the button
   */
  align: PropTypes.oneOf([
    'top',
    'top-left', // deprecated use top-start instead
    'top-right', // deprecated use top-end instead

    'bottom',
    'bottom-left', // deprecated use bottom-start instead
    'bottom-right', // deprecated use bottom-end instead

    'left',
    'left-bottom', // deprecated use left-end instead
    'left-top', // deprecated use left-start instead

    'right',
    'right-bottom', // deprecated use right-end instead
    'right-top', // deprecated use right-start instead

    // new values to match floating-ui
    'top-start',
    'top-end',
    'bottom-start',
    'bottom-end',
    'left-end',
    'left-start',
    'right-end',
    'right-start',
  ]),

  /**
   * Will auto-align the popover on first render if it is not visible. This prop is currently experimental and is subject to future changes.
   */
  autoAlign: PropTypes.bool,

  /**
   * Specify the content you want rendered inside the slug ToggleTip
   */
  children: PropTypes.node,

  /**
   * Specify an optional className to be added to the AI slug
   */
  className: PropTypes.string,

  /**
   * Specify the type of Slug, from the following list of types:
   */
  kind: PropTypes.oneOf(['default', 'inline']),

  /**
   * Callback function that fires when the revert button is clicked
   */
  onRevertClick: PropTypes.func,

  /**
   * Specify whether the revert button should be visible
   */
  revertActive: PropTypes.bool,

  /**
   * Specify the text that should be shown when the revert button is hovered
   */
  revertLabel: PropTypes.string,

  /**
   * Specify the size of the button, from the following list of sizes:
   */
  size: PropTypes.oneOf(['mini', '2xs', 'xs', 'sm', 'md', 'lg', 'xl']),

  /**
   * Specify the content you want rendered inside the slug ToggleTip
   */
  slugContent: PropTypes.node,

  /**
   * Specify the text that will be provided to the aria-label of the `Slug` button
   */
  slugLabel: PropTypes.string,
};
