// packages/ibm-products-web-components/examples/create-full-page/src/components/create-full-page.ts
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property, state } from 'lit/decorators.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element';
import '@carbon/web-components/es/components/button/index.js';
import '@carbon/web-components/es/components/inline-loading/index.js';
import '@carbon/web-components/es/components/modal/index.js';
import '@carbon/ibm-products-web-components/es/components/page-header/index.js';
import type { StepData } from './create-influencer';
import type { ActionButton } from '@carbon/ibm-products-web-components/es/components/action-set/index.js';
import '@carbon/ibm-products-web-components/es/components/action-set/index.js';
import styles from './create-full-page.scss?lit';

const blockClass = 'create-full-page-pattern';

/**
 * CreateFullPage component for web components
 */
@customElement('create-full-page')
export class CreateFullPage extends LitElement {
  /**
   * Page title
   */
  @property({ type: String })
  title = '';

  /**
   * Secondary title (for influencer)
   */
  @property({ type: String, attribute: 'secondary-title' })
  secondaryTitle = '';

  /**
   * Breadcrumbs array
   */
  @property({ type: Array })
  breadcrumbs: any[] = [];

  /**
   * Breadcrumbs overflow aria label
   */
  @property({ type: String, attribute: 'breadcrumbs-overflow-aria-label' })
  breadcrumbsOverflowAriaLabel = 'Open and close additional breadcrumb item list.';

  /**
   * Breadcrumb overflow tooltip alignment
   */
  @property({ type: String, attribute: 'breadcrumb-overflow-tooltip-align' })
  breadcrumbOverflowTooltipAlign = 'bottom';

  /**
   * Maximum visible breadcrumbs
   */
  @property({ type: Number, attribute: 'max-visible-breadcrumbs' })
  maxVisibleBreadcrumbs?: number;

  /**
   * Whether to show trailing slash in breadcrumbs
   */
  @property({ type: Boolean, attribute: 'no-trailing-slash' })
  noTrailingSlash = true;

  /**
   * Cancel button text
   */
  @property({ type: String, attribute: 'cancel-button-text' })
  cancelButtonText = 'Cancel';

  /**
   * Submit button text
   */
  @property({ type: String, attribute: 'submit-button-text' })
  submitButtonText = 'Submit';

  /**
   * Next button text
   */
  @property({ type: String, attribute: 'next-button-text' })
  nextButtonText = 'Next';

  /**
   * Back button text
   */
  @property({ type: String, attribute: 'back-button-text' })
  backButtonText = 'Back';

  /**
   * Modal title
   */
  @property({ type: String, attribute: 'modal-title' })
  modalTitle = 'Are you sure?';

  /**
   * Modal description
   */
  @property({ type: String, attribute: 'modal-description' })
  modalDescription = 'All unsaved changes will be lost.';

  /**
   * Modal danger button text
   */
  @property({ type: String, attribute: 'modal-danger-button-text' })
  modalDangerButtonText = 'Discard changes';

  /**
   * Modal secondary button text
   */
  @property({ type: String, attribute: 'modal-secondary-button-text' })
  modalSecondaryButtonText = 'Continue editing';

  /**
   * Callback when close is requested
   */
  @property({ attribute: false })
  onClose?: () => void;

  /**
   * Callback when submit is requested
   */
  @property({ attribute: false })
  onRequestSubmit?: (formState: any) => void | Promise<void>;

  /**
   * Callback when influencer step is clicked
   */
  @property({ attribute: false })
  onClickInfluencerStep?: (step: number) => void;

  @state()
  private currentStep = 1;

  @state()
  private totalSteps = 0;

  @state()
  private formState: any = {};

  @state()
  private isSubmitting = false;

  @state()
  private modalIsOpen = false;

  @state()
  private stepData: StepData[] = [];


  connectedCallback() {
    super.connectedCallback();
    this.extractStepData();
  }

  extractStepData() {
    const steps = Array.from(
      this.querySelectorAll('create-full-page-step')
    ) as any[];
    this.totalSteps = steps.length;
    this.stepData = steps.map((step) => ({
      title: step.getAttribute('title') || step.title,
      secondaryLabel: step.getAttribute('secondary-label') || step.secondaryLabel,
      shouldIncludeStep: true,
      disableSubmit: step.hasAttribute('disable-submit') || step.disableSubmit,
      invalid: step.hasAttribute('invalid') || step.invalid,
    }));
  }

  private async handleSubmit(e: Event) {
    e.preventDefault();
    if (this.currentStep === this.totalSteps) {
      this.isSubmitting = true;
      try {
        await this.onRequestSubmit?.(this.formState);
      } finally {
        this.isSubmitting = false;
      }
    } else {
      const currentStepElement = this.getCurrentStepElement();
      if (currentStepElement?.onNext) {
        this.isSubmitting = true;
        try {
          await currentStepElement.onNext();
          this.handleNext();
        } catch (error) {
          console.error('Step validation failed:', error);
        } finally {
          this.isSubmitting = false;
        }
      } else {
        this.handleNext();
      }
    }
  }

  private getCurrentStepElement() {
    const steps = Array.from(this.querySelectorAll('create-full-page-step'));
    return steps[this.currentStep - 1] as any;
  }

  private handleNext() {
    if (this.currentStep < this.totalSteps) {
      this.currentStep++;
      this.showCurrentStep();
    }
  }

  private handlePrevious() {
    if (this.currentStep > 1) {
      this.currentStep--;
      this.showCurrentStep();
    }
  }

  private handleGoToStep(step: number) {
    if (step >= 1 && step <= this.totalSteps) {
      this.currentStep = step;
      this.showCurrentStep();
    }
  }

  private showCurrentStep() {
    const steps = Array.from(this.querySelectorAll('create-full-page-step'));
    steps.forEach((step, index) => {
      (step as HTMLElement).style.display =
        index === this.currentStep - 1 ? 'block' : 'none';
    });
    this.requestUpdate();
  }

  private handleCancel() {
    this.modalIsOpen = true;
  }

  private handleModalClose() {
    this.modalIsOpen = false;
  }

  private handleModalConfirm() {
    this.onClose?.();
    this.handleGoToStep(1);
    this.formState = {};
    this.modalIsOpen = false;
  }

  private get isNextDisabled() {
    // Get the current step element directly from Light DOM
    const steps = Array.from(this.querySelectorAll('create-full-page-step')) as any[];
    const currentStepElement = steps[this.currentStep - 1];
    
    if (!currentStepElement) {
      return false;
    }
    
    // Check both the property and attribute for disableSubmit
    const disableSubmit = currentStepElement.disableSubmit ||
                         currentStepElement.hasAttribute('disable-submit');   
    return Boolean(disableSubmit);
  }

  private get actions(): ActionButton[] {
    return [
      {
        key: 'cancel',
        label: this.cancelButtonText,
        kind: 'ghost',       
        onClick: () => this.handleCancel(),
      },
      {
        key: 'back',
        label: this.backButtonText,
        kind: 'secondary',
        onClick: () => this.handlePrevious(),
        disabled: this.currentStep === 1,
      },
      {
        key: 'next',
        label:
          this.currentStep === this.totalSteps
            ? this.submitButtonText
            : this.nextButtonText,
        kind: 'primary',
        onClick: (e) => this.handleSubmit(e),
        loading: this.isSubmitting,
        disabled: this.isNextDisabled,
      },
    ];
  }

  firstUpdated() {
    this.moveStepsToForm();
    this.showCurrentStep();
  }

  updated(changedProperties: Map<string, any>) {
    super.updated(changedProperties);
  }

  private moveStepsToForm() {
    // Since we disabled shadow DOM, we need to manually move slotted steps into the form
    const steps = Array.from(this.querySelectorAll('create-full-page-step[slot="steps"]'));
    const form = this.querySelector(`.${blockClass}__form`);
    
    if (form && steps.length > 0) {
      steps.forEach(step => {
        form.appendChild(step);
      });
    }
  }

  render() {
    return html`
      <div class="${blockClass}">
        ${this.title || this.breadcrumbs.length > 0
          ? html`
              <c4p-page-header class="${blockClass}__header">
                <c4p-page-header-breadcrumb>
                  <c4p-page-header-breadcrumbs-set
                    .breadcrumbsData="${(this.breadcrumbs || []).map((item) => ({
                      text: item.label,
                      href: item.href || '#',
                    }))}"
                     title="page title"
                  ></c4p-page-header-breadcrumbs-set>
                </c4p-page-header-breadcrumb>
                <c4p-page-header-content title="${this.title}">
                </c4p-page-header-content>
              </c4p-page-header>
            `
          : ''}

        <div class="${blockClass}__influencer-and-body-container">
          <div class="${blockClass}__influencer">
            <create-influencer
              .stepData="${this.stepData}"
              current-step="${this.currentStep}"
              title="${this.secondaryTitle}"
              .onClickStep="${this.onClickInfluencerStep}"
            ></create-influencer>
          </div>

          <div class="${blockClass}__body">
            <div class="${blockClass}__main">
              <div class="${blockClass}__content">
                <form
                  class="${blockClass}__form"
                  aria-label="${this.title}"
                  @submit="${this.handleSubmit}"
                >
                  <slot name="steps"></slot>
                </form>
              </div>
              <div class="${blockClass}__buttons">
                <c4p-action-set size="xl">
                  <cds-button
                    kind="ghost"
                    size="2xl"
                    @click="${this.handleCancel}"
                  >
                    ${this.cancelButtonText}
                  </cds-button>
                  <cds-button
                    kind="secondary"
                    size="2xl"
                    ?disabled="${this.currentStep === 1 || this.isSubmitting}"
                    @click="${this.handlePrevious}"
                  >
                    ${this.backButtonText}
                  </cds-button>
                  ${this.isSubmitting
                    ? html`
                        <cds-button kind="primary" size="2xl" disabled>
                          ${this.currentStep === this.totalSteps
                            ? this.submitButtonText
                            : this.nextButtonText}
                          <cds-inline-loading
                            slot="icon"
                            aria-live="off"
                          ></cds-inline-loading>
                        </cds-button>
                      `
                    : html`
                        <cds-button
                          kind="primary"
                          size="2xl"
                          ?disabled="${this.isNextDisabled}"
                          @click="${this.handleSubmit}"
                        >
                          ${this.currentStep === this.totalSteps
                            ? this.submitButtonText
                            : this.nextButtonText}
                        </cds-button>
                      `}
                </c4p-action-set>
              </div>
            </div>
          </div>
  
          ${this.modalIsOpen
            ? html`
                <cds-modal
                  class="${blockClass}__modal"
                  size="sm"
                  ?open="${this.modalIsOpen}"
                  @cds-modal-closed="${this.handleModalClose}"
                >
                  <cds-modal-header>
                    <cds-modal-heading>${this.modalTitle}</cds-modal-heading>
                  </cds-modal-header>
                  <cds-modal-body>
                    <p>${this.modalDescription}</p>
                  </cds-modal-body>
                  <cds-modal-footer>
                    <cds-modal-footer-button
                      kind="secondary"
                      @click="${this.handleModalClose}"
                    >
                      ${this.modalSecondaryButtonText}
                    </cds-modal-footer-button>
                    <cds-modal-footer-button
                      kind="danger"
                      @click="${this.handleModalConfirm}"
                    >
                      ${this.modalDangerButtonText}
                    </cds-modal-footer-button>
                  </cds-modal-footer>
                </cds-modal>
              `
            : ''}
        </div>
      </div>
    `;
  }

  static styles = styles;
}

// packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx
/**
 * Copyright IBM Corp. 2021, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Carbon and package components we use.
import {
  Button,
  ComposedModal,
  Form,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Tooltip,
} from '@carbon/react';
// Import portions of React that are needed.
import React, {
  ForwardedRef,
  ReactNode,
  createContext,
  useEffect,
  useState,
  ReactElement,
  isValidElement,
} from 'react';
import { SimpleHeader } from '../SimpleHeader/SimpleHeader';
import {
  useCreateComponentFocus,
  useCreateComponentStepChange,
  usePreviousValue,
  useValidCreateStepCount,
} from '../../global/js/hooks';

import { ActionSet } from '../ActionSet';
import { CreateInfluencer } from '../CreateInfluencer';
// Other standard imports.
import PropTypes from 'prop-types';
import { StepsContextType } from '../CreateTearsheet/CreateTearsheet';
import cx from 'classnames';
import { getDevtoolsProps } from '../../global/js/utils/devtools';
import { getNumberOfHiddenSteps } from '../../global/js/utils/getNumberOfHiddenSteps';
import { lastIndexInArray } from '../../global/js/utils/lastIndexInArray';
import { pkg } from '../../settings';

const blockClass = `${pkg.prefix}--create-full-page`;
const componentName = 'CreateFullPage';

// This is a general context for the steps container
// containing information about the state of the container
// and providing some callback methods for steps to use
export const StepsContext = createContext<StepsContextType | null>(null);

// This is a context supplied separately to each step in the container
// to let it know what number it is in the sequence of steps
export const StepNumberContext = createContext(-1);

interface HeaderBreadcrumb {
  /** breadcrumb item key */
  key: string;
  /** breadcrumb item label */
  label: string;
  /** breadcrumb item link */
  href?: string;
  /** breadcrumb item title tooltip */
  title?: string;
  /** Provide if this breadcrumb item represents the current page */
  isCurrentPage?: boolean;
}

type MaybePromise<T> = Promise<T> | T;

type CreateFullPageBreadcrumbsProps =
  | {
      /** The header breadcrumbs */
      breadcrumbs?: null | undefined;

      /**
       * Label for open/close overflow button used for breadcrumb items that do not fit
       */
      breadcrumbsOverflowAriaLabel?: never;

      breadcrumbOverflowTooltipAlign?: never;
    }
  | {
      /** The header breadcrumbs */
      breadcrumbs: HeaderBreadcrumb[];

      /**
       * Label for open/close overflow button used for breadcrumb items that do not fit
       */
      breadcrumbsOverflowAriaLabel: string;

      breadcrumbOverflowTooltipAlign?: string;
    };

type CreateFullPageBaseProps = {
  /**
   * The back button text
   */
  backButtonText?: string;

  /**
   * The cancel button text
   */
  cancelButtonText: string;

  /**
   * The main content of the full page
   */
  children?: ReactNode;

  /**
   * Provide an optional class to be applied to the containing node.
   */
  className?: string;

  /**
   * Specifies elements to focus on first on render.
   */
  firstFocusElement?: string;

  /**
   * This can be used to open the component to a step other than the first step.
   * For example, a create flow was previously in progress, data was saved, and
   * is now being completed.
   */
  initialStep?: number;

  /**	Maximum visible breadcrumb-items before overflow is used (values less than 1 are treated as 1) */
  maxVisibleBreadcrumbs?: number;

  /**
   * The primary 'danger' button text in the modal
   */
  modalDangerButtonText: string;

  /**
   * The description located below the title in the modal
   */
  modalDescription?: string;

  /**
   * The secondary button text in the modal
   */
  modalSecondaryButtonText: string;

  /**
   * The title located in the header of the modal
   */
  modalTitle: string;

  /**
   * The next button text
   */
  nextButtonText: string;

  /**
   * A prop to omit the trailing slash for the breadcrumbs
   */
  noTrailingSlash?: boolean;

  /**
   * onChange event for Progress Indicator in the Influencer
   * @param data step index
   */
  onClickInfluencerStep?: (data: number) => void;

  /**
   * An optional handler that is called when the user closes the full page (by
   * clicking the secondary button, located in the modal, which triggers after
   * clicking the ghost button in the modal
   */
  onClose?: () => void;

  /**
   * Specify a handler for submitting the multi step full page (final step).
   * This function can _optionally_ return a promise that is either resolved or rejected and the CreateFullPage will handle the submitting state of the create button.
   *
   * @returns Object - if you want to prevent the modal from closing, return an object with the property preventClose set to true
   */
  onRequestSubmit: () => MaybePromise<{ preventClose?: boolean } | void>;

  /**
   * A secondary title of the full page, displayed in the influencer area
   */
  secondaryTitle?: string;

  /**
   * @ignore
   * The aria label to be used for the UI Shell SideNav Carbon component
   */
  sideNavAriaLabel?: string;

  /**
   * The submit button text
   */
  submitButtonText: string;

  /**
   * The main title of the full page, displayed in the header area
   */
  title?: string;
};

export type CreateFullPageProps = CreateFullPageBaseProps &
  CreateFullPageBreadcrumbsProps;

interface Step {
  introStep?: boolean;
  secondaryLabel?: string;
  shouldIncludeStep?: boolean;
  title?: string;
}
/**
 * Use with creations that must be completed in order for a service to be usable.
 *
 * ### Grid
 *
 * The `CreateFullPage` component utilizes Carbons' grid system in the inner
content of the main section inside of the component. You can read more guidance
on the Carbon's grid system
[here](https://www.carbondesignsystem.com/guidelines/2x-grid/overview). You can
include `<Row>` and `<Column>` components inside of each `CreateFullPageStep`
component to get the desired affect.
 */
export const CreateFullPage = React.forwardRef(
  (
    {
      breadcrumbsOverflowAriaLabel,
      breadcrumbs,
      backButtonText,
      cancelButtonText,
      children,
      className,
      initialStep,
      maxVisibleBreadcrumbs,
      modalDangerButtonText,
      modalDescription,
      modalSecondaryButtonText,
      modalTitle,
      nextButtonText,
      onClickInfluencerStep,
      onClose,
      onRequestSubmit,
      firstFocusElement,
      submitButtonText,
      noTrailingSlash,
      title,
      secondaryTitle,
      breadcrumbOverflowTooltipAlign = 'right',
      ...rest
    }: CreateFullPageProps,
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const [createFullPageActions, setCreateFullPageActions] = useState([]);
    const [shouldViewAll, setShouldViewAll] = useState(false);
    const [currentStep, setCurrentStep] = useState(1);
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [modalIsOpen, setModalIsOpen] = useState(false);
    const previousState = usePreviousValue({ currentStep });
    const [isDisabled, setIsDisabled] = useState(false);
    const [onPrevious, setOnPrevious] = useState();
    const [onNext, setOnNext] = useState();
    const [onMount, setOnMount] = useState();
    const [stepData, setStepData] = useState<Step[]>([]);
    const [firstIncludedStep, setFirstIncludedStep] = useState(1);
    const [lastIncludedStep, setLastIncludedStep] = useState<number>();
    const stepLength = React.Children.toArray(children).filter(
      (item) =>
        isValidElement(item) &&
        (item as ReactElement<any>).props.includeStep !== false
    ).length;

    useEffect(() => {
      const firstItem =
        stepData.findIndex((item) => item?.shouldIncludeStep) + 1;
      const lastItem = lastIndexInArray(stepData, 'shouldIncludeStep', true);
      if (firstItem !== firstIncludedStep) {
        setFirstIncludedStep(firstItem);
      }
      if (lastItem !== lastIncludedStep) {
        setLastIncludedStep(lastItem);
      }

      if (Number(initialStep) > stepLength || Number(initialStep) <= 0) {
        setCurrentStep(1);
      } else if (initialStep) {
        const numberOfHiddenSteps = getNumberOfHiddenSteps(
          stepData,
          initialStep
        );
        setCurrentStep(Number(initialStep + numberOfHiddenSteps));
      }
    }, [
      stepData,
      firstIncludedStep,
      lastIncludedStep,
      initialStep,
      modalIsOpen,
      stepLength,
    ]);

    useEffect(() => {
      checkForValidInitialStep();

      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [initialStep]);

    useCreateComponentFocus({
      previousState,
      currentStep,
      blockClass: `.${blockClass} .${pkg.prefix}--create-full-page__step`,
      onMount,
      firstFocusElement,
    });
    useValidCreateStepCount(stepData.length, componentName);
    useCreateComponentStepChange({
      firstIncludedStep,
      lastIncludedStep,
      stepData,
      onPrevious,
      onNext,
      isSubmitDisabled: isDisabled,
      setCurrentStep,
      setIsSubmitting,
      /**@ts-ignore */
      setShouldViewAll,
      onClose,
      onRequestSubmit,
      componentName,
      currentStep,
      shouldViewAll,
      backButtonText,
      cancelButtonText,
      submitButtonText,
      nextButtonText,
      isSubmitting,
      componentBlockClass: blockClass,
      setCreateComponentActions: setCreateFullPageActions,
      setModalIsOpen,
    });

    const checkForValidInitialStep = () => {
      if (
        (initialStep && stepLength && Number(initialStep) > stepLength) ||
        Number(initialStep) <= 0
      ) {
        console.warn(
          `${componentName}: An invalid \`initialStep\` prop was supplied. The \`initialStep\` prop should be a number that is greater than 0 or less than or equal to the number of steps your ${componentName} has.`
        );
      }
    };
    // currently, we are not supporting the use of 'view all' toggle state
    /* istanbul ignore next */
    return (
      <div
        {...rest}
        ref={ref}
        className={cx(blockClass, className)}
        {...getDevtoolsProps(componentName)}
      >
        {(title || breadcrumbs) && (
          <SimpleHeader
            title={title}
            breadcrumbs={breadcrumbs}
            noTrailingSlash={noTrailingSlash}
            overflowAriaLabel={breadcrumbsOverflowAriaLabel}
            maxVisible={maxVisibleBreadcrumbs}
            className={`${blockClass}__header`}
            overflowTooltipAlign={breadcrumbOverflowTooltipAlign}
          />
        )}
        <div className={`${blockClass}__influencer-and-body-container`}>
          <div className={`${blockClass}__influencer`}>
            <CreateInfluencer
              stepData={stepData}
              currentStep={currentStep}
              title={secondaryTitle}
              onClickStep={onClickInfluencerStep}
            />
          </div>
          <div className={`${blockClass}__body`}>
            <div className={`${blockClass}__main`}>
              <div className={`${blockClass}__content`}>
                <Form
                  className={`${blockClass}__form`}
                  aria-label={title}
                  onSubmit={(e: React.FormEvent<HTMLFormElement>) =>
                    e.preventDefault()
                  }
                >
                  <StepsContext.Provider
                    value={
                      {
                        currentStep,
                        setIsDisabled,
                        setOnPrevious: (fn) => setOnPrevious(() => fn),
                        setOnNext: (fn) => setOnNext(() => fn),
                        setOnMount: (fn) => setOnMount(() => fn),
                        setStepData,
                        stepData,
                      } as any
                    }
                  >
                    {React.Children.toArray(children)
                      .filter(Boolean)
                      .map((child, index) => (
                        <StepNumberContext.Provider
                          value={index + 1}
                          key={index}
                        >
                          {child}
                        </StepNumberContext.Provider>
                      ))}
                  </StepsContext.Provider>
                </Form>
              </div>
              <ActionSet
                className={`${blockClass}__buttons`}
                actions={createFullPageActions}
                buttonSize="2xl"
                size="2xl"
              />
            </div>
          </div>
          <ComposedModal
            className={`${blockClass}__modal`}
            size="sm"
            open={modalIsOpen}
            aria-label={modalTitle}
            onClose={() => {
              setModalIsOpen(false);
            }}
          >
            <ModalHeader title={modalTitle} />
            <ModalBody>
              <p>{modalDescription}</p>
            </ModalBody>
            <ModalFooter>
              <Button
                type="button"
                kind="secondary"
                onClick={() => {
                  setModalIsOpen(!modalIsOpen);
                }}
                data-modal-primary-focus
              >
                {modalSecondaryButtonText}
              </Button>
              <Button type="button" kind="danger" onClick={onClose}>
                {modalDangerButtonText}
              </Button>
            </ModalFooter>
          </ComposedModal>
        </div>
      </div>
    );
  }
);

// Return a placeholder if not released and not enabled by feature flag.

// The display name of the component, used by React. Note that displayName
// is used in preference to relying on function.name.
CreateFullPage.displayName = componentName;

// The types and DocGen commentary for the component props,
// in alphabetical order (for consistency).
// See https://www.npmjs.com/package/prop-types#usage.
CreateFullPage.propTypes = {
  /**
   * The back button text
   */
  backButtonText: PropTypes.string.isRequired,

  /**
   * align breadcrumb overflow tooltip
   */
  breadcrumbOverflowTooltipAlign: Tooltip.propTypes.align,

  /** The header breadcrumbs */
  /**@ts-ignore */
  breadcrumbs: PropTypes.arrayOf(
    PropTypes.shape({
      /** breadcrumb item key */
      key: PropTypes.string.isRequired,
      /** breadcrumb item label */
      label: PropTypes.string.isRequired,
      /** breadcrumb item link */
      href: PropTypes.string,
      /** breadcrumb item title tooltip */
      title: PropTypes.string,
      /** Provide if this breadcrumb item represents the current page */
      isCurrentPage: PropTypes.bool,
    })
  ),

  /**
   * Label for open/close overflow button used for breadcrumb items that do not fit
   */
  breadcrumbsOverflowAriaLabel: PropTypes.string,

  /**
   * The cancel button text
   */
  cancelButtonText: PropTypes.string.isRequired,

  /**
   * The main content of the full page
   */
  children: PropTypes.node,

  /**
   * Provide an optional class to be applied to the containing node.
   */
  className: PropTypes.string,

  /**
   * Specifies elements to focus on first on render.
   */
  firstFocusElement: PropTypes.string,

  /**
   * This can be used to open the component to a step other than the first step.
   * For example, a create flow was previously in progress, data was saved, and
   * is now being completed.
   */
  initialStep: PropTypes.number,

  /**	Maximum visible breadcrumb-items before overflow is used (values less than 1 are treated as 1) */
  maxVisibleBreadcrumbs: PropTypes.number,

  /**
   * The primary 'danger' button text in the modal
   */
  modalDangerButtonText: PropTypes.string.isRequired,

  /**
   * The description located below the title in the modal
   */
  modalDescription: PropTypes.string,

  /**
   * The secondary button text in the modal
   */
  modalSecondaryButtonText: PropTypes.string.isRequired,

  /**
   * The title located in the header of the modal
   */
  modalTitle: PropTypes.string.isRequired,

  /**
   * The next button text
   */
  nextButtonText: PropTypes.string.isRequired,

  /**
   * A prop to omit the trailing slash for the breadcrumbs
   */
  noTrailingSlash: PropTypes.bool,

  /**
   * onChange event for Progress Indicator in the Influencer
   */
  onClickInfluencerStep: PropTypes.func,

  /**
   * An optional handler that is called when the user closes the full page (by
   * clicking the secondary button, located in the modal, which triggers after
   * clicking the ghost button in the modal
   */
  onClose: PropTypes.func,

  /**
   * Specify a handler for submitting the multi step full page (final step).
   * This function can _optionally_ return a promise that is either resolved or rejected and the CreateFullPage will handle the submitting state of the create button.
   */
  onRequestSubmit: PropTypes.func.isRequired,

  /**
   * A secondary title of the full page, displayed in the influencer area
   */
  secondaryTitle: PropTypes.string,

  /**
   * @ignore
   * The aria label to be used for the UI Shell SideNav Carbon component
   */
  sideNavAriaLabel: PropTypes.string,

  /**
   * The submit button text
   */
  submitButtonText: PropTypes.string.isRequired,

  /**
   * The main title of the full page, displayed in the header area
   */
  title: PropTypes.string,
};
