// packages/react/src/components/AILabel/index.js
/**
 * Copyright IBM Corp. 2016, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import PropTypes from 'prop-types';
import React from 'react';

import { usePrefix } from '../../internal/usePrefix';
import {
  Toggletip,
  ToggletipButton,
  ToggletipContent,
  ToggletipActions,
} from '../Toggletip';
import { IconButton } from '../IconButton';
import { Undo } from '@carbon/icons-react';
import { useId } from '../../internal/useId';

export const AILabelContent = React.forwardRef(function AILabelContent(
  { children, className },
  ref
) {
  const prefix = usePrefix();

  const hasAILabelActions = React.Children.toArray(children).some(
    (child) => child.type?.displayName === 'AILabelActions'
  );

  const aiLabelContentClasses = cx(className, {
    [`${prefix}--slug-content`]: true,
    [`${prefix}--slug-content--with-actions`]: hasAILabelActions,
  });

  return (
    <ToggletipContent className={aiLabelContentClasses} ref={ref}>
      {children}
    </ToggletipContent>
  );
});

AILabelContent.displayName = 'AILabelContent';
AILabelContent.propTypes = {
  /**
   * Specify the content you want rendered inside the slug ToggleTip
   */
  children: PropTypes.node,

  /**
   * Specify an optional className to be added to the AI slug callout
   */
  className: PropTypes.string,
};

export const AILabelActions = React.forwardRef(function AILabelActions(
  { children, className },
  ref
) {
  const prefix = usePrefix();

  const aiLabelActionsClasses = cx(className, {
    [`${prefix}--slug-actions`]: true,
  });

  return (
    <ToggletipActions className={aiLabelActionsClasses} ref={ref}>
      {children}
    </ToggletipActions>
  );
});

AILabelActions.displayName = 'AILabelActions';
AILabelActions.propTypes = {
  /**
   * Specify the content you want rendered inside the slug callout toolbar
   */
  children: PropTypes.node,

  /**
   * Specify an optional className to be added to the AI slug toolbar
   */
  className: PropTypes.string,
};

export const AILabel = React.forwardRef(function AILabel(
  {
    aiText = 'AI',
    aiTextLabel,
    align,
    autoAlign = true,
    children,
    className,
    kind = 'default',
    onRevertClick,
    revertActive,
    revertLabel = 'Revert to AI input',
    slugLabel = 'Show information',
    size = 'xs',
    ...rest
  },
  ref
) {
  const prefix = usePrefix();
  const id = useId('AILabel');

  const aiLabelClasses = cx(className, {
    [`${prefix}--slug`]: true,
    [`${prefix}--slug--revert`]: revertActive,
  });

  const aiLabelButtonClasses = cx({
    [`${prefix}--slug__button`]: true,
    [`${prefix}--slug__button--${size}`]: size,
    [`${prefix}--slug__button--${kind}`]: kind,
    [`${prefix}--slug__button--inline-with-content`]:
      kind === 'inline' && aiTextLabel,
  });

  const handleOnRevertClick = (evt) => {
    if (onRevertClick) {
      onRevertClick(evt);
    }
  };

  const ariaLabel = !aiTextLabel
    ? `${aiText} - ${slugLabel}`
    : `${aiText} - ${aiTextLabel}`;

  return (
    <div className={aiLabelClasses} ref={ref} id={id}>
      {revertActive ? (
        <IconButton
          onClick={handleOnRevertClick}
          kind="ghost"
          size="sm"
          label={revertLabel}
          {...rest}>
          <Undo />
        </IconButton>
      ) : (
        <Toggletip align={align} autoAlign={autoAlign} {...rest}>
          <ToggletipButton className={aiLabelButtonClasses} label={ariaLabel}>
            <span className={`${prefix}--slug__text`}>{aiText}</span>
            {aiTextLabel && (
              <span className={`${prefix}--slug__additional-text`}>
                {kind === 'inline' && aiTextLabel}
              </span>
            )}
          </ToggletipButton>
          {children}
        </Toggletip>
      )}
    </div>
  );
});

AILabel.displayName = 'AILabel';
AILabel.propTypes = {
  /**
   * Specify the content you want rendered inside the `AILabel` ToggleTip
   */
  AILabelContent: PropTypes.node,

  /**
   * Specify the correct translation of the AI text
   */
  aiText: PropTypes.string,

  /**
   * Specify additional text to be rendered next to the AI label in the inline variant
   */
  aiTextLabel: PropTypes.string,

  /**
   * Specify how the popover should align with the button
   */
  align: PropTypes.oneOf([
    'top',
    'top-left', // deprecated use top-start instead
    'top-start',
    'top-right', // deprecated use top-end instead
    'top-end',

    'bottom',
    'bottom-left', // deprecated use bottom-start instead
    'bottom-start',
    'bottom-right', // deprecated use bottom-end instead
    'bottom-end',

    'left',
    'left-bottom', // deprecated use left-end instead
    'left-end',
    'left-top', // deprecated use left-start instead
    'left-start',

    'right',
    'right-bottom', // deprecated use right-end instead
    'right-end',
    'right-top', // deprecated use right-start instead
    'right-start',
  ]),

  /**
   * Will auto-align the popover. This prop is currently experimental and is subject to future changes.
   */
  autoAlign: PropTypes.bool,

  /**
   * Specify the content you want rendered inside the `AILabel` ToggleTip
   */
  children: PropTypes.node,

  /**
   * Specify an optional className to be added to the `AILabel`
   */
  className: PropTypes.string,

  /**
   * Specify the type of `AILabel`, from the following list of types:
   */
  kind: PropTypes.oneOf(['default', 'inline']),

  /**
   * Callback function that fires when the revert button is clicked
   */
  onRevertClick: PropTypes.func,

  /**
   * Specify whether the revert button should be visible
   */
  revertActive: PropTypes.bool,

  /**
   * Specify the text that should be shown when the revert button is hovered
   */
  revertLabel: PropTypes.string,

  /**
   * Specify the size of the button, from the following list of sizes:
   */
  size: PropTypes.oneOf(['mini', '2xs', 'xs', 'sm', 'md', 'lg', 'xl']),

  /**
   * Specify the text that will be provided to the aria-label of the `AILabel` button
   */
  slugLabel: PropTypes.string,
};

// packages/web-components/src/components/ai-label/ai-label.ts
/**
 * Copyright IBM Corp. 2019, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { adoptStyles, html, LitElement } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import CDSToggleTip from '../toggle-tip/toggletip';
import popoverStyles from '../popover/popover.scss?lit';
import toggletipStyles from '../toggle-tip/toggletip.scss?lit';
import styles from './ai-label.scss?lit';
import Undo16 from '@carbon/icons/es/undo/16.js';
import { AI_LABEL_SIZE, AI_LABEL_KIND } from './defs';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { iconLoader } from '../../globals/internal/icon-loader';

/**
 * Basic AI Label.
 *
 * @element cds-ai-label
 */
@customElement(`${prefix}-ai-label`)
class CDSAILabel extends CDSToggleTip {
  /**
   * @deprecated the slot string will be renamed to "decorator"
   */
  @property({ reflect: true })
  slot = 'ai-label';

  /**
   * Specify the correct translation of the AI text
   */
  @property({ attribute: 'ai-text' })
  aiText = 'AI';

  /**
   * Specify additional text to be rendered next to the AI label in the inline variant
   */
  @property({ attribute: 'ai-text-label' })
  aiTextLabel = '';

  /**
   * Specify the type of AI Label, from the following list of types: (default, inline)
   */
  @property({ reflect: true })
  kind = AI_LABEL_KIND.DEFAULT;

  /**
   * Specify whether the revert button should be visible
   */
  @property({ type: Boolean, attribute: 'revert-active' })
  revertActive = false;

  /**
   * Specify whether the revert button should be visible
   */
  @property({ attribute: 'revert-label' })
  revertLabel = 'Revert to AI input';

  /**
   * AI Label size should be mini, 2xs, xs, sm, md, lg, xl.
   */
  @property({ reflect: true })
  size = AI_LABEL_SIZE.EXTRA_SMALL;

  /**
   * Specify the text that will be provided to the aria-label of the `AI Label` button
   */
  @property({ attribute: 'button-label' })
  buttonLabel = 'Show information';

  @property()
  previousValue;

  connectedCallback() {
    super.connectedCallback();

    adoptStyles(this.renderRoot as ShadowRoot, [
      popoverStyles,
      toggletipStyles,
      styles,
    ]);
  }

  protected _handleClick = () => {
    if (this.revertActive) {
      this.revertActive = false;
      this.removeAttribute('revert-active');
    } else {
      super._handleClick();
    }
  };

  protected _renderToggleTipLabel = () => {
    return html``;
  };

  protected _renderTooltipButton = () => {
    const { size, kind, aiText, aiTextLabel, buttonLabel } = this;
    const ariaLabel = `${aiText} - ${buttonLabel}`;
    const classes = classMap({
      [`${prefix}--toggletip-button`]: true,
      [`${prefix}--slug__button`]: true,
      [`${prefix}--slug__button--${size}`]: size,
      [`${prefix}--slug__button--${kind}`]: kind,
      [`${prefix}--slug__button--inline-with-content`]:
        kind === AI_LABEL_KIND.INLINE && aiTextLabel,
    });
    return html`
      <button
        aria-controls="${this.id}"
        @click="${this._handleClick}"
        class=${classes}
        aria-label="${ariaLabel}">
        <span class="${prefix}--slug__text">${aiText}</span>
        ${aiTextLabel && kind === AI_LABEL_KIND.INLINE
          ? html`
              <span class="${prefix}--slug__additional-text">
                ${aiTextLabel}
              </span>
            `
          : ``}
      </button>
    `;
  };

  protected _renderInnerContent = () => {
    const { autoalign, revertActive, revertLabel } = this;
    return html`
      ${revertActive
        ? html`
            <cds-icon-button
              ?autoalign=${autoalign}
              kind="ghost"
              size="sm"
              @click="${this._handleClick}">
              <span slot="tooltip-content"> ${revertLabel} </span>
              ${iconLoader(Undo16, { slot: 'icon' })}
            </cds-icon-button>
          `
        : html`
            ${this._renderTooltipButton()} ${this._renderTooltipContent()}
          `}
    `;
  };

  attributeChangedCallback(name, old, newValue) {
    super.attributeChangedCallback(name, old, newValue);

    if (name === 'revert-active') {
      (this.parentElement as LitElement)?.requestUpdate();
    }
  }
}

export default CDSAILabel;
