// packages/web-components/src/components/interstitial-screen/interstitial-screen-footer.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, nothing, PropertyValues } from 'lit';
import { property, state } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import HostListenerMixin from '../../globals/mixins/host-listener';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import '../button/index';
import styles from './interstitial-screen-footer.scss?lit';
import { interstitialDetailsSignal } from './interstitial-screen-context';
import { SignalWatcher } from '@lit-labs/signals';
import '../inline-loading/index';
import CDSModalFooter from '../modal/modal-footer';
import ArrowRight from '@carbon/icons/es/arrow--right/16.js';
import { iconLoader } from '../../globals/internal/icon-loader';
import { registerFocusableContainers } from '../../utilities/manageFocusTrap/manageFocusTrap';
import '../action-set/index';

const blockClass = `${prefix}--interstitial-screen`;

export type ActionType = 'close' | 'start' | 'skip' | 'back' | 'next';

/**
 * interstitial-screen-footer for footer section
 * @element cds-interstitial-screen-footer
 * @fires cds-on-action - The name of the custom event fired just before the action. You can use this event to perform any async/sync validation.
 * if you pass async-action = true, the component will wait for an external listener (e.g., a form validation or confirmation modal) to resolve the proceed()
 *  callback before continuing. When asyncAction is true, you must listen for the eventOnBeforeAction event and call the proceed() function
 *  (either synchronously or with a promise) to allow navigation.
 */
@customElement(`${prefix}-interstitial-screen-footer`)
class CDSInterstitialScreenFooter extends SignalWatcher(
  HostListenerMixin(CDSModalFooter)
) {
  /**
   * The label for the Next button.
   */
  @property({ reflect: true })
  nextButtonLabel: string = 'Next';
  /**
   * The label for the Previous button.
   */
  @property({ reflect: true })
  previousButtonLabel: string = 'Back';
  /**
   * The label for the skip button.
   */
  @property({ reflect: true })
  skipButtonLabel: string = 'Skip';
  /**
   * The label for the start button.
   */
  @property({ reflect: true })
  startButtonLabel = 'Get Started';

  @property({ reflect: true })
  slot = 'footer';

  /**
   * Enables support for asynchronous validation or user confirmation before proceeding
   * to the next interstitial step. When set to true, the component will wait for an external
   *  listener (e.g., a form validation or confirmation modal) to resolve the proceed() callback before continuing.
   * When asyncAction is true, you must listen for the eventOnBeforeAction event and
   * call the proceed() function (either synchronously or with a promise) to allow navigation.
   */
  @property({ type: Boolean, reflect: true, attribute: 'async-action' })
  asyncAction;

  @state()
  loadingAction;

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  protected firstUpdated(_changedProperties?: PropertyValues): void {
    registerFocusableContainers(
      this.childNodes.length > 0 ? this : this.shadowRoot
    );
  }

  protected updated(_changedProperties: PropertyValues): void {
    if (_changedProperties.size === 0) {
      // This logic ensures the start/next button receives focus when focus is lost from the "next" or "back" buttons
      // during step navigation—particularly when those buttons are not rendered.
      this.updateComplete.then(() => {
        const { stepDetails, currentStep } = interstitialDetailsSignal.get();

        const isMultiStep =
          Array.isArray(stepDetails) && stepDetails.length > 0;
        const lastStepIndex = stepDetails?.length - 1;

        if (!isMultiStep) {
          return;
        }

        const focusButton = (selector: string) => {
          const btn = this.shadowRoot?.querySelector(
            selector
          ) as HTMLButtonElement | null;
          btn?.focus();
        };

        if (currentStep === lastStepIndex) {
          focusButton(`.${prefix}--interstitial-screen--start-btn`);
        } else if (currentStep === 0) {
          focusButton(`.${prefix}--interstitial-screen--next-btn`);
        }
      });
    }
  }

  private _handleUserInitiatedClose(
    triggeredBy: EventTarget | null | ActionType
  ) {
    const init = {
      bubbles: true,
      cancelable: true,
      composed: true,
      detail: {
        triggeredBy,
      },
    };

    this.dispatchEvent(
      new CustomEvent(
        (
          this.constructor as typeof CDSInterstitialScreenFooter
        ).eventRequestClose,
        init
      )
    );
  }

  private handleSkip = () => this.handleAction('skip');
  private handleStart = () => this.handleAction('start');
  private handleClickNext = () => this.handleAction('next');
  private handleClickPrev = () => this.handleAction('back');

  private handleAction = async (actionType: ActionType) => {
    this.loadingAction = actionType;

    const { currentStep, stepDetails } = interstitialDetailsSignal.get();
    const stepCount = stepDetails.length;

    let resolvePromise;
    const proceedPromise = new Promise<boolean>((resolve) => {
      resolvePromise = resolve;
    });

    const customEvent = new CustomEvent(
      (
        this.constructor as typeof CDSInterstitialScreenFooter
      ).eventOnBeforeAction,
      {
        bubbles: true,
        composed: true,
        cancelable: true,
        detail: {
          step: currentStep,
          stepCount: stepCount,
          proceed: (allow: boolean | Promise<boolean>) => {
            Promise.resolve(allow).then(resolvePromise);
          },
        },
      }
    );

    const eventNotCanceled = this.dispatchEvent(customEvent);

    if (!eventNotCanceled) {
      return;
    }

    const canProceed = this.asyncAction ? await proceedPromise : true;

    this.loadingAction = '';

    if (canProceed) {
      const { carouselAPI } = interstitialDetailsSignal.get();

      if (actionType == 'next') {
        carouselAPI?.next();
      } else if (actionType === 'back') {
        carouselAPI?.prev();
      } else {
        this._handleUserInitiatedClose?.(actionType);
      }
    }
  };

  render() {
    const { stepDetails, currentStep, disableActions } =
      interstitialDetailsSignal.get();
    const { start, next, back, skip } = disableActions;
    const isMulti = stepDetails?.length > 0;
    const progStepCeil = stepDetails?.length - 1;

    return html`<slot>
      <div class="${blockClass}--footer">
        <cds-action-set size="xl">
          ${isMulti
            ? html`
                <cds-button
                  class="${blockClass}--skip-btn"
                  kind="ghost"
                  size="xl"
                  title="${this.skipButtonLabel}"
                  @click="${this.handleSkip}"
                  ?disabled="${skip}">
                  ${this.skipButtonLabel}
                </cds-button>
              `
            : ''}
          ${isMulti && currentStep > 0
            ? html`
                <cds-button
                  class="${blockClass}--prev-btn"
                  kind="secondary"
                  size="xl"
                  title="${this.previousButtonLabel}"
                  ?disabled="${back}"
                  @click="${this.handleClickPrev}">
                  ${this.previousButtonLabel}
                  ${this.loadingAction === 'back'
                    ? html` <cds-inline-loading slot="icon" aria-live="off">
                      </cds-inline-loading>`
                    : nothing}
                </cds-button>
              `
            : nothing}
          ${isMulti && currentStep < progStepCeil
            ? html`
                <cds-button
                  class="${blockClass}--next-btn"
                  kind="primary"
                  size="xl"
                  title="${this.nextButtonLabel}"
                  ?disabled="${next}"
                  @click="${this.handleClickNext}">
                  ${this.nextButtonLabel}
                  ${this.loadingAction === 'next'
                    ? html` <cds-inline-loading slot="icon" aria-live="off">
                      </cds-inline-loading>`
                    : html`${iconLoader(ArrowRight, { slot: 'icon' })}`}
                </cds-button>
              `
            : nothing}
          ${(isMulti && currentStep === progStepCeil) || !isMulti
            ? html`
                <cds-button
                  class="${blockClass}--start-btn"
                  kind="primary"
                  size="xl"
                  title="${this.startButtonLabel}"
                  ?disabled="${start}"
                  @click="${this.handleStart}">
                  ${this.startButtonLabel}
                  ${this.loadingAction === 'start'
                    ? html` <cds-inline-loading slot="icon" aria-live="off">
                      </cds-inline-loading>`
                    : html`${iconLoader(ArrowRight, { slot: 'icon' })}`}
                </cds-button>
              `
            : nothing}
        </cds-action-set>
      </div>
    </slot>`;
  }

  static styles = styles;

  static get eventRequestClose() {
    return `${prefix}-request-close`;
  }

  /**
   * The name of the custom event fired just before the action.
   */
  static get eventOnBeforeAction() {
    return `${prefix}-on-action`;
  }
}
export default CDSInterstitialScreenFooter;

// packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenFooter.tsx
/**
 * Copyright IBM Corp. 2024, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import React, { useContext, useEffect, useMemo, useRef, useState } from 'react';

import PropTypes from 'prop-types';

import {
  InterstitialScreenContext,
  blockClass,
  ActionType,
  disableButtonConfigType,
} from './context';
import {
  Button,
  ButtonSet,
  InlineLoading,
  ModalFooter,
  usePrefix,
} from '@carbon/react';
import { clamp } from '../../global/js/utils/clamp';
import { ArrowRight } from '@carbon/react/icons';
import { getDevtoolsProps } from '../../global/js/utils/devtools';

type actionButtonRendererArgs = {
  handleGotoStep?: (value: number) => void;
  progStep?: number;
  stepCount?: number;
  disableButtonConfig?: disableButtonConfigType;
};

export interface InterstitialScreenFooterProps {
  /**
   * Provide an optional class to be applied to the containing node.
   */
  className?: string;
  /**
   * The label for the Previous button.
   */
  previousButtonLabel?: string;

  /**
   * The label for the skip button.
   */
  skipButtonLabel?: string;
  /**
   * The label for the start button.
   */
  startButtonLabel?: string;
  /**
   * The label for the Next button.
   */
  nextButtonLabel?: string;
  /**
   * This is an optional callback prop that allows to render your custom footer action buttons.
   * note: this is applicable when not using custom actionButtonRenderer
   */
  actionButtonRenderer?: (config: actionButtonRendererArgs) => React.ReactNode;

  /**
   * optional asynchronous callback on action button click
   */
  onAction?: (actionName: ActionType, config: actionButtonRendererArgs) => void;
}
const InterstitialScreenFooter = React.forwardRef<
  HTMLDivElement,
  InterstitialScreenFooterProps
>((props, ref) => {
  const {
    className = '',
    skipButtonLabel = 'Skip',
    previousButtonLabel = 'Back',
    nextButtonLabel = 'Next',
    startButtonLabel = 'Get Started',
    actionButtonRenderer,
    onAction,
    ...rest
  } = props;

  const footerBlockClass = `${blockClass}--footer`;
  const {
    handleClose,
    progStep,
    handleGotoStep,
    stepCount,
    disableButtonConfig,
    isFullScreen,
  } = useContext(InterstitialScreenContext);
  const startButtonRef = useRef<HTMLButtonElement | null>(null);
  const nextButtonRef = useRef<HTMLButtonElement | null>(null);
  const [loadingAction, setLoadingAction] = useState('');

  const carbonPrefix = usePrefix();

  const isMultiStep = !!stepCount && stepCount > 1;
  const progStepFloor = 0;
  const progStepCeil = stepCount - 1;
  //this will focus the start button on last step when next button is hidden and start button is shown
  useEffect(() => {
    if (progStep + 1 === stepCount && startButtonRef.current) {
      startButtonRef.current.focus();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [progStep]);

  const handleAction = async (actionType: ActionType) => {
    setLoadingAction(actionType);

    const abortContinue = await onAction?.(actionType, {
      handleGotoStep,
      progStep,
      stepCount,
      disableButtonConfig,
    });

    setLoadingAction('');

    // Skip navigation if onAction explicitly returns true
    if (abortContinue) {
      return;
    }

    if (actionType === 'next' || actionType === 'back') {
      const stepDelta = actionType === 'next' ? 1 : -1;
      const targetStep = clamp(
        progStep + stepDelta,
        progStepFloor,
        progStepCeil
      );
      handleGotoStep?.(targetStep as number);
    } else {
      handleClose?.(actionType);
    }
  };

  // Usage
  const handleStart = () => handleAction('start');
  const handleSkip = () => handleAction('skip');
  const handleClickNext = () => handleAction('next');
  const handleClickPrev = () => handleAction('back');

  const getRenderIcon = useMemo(() => {
    if (loadingAction !== 'start' && isMultiStep && progStep === progStepCeil) {
      return { renderIcon: ArrowRight };
    }
    return {};
  }, [loadingAction, isMultiStep, progStep, progStepCeil]);

  const getFooterContent = () => (
    <ButtonSet>
      {isMultiStep && skipButtonLabel !== '' && (
        <Button
          className={`${blockClass}--skip-btn`}
          kind="ghost"
          size="lg"
          title={skipButtonLabel}
          onClick={handleSkip}
          disabled={disableButtonConfig?.skip}
        >
          {skipButtonLabel}
          {loadingAction === 'skip' && <InlineLoading />}
        </Button>
      )}

      {isMultiStep && progStep > 0 && (
        <Button
          className={`${blockClass}--prev-btn`}
          kind="secondary"
          size="lg"
          title={previousButtonLabel}
          disabled={disableButtonConfig?.back}
          onClick={handleClickPrev}
        >
          {previousButtonLabel}
          {loadingAction === 'back' && <InlineLoading />}
        </Button>
      )}

      {isMultiStep && progStep < progStepCeil && (
        <Button
          className={`${blockClass}--next-btn`}
          renderIcon={loadingAction !== 'next' ? ArrowRight : undefined}
          ref={nextButtonRef}
          size="lg"
          title={nextButtonLabel}
          disabled={disableButtonConfig?.next}
          onClick={handleClickNext}
        >
          {nextButtonLabel}
          {loadingAction === 'next' && <InlineLoading />}
        </Button>
      )}
      {((isMultiStep && progStep === progStepCeil) || !isMultiStep) && (
        <Button
          className={`${blockClass}--start-btn`}
          ref={startButtonRef}
          size="lg"
          title={startButtonLabel}
          disabled={disableButtonConfig?.start}
          onClick={handleStart}
          {...getRenderIcon}
        >
          {startButtonLabel}
          {loadingAction === 'start' && <InlineLoading />}
        </Button>
      )}
    </ButtonSet>
  );
  const footerContent = actionButtonRenderer
    ? actionButtonRenderer({
        handleGotoStep,
        progStep,
        stepCount,
        disableButtonConfig,
      })
    : getFooterContent();

  return isFullScreen ? (
    <div
      ref={ref}
      className={`${footerBlockClass} ${className}  ${carbonPrefix}--modal-footer`}
      {...getDevtoolsProps('InterstitialScreenFooter')}
      {...rest}
    >
      {footerContent}
    </div>
  ) : (
    <ModalFooter
      className={`${footerBlockClass} ${className}`}
      ref={ref}
      {...rest}
    >
      {footerContent}
    </ModalFooter>
  );
});

export default InterstitialScreenFooter;

InterstitialScreenFooter.propTypes = {
  /**
   * This is an optional callback prop that allows to render your custom footer action buttons.
   */
  actionButtonRenderer: PropTypes.func,
  /**
   * Provide an optional class to be applied to the containing node.
   */
  className: PropTypes.string,

  /**
   * The label for the Next button.
   */
  nextButtonLabel: PropTypes.string,
  /**
   * optional asynchronous callback on action button click (skip, previous, next and start)
   * note: this is applicable when not using custom actionButtonRenderer
   */
  onAction: PropTypes.func,
  /**
   * The label for the Previous button.
   *
   */
  previousButtonLabel: PropTypes.string,
  /**
   * The label for the skip button.
   */
  skipButtonLabel: PropTypes.string,
  /**
   * The label for the start button.
   */
  startButtonLabel: PropTypes.string,
};
