// packages/web-components/src/components/fluid-date-picker/fluid-date-picker-skeleton.ts
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { prefix } from '../../globals/settings';
import { html, LitElement } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { iconLoader } from '../../globals/internal/icon-loader';
import Calendar16 from '@carbon/icons/es/calendar/16.js';
import styles from './fluid-date-picker.scss?lit';

/**
 * Fluid date picker skeleton.
 *
 * @element cds-fluid-date-picker-skeleton
 */
class CDSFluidDatePickerSkeleton extends LitElement {
  static is = `${prefix}-fluid-date-picker-skeleton`;

  @property({ reflect: true, attribute: 'date-picker-type' })
  datePickerType: 'simple' | 'single' | 'range' = 'single';

  private _renderContainer(showIcon: boolean) {
    return html`
      <div class="${prefix}--date-picker--fluid__skeleton--container">
        <span class="${prefix}--label ${prefix}--skeleton"></span>
        <div class="${prefix}--skeleton ${prefix}--text-input"></div>
        ${showIcon
          ? iconLoader(Calendar16, {
              class: `${prefix}--date-picker__icon`,
              role: 'img',
              'aria-hidden': 'true',
            })
          : null}
      </div>
    `;
  }

  render() {
    const { datePickerType } = this;
    const isRange = datePickerType === 'range';
    const showIcon = datePickerType !== 'simple';

    const wrapperClasses = classMap({
      [`${prefix}--date-picker--fluid__skeleton`]: true,
      [`${prefix}--date-picker--fluid__skeleton--range`]: isRange,
    });

    return html`
      <div class="${wrapperClasses}">
        ${this._renderContainer(showIcon)}
        ${isRange ? this._renderContainer(true) : null}
      </div>
    `;
  }

  static styles = [styles];
}

export default CDSFluidDatePickerSkeleton;

// packages/react/src/components/FluidDatePicker/FluidDatePicker.Skeleton.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import classnames from 'classnames';
import { usePrefix } from '../../internal/usePrefix';
import { FormContext } from '../FluidForm/FormContext';
import { Calendar } from '@carbon/icons-react';

function FluidDatePickerSkeleton({
  className,
  datePickerType = 'single',
  ...other
}) {
  const prefix = usePrefix();

  const classNames = classnames(
    className,
    `${prefix}--form-item ${prefix}--date-picker--fluid__skeleton`,
    {
      [`${prefix}--date-picker--fluid__skeleton--range`]:
        datePickerType === 'range',
    }
  );

  return (
    <FormContext.Provider value={{ isFluid: true }}>
      <div className={classNames} {...other}>
        <div className={`${prefix}--date-picker--fluid__skeleton--container`}>
          <span className={`${prefix}--label ${prefix}--skeleton`} />
          <div className={`${prefix}--skeleton ${prefix}--text-input`} />
          {datePickerType !== 'simple' && (
            <Calendar
              className={`${prefix}--date-picker__icon`}
              role="img"
              aria-hidden="true"></Calendar>
          )}
        </div>
        {datePickerType === 'range' && (
          <div className={`${prefix}--date-picker--fluid__skeleton--container`}>
            <span className={`${prefix}--label ${prefix}--skeleton`} />
            <div className={`${prefix}--skeleton ${prefix}--text-input`} />
            <Calendar
              className={`${prefix}--date-picker__icon`}
              role="img"
              aria-hidden="true"></Calendar>
          </div>
        )}
      </div>
    </FormContext.Provider>
  );
}

FluidDatePickerSkeleton.propTypes = {
  /**
   * Specify an optional className to be applied to the outer FluidForm wrapper
   */
  className: PropTypes.string,

  /**
   * Specify which variant of the DatePicker the skeleton should mimic
   */
  datePickerType: PropTypes.oneOf(['simple', 'single', 'range']),
};

export default FluidDatePickerSkeleton;
