// web-components/packages/carbon-web-components/src/components/ui-shell/header-panel.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property, customElement } from 'lit/decorators.js';
import styles from './header.scss';
import { prefix } from '../../globals/settings';

/**
 * Header panel
 *
 * @element cds-header-panel
 */
@customElement(`${prefix}-header-panel`)
class CDSHeaderPanel extends LitElement {
  /**
   * Specify whether the panel is expanded
   */
  @property({ type: Boolean, reflect: true })
  expanded;

  render() {
    return html`<slot></slot>`;
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSHeaderPanel;

// packages/react/src/components/UIShell/HeaderPanel.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import cx from 'classnames';
import PropTypes from 'prop-types';
import { usePrefix } from '../../internal/usePrefix';

const HeaderPanel = React.forwardRef(function HeaderPanel(
  { children, className: customClassName, expanded, ...other },
  ref
) {
  const prefix = usePrefix();

  const className = cx(`${prefix}--header-panel`, {
    [`${prefix}--header-panel--expanded`]: expanded,
    [customClassName]: !!customClassName,
  });

  return (
    <div {...other} className={className} ref={ref}>
      {children}
    </div>
  );
});

HeaderPanel.propTypes = {
  /**
   * The content that will render inside of the `HeaderPanel`
   */
  children: PropTypes.node,

  /**
   * Optionally provide a custom class to apply to the underlying `<li>` node
   */
  className: PropTypes.string,

  /**
   * Specify whether the panel is expanded
   */
  expanded: PropTypes.bool,
};

HeaderPanel.displayName = 'HeaderPanel';

export default HeaderPanel;
