// web-components/packages/carbon-web-components/src/components/skip-to-content/skip-to-content.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property, customElement } from 'lit/decorators.js';
import settings from 'carbon-components/es/globals/js/settings.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import FocusMixin from '../../globals/mixins/focus';
import styles from './skip-to-content.scss';

const { prefix } = settings;

/**
 * Skip-to-content link.
 *
 * @element bx-skip-to-content
 */
@customElement(`${prefix}-skip-to-content`)
class BXSkipToContent extends FocusMixin(LitElement) {
  /**
   * The assistive text for the link,
   */
  @property({ attribute: 'link-assistive-text' })
  linkAssisstiveText = 'Skip to main content';

  /**
   * The skip link href.
   */
  @property()
  href?: string;

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'navigation');
    }
    super.connectedCallback();
  }

  render() {
    const { linkAssisstiveText } = this;
    return html`
      <a class="${prefix}--skip-to-content" href="${ifDefined(this.href)}"
        ><slot>${linkAssisstiveText}</slot></a
      >
    `;
  }

  updated(changedProperties) {
    if (changedProperties.has('linkAssisstiveText')) {
      const { linkAssisstiveText } = this;
      this.setAttribute('aria-label', linkAssisstiveText);
    }
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXSkipToContent;

// packages/react/src/components/UIShell/SkipToContent.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { settings } from 'carbon-components';
import cx from 'classnames';
import React from 'react';
import PropTypes from 'prop-types';

const { prefix } = settings;

const SkipToContent = ({
  children,
  className: customClassName,
  href,
  tabIndex,
  ...rest
}) => {
  const className = cx(`${prefix}--skip-to-content`, customClassName);
  return (
    <a {...rest} className={className} href={href} tabIndex={tabIndex}>
      {children}
    </a>
  );
};

SkipToContent.propTypes = {
  className: PropTypes.string,

  /**
   * Provide text to display in the SkipToContent `a` tag
   */
  children: PropTypes.string.isRequired,

  /**
   * Provide the `href` to the id of the element on your package that is the
   * main content.
   */
  href: PropTypes.string.isRequired,

  /**
   * Optionally override the default tabindex of 0
   */
  tabIndex: PropTypes.string,
};

SkipToContent.defaultProps = {
  children: 'Skip to main content',
  href: '#main-content',
  tabIndex: '0',
};

export default SkipToContent;
