// web-components/packages/carbon-web-components/src/components/slider/slider-story-react.tsx
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
// Below path will be there when an application installs `carbon-web-components` package.
// In our dev env, we auto-generate the file and re-map below path to to point to the generated file.
// @ts-ignore
import BXSlider from 'carbon-web-components/es/components-react/slider/slider';
// @ts-ignore
import BXSliderInput from 'carbon-web-components/es/components-react/slider/slider-input';
// @ts-ignore
import BXSliderSkeleton from 'carbon-web-components/es/components-react/slider/slider-skeleton';
import { Default as baseDefault, withInputBox as baseWithInputBox } from './slider-story';

export { default } from './slider-story';

export const Default = args => {
  const { disabled, labelText, max, min, name, step, value, onChange } = args?.['bx-slider'];
  return (
    <BXSlider
      disabled={disabled}
      labelText={labelText}
      max={max}
      min={min}
      name={name}
      step={step}
      value={value}
      onChange={onChange}
    />
  );
};

Object.assign(Default, baseDefault);

export const withInputBox = args => {
  const { disabled, labelText, max, min, name, step, value, onChange } = args?.['bx-slider'];
  return (
    <BXSlider
      disabled={disabled}
      labelText={labelText}
      max={max}
      min={min}
      name={name}
      step={step}
      value={value}
      onChange={onChange}>
      <BXSliderInput aria-label="Slider value" type="number" />
    </BXSlider>
  );
};

Object.assign(withInputBox, baseWithInputBox);

export const skeleton = () => <BXSliderSkeleton />;

// web-components/packages/carbon-web-components/src/components/slider/slider-story-angular.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { moduleMetadata } from '@storybook/angular';
import baseStory, { Default as baseDefault, withInputBox as baseWithInputBox } from './slider-story';

export const Default = args => ({
  template: `
    <bx-slider
      [disabled]="disabled"
      [labelText]="labelText"
      [max]="max"
      [min]="min"
      [name]="name"
      [step]="step"
      [value]="value"
      (bx-slider-changed)="onChange($event)"
    ></bx-slider>
  `,
  props: args?.['bx-slider'],
});

Object.assign(Default, baseDefault);

export const withInputBox = args => ({
  template: `
    <bx-slider
      [disabled]="disabled"
      [labelText]="labelText"
      [max]="max"
      [min]="min"
      [name]="name"
      [step]="step"
      [value]="value"
      (bx-slider-changed)="onChange($event)"
    >
      <bx-slider-input aria-label="Slider value" type="number"></bx-slider-input>
    </bx-slider>
  `,
  props: args?.['bx-slider'],
});

Object.assign(withInputBox, baseWithInputBox);

export const skeleton = () => ({
  template: `<bx-slider-skeleton></bx-slider-skeleton>`,
});

export default Object.assign(baseStory, {
  decorators: [
    moduleMetadata({
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
    }),
  ],
});
