// packages/web-components/src/examples/EmptyState/example/preview-components/EmptyStateUnit.ts
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Recipe component — copy-and-customize, not a published package export.
 */

import { LitElement, html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';

// ─── Import web component definitions ────────────────────────────────────────
// In a standalone project, replace these with:
//   import '@carbon/web-components/es/components/button/index.js'; etc.
import '../../../../components/button/index';
import '../../../../components/data-table/index';
import '../../../../components/link/index';
import '../../../../components/overflow-menu/index';
import '../../../../components/skip-to-content/index';
import '../../../../components/tile/index';
import '../../../../components/ui-shell/index';

import { Search20, Settings16 } from '@carbon/icons';
import { iconLoader } from '../../../../globals/internal/icon-loader';
import '../components/EmptyState';
import notFoundSrc from '../assets/not-found.svg?url';
import unauthorizedSrc from '../assets/unauthorized.svg?url';
import errorSrc from '../assets/error.svg?url';

// ─── Static table data ────────────────────────────────────────────────────────

const TABLE_HEADERS = [
  { key: 'name', header: 'Name' },
  { key: 'protocol', header: 'Protocol' },
  { key: 'port', header: 'Port' },
  { key: 'rule', header: 'Rule' },
];

const TABLE_ROWS = [
  { id: 'a', name: 'Load Balancer 1', protocol: 'HTTP', port: 443, rule: 'Round robin' },
  { id: 'b', name: 'Load Balancer 2', protocol: 'HTTP', port: 80, rule: 'DNS delegation' },
  { id: 'c', name: 'Load Balancer 3', protocol: 'HTTP', port: 3000, rule: 'Round robin' },
];

const SIDE_NAV_LINKS = [
  'Overview',
  'Assets',
  'Monitoring',
  'Activity',
  'Configuration',
  'Access',
  'Billing',
];

/**
 * `cds-empty-state-unit`
 *
 * Full UI Shell demo showing three empty-state placement scenarios:
 *  1. Inside a DataTable (no search results)
 *  2. Inside a tall vertical tile
 *  3. Inside wide horizontal tiles
 *
 * Toggle `placement` between `left` and `centre`.
 *
 * @example
 * <!-- Left-aligned (default) -->
 * <cds-empty-state-unit></cds-empty-state-unit>
 *
 * <!-- Centred -->
 * <cds-empty-state-unit placement="centre"></cds-empty-state-unit>
 *
 * @element cds-empty-state-unit
 */
@customElement('cds-empty-state-unit')
export class CDSEmptyStateUnit extends LitElement {
  /**
   * Alignment of every empty state relative to its own container.
   * @default 'left'
   */
  @property({ reflect: true })
  placement: 'left' | 'centre' = 'left';

  @state()
  private _searchValue = '';

  @state()
  private _sideNavExpanded = false;

  private get _filteredRows() {
    const q = this._searchValue.trim().toLowerCase();
    if (!q) return TABLE_ROWS;
    return TABLE_ROWS.filter((row) =>
      Object.values(row).some((v) => String(v).toLowerCase().includes(q))
    );
  }

  private _handleSearch(e: Event) {
    this._searchValue = (e.target as HTMLInputElement).value ?? '';
  }

  private _clearSearch() {
    this._searchValue = '';
    const search = this.renderRoot?.querySelector(
      'cds-table-toolbar-search'
    ) as HTMLInputElement | null;
    if (search) search.value = '';
  }

  private _toggleSideNav() {
    this._sideNavExpanded = !this._sideNavExpanded;
  }

  // No Shadow DOM — styles from _story-styles.scss and _empty-state.scss
  // must reach the rendered HTML directly.
  protected createRenderRoot() {
    return this;
  }

  render() {
    const { placement, _filteredRows: filteredRows, _sideNavExpanded: expanded } = this;
    const isCentre = placement === 'centre';
    const noResults = filteredRows.length === 0;
    const emptyWrapMod = isCentre
      ? 'es-example__empty-wrap--centre'
      : 'es-example__empty-wrap--left';

    return html`
      <cds-header aria-label="IBM Platform">
        <cds-skip-to-content></cds-skip-to-content>
        <cds-header-menu-button
          aria-label="${expanded ? 'Close menu' : 'Open menu'}"
          ?active="${expanded}"
          @click="${this._toggleSideNav}">
        </cds-header-menu-button>
        <cds-header-name href="#" prefix="IBM">[Platform]</cds-header-name>
        <cds-header-nav aria-label="IBM Platform">
          <cds-header-nav-item href="#">Link</cds-header-nav-item>
          <cds-header-nav-item href="#">Link</cds-header-nav-item>
          <cds-header-nav-item href="#">Link</cds-header-nav-item>
        </cds-header-nav>
        <div class="cds--header__global">
          <cds-header-global-action aria-label="Search" tooltip-text="Search">
            ${iconLoader(Search20, { slot: 'icon' })}
          </cds-header-global-action>
        </div>
        <cds-side-nav
          aria-label="Side navigation"
          ?expanded="${expanded}"
          is-not-persistent>
          ${SIDE_NAV_LINKS.map((label) => html`
            <cds-side-nav-link href="#">${label}</cds-side-nav-link>
          `)}
        </cds-side-nav>
      </cds-header>

      <main class="es-example__content">
        <div class="es-example__grid">

          <!-- ── DataTable with inline empty state ─────────────────────── -->
          <div class="es-example__col-full">
            <cds-table>
              <cds-table-header-title slot="title">Assets</cds-table-header-title>
              <cds-table-header-description slot="description">
                Search to filter results
              </cds-table-header-description>
              <cds-table-toolbar slot="toolbar">
                <cds-table-toolbar-content>
                  <cds-table-toolbar-search
                    persistent
                    placeholder="Search"
                    @cds-search-input="${this._handleSearch}">
                  </cds-table-toolbar-search>
                  <cds-overflow-menu toolbar-action>
                    ${iconLoader(Settings16, {
                      slot: 'icon',
                      class: 'cds--overflow-menu__icon',
                    })}
                    <span slot="tooltip-content">Settings</span>
                    <cds-overflow-menu-body flipped>
                      <cds-overflow-menu-item>Action 1</cds-overflow-menu-item>
                      <cds-overflow-menu-item>Action 2</cds-overflow-menu-item>
                    </cds-overflow-menu-body>
                  </cds-overflow-menu>
                  <cds-button kind="primary">Add asset</cds-button>
                </cds-table-toolbar-content>
              </cds-table-toolbar>
              <cds-table-head>
                <cds-table-header-row>
                  ${TABLE_HEADERS.map(
                    (h) => html`<cds-table-header-cell>${h.header}</cds-table-header-cell>`
                  )}
                </cds-table-header-row>
              </cds-table-head>
              <cds-table-body>
                ${!noResults
                  ? filteredRows.map(
                      (row) => html`
                        <cds-table-row>
                          <cds-table-cell>${row.name}</cds-table-cell>
                          <cds-table-cell>${row.protocol}</cds-table-cell>
                          <cds-table-cell>${row.port}</cds-table-cell>
                          <cds-table-cell>${row.rule}</cds-table-cell>
                        </cds-table-row>
                      `
                    )
                  : ''}
              </cds-table-body>
            </cds-table>

            ${noResults
              ? html`
                  <div class="es-example__empty-wrap ${emptyWrapMod}">
                    <cds-empty-state
                      illustration-src="${notFoundSrc}"
                      illustration-description="No results illustration"
                      heading="No results match the current search"
                      subtitle="Clear the search field to see all results, or try a different search term."
                      action-text="Clear search"
                      action-kind="tertiary"
                      @cds-empty-state-action-click="${this._clearSearch}">
                    </cds-empty-state>
                  </div>
                `
              : ''}
          </div>

          <!-- ── Vertical tile (spans 2 grid rows) ─────────────────────── -->
          <div class="es-example__col--span-2">
            <cds-tile class="es-example__tile">
              <p class="es-example__tile-label">Label</p>
              <p class="es-example__tile-title">Title</p>
              <div
                class="es-example__tile-empty--vertical${isCentre
                  ? ' es-example__tile-empty--vertical--centre'
                  : ''}">
                <cds-empty-state
                  size="sm"
                  illustration-src="${errorSrc}"
                  illustration-description="Error illustration"
                  heading="This insight is unavailable"
                  subtitle="Try loading the page once again after adding an asset."
                  link-text="Learn more"
                  link-href="https://carbondesignsystem.com/patterns/empty-states-pattern/">
                </cds-empty-state>
              </div>
            </cds-tile>
          </div>

          <!-- ── Horizontal tiles ───────────────────────────────────────── -->
          <div class="es-example__col-bottom">
            ${([0, 1] as const).map(
              () => html`
                <div class="es-example__col-half">
                  <cds-tile class="es-example__tile">
                    <p class="es-example__tile-label">Label</p>
                    <p class="es-example__tile-title">Title</p>
                    <div
                      class="es-example__tile-empty--horizontal${isCentre
                        ? ' es-example__tile-empty--horizontal--centre'
                        : ''}">
                      <cds-empty-state
                        size="sm"
                        illustration-src="${unauthorizedSrc}"
                        illustration-description="Unauthorized illustration"
                        heading="You do not have access"
                        subtitle="Unlock product insights by requesting view access from your admin."
                        action-text="Request access"
                        action-kind="tertiary">
                      </cds-empty-state>
                    </div>
                  </cds-tile>
                </div>
              `
            )}
          </div>

        </div>
      </main>
    `;
  }
}

export default CDSEmptyStateUnit;

// packages/react/src/examples/EmptyState/example/preview-components/EmptyStateUnit.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useState } from 'react';
import {
  Button,
  Column,
  Content,
  DataTable,
  Grid,
  Header,
  HeaderContainer,
  HeaderGlobalAction,
  HeaderGlobalBar,
  HeaderMenuButton,
  HeaderMenuItem,
  HeaderName,
  HeaderNavigation,
  SideNav,
  SideNavItems,
  SideNavLink,
  SkipToContent,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableHeader,
  TableRow,
  TableToolbar,
  TableToolbarAction,
  TableToolbarContent,
  TableToolbarMenu,
  TableToolbarSearch,
  Tile,
} from '@carbon/react';
import { Search as SearchIcon } from '@carbon/icons-react';
import { EmptyState } from '../components/EmptyState';
import notFoundIllustration from '../assets/not-found.svg';
import unauthorizedIllustration from '../assets/unauthorized.svg';
import errorIllustration from '../assets/error.svg';
import '../styles/_empty-state.scss';
import '../styles/_story-styles.scss';

const TABLE_HEADERS = [
  { key: 'name', header: 'Name' },
  { key: 'protocol', header: 'Protocol' },
  { key: 'port', header: 'Port' },
  { key: 'rule', header: 'Rule' },
];

const TABLE_ROWS = [
  { id: 'a', name: 'Load Balancer 1', protocol: 'HTTP', port: 443, rule: 'Round robin' },
  { id: 'b', name: 'Load Balancer 2', protocol: 'HTTP', port: 80, rule: 'DNS delegation' },
  { id: 'c', name: 'Load Balancer 3', protocol: 'HTTP', port: 3000, rule: 'Round robin' },
];

const SIDE_NAV_LINKS = [
  'Overview',
  'Assets',
  'Monitoring',
  'Activity',
  'Configuration',
  'Access',
  'Billing',
];

interface PageContentProps {
  placement: 'left' | 'centre';
}

const PageContent = ({ placement }: PageContentProps) => {
  const isCentre = placement === 'centre';
  const [searchValue, setSearchValue] = useState('');
  const [searchKey, setSearchKey] = useState(0);

  const filteredRows = TABLE_ROWS.filter((row) => {
    const q = searchValue.trim().toLowerCase();
    if (!q) return true;
    return Object.values(row).some((v) => String(v).toLowerCase().includes(q));
  });

  const noResults = filteredRows.length === 0;
  const emptyWrapClass = `es-example__empty-wrap es-example__empty-wrap--${
    isCentre ? 'centre' : 'left'
  }`;

  return (
    <Content>
      <Grid withRowGap>
        <Column sm={4} md={6} lg={12}>
          <DataTable rows={filteredRows} headers={TABLE_HEADERS}>
            {({
              rows,
              headers,
              getHeaderProps,
              getRowProps,
              getTableProps,
              getToolbarProps,
              getTableContainerProps,
              getCellProps,
            }) => (
              <TableContainer
                title="Assets"
                description="Search to filter results"
                {...getTableContainerProps()}>
                <TableToolbar {...getToolbarProps()} aria-label="asset table toolbar">
                  <TableToolbarContent>
                    <TableToolbarSearch
                      key={searchKey}
                      onChange={(_evt, value) => setSearchValue(value ?? '')}
                      persistent
                    />
                    <TableToolbarMenu>
                      <TableToolbarAction onClick={() => {}}>Action 1</TableToolbarAction>
                      <TableToolbarAction onClick={() => {}}>Action 2</TableToolbarAction>
                    </TableToolbarMenu>
                    <Button kind="primary" onClick={() => {}}>
                      Add asset
                    </Button>
                  </TableToolbarContent>
                </TableToolbar>
                <Table {...getTableProps()} aria-label="assets table">
                  <TableHead>
                    <TableRow>
                      {headers.map((header) => (
                        <TableHeader {...getHeaderProps({ header })} key={header.key}>
                          {header.header}
                        </TableHeader>
                      ))}
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {!noResults &&
                      rows.map((row) => (
                        <TableRow key={row.id} {...getRowProps({ row })}>
                          {row.cells.map((cell) => (
                            <TableCell key={cell.id} {...getCellProps({ cell })}>
                              {cell.value}
                            </TableCell>
                          ))}
                        </TableRow>
                      ))}
                  </TableBody>
                </Table>
                {noResults && (
                  <div className={emptyWrapClass}>
                    <EmptyState
                      illustration={notFoundIllustration}
                      illustrationDescription="No results illustration"
                      title="No results match the current search"
                      subtitle="Clear the search field to see all results, or try a different search term."
                      action={{
                        text: 'Clear search',
                        kind: 'tertiary',
                        onClick: () => {
                          setSearchValue('');
                          setSearchKey((k) => k + 1);
                        },
                      }}
                    />
                  </div>
                )}
              </TableContainer>
            )}
          </DataTable>
        </Column>

        <Column sm={4} md={2} lg={4} className="es-example__col--span-2">
          <Tile className="es-example__tile">
            <p className="es-example__tile-label">Label</p>
            <p className="es-example__tile-title">Title</p>
            <div
              className={`es-example__tile-empty--vertical${
                isCentre ? ' es-example__tile-empty--vertical--centre' : ''
              }`}>
              <EmptyState
                size="sm"
                illustration={errorIllustration}
                illustrationDescription="Error illustration"
                title="This insight is unavailable"
                subtitle="Try loading the page once again after adding an asset."
                link={{
                  text: 'Learn more',
                  href: 'https://carbondesignsystem.com/patterns/empty-states-pattern/',
                }}
              />
            </div>
          </Tile>
        </Column>

        {[0, 1].map((i) => (
          <Column key={i} sm={2} md={3} lg={6}>
            <Tile className="es-example__tile">
              <p className="es-example__tile-label">Label</p>
              <p className="es-example__tile-title">Title</p>
              <div
                className={`es-example__tile-empty--horizontal${
                  isCentre ? ' es-example__tile-empty--horizontal--centre' : ''
                }`}>
                <EmptyState
                  size="sm"
                  illustration={unauthorizedIllustration}
                  illustrationDescription="Unauthorized illustration"
                  title="You do not have access"
                  subtitle="Unlock product insights by requesting view access from your admin."
                  action={{ text: 'Request access', kind: 'tertiary', onClick: () => {} }}
                />
              </div>
            </Tile>
          </Column>
        ))}
      </Grid>
    </Content>
  );
};

interface EmptyStateUnitProps {
  placement?: 'left' | 'centre';
}

export const EmptyStateUnit = ({ placement = 'left' }: EmptyStateUnitProps) => (
  <HeaderContainer
    render={({
      isSideNavExpanded,
      onClickSideNavExpand,
    }: {
      isSideNavExpanded: boolean;
      onClickSideNavExpand: () => void;
    }) => (
      <>
        <Header aria-label="IBM Platform">
          <SkipToContent />
          <HeaderMenuButton
            aria-label={isSideNavExpanded ? 'Close menu' : 'Open menu'}
            onClick={onClickSideNavExpand}
            isActive={isSideNavExpanded}
          />
          <HeaderName href="#" prefix="IBM">
            [Platform]
          </HeaderName>
          <HeaderNavigation aria-label="IBM Platform">
            <HeaderMenuItem href="#">Link</HeaderMenuItem>
            <HeaderMenuItem href="#">Link</HeaderMenuItem>
            <HeaderMenuItem href="#">Link</HeaderMenuItem>
          </HeaderNavigation>
          <HeaderGlobalBar>
            <HeaderGlobalAction aria-label="Search" onClick={() => {}}>
              <SearchIcon size={20} />
            </HeaderGlobalAction>
          </HeaderGlobalBar>
          <SideNav
            aria-label="Side navigation"
            expanded={isSideNavExpanded}
            isPersistent={false}>
            <SideNavItems>
              {SIDE_NAV_LINKS.map((label) => (
                <SideNavLink key={label} href="#">
                  {label}
                </SideNavLink>
              ))}
            </SideNavItems>
          </SideNav>
        </Header>
        <PageContent placement={placement} />
      </>
    )}
  />
);
