// packages/react/src/components/ChatButton/ChatButton.Skeleton.js
/**
 * Copyright IBM Corp. 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';
import React from 'react';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';

const ChatButtonSkeleton = ({ className, size, ...rest }) => {
  const prefix = usePrefix();
  const skeletonClasses = cx(
    className,
    `${prefix}--skeleton`,
    `${prefix}--btn`,
    `${prefix}--chat-btn`,
    { [`${prefix}--layout--size-${size}`]: size }
  );

  return <div className={skeletonClasses} {...rest} />;
};

ChatButtonSkeleton.propTypes = {
  /**
   * Specify an optional className to add.
   */
  className: PropTypes.string,

  /**
   * Specify the size of the `ChatButtonSkeleton`, from the following list of sizes:
   */
  size: PropTypes.oneOf(['sm', 'md', 'lg']),
};

export default ChatButtonSkeleton;

// packages/web-components/src/components/chat-button/chat-button-skeleton.ts
/**
 * Copyright IBM Corp. 2019, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import { CHAT_BUTTON_SIZE } from './defs';
import styles from './chat-button.scss?lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

export { CHAT_BUTTON_SIZE };
/**
 * Chat button skeleton.
 *
 * @element cds-chat-button-skeleton
 */
@customElement(`${prefix}-chat-button-skeleton`)
class CDSChatButtonSkeleton extends LitElement {
  /**
   * Specify the size of the `ChatButtonSkeleton`, from the following list of sizes: 'sm', 'md', 'lg'
   */
  @property({ reflect: true })
  size = CHAT_BUTTON_SIZE.LARGE;

  render() {
    const skeletonClasses = classMap({
      [`${prefix}--skeleton`]: true,
      [`${prefix}--btn`]: true,
      [`${prefix}--chat-btn`]: true,
      [`${prefix}--layout--size-${this.size}`]: this.size,
    });

    return html` <div class="${skeletonClasses}"></div> `;
  }

  static styles = styles;
}

export default CDSChatButtonSkeleton;
