// packages/web-components/src/components/layer/layer.ts
/**
 * Copyright IBM Corp. 2019, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { prefix } from '../../globals/settings';
import styles from './layer.scss?lit';

/**
 * Layer level constants
 */
export const MIN_LEVEL = 0;
export const MAX_LEVEL = 2;
export const levels = ['zero', 'one', 'two'];
export type LayerLevel = 0 | 1 | 2;

/**
 * Basic layer
 *
 * @element cds-layer
 * @fires cds-use-layer
 *   The name of the custom event fired when the "use layer" action occurs.
 * @slot children - The elements contained within the component.
 */
@customElement(`${prefix}-layer`)
class CDSLayer extends LitElement {
  /**
   * Specify the layer level and override any existing levels based on hierarchy
   */
  @property({ type: Number, reflect: true })
  level = 0;

  @property()
  layers;

  updated() {
    if (!this.layers) {
      this.layers = this.querySelectorAll(
        (this.constructor as typeof CDSLayer).selectorLayer
      );
    }

    this.layers.forEach((item) => {
      const nextLevel = Math.max(
        MIN_LEVEL,
        Math.min(this.level + 1, MAX_LEVEL)
      );
      (item as HTMLElement).setAttribute('level', nextLevel.toString());
    });

    this.dispatchEvent(
      new CustomEvent((this.constructor as typeof CDSLayer).eventUseLayer, {
        bubbles: true,
        cancelable: true,
        composed: true,
        detail: {
          layer: this,
          level: this.level,
        },
      })
    );
  }

  render() {
    return html` <slot></slot> `;
  }

  /**
   * A selector that selects a layer component.
   */
  static get selectorLayer() {
    return `${prefix}-layer`;
  }

  /**
   * A selector that selects a layer component.
   */
  static get eventUseLayer() {
    return `${prefix}-use-layer`;
  }

  static styles = styles;
}

export default CDSLayer;

// packages/react/src/components/Layer/index.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { usePrefix } from '../../internal/usePrefix';
import { LayerContext } from './LayerContext';

const levels = ['one', 'two', 'three'];
const MAX_LEVEL = levels.length - 1;

export function Layer({
  as: BaseComponent = 'div',
  className: customClassName,
  children,
  level: overrideLevel,
  ...rest
}) {
  const level = React.useContext(LayerContext);
  const prefix = usePrefix();
  const className = cx(
    `${prefix}--layer-${levels[overrideLevel ?? level]}`,
    customClassName
  );
  // The level should be between 0 and MAX_LEVEL
  const value = overrideLevel ?? Math.max(0, Math.min(level + 1, MAX_LEVEL));

  return (
    <LayerContext.Provider value={value}>
      <BaseComponent {...rest} className={className}>
        {children}
      </BaseComponent>
    </LayerContext.Provider>
  );
}

Layer.propTypes = {
  /**
   * Specify a custom component or element to be rendered as the top-level
   * element in the component
   */
  as: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.string,
    PropTypes.elementType,
  ]),

  /**
   * Provide child elements to be rendered inside of `Theme`
   */
  children: PropTypes.node,

  /**
   * Provide a custom class name to be used on the outermost element rendered by
   * the component
   */
  className: PropTypes.string,

  /**
   * Provide a level value that will override the existing value in context
   */
  level: PropTypes.oneOf([0, 1, 2]),
};
